### ISSUE TITLE
Scopes dictionary

### ISSUE THREAD

**Issue by kmakarenko** [ehealth-ua/api-spec#10]
Please provide a scope dictionary.

**Comment by warehousman** [comment]
@kmakarenko Please specify your request. What works wrong?

**Comment by sreva** [comment]
Потрібне розуміння, який набір скоупів взагалі є доступним

**Comment by AlekzandrV** [comment]
Ось [тут](https://edenlab.atlassian.net/wiki/display/EH/Scopes+model) можна переглянути скоупи для ролі користувача
З запуском сервісів скоупи будуть додаватись до існуючого переліку
Всі вони поділені по ролям користувача (зареєстрованого співробітника)

**Comment by kmakarenko** [comment]
Please make the link public.
