### ISSUE TITLE
Не можу отримати Code Grant

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#100]
Створюю запит:
http://auth.demo.ehealth.world/sign-in?client_id=51d1b966-2bab-4b02-8e72-f4157e46c461&redirect_uri=https://93.18.20.83/CodeGrant/569313B7DC64425DAC8F31951294F9B1&scope=legal_entity:read legal_entity:write&email=dmytropieskov@gmail.com

client_id - підставляю значення із urgent-security-client_id коли реєструю юр. особу.

Логин та пароль правильний.
Після того як натискаю на кнопку "Прийняти та продовжити отримую помилку: User not found (invalid_client)

**Comment by lymychp** [comment]
проблема в тому, що у користувача `dmytropieskov@gmail.com` немає жодної ролі в закладі `51d1b966-2bab-4b02-8e72-f4157e46c461`.
Наразі у закладу `51d1b966-2bab-4b02-8e72-f4157e46c461` взагалі немає жодного користувача.
Рекомендую пройти процедуру реєстрації закладу `КНП "Перший Черкаський міський центр первинної медико-санітарної допомоги"` знову і до кінця. Після чого спробувати ще раз отримати code grant
