### ISSUE TITLE
Создание Persons

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#101]
Есть метод по созданию Persons, описанный в документации, но не работающий, когда к нему обращаются.

`{
    "meta": {
        "url": "http://demo.ehealth.world/api/persons/",
        "type": "object",
        "request_id": "2947kobfnubh963v1v5kohn483th8p45",
        "code": 404
    },
    "error": {
        "type": "not_found"
    }
}`

**Comment by pzhuk** [comment]
С каким токеном обращение?

**Comment by pzhuk** [comment]
Пожалуйста, оформите задачу в соответствии с рекомендациями - среда, полный запрос итд
