### ISSUE TITLE
500 при підтвердженні заявки на створення співробітника

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#102]
## Steps to Reproduce (Repro steps)

- [ ] http://auth.demo.ehealth.world/invite/accept?invite=d06d34c2-5be1-4c5f-abb9-5bf811b06c9e

- [ ] 
1) створили заявку на створення співробітника
2) отримали лист
3) при підтвердженні отримали 500 http://prntscr.com/gad487
`{"meta":{"url":"http://demo.ehealth.world/api/employee_requests/d06d34c2-5be1-4c5f-abb9-5bf811b06c9e/approve","type":"object","request_id":"taujqj13da78hm0m2so7mcu6k2umh23l","code":500},"error":{"type":"internal_error"}}`

## Actual result
- [ ] у відповіді get employee_list отримуємо 3 дублі (ІПН=1840900830, email = xima@golemico.com) цього співробітника

## Expected result
- [ ] вдале підтвердження і 1 співробітник

**Comment by sreva** [comment]
3 дублі,по причині що  тричі нажимав "Прийняти запрошення" і тричі отримував 500

**Comment by AlekzandrV** [comment]
Спробуйте, будь-ласка, зараз заапрувити

**Comment by sreva** [comment]
Працює, дякую

**Comment by AlekzandrV** [comment]
Причину ми дізналися та виправили. Подібна проблема не повинна повторюватись
