### ISSUE TITLE
Не оновлюеються OWNER для LegalEntity

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#103]
Роблю запит:
GET /api/employee_requests HTTP/1.1
Host: demo.ehealth.world
Authorization: Bearer cTNIQXZEbHVnNVBKZ21YSlBVNDJ4dz09
Cache-Control: no-cache
Postman-Token: 9907998f-91e1-ef4b-6e55-d0adda5d9e79

У перших 9-ти однакові ІПН+дата нородження, та всі вони мають тип OWNER.

Отримую:
{
    "paging": {
        "size": null,
        "limit": 50,
        "has_more": false,
        "cursors": {
            "starting_after": "202a4707-d3a5-4494-94e1-f887261c18a4",
            "ending_before": "e33fe579-fbe5-42d1-98c7-5733006a16e5"
        }
    },
    "meta": {
        "url": "http://demo.ehealth.world/api/employee_requests",
        "type": "list",
        "request_id": "6kbansb8perqdkbkm39sb68qvdmueq5c",
        "code": 200
    },
    "data": [
        {
            "status": "NEW",
            "second_name": "Дмитро5",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Ол5",
            "inserted_at": "2017-08-19T14:53:59.944192",
            "id": "e33fe579-fbe5-42d1-98c7-5733006a16e5",
            "first_name": "Пєсков5",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Дмитро4",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Олекс4",
            "inserted_at": "2017-08-19T14:50:30.026618",
            "id": "930ab9e3-f7af-42f5-a3a0-fabdb6a956f5",
            "first_name": "Пєсков4",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Дмитро4",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Олекс4",
            "inserted_at": "2017-08-19T14:50:03.503072",
            "id": "7c670115-ad65-4f8a-a664-b8871031b564",
            "first_name": "Пєсков4",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Дмитро4",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Олекс4",
            "inserted_at": "2017-08-19T14:49:35.291567",
            "id": "6bfce833-08af-4e07-ab25-3368add63939",
            "first_name": "Пєсков4",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Дмитро4",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Олекс4",
            "inserted_at": "2017-08-19T14:49:08.112223",
            "id": "28545285-930c-4175-9980-ee8a82a65e8c",
            "first_name": "Пєсков4",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Дмитро3",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Олекс3",
            "inserted_at": "2017-08-19T13:41:31.381714",
            "id": "fedeb713-ca1d-4cf8-b104-98841c6da5cc",
            "first_name": "Пєсков3",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Дмитро2",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Олекс2",
            "inserted_at": "2017-08-19T13:35:58.617495",
            "id": "957259a3-e80a-4937-8cb9-90f68913800e",
            "first_name": "Пєсков2",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Дмитро2",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Олекс2",
            "inserted_at": "2017-08-19T13:35:28.813945",
            "id": "46fccd65-0e79-47b9-b345-dd7ac0a1d497",
            "first_name": "Пєсков2",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Дмитро2",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Олекс2",
            "inserted_at": "2017-08-19T13:34:52.127653",
            "id": "6b654c83-190d-4b9b-b4c3-6d1e453a5973",
            "first_name": "Пєсков2",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "dfbdfb",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "dfbdfbdfb",
            "inserted_at": "2017-08-19T13:06:26.599121",
            "id": "aac3bbe7-b0d5-4f35-ae0a-d708cd5ac53e",
            "first_name": "dfbdfbdf",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Александрович",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Дмитрий",
            "inserted_at": "2017-08-17T14:22:35.680135",
            "id": "6437aa05-528a-4a6e-af42-33f97c80196d",
            "first_name": "Песков",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Александрович",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Дмитрий",
            "inserted_at": "2017-08-17T12:53:46.417096",
            "id": "303077c6-ee62-40ed-8800-5f3781f5e0ab",
            "first_name": "Песков",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Иван",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Иванович",
            "inserted_at": "2017-08-17T10:06:17.037835",
            "id": "e4558a3a-bf6f-4c61-8468-5c2576e1a801",
            "first_name": "Иванов",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Александрович",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Дмитрий",
            "inserted_at": "2017-08-17T09:52:53.913192",
            "id": "65afef93-6820-4716-838a-defd637f08d7",
            "first_name": "Песков",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "esrgserh",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "serhserh",
            "inserted_at": "2017-08-17T08:05:21.424700",
            "id": "bb339afd-7eca-4c0f-90e4-50732d6faa7b",
            "first_name": "gg",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "sadasdg",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "asdgasg",
            "inserted_at": "2017-08-17T07:55:45.347945",
            "id": "375ae836-ab2c-428f-88bc-64e78e90eaec",
            "first_name": "sdasdg",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "sadasdg",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "asdgasg",
            "inserted_at": "2017-08-17T07:54:34.627444",
            "id": "abf2c815-8a62-4355-8359-010f434ed30e",
            "first_name": "sdasdg",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "dfbdfb",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "dfbdfbdfb",
            "inserted_at": "2017-08-16T13:39:21.944069",
            "id": "a137d8d7-aa29-4149-b4ca-7a4874cdabb3",
            "first_name": "dfbdfbdf",
            "edrpou": "38469862"
        },
        {
            "status": "NEW",
            "second_name": "Михайло",
            "legal_entity_name": "КНП \"Перший Черкаський міський центр первинної медико-санітарної допомоги\"",
            "last_name": "Павлович",
            "inserted_at": "2017-06-19T07:48:37.055044",
            "id": "202a4707-d3a5-4494-94e1-f887261c18a4",
            "first_name": "Шевченко",
            "edrpou": "38469862"
        }
    ]
}

**Comment by lymychp** [comment]
employee_request - заявка на створення employee
тільки після підтвердження користувачем буде на основі даних з employee_request створений новий employee. Або будуть оновлені дані по існуючому, якщо співпадає ІПН та дата народження. Підтвердження виконується по лінку, що відправляєтсья на email після створення employee_request
