### ISSUE TITLE
Помилка при оновленні даних співробітника

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#104]
## Steps to Reproduce (Repro steps)

- [ ] /api/employee_requests
- [ ] Створюмо і підтверджуємо співробітника "employee_id" : "fe55fcb0-10b6-44a8-ae0b-9867ffb36911"
- [ ] редагуємо дані по співробітнику, робимо запит POST /api/employee_requests де в атрибут employee_id передаємо "fe55fcb0-10b6-44a8-ae0b-9867ffb36911", на почті підтверджуємо зміни.

## Actual result
- [ ] Дані по співробітника "fe55fcb0-10b6-44a8-ae0b-9867ffb36911" змінились, а також додатково створився "employee_id" : "7f4ab2e0-9a7b-4766-a070-78d92a927796" з аналогічним набором даних.

## Expected result
- [ ] оновлюються дані по співробітнику, дубль не створюється.

**Comment by sreva** [comment]
Якщо потрібно, можемо прогнати ще один кейс і додати до задачі самі запити.

**Comment by lymychp** [comment]
не треба, сьогодні буде нова версія на демо з фіксом
