### ISSUE TITLE
Не перевіряється відповідність ИНН даті народження при редагуванні співробітника

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#106]
Не перевіряється відповідність ИНН даті народження при редагуванні співробітника

**Comment by AlekzandrV** [comment]
Можете детальніше описати, що саме не перевіряється та надати приклад запиту?

**Comment by pieskov** [comment]
При редагуванні даних співробітника можна вказати будь яку дату народження и все пройде без помилок.

**Comment by AlekzandrV** [comment]
Це відома проблема і на дев вже виправлена. В найближчому релізі на демо буде діставлена на демо

Як буде: Через Employee request можна змінити все особі та деталям лікаря, окрім:
* birth_date
* tax_id
* employee_type
* start_date
* legal_entity_id
