### ISSUE TITLE
Ид OWNER'a при створенні LegalEntity

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#107]
Чи можна при створені LegalEntity принаймі повертати ИД OWNER'a, щоб ми могли його зберігати у себе і мати його Ид щоб на пряму отримувати по ньому данні. а на запитувати employees для LegalEntity з типом OWNER.

Булоб дуже зручно нам. а Вам + 100 в карму.

**Comment by AlekzandrV** [comment]
На момент створення Legal Entity та на момент респонсу ще немає створеного співробітника з типом OWNER, є лише запит на створення співробітника, який OWNER повинен підтвердити. Тому ми додали в респонс 'employee_request_id', щоб з нього вже можна було знайти співробітника чи статус запиту

**Comment by pieskov** [comment]
+100
