### ISSUE TITLE
Get authorize token на DEMO

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#109]
## Request

{
   "token":{
      "grant_type":"password",
      "email":"sp.virny+100@gmail.com",
      "password":"UmE0L0d4d2NpZ2MyQnVOdDVleXBDQT09",
      "client_id":"786d84d9-e1c5-4d58-9f0f-f5f3d826b26e",
      "scope":"app:authorize"
   }
}

## Result

{
    "meta": {
        "url": "http://demo.ehealth.world/oauth/tokens",
        "type": "object",
        "request_id": "lfcoq070asj4eqn3pq1v57fe884k2ctn",
        "code": 401
    },
    "error": {
        "invalid_client": "Client is not allowed to issue login token."
    }
}

**Comment by pzhuk** [comment]
"grant_type":"password" ніколи не має виконуватись зі сторони client_id MIS/MSP. Цей запит, виконується технічно зі сторони E-health фронтенду, на E-Health backend. 
Тобто з client_id який належить MSP такий тест ніколи не буде успішний
