### ISSUE TITLE
Лист підтвердження реєстрації

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#11]
Є декілька питань по листу підтвердження реєстрації.
В тому вигляді в якому він є зараз він більше підходить для всіх співробітників крім "Керівника".
Для куріника пропоную змінити текст на:
"Вітаємо!
Ви зробили перший крок в рамках впровадження в Україні електронної системи охорони здоров'я.
Цим листом ми підтверджуємо, що заклад "...", який зареєстровано за адресою: ..... зареєстровано в системі eHealth.

Для завершення реєстрації, будь ласка, перейдіть за посиланням:

........
"

А також, додати щось про те що функціонал поки, що не повний чекайте.

Тепер по багам:
1) https://prnt.sc/fe695v - не виводить адресу, вказана не назва посади, а ІД
2) https://prnt.sc/fe68q3 - не вірний формат дати
3) https://prnt.sc/fe68zj - по нажаттю на "Прийняв запрошення" нічого не відбувається

**Comment by sreva** [comment]
"request_id" : "sq9fom9k9crb0tus825vkpvsarsidsrs"
[request data.txt](https://github.com/ehealth-ua/api-spec/files/1041547/request.data.txt)
[signedRequestData_.txt](https://github.com/ehealth-ua/api-spec/files/1041554/signedRequestData_.txt)

**Comment by lymychp** [comment]
[request data.txt](https://github.com/ehealth-ua/api-spec/files/1041573/request.data.txt)
[signedRequestData_.txt](https://github.com/ehealth-ua/api-spec/files/1041576/signedRequestData_.txt)

**Comment by warehousman** [comment]
"request_id" : "sq9fom9k9crb0tus825vkpvsarsidsrs"
[request data.txt](https://github.com/ehealth-ua/api-spec/files/1041970/request.data.txt)
[signedRequestData_.txt](https://github.com/ehealth-ua/api-spec/files/1041971/signedRequestData_.txt)

**Comment by lymychp** [comment]
Знайшли декілька проблем в реквесті:
1. "birth_date": "19.11.1998", некоректний формат, має бути "1998-11-19"
2. settlement_id має бути з довідника UAddresses

**Comment by warehousman** [comment]
3. Во втором адресе нет атрибута type

**Comment by warehousman** [comment]
4. "legal_form": "540", это значение было удалено из справочника по просьбе Иры Шевченко

**Comment by warehousman** [comment]
Ви зробили перший крок в рамках впровадження в Україні електронної системи охорони здоров'я.
Цим листом ми підтверджуємо, що заклад "...", який зареєстровано за адресою: ..... зареєстровано в системі eHealth. - этот текст можем добавить в текст письма про подтверждение регистрации до релиза полноценной версии.

**Comment by lymychp** [comment]
> 1. https://prnt.sc/fe695v - не виводить адресу, вказана не назва посади, а ІД
> 2. https://prnt.sc/fe68q3 - не вірний формат дати
> 3. https://prnt.sc/fe68zj - по нажаттю на "Прийняв запрошення" нічого не відбувається

Все поправили і додали валідації. Усі проблеми були через те, що при створенні legal_entity був переданий некоректний контент:
  * birth_date format
  * address type
  * settlement_id

Спробуйте сформувати коректний json і повторити.
