### ISSUE TITLE
Create legal entity (edrpou)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#110]
json data includes edrpou but still returns error

## Request 
{
  "signed_legal_entity_request":
"MIIZPgYJKoZIhvcNAQcCoIIZLzCCGSsCAQExDjAMBgoqhiQCAQEBAQIBMIIJzAYJKoZIhvcNAQcBoIIJvQSCCbl7DQogICJuYW1lIjogIjEiLA0KICAic2hvcnRfbmFtZSI6ICIxIiwNCiAgInB1YmxpY19uYW1lIjogIjEiLA0KICAidHlwZSI6ICJNU1AiLA0KICAib3duZXJfcHJvcGVydHlfdHlwZSI6ICJQUklWQVRFIiwNCiAgImxlZ2FsX2Zvcm0iOiAiMTIwIiwNCiAgImVkcnBvdSI6ICIzMDMwMDc3MSIsDQogICJrdmVkcyI6IFsNCiAgICAiODYuMTAiDQogIF0sDQogICJhZGRyZXNzZXMiOiBbDQogICAgew0KICAgICAgInppcCI6ICI3MDA5MCIsDQogICAgICAidHlwZSI6ICJSRUdJU1RSQVRJT04iLA0KICAgICAgInN0cmVldF90eXBlIjogIlNUUkVFVCIsDQogICAgICAic3RyZWV0IjogItCo0LXQstGH0LXQvdC60LAiLA0KICAgICAgInNldHRsZW1lbnRfdHlwZSI6ICJWSUxMQUdFIiwNCiAgICAgICJzZXR0bGVtZW50X2lkIjogIjIzNUQ4NUJDLTEwQjUtNDdENS1CMzRGLTAwQTk4MURGRTY4QSIsDQogICAgICAic2V0dGxlbWVudCI6ICLQotCe0J/QntCg0IbQkiIsDQogICAgICAicmVnaW9uIjogItCR0KPQodCs0JrQmNCZIiwNCiAgICAgICJjb3VudHJ5IjogIlVBIiwNCiAgICAgICJidWlsZGluZyI6ICIxIiwNCiAgICAgICJhcmVhIjogItCb0KzQktCG0JLQodCs0JrQkCIsDQogICAgICAiYXBhcnRtZW50IjogIjEiDQogICAgfQ0KICBdLA0KICAicGhvbmVzIjogWw0KICAgIHsNCiAgICAgICJ0eXBlIjogIkxBTkRfTElORSIsDQogICAgICAibnVtYmVyIjogIiszODA2MzIxNTkzODAiDQogICAgfQ0KICBdLA0KICAiZW1haWwiOiAiaXZhbnBhYmVyQGdtYWlsLmNvbSIsDQogICJvd25lciI6IHsNCiAgICAiZmlyc3RfbmFtZSI6ICJUZXN0IiwNCiAgICAibGFzdF9uYW1lIjogIlRlc3QiLA0KICAgICJzZWNvbmRfbmFtZSI6ICJUZXN0b3Z1Y2giLA0KICAgICJ0YXhfaWQiOiAiMzA2NzMwNTk5OCIsDQogICAgImJpcnRoX2RhdGUiOiAiMjAxNy0wOC0yMSIsDQogICAgImJpcnRoX3BsYWNlIjogItCb0KzQstGW0LIiLA0KICAgICJnZW5kZXIiOiAiTUFMRSIsDQogICAgImVtYWlsIjogIml2YW5wYWJlckBnbWFpbC5jb20iLA0KICAgICJkb2N1bWVudHMiOiBbDQogICAgICB7DQogICAgICAgICJ0eXBlIjogIlBBU1NQT1JUIiwNCiAgICAgICAgIm51bWJlciI6ICIwNDIxMzUiDQogICAgICB9DQogICAgXSwNCiAgICAicGhvbmVzIjogWw0KICAgICAgew0KICAgICAgICAidHlwZSI6ICJNT0JJTEUiLA0KICAgICAgICAibnVtYmVyIjogIiszODA2MzIxNTkzODAiDQogICAgICB9DQogICAgXSwNCiAgICAicG9zaXRpb24iOiAiUDEiDQogIH0sDQogICJtZWRpY2FsX3NlcnZpY2VfcHJvdmlkZXIiOiB7DQogICAgImxpY2Vuc2VzIjogWw0KICAgICAgew0KICAgICAgICAid2hhdF9saWNlbnNlZCI6ICLQmtCy0LDQu9GW0YTRltC60LDRhtC50L3QsCDQutC+0LzRltGB0ZbRjyIsDQogICAgICAgICJsaWNlbnNlX251bWJlciI6ICJmZDEyMzQ1NiIsDQogICAgICAgICJpc3N1ZWRfZGF0ZSI6ICIyMDEyLTEyLTI4IiwNCiAgICAgICAgImlzc3VlZF9ieSI6ICJ0ZXN0IiwNCiAgICAgICAgImV4cGlyeV9kYXRlIjogIjIwNTAtMTItMjgiLA0KICAgICAgICAiYWN0aXZlX2Zyb21fZGF0ZSI6ICIyMDE3LTA4LTIzIiwNCiAgICAgICAgIm9yZGVyX25vIjogImZkNjU0MzIxIg0KICAgICAgfQ0KICAgIF0sDQogICAgImFjY3JlZGl0YXRpb24iOiB7DQogICAgICAiY2F0ZWdvcnkiOiAiRklSU1QiLA0KICAgICAgImlzc3VlZF9kYXRlIjogIjIwMTctMDgtMjMiLA0KICAgICAgImV4cGlyeV9kYXRlIjogIjIwMjItMDgtMDEiLA0KICAgICAgIm9yZGVyX25vIjogImZkNjU0MzIxIiwNCiAgICAgICJvcmRlcl9kYXRlIjogIjIwMTctMDgtMTYiDQogICAgfQ0KICB9LA0KICAic2VjdXJpdHkiOiB7DQogICAgInJlZGlyZWN0X3VyaSI6ICJodHRwczovL3BvcnRhbC1kb2N0b3IuZWxla3MuY29tL3dlYi9laGVhbHRoIg0KICB9LA0KICAicHVibGljX29mZmVyIjogew0KICAgICJjb25zZW50IjogdHJ1ZSwNCiAgICAiY29uc2VudF90ZXh0IjogItCX0L7QsdC+0LIn0Y/Qt9GD0Y7RgdGMINC00L7RgtGA0LjQvNGD0LLQsNGC0LjRgdGMINCg0LXQs9C70LDQvNC10L3RgtGDINGE0YPQvdC60YbRltC+0L3Rg9Cy0LDQvdC90Y8g0YHQuNGB0YLQtdC80LggZUhlYWx0aC4g0J/RltC00YLQstC10YDQtNC20YPRjiDQtNC+0YHRgtC+0LLRltGA0L3RltGB0YLRjCDQstC60LDQt9Cw0L3QuNGFINC80L3QvtGOINC00LDQvdC40YUg0YLQsCDQtNC+0LHRgNC+0LLRltC70YzQvdGW0YHRgtGMINC90LDQtNCw0L3QvdGPINGG0LjRhSDQtNCw0L3QuNGFLiDQo9GB0LLRltC00L7QvNC70Y7Rjiwg0YnQviDRgyDQstC40L/QsNC00LrRgyDQvdCw0LTQsNC90L3RjyDQvNC90L7RjiDQvdC10LLRltGA0L3QvtGXINGW0L3RhNC+0YDQvNCw0YbRltGXLCDQvNC10L3RliDQvNC+0LbQtSDQsdGD0YLQuCDQstGW0LTQvNC+0LLQu9C10L3QviDRgyDRgNC10ZTRgdGC0YDQsNGG0ZbRlyDQsiDRgdC40YHRgtC10LzRliBlSGVhbHRoLiINCiAgfQ0KfaCCBy0wggcpMIIG0aADAgECAhQztst79yG5zgQAAAB9wyEASWFPADANBgsqhiQCAQEBAQMBATCCAVAxVDBSBgNVBAoMS9CG0L3RhNC+0YDQvNCw0YbRltC50L3Qvi3QtNC+0LLRltC00LrQvtCy0LjQuSDQtNC10L/QsNGA0YLQsNC80LXQvdGCINCU0KTQoTFeMFwGA1UECwxV0KPQv9GA0LDQstC70ZbQvdC90Y8gKNGG0LXQvdGC0YApINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTFiMGAGA1UEAwxZ0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExFDASBgNVBAUMC1VBLTM5Mzg0NDc2MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIwHhcNMTcwMTE3MjIwMDAwWhcNMTkwMTE3MjIwMDAwWjCB3zE8MDoGA1UECgwz0KLQntCSICLQldCk0IbQoiDQotCV0JrQndCe0JvQntCU0JbQhtChIiAo0KLQldCh0KIpMREwDwYDVQQLDAjQotC10YHRgjERMA8GA1UEDAwI0YLQtdGB0YIxGDAWBgNVBAMMD9Ci0LXRgdGCINCiLtCiLjERMA8GA1UEBAwI0KLQtdGB0YIxGjAYBgNVBCoMEdCi0LXRgdGCINCi0LXRgdGCMRAwDgYDVQQFDAcyMjEyNzMzMQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIwgfIwgckGCyqGJAIBAQEBAwEBMIG5MHUwBwICAQECAQwCAQAEIRC+49tq6p4fhleMRcEllP+UI5Sn1zj5GH5lFQFylPTOAQIhAIAAAAAAAAAAAAAAAAAAAABnWSE68YLph9PhdxSQfUcNBCG2D9LY3OipNCPGEBvKkcR6AH5sMAsmzVVsmw59IO8pKgAEQKnW60XxPHCCgMSWeyMfXq32WOukwDcpHTjZa/Alyk4X+OlyDcYVtDool18Lwd6jZDi1ZOosF5/QEj5tuPrFeQQDJAAEIZGDb2seIO/u4I3wv8PAqSNdIuAwtuyMrKWnc0qZAw0iAKOCA1gwggNUMCkGA1UdDgQiBCBUL7RNpgF5Cez6tDtwY/HhONbweSp8VvKrBW2wtIECwjArBgNVHSMEJDAigCAztst79yG5zu7j3i5i/uo7cBpLZ2C8HC/PNWUWtQ68qjAvBgNVHRAEKDAmoBEYDzIwMTcwMTE3MjIwMDAwWqERGA8yMDE5MDExNzIyMDAwMFowDgYDVR0PAQH/BAQDAgbAMBkGA1UdIAEB/wQPMA0wCwYJKoYkAgEBAQICMAwGA1UdEwEB/wQCMAAwHgYIKwYBBQUHAQMBAf8EDzANMAsGCSqGJAIBAQECATCBpwYDVR0RBIGfMIGcoE0GDCsGAQQBgZdGAQEEAqA9DDswNDA4Niwg0LwuINCa0LjRl9CyLCDQstGD0LsuINCe0LvQtdC90Lgg0KLQtdC70ZbQs9C4LCAzOS3QkKAmBgwrBgEEAYGXRgEBBAGgFgwUKzM4ICgwIDQ0KSAzODMtMzItMzeBEGluZm9AZWZpdC5jb20udWGgEQYKKwYBBAGCNxQCA6ADDAE2MEgGA1UdHwRBMD8wPaA7oDmGN2h0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jcmxzL0FDU0tJRERERlMtRnVsbC5jcmwwSQYDVR0uBEIwQDA+oDygOoY4aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NybHMvQUNTS0lERERGUy1EZWx0YS5jcmwwgYgGCCsGAQUFBwEBBHwwejAwBggrBgEFBQcwAYYkaHR0cDovL2Fjc2tpZGQuZ292LnVhL3NlcnZpY2VzL29jc3AvMEYGCCsGAQUFBzAChjpodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxvYWQvY2VydGlmaWNhdGVzL2FsbGFjc2tpZGQucDdiMD8GCCsGAQUFBwELBDMwMTAvBggrBgEFBQcwA4YjaHR0cDovL2Fjc2tpZGQuZ292LnVhL3NlcnZpY2VzL3RzcC8wZQYDVR0JBF4wXDAaBgwqhiQCAQEBCwEEAgExChMIMzg3ODIzMjMwHAYMKoYkAgEBAQsBBAEBMQwTCjExMTExMTExMTEwIAYMKoYkAgEBAQsBBAsBMRATDjE5OTEwODI0LTAwMDI2MA0GCyqGJAIBAQEBAwEBA0MABEANDSYnZP3K3h4btUkLXDQ1UhVjcCI1XowtD0+hX343N9xfwWOq34G+hYlPAogkNSrjj8erdoGh+xptn9qtUi8aMYIIEzCCCA8CAQEwggFqMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUM7bLe/chuc4EAAAAfcMhAElhTwAwDAYKKoYkAgEBAQECAaCCBjswGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTcwODIzMDk1NjA1WjAvBgkqhkiG9w0BCQQxIgQggdPVFblfYwoP90wbcx3sB3iyaFtCMaVL3bxF9z6Mr5cwggHDBgsqhkiG9w0BCRACLzGCAbIwggGuMIIBqjCCAaYwDAYKKoYkAgEBAQECAQQgu3HKZnnH4cO5cwoRg4uYEfQRNFf4iiIdOVHDcyfybdAwggFyMIIBWKSCAVQwggFQMVQwUgYDVQQKDEvQhtC90YTQvtGA0LzQsNGG0ZbQudC90L4t0LTQvtCy0ZbQtNC60L7QstC40Lkg0LTQtdC/0LDRgNGC0LDQvNC10L3RgiDQlNCk0KExXjBcBgNVBAsMVdCj0L/RgNCw0LLQu9GW0L3QvdGPICjRhtC10L3RgtGAKSDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExYjBgBgNVBAMMWdCQ0LrRgNC10LTQuNGC0L7QstCw0L3QuNC5INGG0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMRQwEgYDVQQFDAtVQS0zOTM4NDQ3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQztst79yG5zgQAAAB9wyEASWFPADCCBAcGCyqGSIb3DQEJEAIUMYID9jCCA/IGCSqGSIb3DQEHAqCCA+MwggPfAgEDMQ4wDAYKKoYkAgEBAQECATBrBgsqhkiG9w0BCRABBKBcBFowWAIBAQYKKoYkAgEBAQIDATAwMAwGCiqGJAIBAQEBAgEEIIHT1RW5X2MKD/dMG3Md7Ad4smhbQjGlS928Rfc+jK+XAgQDQmcTGA8yMDE3MDgyMzA5NTYwM1oxggNbMIIDVwIBATCCARMwgfoxPzA9BgNVBAoMNtCc0ZbQvdGW0YHRgtC10YDRgdGC0LLQviDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotChINCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQstGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEtMDAwMTU2MjItMjAxMjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQwBHUd7yx4rgIAAAABAAAATgAAADAMBgoqhiQCAQEBAQIBoIIB2jAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwHAYJKoZIhvcNAQkFMQ8XDTE3MDgyMzA5NTYwM1owLwYJKoZIhvcNAQkEMSIEIEsOQiGOuvh7H4FymeS5CrSsPw2koyxAWhr8ep86SDEGMIIBawYLKoZIhvcNAQkQAi8xggFaMIIBVjCCAVIwggFOMAwGCiqGJAIBAQEBAgEEIJcRIAuIXEA66kPAobtFVzHIHYtOrppo+r7SnKM/odYBMIIBGjCCAQCkgf0wgfoxPzA9BgNVBAoMNtCc0ZbQvdGW0YHRgtC10YDRgdGC0LLQviDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotChINCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQstGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEtMDAwMTU2MjItMjAxMjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQwBHUd7yx4rgIAAAABAAAATgAAADANBgsqhiQCAQEBAQMBAQRAiyjgK+c/i+4F51rpYQ6twKtzKo4mDhdbH7Dpc0+asVq0LZNiEfPVcKuScjlJmjQ+ZmgruXBctRHw6QJCqWd2BDANBgsqhiQCAQEBAQMBAQRAqWrC9CkX5Zy5EG+vx0S3P2918/ZrrTaqy56WLfiqoGq1mEkR9JeTG/U2kfHhqPEBofVF/UcAJSh7HygCAOumew==",
  "signed_content_encoding":"base64"
}

## Response 

{
    "meta": {
        "url": "http://demo.ehealth.world/api/legal_entities",
        "type": "object",
        "request_id": "ser3l42l35pgqr3m8tag1mh2feicoamf",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "inclusion",
                        "params": [
                            "30300771"
                        ],
                        "description": "is invalid"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.edrpou"
            }
        ]
    }
}

**Comment by lymychp** [comment]
please check that edrpou from the json is equal to the edrpou of the digital sign.
