### ISSUE TITLE
Потрібна допомога з пошуком вулиці

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#111]
Робимо запит з http://docs.ehealthmisapi.apiary.io/#reference/public.-medical-service-provider-integration-layer/search-streets/list-of-streets-by-search-params?console=1:
`GET http://demo.ehealth.world/streets?settlement_id=adaa4abf-f530-461c-bcbf-a0ac210d955b`
Отримуємо відповідь:
`{
    "status" : "error",
    "message" : "Not Found",
    "statusCode" : 404,
    "headers" : {
        "server" : "Cowboy",
        "date" : "Thu, 24 Aug 2017 13:02:44 GMT",
        "content-length" : "156",
        "cache-control" : "max-age=0, private, must-revalidate",
        "x-request-id" : "a6nfk177dr62ai53i23oqfftk1h1b038",
        "content-type" : "application/json; charset=utf-8"
    },
    "body" : {
        "meta" : {
            "url" : "http://demo.ehealth.world/streets",
            "type" : "object",
            "request_id" : "a6nfk177dr62ai53i23oqfftk1h1b038",
            "code" : 404
        },
        "error" : {
            "type" : "not_found"
        }
    }
}`

Робимо запит на зразок запитів у постман по містам: 
`GET http://demo.ehealth.world/api/uaddresses/search/streets?settlement_id=adaa4abf-f530-461c-bcbf-a0ac210d955b`

Отримуємо відповідь: 
`{
    "paging": {
        "size": null,
        "limit": 10,
        "has_more": false,
        "cursors": {
            "starting_after": null,
            "ending_before": null
        }
    },
    "meta": {
        "url": "http://demo.ehealth.world/search/streets",
        "type": "list",
        "request_id": "bo3qn8bkummff2b7j2kbsj3f3ai3h9qq",
        "code": 200
    },
    "data": []
}`

Підкажіть, будь ласка, як правильно зробити пошук вулиці

**Comment by pzhuk** [comment]
Список вулиць поки що не на демо

**Comment by sreva** [comment]
@pzhuk А запит правильний?

**Comment by lymychp** [comment]
приклад запиту на пошук вулиці
```
curl -X GET \
  'http://demo.ehealth.world/api/uaddresses/streets?settlement_id=ce99fe75-b9b5-4ddc-aa09-a9f1dd3d93e1&type=STREET
```
просто в демо не всі міста мають вулиці

**Comment by sreva** [comment]
Дякую
