### ISSUE TITLE
Помилка при створенні declaration requests з офлайн авторизацією

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#112]
## Steps to Reproduce (Repro steps)

- [ ] http://demo.ehealth.world/api/declaration_requests
- [ ] Створюємо declaration requests з типом авторизації OFFLINE, не передаємо атрибут phones (він не обов'язковий з даним типом авторизації у відповідності до [специфікації](http://docs.ehealthmisapi.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/create-declaration-request) )
Запит: 
```
 {
  "declaration_request": {
    "person": {
      "first_name": "Рева",
      "last_name": "Сергій",
      "second_name": "Петрович",
      "birth_date": "1991-08-19",
      "birth_country": "Україна",
      "birth_settlement": "Германівка",
      "gender": "MALE",
      "tax_id": "3378115538",
      "secret": "Слово1",
      "documents": [
                {
                    "type" : "NATIONAL_ID",
                    "number" : "11111111111111111"
                }
      ],
      "addresses": [
      {
        "type": "REGISTRATION",
        "country": "UA",
        "area": "ЛЬВІВСЬКА",
        "region": "ПУСТОМИТІВСЬКИЙ",
        "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
        "settlement_type": "CITY",
        "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
        "street_type": "STREET",
        "street": "Ніжинська",
        "building": "15",
        "apartment": "23",
        "zip": "02090"
      },
      {
        "type": "RESIDENCE",
        "country": "UA",
        "area": "ЛЬВІВСЬКА",
        "region": "ПУСТОМИТІВСЬКИЙ",
        "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
        "settlement_type": "CITY",
        "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
        "street_type": "STREET",
        "street": "Ніжинська",
        "building": "15",
        "apartment": "23",
        "zip": "02090"
      }
    ],
     
      "authentication_methods": [
        {
          "type": "OFFLINE"
        }
      ],
      "emergency_contact": {
        "first_name": "Петро",
        "last_name": "Іванов",
        "second_name": "Миколайович",
        "phones": [
          {
            "type": "MOBILE",
            "number": "+380503410870"
          }
        ]
      },
      "patient_signed": false,
      "process_disclosure_data_consent": true
    },
    "scope": "FAMILY_DOCTOR",
    "employee_id": "27116b6c-5ab3-41e3-a882-b06fd994e19a",
    "division_id": "17e39df8-f6f4-4283-a6f8-32b75edac9d6"
  }
}
```

## Actual result
- [ ] `{
    "meta": {
        "url": "http://demo.ehealth.world/api/declaration_requests",
        "type": "object",
        "request_id": "scifnvejoqep803ho8g7k3pnr1kvl952",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": null,
                        "params": [],
                        "description": "Error during MAN interaction. Result from MAN: \"{\\\"type\\\":\\\"internal_error\\\"}\""
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.printout_content"
            }
        ]
    }
} `

## Expected result
- [ ] Можна створити declaration requests.

**Comment by AlekzandrV** [comment]
Помилка виправлена. Фікс задеплоено на демо

**Comment by sreva** [comment]
дякую
