### ISSUE TITLE
Старий овнер після перереєстрації МСП може авторизуватися. Потрібна консультація

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#113]
## Steps to Reproduce (Repro steps)

- [ ] http://demo.ehealth.world/api/legal_entities 
- [ ] Вже є зареєстрований МСП.  id = 879d1c9a-1e59-46bf-8dad-75f625d32c5b
- [ ] Перереєстровуємо МСП, створюємо нового овнера і підтверждуємо його. 
    employee_request_id (нового керівника) = 50e457db-2570-4899-9bb0-ddc9a0765a91
    employee_id (нового керівника) : e867646a-3aba-4105-88b0-0513d796d268
    request_id (реєстрації)  = uqm099c5tepigkog5uhi0ophf8e97jgn
    email (нового керівника) = reva.serhii@gmail.com
    email (старого керівника) = petrovich130@ukr.net
    employee_id (старого керівника) : 538e232c-f327-48f2-9ce9-537e8b94d475
## Actual result
- [ ] Система дає можливість авторизуватися старому овнеру "petrovich130@ukr.net"

## Expected result
- [ ] Потрібна консультація. Так і має бути, чи тут помилка.

**Comment by lymychp** [comment]
так не має бути. Взяли в роботу

**Comment by AlekzandrV** [comment]
Помилка локалізована та виправлена на Дев. Найближчим часом буде доставлено на Демо

**Comment by AlekzandrV** [comment]
Виправлення вже на Демо. Перевірте будь-ласка

**Comment by sreva** [comment]
Дякую
