### ISSUE TITLE
Тестування АЦСК МВС

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#115]
Тестування нового АЦСК http://ca.mvs.gov.ua/

**Comment by lymychp** [comment]
залили сертифікат на демо

**Comment by pzhuk** [comment]
Об"єкт register legal entity піписаний він АЦСК МВС
На демо запит не працює - віддає 

```
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "json"
                    }
                ],
                "entry_type": "request"
            }



```
[msp.json.p7s.txt](https://github.com/ehealth-ua/api-spec/files/1287951/msp.json.p7s.txt)

**Comment by pzhuk** [comment]
done
