### ISSUE TITLE
Повернення 401 коду замість 403 при "протуханні" access token

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#118]
Є побажання, _якщо це можливо звичайно_, повертати 401 код замість 403 при "протуханні" _access token_. 
Визвано тим, що ми запитуємо endpoint, до якого у користувача немає доступу і отримуємо 403 - forbidden, у відповідності до специфікації oAuth, при отриманні 403 коду ми маємо зміннювати 
_refresh token_ на _access token_ . А по факту у користувача лише немає до цього доступу і оновлювати токен не потрібно. Як інший варіант вирішення, цього питання у боді 403 передавати якийсь параметр, щоб ми могли по ньому розрізняти.

**Comment by pzhuk** [comment]
@lymychp що скажеш на цю пропозицію? Виходить, що у нас overlap по reponse кодах від різних сервісів, 403 може повертати і auth і інші.

**Comment by lymychp** [comment]
@sreva will fix that

**Comment by lymychp** [comment]
deployed to demo
