### ISSUE TITLE
уточнити HTTP відповідь в settlements search

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#12]
http://demo.ehealth.world/api/uaddresses/search/settlements?settlement_name=Луц&region=Воли&district=Волинська

В такому запиті маємо HTTP/200, хоча нічого не знайдень. Пропонується уточнити на HTTP/204, наприклад

**Comment by pzhuk** [comment]
@lymychp що скажеш?

**Comment by lymychp** [comment]
@pzhuk ok, поправимо

**Comment by warehousman** [comment]
Transfered to project backlog #314
