### ISSUE TITLE
При реєстрації клініки виникає неідентифікована помилка

### ISSUE THREAD

**Issue by akelara** [ehealth-ua/api-spec#120]
## Steps to Reproduce (Repro steps)
1. Регистрируем клинику в eHealth на Production
2. Отправляем:
`data:application/pkcs7-signature;base64,MIINYwYJKoZIhvcNAQcCoIINVDCCDVACAQExDjAMBgoqhiQCAQEBAQIBMAsGCSqGSIb3DQEHAaCCBjgwggY0MIIFsKADAgECAhQZFacGAAAAAAAAAAAAAAAAAAAAATANBgsqhiQCAQEBAQMBATCCARwxWzBZBgNVBAMMUtCQ0KbQodCaINCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxETAPBgNVBAcMCNCa0LjRl9CyMRkwFwYDVQQFDBBVQS0zNjg2NTc1My0wMTE0MVIwUAYDVQQKDEnQotCe0JIgItCm0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C90LAiMS4wLAYDVQQLDCXQktGW0LTQtNGW0Lsg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXMQswCQYDVQQGDAJVQTAeFw0xNjEyMTQwODM0MzlaFw0xNzEyMTMyMTU5NTlaMIIBlDEmMCQGA1UEAwwd0J/QntCd0J7QnNCQ0KDQldCd0JrQniDQni7QkC4xKTAnBgNVBAgMINCU0J3QhtCf0KDQntCf0JXQotCg0J7QktCh0KzQmtCQMRwwGgYDVQQHDBPQmtCQ0Jwn0K/QndCh0KzQmtCVMQ4wDAYDVQQRDAU1MTkzNDE9MDsGA1UECQw00J/QoNCe0KHQn9CV0JrQoiDQkNCd0J7QqNCa0IbQndCQLCDQkdCj0JTQmNCd0J7QmiA3MjEkMCIGA1UEDAwb0JPQvtC70L7QstC90LjQuSDQu9GW0LrQsNGAMR8wHQYDVQQEDBbQn9Ce0J3QntCc0JDQoNCV0J3QmtCeMTAwLgYDVQQqDCfQntCb0JXQmtCh0IbQmSDQkNCd0JDQotCe0JvQhtCZ0J7QktCY0KcxFDASBgNVBAUMCzI2NDQxMTEwNzdEMTYwNAYDVQQKDC3QmtCXICLQmtCQ0Jwn0K/QndCh0KzQmtCQINCc0Jsg4oSWIDkiINCU0J7QoCIxCzAJBgNVBAYMAlVBMFswHgYLKoYkAgEBAQEDAQEwDwYNKoYkAgEBAQEDAQECCQM5AAQ2De5EmngvlMOKFdgf4QNsuERp29SddZ4ByzUIt6wFISyKEScmeTXgImbCLavNEQuTI4xFrTRZo4ICTTCCAkkwQwYDVR0JBDwwOjAaBgwqhiQCAQEBCwEEAgExChMIMDE5ODU4NjAwHAYMKoYkAgEBAQsBBAEBMQwTCjI2NDQxMTEwNzcwHwYDVR0RBBgwFoEUenZpdDAxOTg1ODYwQHVrci5uZXQwKQYDVR0OBCIEIDAaxd1S2lkdEf2kSsMxoysnUx//fCoFNYgyLUOIbcTpMCsGA1UdIwQkMCKAILEo01R0J5ei74nN0y6lQDGfX3/OHrjqM/VkdvWcPIChMA4GA1UdDwEB/wQEAwIAwDAYBgNVHSUEETAPBg0qhiQCAQEBC5HKjVkBMBkGA1UdIAEB/wQPMA0wCwYJKoYkAgEBAQICMDIGCCsGAQUFBwEDAQH/BCMwITALBgkqhiQCAQEBAgEwEgYDBAACMAsTA1VBSAIBAQIBBjAzBgNVHS4ELDAqMCigJqAkhiJodHRwOi8vdWFrZXkuY29tLnVhL2xpc3QtZGVsdGEuY3JsMC0GA1UdHwQmMCQwIqAgoB6GHGh0dHA6Ly91YWtleS5jb20udWEvbGlzdC5jcmwwPQYIKwYBBQUHAQsEMTAvMC0GCCsGAQUFBzADhiFodHRwOi8vdWFrZXkuY29tLnVhL3NlcnZpY2VzL3RzcC8wbQYIKwYBBQUHAQEEYTBfMC0GCCsGAQUFBzAChiFodHRwOi8vdWFrZXkuY29tLnVhL3Vha2V5Y2VydC5wN2IwLgYIKwYBBQUHMAGGImh0dHA6Ly91YWtleS5jb20udWEvc2VydmljZXMvb2NzcC8wDQYLKoYkAgEBAQEDAQEDbwAEbMkpquvz0LlXDIz19lIHRPARTY+rTL/n0Monu0kR0pLUowvd2Ytq0nJgBLhjDOFI4Cexzq+eHZN7IhKYwPqa6j01+p/7dEL/vp/EQMic1HJT32lhkE1lUgyUj5sRSHx4PyXR9J982cHvOYU0IzGCBvAwggbsAgEBMIIBNjCCARwxWzBZBgNVBAMMUtCQ0KbQodCaINCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxETAPBgNVBAcMCNCa0LjRl9CyMRkwFwYDVQQFDBBVQS0zNjg2NTc1My0wMTE0MVIwUAYDVQQKDEnQotCe0JIgItCm0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C90LAiMS4wLAYDVQQLDCXQktGW0LTQtNGW0Lsg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXMQswCQYDVQQGDAJVQQIUGRWnBgAAAAAAAAAAAAAAAAAAAAEwDAYKKoYkAgEBAQECAaCCBSAwGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTcwOTA2MDgxOTQwWjAvBgkqhkiG9w0BCQQxIgQgvTxRaMCwM0DWZ3FoRprRmt0NQHJS2Jb8XDVHvXeyxfEwggGPBgsqhkiG9w0BCRACLzGCAX4wggF6MIIBdjCCAXIwDAYKKoYkAgEBAQECAQQgvnAuN+ylUlubgXMM/JDCTmVOZ9B0QIeycvp7MF4OVsgwggE+MIIBJKSCASAwggEcMVswWQYDVQQDDFLQkNCm0KHQmiDQotCe0JIgItCm0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C90LAiMREwDwYDVQQHDAjQmtC40ZfQsjEZMBcGA1UEBQwQVUEtMzY4NjU3NTMtMDExNDFSMFAGA1UECgxJ0KLQntCSICLQptC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgItCj0LrRgNCw0ZfQvdCwIjEuMCwGA1UECwwl0JLRltC00LTRltC7INGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlzELMAkGA1UEBgwCVUECFBkVpwYAAAAAAAAAAAAAAAAAAAABMIIDIAYLKoZIhvcNAQkQAhQxggMPMIIDCwYJKoZIhvcNAQcCoIIC/DCCAvgCAQMxDjAMBgoqhiQCAQEBAQIBMGkGCyqGSIb3DQEJEAEEoFoEWDBWAgEBBggrBgEFBQcDCDAwMAwGCiqGJAIBAQEBAgEEIL08UWjAsDNA1mdxaEaa0ZrdDUByUtiW/Fw1R713ssXxAgQNyAgiGA8yMDE3MDkwNjA4MTkzNloxggJ2MIICcgIBAaAiBCAC/2fnFE8+R5roPnDqcqdqWwdfmxLImhiOK5eJd4ua7zAMBgoqhiQCAQEBAQIBoIIBvDAvBgkqhkiG9w0BCQQxIgQgo0+k+x26Hd41I4I7rY4oRfi0Ah7hUuP7XZ6eLJmESogwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMIIBawYLKoZIhvcNAQkQAi8xggFaMIIBVjCCAVIwggFOMAwGCiqGJAIBAQEBAgEEIB2iuRRPHWaBlJWy/rQFP/uqT4LQSEdouoVOBaEuuNsOMIIBGjCCAQCkgf0wgfoxPzA9BgNVBAoMNtCc0ZbQvdGW0YHRgtC10YDRgdGC0LLQviDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotChINCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQstGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEtMDAwMTU2MjItMjAxMjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQwBHUd7yx4rgIAAAABAAAACQAAADANBgsqhiQCAQEBAQMBAQRsArIgGBQvwiZ4cNZUFgqJnuzE7sdeCXy/+QpFnS4bPZw7vcn+ySvsmZ8klieK9XNGd+e6ZsIb5WfO8oCjHFAmJzKHw5prUFwDP5OwbtWW2HujTmAAvrWJFvnh3YYsGmuwcPdc4lhw+3cVj0kdMA0GCyqGJAIBAQEBAwEBBGw/NEAdr4sz/flmqBkgVlLuCqHezgeZ/czKduDzsnd7Chx1DtIdi9hyMFK+M8jByZe9SuhcuB0TdQVR6X0174LbMSSTc6hksX96Se6hwgIngs3W9GbiHRjfE98d2wyKLoWygFp93d8XT+HSJxk=`
## Actual result
Неизвестная ошибка.
## Expected result
Успешная регистрация.
##Additional information
Код ЕДРПОУ 01985860

**Comment by pzhuk** [comment]
вы упаковываете pkcs7 неправильно - необходимо использовать способ, когда контент и сертификат передаются одним файлом, а не отдельно, как в Вашем случае
