### ISSUE TITLE
При регистрации клиники выпадает неизвестная ошибка

### ISSUE THREAD

**Issue by akelara** [ehealth-ua/api-spec#121]
## Steps to Reproduce (Repro steps)
1. Регистрируем клинику в eHealth на Production
2. Отправляем:
`data:application/pkcs7-signature;base64,MIIWaQYJKoZIhvcNAQcCoIIWWjCCFlYCAQExDjAMBgoqhiQCAQEBAQIBMIIIRAYJKoZIhvcNAQcBoIIINQSCCDHvu797Im93bmVyIjp7ImdlbmRlciI6Ik1BTEUiLCJwaG9uZXMiOlt7InR5cGUiOiJMQU5EX0xJTkUiLCJudW1iZXIiOiIrMzgwNTYzODIyMzYzIn1dLCJkb2N1bWVudHMiOlt7InR5cGUiOiJQQVNTUE9SVCIsIm51bWJlciI6ItCQ0JogNDMzOTYzIn1dLCJsYXN0X25hbWUiOiLQmtCe0JvQntCc0J7QhNCm0KwiLCJmaXJzdF9uYW1lIjoi0JLQntCb0J7QlNCY0JzQmNCgIiwic2Vjb25kX25hbWUiOiLQnNCY0JrQntCb0JDQmdCe0JLQmNCnIiwicG9zaXRpb24iOiJQMyIsImJpcnRoX2RhdGUiOiIxOTU0LTA5LTI3IiwidGF4X2lkIjoiMTk5OTMwNzEyMCIsImVtYWlsIjoicG9rcm92a2FjcmxAdWtyLm5ldCIsImJpcnRoX3BsYWNlIjoi0J/QntCa0KDQntCS0KHQrNCa0JUsINCj0JrQoNCQ0IfQndCQIn0sIm1lZGljYWxfc2VydmljZV9wcm92aWRlciI6eyJsaWNlbnNlcyI6W3sibGljZW5zZV9udW1iZXIiOiI1OTcwNDEiLCJ3aGF0X2xpY2Vuc2VkIjoi0JzQldCU0JjQp9Cd0JAg0J/QoNCQ0JrQotCY0JrQkCIsImlzc3VlZF9ieSI6ItCc0J7QlyDQo9Ca0KDQkNCH0J3QmCIsImlzc3VlZF9kYXRlIjoiMjAxMi0wMi0wOCIsImFjdGl2ZV9mcm9tX2RhdGUiOiIyMDEyLTAxLTMwIn1dfSwiYWRkcmVzc2VzIjpbeyJhcmVhIjoi0JTQndCG0J/QoNCe0J/QldCi0KDQntCS0KHQrNCa0JAiLCJyZWdpb24iOiLQn9Ce0JrQoNCe0JLQodCs0JrQmNCZIiwic2V0dGxlbWVudCI6ItCf0J7QmtCg0J7QktCh0KzQmtCVIiwic2V0dGxlbWVudF90eXBlIjoiVE9XTlNISVAiLCJzZXR0bGVtZW50X2lkIjoiMjE0NmRkOWEtODYzMi00NjA0LTk0ODAtYzQ0OGM0MzZiOTFmIiwiemlwIjoiNTM2MDAiLCJzdHJlZXRfdHlwZSI6IlNUUkVFVCIsInN0cmVldCI6ItCU0JzQmNCi0KDQkCDQr9CS0J7QoNCd0JjQptCs0JrQntCT0J4iLCJidWlsZGluZyI6IjEyMSIsInR5cGUiOiJSRUdJU1RSQVRJT04iLCJhcGFydG1lbnQiOiIwIiwiY291bnRyeSI6IlVBIn1dLCJwaG9uZXMiOlt7InR5cGUiOiJMQU5EX0xJTkUiLCJudW1iZXIiOiIrMzgwNTYzODIxODYyIn1dLCJrdmVkcyI6WyI4Ni4xMCJdLCJlZHJwb3UiOiIwMTk4ODk1MyIsIm5hbWUiOiLQmtCe0JzQo9Cd0JDQm9Cs0J3QmNCZINCX0JDQmtCb0JDQlCBcItCf0J7QmtCg0J7QktCh0KzQmtCQINCm0JXQndCi0KDQkNCb0KzQndCQINCg0JDQmdCe0J3QndCQINCb0IbQmtCQ0KDQndCvXCIg0JTQndCG0J/QoNCe0J/QldCi0KDQntCS0KHQrNCa0J7QhyDQntCR0JvQkNCh0J3QntCHINCg0JDQlNCYXCIiLCJzaG9ydF9uYW1lIjoi0JrQlyDQn9Ce0JrQoNCe0JLQodCs0JrQkCDQptCg0Jsg0JTQndCG0J/QoNCe0J/QldCi0KDQntCS0KHQrNCa0J7QhyDQntCR0JvQkNCh0J3QntCHINCg0JDQlNCYIiwibGVnYWxfZm9ybSI6IjQyNSIsIm93bmVyX3Byb3BlcnR5X3R5cGUiOiJTVEFURSIsInB1YmxpY19uYW1lIjoi0J/QntCa0KDQntCS0KHQrNCa0JAg0KbQoNCbIiwiZW1haWwiOiJwb2tyb3ZrYWNybEB1a3IubmV0IiwidHlwZSI6Ik1TUCIsInNlY3VyaXR5Ijp7InJlZGlyZWN0X3VyaSI6Imh0dHBzOi8vbmV3bWVkaWNpbmUuY29tLnVhIn0sInB1YmxpY19vZmZlciI6eyJjb25zZW50Ijp0cnVlLCJjb25zZW50X3RleHQiOiLQl9C+0LHQvtCyJ9GP0LfRg9GO0YHRjCDQtNC+0YLRgNC40LzRg9Cy0LDRgtC40YHRjCDQoNC10LPQu9Cw0LzQtdC90YLRgyDRhNGD0L3QutGG0ZbQvtC90YPQstCw0L3QvdGPINGB0LjRgdGC0LXQvNC4IGVIZWFsdGguINCf0ZbQtNGC0LLQtdGA0LTQttGD0Y4g0LTQvtGB0YLQvtCy0ZbRgNC90ZbRgdGC0Ywg0LLQutCw0LfQsNC90LjRhSDQvNC90L7RjiDQtNCw0L3QuNGFINGC0LAg0LTQvtCx0YDQvtCy0ZbQu9GM0L3RltGB0YLRjCDQvdCw0LTQsNC90L3RjyDRhtC40YUg0LTQsNC90LjRhS4g0KPRgdCy0ZbQtNC+0LzQu9GO0Y4sINGJ0L4g0YMg0LLQuNC/0LDQtNC60YMg0L3QsNC00LDQvdC90Y8g0LzQvdC+0Y4g0L3QtdCy0ZbRgNC90L7RlyDRltC90YTQvtGA0LzQsNGG0ZbRlywg0LzQtdC90ZYg0LzQvtC20LUg0LHRg9GC0Lgg0LLRltC00LzQvtCy0LvQtdC90L4g0YMg0YDQtdGU0YHRgtGA0LDRhtGW0Zcg0LIg0YHQuNGB0YLQtdC80ZYgZUhlYWx0aC4ifX2gggX8MIIF+DCCBaCgAwIBAgIUDYTtobuTgegEAAAAnPwRANdgNgAwDQYLKoYkAgEBAQEDAQEwggFCMXwwegYDVQQKDHPQn9Cj0JHQm9CG0KfQndCVINCQ0JrQptCG0J7QndCV0KDQndCVINCi0J7QktCQ0KDQmNCh0KLQktCeINCa0J7QnNCV0KDQptCG0JnQndCY0Jkg0JHQkNCd0JogwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MREwDwYDVQQLDAjQkNCm0KHQmjE2MDQGA1UEAwwt0JDQptCh0Jog0J/QkNCiINCa0JEgwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MRYwFAYDVQQFDA1VQS0xNDM2MDU3MC0xMQswCQYDVQQGEwJVQTEnMCUGA1UEBwwe0JTQvdGW0L/RgNC+0L/QtdGC0YDQvtCy0YHRjNC6MSkwJwYDVQQIDCDQlNC90ZbQv9GA0L7Qv9C10YLRgNC+0LLRgdGM0LrQsDAeFw0xNzAyMjgwNzUzMjdaFw0xODAyMjgyMTU5NTlaMIIBQDEwMC4GA1UECgwn0J7QnNChINCf0J7QmtCg0J7QktCh0KzQmtCQINCm0KDQmyDQmtCXMRswGQYDVQQMDBLQkdCj0KXQk9CQ0JvQotCV0KAxPTA7BgNVBAMMNNCn0JXQoNCS0J7QndCe0KEg0J3QkNCi0JDQm9CG0K8g0JLQhtCa0KLQntCg0IbQktCd0JAxGTAXBgNVBAQMENCn0JXQoNCS0J7QndCe0KExLDAqBgNVBCoMI9Cd0JDQotCQ0JvQhtCvINCS0IbQmtCi0J7QoNCG0JLQndCQMRAwDgYDVQQFDAcxMTc4NzgwMQswCQYDVQQGEwJVQTEdMBsGA1UEBwwU0J/QntCa0KDQntCS0KHQrNCa0JUxKTAnBgNVBAgMINCU0J3QhtCf0KDQntCf0JXQotCg0J7QktCh0KzQmtCQMEYwHgYLKoYkAgEBAQEDAQEwDwYNKoYkAgEBAQEDAQECBgMkAAQh59yfwjb5bJG2MVVerGw413ZX5tL8e5pdiy9MAUocFQoAo4ICgDCCAnwwKQYDVR0OBCIEICtzb4f4s1j5QsrVUyiNKjtReh9R937b5zyI4ycTuixtMCsGA1UdIwQkMCKAII2E7aG7k4HowxGQqKyShT/E2MeExkoBuDcRV9hdGFVXMC8GA1UdEAQoMCagERgPMjAxNzAyMjgwNzUzMjdaoREYDzIwMTgwMjI4MjE1OTU5WjAOBgNVHQ8BAf8EBAMCBsAwGQYDVR0gAQH/BA8wDTALBgkqhiQCAQEBAgIwDAYDVR0TAQH/BAIwADAeBggrBgEFBQcBAwEB/wQPMA0wCwYJKoYkAgEBAQIBMDUGA1UdHwQuMCwwKqAooCaGJGh0dHA6Ly9hY3NrLnByaXZhdGJhbmsudWEvY3JsL1BCLmNybDBABgNVHS4EOTA3MDWgM6Axhi9odHRwOi8vYWNzay5wcml2YXRiYW5rLnVhL2NybGRlbHRhL1BCLURlbHRhLmNybDCBlAYIKwYBBQUHAQEEgYcwgYQwNAYIKwYBBQUHMAGGKGh0dHA6Ly9hY3NrLnByaXZhdGJhbmsudWEvc2VydmljZXMvb2NzcC8wTAYIKwYBBQUHMAKGQGh0dHA6Ly9hY3NrLnByaXZhdGJhbmsudWEvZG93bmxvYWQvY2VydGlmaWNhdGVzL2NlcnRpZmljYXRlcy5wN2IwQwYIKwYBBQUHAQsENzA1MDMGCCsGAQUFBzADhidodHRwOi8vYWNzay5wcml2YXRiYW5rLnVhL3NlcnZpY2VzL3RzcC8wQwYDVR0JBDwwOjAaBgwqhiQCAQEBCwEEAgExChMIMDE5ODg5NTMwHAYMKoYkAgEBAQsBBAEBMQwTCjIyMjMzMDMxODkwDQYLKoYkAgEBAQEDAQEDQwAEQDMDGvV7VkkQK3pxjAc4+4aWEl9sEo0RDEMqjT1fT0UoKb9jM+LHwzVCcr6DfqRq7Ao+mKGpEZOLFqdjGLhlQisxggf3MIIH8wIBATCCAVwwggFCMXwwegYDVQQKDHPQn9Cj0JHQm9CG0KfQndCVINCQ0JrQptCG0J7QndCV0KDQndCVINCi0J7QktCQ0KDQmNCh0KLQktCeINCa0J7QnNCV0KDQptCG0JnQndCY0Jkg0JHQkNCd0JogwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MREwDwYDVQQLDAjQkNCm0KHQmjE2MDQGA1UEAwwt0JDQptCh0Jog0J/QkNCiINCa0JEgwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MRYwFAYDVQQFDA1VQS0xNDM2MDU3MC0xMQswCQYDVQQGEwJVQTEnMCUGA1UEBwwe0JTQvdGW0L/RgNC+0L/QtdGC0YDQvtCy0YHRjNC6MSkwJwYDVQQIDCDQlNC90ZbQv9GA0L7Qv9C10YLRgNC+0LLRgdGM0LrQsAIUDYTtobuTgegEAAAAnPwRANdgNgAwDAYKKoYkAgEBAQECAaCCBi0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTcwOTA2MDY1MDU2WjAvBgkqhkiG9w0BCQQxIgQgoZVCNpOA3XBYaT9ygwanL1YBMvogw2duaGp++FYUKCQwggG1BgsqhkiG9w0BCRACLzGCAaQwggGgMIIBnDCCAZgwDAYKKoYkAgEBAQECAQQgE5hBXXrqTQ07eZP1K8RebPr56SBm4bF4xiuIFVGVaL0wggFkMIIBSqSCAUYwggFCMXwwegYDVQQKDHPQn9Cj0JHQm9CG0KfQndCVINCQ0JrQptCG0J7QndCV0KDQndCVINCi0J7QktCQ0KDQmNCh0KLQktCeINCa0J7QnNCV0KDQptCG0JnQndCY0Jkg0JHQkNCd0JogwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MREwDwYDVQQLDAjQkNCm0KHQmjE2MDQGA1UEAwwt0JDQptCh0Jog0J/QkNCiINCa0JEgwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MRYwFAYDVQQFDA1VQS0xNDM2MDU3MC0xMQswCQYDVQQGEwJVQTEnMCUGA1UEBwwe0JTQvdGW0L/RgNC+0L/QtdGC0YDQvtCy0YHRjNC6MSkwJwYDVQQIDCDQlNC90ZbQv9GA0L7Qv9C10YLRgNC+0LLRgdGM0LrQsAIUDYTtobuTgegEAAAAnPwRANdgNgAwggQHBgsqhkiG9w0BCRACFDGCA/YwggPyBgkqhkiG9w0BBwKgggPjMIID3wIBAzEOMAwGCiqGJAIBAQEBAgEwawYLKoZIhvcNAQkQAQSgXARaMFgCAQEGCiqGJAIBAQECAwEwMDAMBgoqhiQCAQEBAQIBBCChlUI2k4DdcFhpP3KDBqcvVgEy+iDDZ25oan74VhQoJAIEB+DL/xgPMjAxNzA5MDYwNjUyMjJaMYIDWzCCA1cCAQEwggETMIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTIxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUMAR1He8seK4CAAAAAQAAAEoAAAAwDAYKKoYkAgEBAQECAaCCAdowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJBTEPFw0xNzA5MDYwNjUyMjJaMC8GCSqGSIb3DQEJBDEiBCBDHo3xe43eVbbIJre+AgmpkTiErm5UJjbSjqEPRaDM+TCCAWsGCyqGSIb3DQEJEAIvMYIBWjCCAVYwggFSMIIBTjAMBgoqhiQCAQEBAQIBBCDZDaa2SFPDLb+XuPblXM1qxXlSA+KYRLrjydZWG2e86jCCARowggEApIH9MIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTIxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUMAR1He8seK4CAAAAAQAAAEoAAAAwDQYLKoYkAgEBAQEDAQEEQPEWB+QD5RaG+7VjEY/Y9hOahNgEANUZeLTwGlrPqCUUKBME/QrY/CVMCmU5sFcka3Vb6sstbgc31ErAFLk/G1MwDQYLKoYkAgEBAQEDAQEEQClvsn9pBf+KQLprJL3o80ScAlywlCQYSTj3Fg+49LY2xI9CnKmdTARpcQ6k0a8NGRF5FA3I6MnUf1KYqW6uRnI=`
## Actual result
Неизвестная ошибка.
## Expected result
Успешная регистрация.
##Additional information
Код ЕДРПОУ 01988953

**Comment by pzhuk** [comment]
Полный запрос и ответ покажите, пожалуйста

**Comment by akelara** [comment]
`{"meta":{"url":"http://api.ehealth-ukraine.org/api/legal_entities","type":"object","request_id":"mdjj6gh4eamfgl776gdql8t0iu3alpec","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"cast","params":["object"],"description":"type mismatch. Expected Object but got String"}],"entry_type":"json_data_property","entry":"$"}]}}`

**Comment by akelara** [comment]
Добрый день, не получили ответа. Клиника очень хочет зарегистрироваться. В чем может быть проблема?

**Comment by pzhuk** [comment]
@akelara  вы просто два одинаковых запроса открыли, этот - закрыт.
ответ дан в другом - https://github.com/ehealth-ua/api-spec/issues/120

**Comment by akelara** [comment]
они не одинаковые, они с разными едрпоу... но ответ в обоих случаях одинаков - контейнер?

**Comment by pzhuk** [comment]
на первый взгляд - одинаковы, неверный контейнер

**Comment by akelara** [comment]
спасибо, будем смотреть
