### ISSUE TITLE
фільтр по деклараціям повертає http/403

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#122]
## Steps to Reproduce (Repro steps)

- [*] endpoint address
demo, /api/declarations

- [*] preconditions if any
Bearer of DOCTOR, and doctor has NO any active declaration

- [*] sequence of actions that should be taken to reproduce the behavior.
Doctor has declarations with status pending_verification, and no any active declarations

- [*] test data, requests examples, json files, curl requests etc
GET /api/declarations?status=active HTTP/1.1
Host: demo.ehealth.world
Authorization: Bearer MnpjVTdvQy9tY2FsT2hDVEg4NW9hdz09

## Actual result
- [*] response example (*.json file)

```
    "error": {
        "type": "forbidden",
        "message": "This API method returns only exact match results, please retry with more specific search parameters"
    }
```

## Expected result
- [*] description of the expected system behavior.

~~1) filter  active should return also 'pending_verification'~~
2) if filter returns no data, there should be http/200 instead of http/403

**Comment by lymychp** [comment]
були проблеми з даними в MPI - прогнали міграцію, тепер працює

**Comment by sreva** [comment]
Пробували на пре-прод - працює

**Comment by sreva** [comment]
Запит:
```
 {
            "method" : "GET",
            "uri" : "https://api.ehealth.world/api/declarations",
            "formParams" : [],
            "additionalParams" : {
                "query" : {
                    "limit" : 50,
                    "status" : "active"
                }
            }
        } 
```
Відповідь: 
```
 {
            "meta" : {
                "url" : "http://api.ehealth.world/api/declarations",
                "type" : "object",
                "request_id" : "skavop8cv44b8sae2j404tv635toj5d5",
                "code" : 404
            },
            "error" : {
                "type" : "not_found"
            }
        } 
```
має бути 200 і пустий масив

**Comment by lymychp** [comment]
fixed on demo/preprod.
