### ISSUE TITLE
проблеми з формою для друку декларації

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#123]
1) отримуємо в печатній формі декларації якщо не вказати ІПН http://prntscr.com/gk5wlr
2) не зрозуміло - http://prntscr.com/gk5y7x

**Comment by lymychp** [comment]
1. Глянемо
2. тут в формі декларації має бути номер телефону division та email.

**Comment by lymychp** [comment]
fixed on demo and pre-prod.
