### ISSUE TITLE
Не працює фільтр по статусу підрозділу

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#126]
Не працює фільтр по статусу підрозділу. Видає і активні и неактивні.

https://demo.ehealth.world/api/divisions?status=ACTIVE

**Comment by pzhuk** [comment]
Не думаю, що цей фільтр було імплементовано. Кількість підрозділів в одному МСП завжди буде достатньо малою, щоб фільтрацію можна було зробити на стороні клієнта

**Comment by pieskov** [comment]
Так написати і в документації.

**Comment by lymychp** [comment]
it has been implemented in new version - can be tested on demo.
