### ISSUE TITLE
Signed content does not match the previously created content

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#129]
Намагаюсь підписати заявку на створення декларації. 

Запит:
PATCH /api/declaration_requests/adab80db-2be6-42b6-bc4f-6d6a402c288d/actions/sign HTTP/1.1
Host: demo.ehealth.world
Authorization: Bearer bFRtTXloeGlvbmtaN01LVzhLTFB3QT09
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: c0b89990-ae87-17d5-75f7-a6db55cab02a

{"signed_declaration_request":"текст у слаку по посиленню(дуже довга строка) https://startehealthatlast.slack.com/archives/C5KMY92F5/p1506425540000191","signed_content_encoding":"base64"}

Відповідь:
`{
    "meta": {
        "url": "http://demo.ehealth.world/api/declaration_requests/adab80db-2be6-42b6-bc4f-6d6a402c288d/actions/sign",
        "type": "object",
        "request_id": "dnq3tb8akjtp10gmvrdsiabsbo65kja2",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "invalid",
                        "params": [],
                        "description": "Signed content does not match the previously created content"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.content"
            }
        ]
    }
}`

**Comment by pzhuk** [comment]
Repro on demo

```
{"timestamp":"2017-09-27T09:44:53.151Z","sourceLocation":{"line":27,"function":"Elixir.Phoenix.Logger.phoenix_controller_call/3","file":"/opt/app/deps/phoenix/lib/phoenix/logger.ex"},"severity":"DEBUG","metadata
":{"request_id":"l441vfai1krsa9eo6qde1kbqsjt5g9qb","application":"phoenix"},"jsonPayload":{"serviceContext":{"version":[49,46,51,46,48],"service":"phoenix"},"message":"Processing with EHealth.Web.DeclarationRequ
estController.sign
```

**Comment by pzhuk** [comment]
[gw_request_body.csv.txt](https://github.com/ehealth-ua/api-spec/files/1336944/gw_request_body.csv.txt)
[decl-signed.txt](https://github.com/ehealth-ua/api-spec/files/1336948/decl-signed.txt)

**Comment by pzhuk** [comment]
[gw_sign_content.txt](https://github.com/ehealth-ua/api-spec/files/1336991/gw_sign_content.txt)
[request_printout_content.txt](https://github.com/ehealth-ua/api-spec/files/1336990/request_printout_content.txt)

**Comment by lymychp** [comment]
@pieskov @pzhuk дайте плз json, який підписувався

**Comment by pieskov** [comment]
В слаку, особисте повідомлення.

**Comment by lymychp** [comment]
судячи з усього, для підписання використовувся не json об'єкт, що повертає наш ендпойнт `/api/declaration_requests/id`, а щось кастомне.
У Вас, наприклад, `"division"."location": null` лишній

**Comment by pzhuk** [comment]
@pieskov будь-ласка порівняйте json контент, доведіть до іденичного стану(окрім patient_signed) і дайте нам знати, якщо проблема повториться
