### ISSUE TITLE
Поява нових обовязкових полів в реєстрації MSP

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#13]
Колеги, підкажіть, будь ласка. 
1) Чому поля public_name + short_name стали обовязковими?
вчора було - https://prnt.sc/fe7fv1
сьогодні - https://prnt.sc/fe7go1
2) Можете в таких випадках скидати для нас Release Notes.

**Comment by lymychp** [comment]
1. поля  public_name + short_name - в реквестах optional 
2. Всі апдейти спеки відбуваються через [релізи](https://github.com/ehealth-ua/api-spec/releases) в GitHub з releaseNotes

**Comment by sreva** [comment]
Дякую
