### ISSUE TITLE
500 при створенні запиту на декларацію

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#133]
## Steps to Reproduce (Repro steps)

- [ ] POST  https://api.ehealth.world/api/declaration_requests 
- [ ]  ``` {
                "declaration_request" : {
                    "person" : {
                        "first_name" : "Сергій",
                        "last_name" : "Рева",
                        "birth_date" : "1989-12-15",
                        "birth_country" : "Україна",
                        "birth_settlement" : "Київ",
                        "gender" : "MALE",
                        "secret" : "Слово555",
                        "documents" : [ 
                            {
                                "type" : "PASSPORT",
                                "number" : "ввввв"
                            }
                        ],
                        "addresses" : [ 
                            {
                                "type" : "RESIDENCE",
                                "country" : "UA",
                                "area" : "ВІННИЦЬКА",
                                "settlement" : "ВІННИЦЯ",
                                "settlement_type" : "CITY",
                                "settlement_id" : "90cf1df9-7306-424d-98b0-18f03098f9bd",
                                "street_type" : "STREET",
                                "street" : "Смирнова",
                                "building" : "12",
                                "apartment" : "1",
                                "zip" : "12345"
                            }, 
                            {
                                "type" : "REGISTRATION",
                                "country" : "UA",
                                "area" : "ВІННИЦЬКА",
                                "settlement" : "ВІННИЦЯ",
                                "settlement_type" : "CITY",
                                "settlement_id" : "90cf1df9-7306-424d-98b0-18f03098f9bd",
                                "street_type" : "STREET",
                                "street" : "Смирнова",
                                "building" : "12",
                                "apartment" : "1",
                                "zip" : "12345"
                            }
                        ],
                        "authentication_methods" : [ 
                            {
                                "type" : "OFFLINE"
                            }
                        ],
                        "emergency_contact" : {
                            "first_name" : "Сергій",
                            "last_name" : "Рева",
                            "second_name" : "Вас",
                            "phones" : [ 
                                {
                                    "type" : "MOBILE",
                                    "number" : "+380999999999"
                                }
                            ]
                        },
                        "patient_signed" : false,
                        "process_disclosure_data_consent" : true
                    },
                    "scope" : "family_doctor",
                    "employee_id" : "2d61778a-ed51-49c5-b014-79b2379a7c0f",
                    "division_id" : "4f78d9c9-037d-4da5-967e-1bfd65a8a18d"
                }
            } ```

## Actual result
```
{
    "meta": {
        "url": "http://api.ehealth.world/api/declaration_requests",
        "type": "object",
        "request_id": "h3s54550kpnrmvfunq3a79pnlu5rvv0b",
        "code": 500
    },
    "error": {
        "type": "internal_error"
    }
}
```

##  Expected result

- [ ]  успішне створення

**Comment by sreva** [comment]
Сьогодні вже працює

**Comment by lymychp** [comment]
Вчора пофіксили
