### ISSUE TITLE
http 403 на перегляд декларацій в статусі active

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#135]
## Steps to Reproduce (Repro steps)

- [ ] `GET https://api.ehealth.world/api/declarations?status=active`
- [ ] preconditions if any `employee_type = DOCTOR`

## Actual result
- [ ] ``` {
            "meta" : {
                "url" : "http://api.ehealth.world/api/declarations",
                "type" : "object",
                "request_id" : "7eq127uea164k9rrt4d67kjvqaoilmqs",
                "code" : 403
            },
            "error" : {
                "type" : "forbidden",
                "message" : "This API method returns only exact match results, please retry with more specific search parameters"
            }
        }```

При запиті:
`https://api.ehealth.world/api/declarations` і `https://api.ehealth.world/api/declarations?status=pending_verification` - повертає http 200

## Expected result
- [ ] http 200

**Comment by lymychp** [comment]
fixed on all the environments
