### ISSUE TITLE
Злітають ролі у керівника

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#136]
1. Створюю юр. особу з керівником.
2. Цей керівник займає і лікарську посаду. Строрюю за його даними лікаря.
У керавника і лікаря EMail однакові(і всі дані персони теж).
3. Звільняємо лікаря, і під керівником вже зайти в систему не можливо.

**Comment by EdwardVoloshin** [comment]
Добрий день!
Вкажить будь ласка в якому середовищі відбувалась дана помилка (DEMO/PRE-PROD/PROD) та коли приблизно (дата) створювалась юр.особа та лікар?

**Comment by pieskov** [comment]
Помилка виявлена на Демо. Коли створювались не пам"ятаю. Відалялись вчора зранку.

**Comment by EdwardVoloshin** [comment]
Завтра дам відповідь

**Comment by EdwardVoloshin** [comment]
З'ясовано що це помилка, а не функціональна логіка/поведінка. Завтра ще раз протестуемо і в разі підтвердження помилки - поставимо на доопрацювання.

**Comment by EdwardVoloshin** [comment]
Добрий день.
Протестували цей кейс в різних середовищах і на ДЕМО також - проблема не підтверджуеться. 
Можна спробувати подивитись ваші дані - чи все таки деактивовано керівника чи ні.
Також важливо на які скоупи йде запит при авторизації.
Тобто дайте нам ідентификатор юр.особи та приклад запроса на авторизацію в частині скоупів.

**Comment by EdwardVoloshin** [comment]
Або ще варіант що спробуете з нуля (новий) знову повторити цей кейс на будь якому середовищі, і у випадку підтвердження проблеми - надати дані для ідентифікації.

**Comment by EdwardVoloshin** [comment]
Доброй вечір.
Закриваемо цей issue чи ще будете перевіряти?
