### ISSUE TITLE
Redirect_uri in Legal Entity Create/Update Response is wrong

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#14]
When creating legal entity, we are getting response of redirect_uri== redirect_uri.com, instead of echo of URI sent in request

**Comment by AlekzandrV** [comment]
@pzhuk Please provide request data
Is this case on dev or demo environment?

**Comment by mmiliaieva** [comment]
@pzhuk We have fixed problem, please, try to reproduce

**Comment by lymychp** [comment]
@pzhuk it has been fixed.
