### ISSUE TITLE
Неідентифікована помилка при реєстрації клініки

### ISSUE THREAD

**Issue by akelara** [ehealth-ua/api-spec#140]
Є клініка, номер ЄДРПОУ якої на сайті мінюсту в двух станах - припинено і не перебуває в стані припинено. 
При реєстрації клініки в реєстрі e-health - неідентифікована помилка. 
Відповідь:
`{"meta":{"url":"http://api.ehealth-ukraine.org/api/legal_entities","type":"object","request_id":"7udfl6fvvmm7e6lj29tjrqdsr716e154","code":400},"error":{"type":"request_malformed","message":"Signed request data is invalid","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}`
Запит:
`data:application/pkcs7-signature;base64,MIIM/QYJKoZIhvcNAQcCoIIM7jCCDOoCAQExDjAMBgoqhiQCAQEBAQIBMAsGCSqGSIb3DQEHAaCCBf4wggX6MIIFdqADAgECAhQNhrkGAAAAAAAAAAAAAAAAAAAAATANBgsqhiQCAQEBAQMBATCCARwxWzBZBgNVBAMMUtCQ0KbQodCaINCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxETAPBgNVBAcMCNCa0LjRl9CyMRkwFwYDVQQFDBBVQS0zNjg2NTc1My0wMTE0MVIwUAYDVQQKDEnQotCe0JIgItCm0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C90LAiMS4wLAYDVQQLDCXQktGW0LTQtNGW0Lsg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXMQswCQYDVQQGDAJVQTAeFw0xNzA2MDIwNzQ2MzdaFw0xODA2MDEyMDU5NTlaMIIBdzEoMCYGA1UEAwwf0JrQntCm0K7QkdCY0J3QodCs0JrQmNCZINCeLtCSLjEdMBsGA1UECAwU0KDQhtCS0J3QldCd0KHQrNCa0JAxHjAcBgNVBAcMFdC80ZbRgdGC0L4g0JLQkNCg0JDQqDEOMAwGA1UEEQwFMzQ0MDAxLDAqBgNVBAkMIyDQldCd0JXQoNCT0JXQotCY0JrQhtCSLCDQsdGD0LQuIDIzMRswGQYDVQQMDBLQndCQ0KfQkNCb0KzQndCY0JoxITAfBgNVBAQMGNCa0J7QptCu0JHQmNCd0KHQrNCa0JjQmTE2MDQGA1UEKgwt0J7Qm9CV0JrQodCQ0J3QlNCgINCS0J7Qm9Ce0JTQmNCc0JjQoNCe0JLQmNCnMRQwEgYDVQQFDAsyNTk2MjAyODk3RDEzMDEGA1UECgwq0JTQlyAi0KHQnNCh0Kcg4oSWMyDQnNCe0Jcg0KPQmtCg0JDQh9Cd0JgiMQswCQYDVQQGDAJVQTBGMB4GCyqGJAIBAQEBAwEBMA8GDSqGJAIBAQEBAwEBAgYDJAAEIR/uAOqETRatpqDuSUCvWh8yrBumuKfyYqySM6s+DOUjAKOCAkUwggJBMEMGA1UdCQQ8MDowGgYMKoYkAgEBAQsBBAIBMQoTCDMzOTkyNDE0MBwGDCqGJAIBAQELAQQBATEMEwoyNTk2MjAyODk3MBcGA1UdEQQQMA6BDHp2aXRAdWtyLm5ldDApBgNVHQ4EIgQgCLnoyjs8/SRp0ElZyHKMPdxLQjkF/Qm5ifI7bC9EUnUwKwYDVR0jBCQwIoAgsSjTVHQnl6Lvic3TLqVAMZ9ff84euOoz9WR29Zw8gKEwDgYDVR0PAQH/BAQDAgDAMBgGA1UdJQQRMA8GDSqGJAIBAQELkcqNWQEwGQYDVR0gAQH/BA8wDTALBgkqhiQCAQEBAgIwMgYIKwYBBQUHAQMBAf8EIzAhMAsGCSqGJAIBAQECATASBgMEAAIwCxMDVUFIAgEBAgEGMDMGA1UdLgQsMCowKKAmoCSGImh0dHA6Ly91YWtleS5jb20udWEvbGlzdC1kZWx0YS5jcmwwLQYDVR0fBCYwJDAioCCgHoYcaHR0cDovL3Vha2V5LmNvbS51YS9saXN0LmNybDA9BggrBgEFBQcBCwQxMC8wLQYIKwYBBQUHMAOGIWh0dHA6Ly91YWtleS5jb20udWEvc2VydmljZXMvdHNwLzBtBggrBgEFBQcBAQRhMF8wLQYIKwYBBQUHMAKGIWh0dHA6Ly91YWtleS5jb20udWEvdWFrZXljZXJ0LnA3YjAuBggrBgEFBQcwAYYiaHR0cDovL3Vha2V5LmNvbS51YS9zZXJ2aWNlcy9vY3NwLzANBgsqhiQCAQEBAQMBAQNvAARsBXyH+c4AsSzamx38yHE3JCjazX7nlNEuzRvOQRjnF7hbrAVngvicAmw/H68VRsHnLJSYymYFNqhu15LVo6kzELbgycLU0FTIUP2vFnllI8P74LgeCEfS1EVKv8fO0t6RUW/zagxBjgRyALIwMYIGxDCCBsACAQEwggE2MIIBHDFbMFkGA1UEAwxS0JDQptCh0Jog0KLQntCSICLQptC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgItCj0LrRgNCw0ZfQvdCwIjERMA8GA1UEBwwI0JrQuNGX0LIxGTAXBgNVBAUMEFVBLTM2ODY1NzUzLTAxMTQxUjBQBgNVBAoMSdCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxLjAsBgNVBAsMJdCS0ZbQtNC00ZbQuyDRgdC10YDRgtC40YTRltC60LDRhtGW0ZcxCzAJBgNVBAYMAlVBAhQNhrkGAAAAAAAAAAAAAAAAAAAAATAMBgoqhiQCAQEBAQIBoIIFIDAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xNzEwMTIwODE0MDlaMC8GCSqGSIb3DQEJBDEiBCDarGXBQBbTr4y1FpM7vcFdpHkvAK9RFLNlKK9fI6XflzCCAY8GCyqGSIb3DQEJEAIvMYIBfjCCAXowggF2MIIBcjAMBgoqhiQCAQEBAQIBBCCUOoEy2ns94qQ46Vd5wwUohzhmy4Z/ETN5DZg3msX7dDCCAT4wggEkpIIBIDCCARwxWzBZBgNVBAMMUtCQ0KbQodCaINCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxETAPBgNVBAcMCNCa0LjRl9CyMRkwFwYDVQQFDBBVQS0zNjg2NTc1My0wMTE0MVIwUAYDVQQKDEnQotCe0JIgItCm0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C90LAiMS4wLAYDVQQLDCXQktGW0LTQtNGW0Lsg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXMQswCQYDVQQGDAJVQQIUDYa5BgAAAAAAAAAAAAAAAAAAAAEwggMgBgsqhkiG9w0BCRACFDGCAw8wggMLBgkqhkiG9w0BBwKgggL8MIIC+AIBAzEOMAwGCiqGJAIBAQEBAgEwaQYLKoZIhvcNAQkQAQSgWgRYMFYCAQEGCCsGAQUFBwMIMDAwDAYKKoYkAgEBAQECAQQg2qxlwUAW06+MtRaTO73BXaR5LwCvURSzZSivXyOl35cCBA6tNyUYDzIwMTcxMDEyMDgxNDA0WjGCAnYwggJyAgEBoCIEIAL/Z+cUTz5Hmug+cOpyp2pbB1+bEsiaGI4rl4l3i5rvMAwGCiqGJAIBAQEBAgGgggG8MC8GCSqGSIb3DQEJBDEiBCBeUgoQDUQc1IWA5LSmTg0/QcUTUiVX75GLzxXV6UQ2nzAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwggFrBgsqhkiG9w0BCRACLzGCAVowggFWMIIBUjCCAU4wDAYKKoYkAgEBAQECAQQgHaK5FE8dZoGUlbL+tAU/+6pPgtBIR2i6hU4FoS642w4wggEaMIIBAKSB/TCB+jE/MD0GA1UECgw20JzRltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDEyMQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFDAEdR3vLHiuAgAAAAEAAAAJAAAAMA0GCyqGJAIBAQEBAwEBBGyiHl1MjNwfd3DuM6x6lSF4yLBCtHvtwjce4AegdIjcJ5/7T+P5nRwYkEOtQgEIfRioq9su7xaKLd2x6HLsX0y87uEDKB9KnmnSUJ0V0Pj/AwgoeUvC7jUm/+ar4G8pg9MIlJDOnUbeFNHdyDwwDQYLKoYkAgEBAQEDAQEEQJyxidUXGz5M2B+d4FqyJNySXxdaa+Ytse6UCYDTgwokufXUJQ3Ae2WNas7oQhfbK4xH4L+RQoHqQ+i0t7zFhEQ=`

**Comment by pzhuk** [comment]
(видалив попереднє повідомлення)

У вашому запиті немає json контенту -  перевірте чому
