### ISSUE TITLE
як правильно читати вулиці?

### ISSUE THREAD

**Issue by romanm** [ehealth-ua/api-spec#143]
Доброго дня всім.
як правильно читати вулиці?
Я пробував наприклад по Хмельницькому
https://api.ehealth.world/api/uaddresses/streets?settlement_id=cf312385-7788-4dde-ba22-f549462c17a0

**Comment by pzhuk** [comment]
Нарешті додали вулиці,

Приклад використання

```
curl -X GET \
  'http://demo.ehealth.world/api/uaddresses/streets?settlement_id=1cc9d09e-a6c3-4da6-98f6-1a1a6da1f911&type=STREET' \
  -H 'api-key: d036273f779b1741dcf0' \
  -H 'authorization: Bearer scope_address' 
```
