### ISSUE TITLE
Регистрация медзакладу 422 Unprocessable Entity

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#148]
Выполняю на Руби 
values = {
    :signed_legal_entity_request => "MIIXZwYJKoZIhvcNAQcCoIIXWDCCF1QCAQExDjAMBgoqhiQCAQEBAQIBMIIH9QYJKoZIhvcNAQcBoIIH5gSCB+J7CiAgIm5hbWUiOiAi0JrQu9GW0L3RltC60LAg0JDQtNC+0L3RltGBMjAiLAogICJzaG9ydF.......",
    :signed_content_encoding => "base64"
}

resp = RestClient.put('https://demo.ehealth.world/api/legal_entities', values.to_json, headers)

Получаю ответ
22 Unprocessable Entity (RestClient::UnprocessableEntity)

Что не так?

**Comment by pzhuk** [comment]
Пожалуйста, оформите запрос в соотвтетствиями с рекомендациями - полный лог HTTP запрос-ответ

**Comment by Charly3X** [comment]
полный хеш
{"signed_legal_entity_request":"MIIYdwYJKoZIhvcNAQcCoIIYaDCCGGQCAQExDjAMBgoqhiQCAQEBAQIBMIIJ\nmwYJKoZIhvcNAQcBoIIJjASCCYh7CiAgIm5hbWUiOiAi0JrQu9GW0L3RltC6\n0LAg0JHQvtGA0LjRgSIsCiAgInNob3J0X25hbWUiOiAi0JHQvtGA0LjRgSIs\nCiAgInB1YmxpY19uYW1lIjogItCR0L7RgNC40YEiLAogICJ0eXBlIjogIk1T\nUCIsCiAgIm93bmVyX3Byb3BlcnR5X3R5cGUiOiAiU1RBVEUiLAogICJsZWdh\nbF9mb3JtIjogIjE0MCIsCiAgImVkcnBvdSI6ICIzMjMyMzQ1NCIsCiAgImt2\nZWRzIjogWwogICAgIjg2LjEwIgogIF0sCiAgImFkZHJlc3NlcyI6IFsKICAg\nIHsKICAgICAgInR5cGUiOiAiUkVTSURFTkNFIiwKICAgICAgImNvdW50cnki\nOiAiVUEiLAogICAgICAiYXJlYSI6ICLQltC40YLQvtC80LjRgNGB0YzQutCw\nIiwKICAgICAgInJlZ2lvbiI6ICLQkdC10YDQtNC40YfRltCy0YHRjNC60LjQ\nuSIsCiAgICAgICJzZXR0bGVtZW50IjogItCa0LjRl9CyIiwKICAgICAgInNl\ndHRsZW1lbnRfdHlwZSI6ICJDSVRZIiwKICAgICAgInNldHRsZW1lbnRfaWQi\nOiAiNDM0MzI0MzIiLAogICAgICAic3RyZWV0X3R5cGUiOiAiU1RSRUVUIiwK\nICAgICAgInN0cmVldCI6ICLQstGD0LsuINCd0ZbQttC40L3RgdGM0LrQsCIs\nCiAgICAgICJidWlsZGluZyI6ICIxNSIsCiAgICAgICJhcGFydG1lbnQiOiAi\nMjMiLAogICAgICAiemlwIjogIjAyMDkwIgogICAgfQogIF0sCiAgInBob25l\ncyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiTU9CSUxFIiwKICAgICAgIm51\nbWJlciI6ICIrMzgwNTAzNDEwODcwIgogICAgfQogIF0sCiAgImVtYWlsIjog\nImtpbm92aG9kQGdtYWlsLmNvbSIsCiAgIm93bmVyIjogewogICAgImZpcnN0\nX25hbWUiOiAi0J/QtdGC0YDQviIsCiAgICAibGFzdF9uYW1lIjogItCG0LLQ\nsNC90L7QsiIsCiAgICAic2Vjb25kX25hbWUiOiAi0JzQuNC60L7Qu9Cw0LnQ\nvtCy0LjRhyIsCiAgICAidGF4X2lkIjogIjMwMTU0OTI1NjMiLAogICAgImJp\ncnRoX2RhdGUiOiAiMTk5MS0wOC0xOVQwMDowMDowMC4wMDBaIiwKICAgICJn\nZW5kZXIiOiAiTUFMRSIsCiAgICAiZW1haWwiOiAia2lub3Zob2RAZ21haWwu\nY29tIiwKICAgICJkb2N1bWVudHMiOiBbCiAgICAgIHsKICAgICAgICAidHlw\nZSI6ICJQQVNTUE9SVCIsCiAgICAgICAgIm51bWJlciI6ICIxMjA1MTgiCiAg\nICAgIH0KICAgIF0sCiAgICAicGhvbmVzIjogWwogICAgICB7CiAgICAgICAg\nInR5cGUiOiAiTU9CSUxFIiwKICAgICAgICAibnVtYmVyIjogIiszODA1MDM0\nMTA4NzAiCiAgICAgIH0KICAgIF0sCiAgICAicG9zaXRpb24iOiAiIgogIH0s\nCiAgIm1lZGljYWxfc2VydmljZV9wcm92aWRlciI6IHsKICAgICJsaWNlbnNl\ncyI6IFsKICAgICAgewogICAgICAgICJsaWNlbnNlX251bWJlciI6ICJmZDEy\nMzQ0MyIsCiAgICAgICAgImlzc3VlZF9ieSI6ICLQmtCy0LDQu9GW0YTRltC6\n0LDRhtC50L3QsCDQutC+0LzRltGB0ZbRjyIsCiAgICAgICAgImlzc3VlZF9k\nYXRlIjogIjIwMTctMDItMjgiLAogICAgICAgICJleHBpcnlfZGF0ZSI6ICIy\nMDE3LTAyLTI4IiwKICAgICAgICAiYWN0aXZlX2Zyb21fZGF0ZSI6ICIyMDE3\nLTAyLTI4IiwKICAgICAgICAid2hhdF9saWNlbnNlZCI6ICLRgNC10LDQu9GW\n0LfQsNGG0ZbRjyDQvdCw0YDQutC+0YLQuNGH0L3QuNGFINC30LDRgdC+0LHR\nltCyIgogICAgICB9CiAgICBdLAogICAgImFjY3JlZGl0YXRpb24iOiB7CiAg\nICAgICJjYXRlZ29yeSI6ICLQtNGA0YPQs9CwIiwKICAgICAgImlzc3VlZF9k\nYXRlIjogIjIwMTctMDItMjgiLAogICAgICAiZXhwaXJ5X2RhdGUiOiAiMjAx\nNy0wMi0yOCIsCiAgICAgICJvcmRlcl9ubyI6ICJmZDEyMzQ0MyIsCiAgICAg\nICJvcmRlcl9kYXRlIjogIjIwMTctMDItMjgiCiAgICB9CiAgfSwKICAic2Vj\ndXJpdHkiOiB7CiAgICAicmVkaXJlY3RfdXJpIjogImh0dHA6Ly9sb2NhbGhv\nc3Q6MzAwMCIKICB9LAogICJwdWJsaWNfb2ZmZXIiOiB7CiAgICAiY29uc2Vu\ndCI6IHRydWUsCiAgICAiY29uc2VudF90ZXh0IjogItCX0L7QsdC+0LJcJ9GP\n0LfRg9GO0YHRjCDQtNC+0YLRgNC40LzRg9Cy0LDRgtC40YHRjCDQoNC10LPQ\nu9Cw0LzQtdC90YLRgyDRhNGD0L3QutGG0ZbQvtC90YPQstCw0L3QvdGPINGB\n0LjRgdGC0LXQvNC4IGVIZWFsdGguINCf0ZbQtNGC0LLQtdGA0LTQttGD0Y4g\n0LTQvtGB0YLQvtCy0ZbRgNC90ZbRgdGC0Ywg0LLQutCw0LfQsNC90LjRhSDQ\nvNC90L7RjiDQtNCw0L3QuNGFINGC0LAg0LTQvtCx0YDQvtCy0ZbQu9GM0L3R\nltGB0YLRjCDQvdCw0LTQsNC90L3RjyDRhtC40YUg0LTQsNC90LjRhS4g0KPR\ngdCy0ZbQtNC+0LzQu9GO0Y4sINGJ0L4g0YMg0LLQuNC/0LDQtNC60YMg0L3Q\nsNC00LDQvdC90Y8g0LzQvdC+0Y4g0L3QtdCy0ZbRgNC90L7RlyDRltC90YTQ\nvtGA0LzQsNGG0ZbRlywg0LzQtdC90ZYg0LzQvtC20LUg0LHRg9GC0Lgg0LLR\nltC00LzQvtCy0LvQtdC90L4g0YMg0YDQtdGU0YHRgtGA0LDRhtGW0Zcg0LIg\n0YHQuNGB0YLQtdC80ZYgZUhlYWx0aC4iCiAgfQp9oIIGlzCCBpMwggY7oAMC\nAQICFDO2y3v3IbnOBAAAAN1qGwCtUVgAMA0GCyqGJAIBAQEBAwEBMIIBUDFU\nMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQ\nutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYD\nVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA\n0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNCh\nMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3R\ngtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQ\nlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVB\nMREwDwYDVQQHDAjQmtC40ZfQsjAeFw0xNzA2MTIyMTAwMDBaFw0xOTA2MTIy\nMTAwMDBaMIHzMRwwGgYDVQQKDBPQp9Cw0YDQvtGP0L0g0J4u0JIuMTkwNwYD\nVQQDDDDQp9Cw0YDQvtGP0L0g0J7Qu9C10LrRgdGW0Lkg0JLQsNGA0YLQsNC9\n0L7QstC40YcxFTATBgNVBAQMDNCn0LDRgNC+0Y/QvTEsMCoGA1UEKgwj0J7Q\nu9C10LrRgdGW0Lkg0JLQsNGA0YLQsNC90L7QstC40YcxEDAOBgNVBAUMBzE3\nOTY4MjkxCzAJBgNVBAYTAlVBMRUwEwYDVQQHDAzQpdCw0YDQutGW0LIxHTAb\nBgNVBAgMFNCl0LDRgNC60ZbQstGB0YzQutCwMIHyMIHJBgsqhiQCAQEBAQMB\nATCBuTB1MAcCAgEBAgEMAgEABCEQvuPbauqeH4ZXjEXBJZT/lCOUp9c4+Rh+\nZRUBcpT0zgECIQCAAAAAAAAAAAAAAAAAAAAAZ1khOvGC6YfT4XcUkH1HDQQh\ntg/S2NzoqTQjxhAbypHEegB+bDALJs1VbJsOfSDvKSoABECp1utF8TxwgoDE\nlnsjH16t9ljrpMA3KR042WvwJcpOF/jpcg3GFbQ6KJdfC8Heo2Q4tWTqLBef\n0BI+bbj6xXkEAyQABCFxgNs8P6EmHKD4+hDcg1fyhPY5U284oOvhuHkhBJOG\n7AGjggKuMIICqjApBgNVHQ4EIgQgPYpQd1CFaIMIOlt9HJBFd3R8uAF53D2n\nAI9HPL5fuCwwKwYDVR0jBCQwIoAgM7bLe/chuc7u494uYv7qO3AaS2dgvBwv\nzzVlFrUOvKowLwYDVR0QBCgwJqARGA8yMDE3MDYxMjIxMDAwMFqhERgPMjAx\nOTA2MTIyMTAwMDBaMA4GA1UdDwEB/wQEAwIGwDAZBgNVHSABAf8EDzANMAsG\nCSqGJAIBAQECAjAMBgNVHRMBAf8EAjAAMB4GCCsGAQUFBwEDAQH/BA8wDTAL\nBgkqhiQCAQEBAgEwHgYDVR0RBBcwFaATBgorBgEEAYI3FAIDoAUMAzE0NDBI\nBgNVHR8EQTA/MD2gO6A5hjdodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxv\nYWQvY3Jscy9BQ1NLSUREREZTLUZ1bGwuY3JsMEkGA1UdLgRCMEAwPqA8oDqG\nOGh0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jcmxzL0FDU0tJRERE\nRlMtRGVsdGEuY3JsMIGIBggrBgEFBQcBAQR8MHowMAYIKwYBBQUHMAGGJGh0\ndHA6Ly9hY3NraWRkLmdvdi51YS9zZXJ2aWNlcy9vY3NwLzBGBggrBgEFBQcw\nAoY6aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NlcnRpZmljYXRl\ncy9hbGxhY3NraWRkLnA3YjA/BggrBgEFBQcBCwQzMDEwLwYIKwYBBQUHMAOG\nI2h0dHA6Ly9hY3NraWRkLmdvdi51YS9zZXJ2aWNlcy90c3AvMEUGA1UdCQQ+\nMDwwHAYMKoYkAgEBAQsBBAIBMQwTCjI4ODA2MTQzMTAwHAYMKoYkAgEBAQsB\nBAEBMQwTCjI4ODA2MTQzMTAwDQYLKoYkAgEBAQEDAQEDQwAEQMWg1OLNQqYu\nTQTaOYeEfyGPvYtLnFizmVLBdWtq9qNcepAjc9nHi7AYAUb4aCwuqpP+CwMB\nhrWcf8qUYccPhEcxgggTMIIIDwIBATCCAWowggFQMVQwUgYDVQQKDEvQhtC9\n0YTQvtGA0LzQsNGG0ZbQudC90L4t0LTQvtCy0ZbQtNC60L7QstC40Lkg0LTQ\ntdC/0LDRgNGC0LDQvNC10L3RgiDQlNCk0KExXjBcBgNVBAsMVdCj0L/RgNCw\n0LLQu9GW0L3QvdGPICjRhtC10L3RgtGAKSDRgdC10YDRgtC40YTRltC60LDR\nhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExYjBgBgNVBAMMWdCQ\n0LrRgNC10LTQuNGC0L7QstCw0L3QuNC5INGG0LXQvdGC0YAg0YHQtdGA0YLQ\nuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMRQw\nEgYDVQQFDAtVQS0zOTM4NDQ3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa\n0LjRl9CyAhQztst79yG5zgQAAADdahsArVFYADAMBgoqhiQCAQEBAQIBoIIG\nOzAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0x\nNzEwMjkxNjE1NTRaMC8GCSqGSIb3DQEJBDEiBCAuXKHiwmAj1s8nHdnIzFlx\nKoRZV2TbfZ9CIAp8YmwJRTCCAcMGCyqGSIb3DQEJEAIvMYIBsjCCAa4wggGq\nMIIBpjAMBgoqhiQCAQEBAQIBBCBCirj6uuFHEmw+oePXcyHide+F9T4EW+dF\nBAQyxeeTJjCCAXIwggFYpIIBVDCCAVAxVDBSBgNVBAoMS9CG0L3RhNC+0YDQ\nvNCw0YbRltC50L3Qvi3QtNC+0LLRltC00LrQvtCy0LjQuSDQtNC10L/QsNGA\n0YLQsNC80LXQvdGCINCU0KTQoTFeMFwGA1UECwxV0KPQv9GA0LDQstC70ZbQ\nvdC90Y8gKNGG0LXQvdGC0YApINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQ\nutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTFiMGAGA1UEAwxZ0JDQutGA0LXQ\ntNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC6\n0LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExFDASBgNVBAUM\nC1VBLTM5Mzg0NDc2MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIC\nFDO2y3v3IbnOBAAAAN1qGwCtUVgAMIIEBwYLKoZIhvcNAQkQAhQxggP2MIID\n8gYJKoZIhvcNAQcCoIID4zCCA98CAQMxDjAMBgoqhiQCAQEBAQIBMGsGCyqG\nSIb3DQEJEAEEoFwEWjBYAgEBBgoqhiQCAQEBAgMBMDAwDAYKKoYkAgEBAQEC\nAQQgLlyh4sJgI9bPJx3ZyMxZcSqEWVdk232fQiAKfGJsCUUCBAQeagYYDzIw\nMTcxMDI5MTYxNjEyWjGCA1swggNXAgEBMIIBEzCB+jE/MD0GA1UECgw20JzR\nltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw\n0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQ\nhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5\nINC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkw\nFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDEyMQswCQYDVQQGEwJVQTERMA8GA1UE\nBwwI0JrQuNGX0LICFDAEdR3vLHiuAgAAAAEAAABOAAAAMAwGCiqGJAIBAQEB\nAgGgggHaMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAcBgkqhkiG9w0B\nCQUxDxcNMTcxMDI5MTYxNjEyWjAvBgkqhkiG9w0BCQQxIgQgiSW3SwePLJmM\nVQ0zJVpHLI0jIYxEAr1PNy/uFbiL4tkwggFrBgsqhkiG9w0BCRACLzGCAVow\nggFWMIIBUjCCAU4wDAYKKoYkAgEBAQECAQQglxEgC4hcQDrqQ8Chu0VXMcgd\ni06ummj6vtKcoz+h1gEwggEaMIIBAKSB/TCB+jE/MD0GA1UECgw20JzRltC9\n0ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQ\nvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi\n0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC3\n0LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYD\nVQQFDBBVQS0wMDAxNTYyMi0yMDEyMQswCQYDVQQGEwJVQTERMA8GA1UEBwwI\n0JrQuNGX0LICFDAEdR3vLHiuAgAAAAEAAABOAAAAMA0GCyqGJAIBAQEBAwEB\nBEDvsF2O/66kzppTsDM8lOnO/kNSmUuosJRJXt1AUO8tGGYfpsAfFx9fpHJu\n5AcMWl9goIPxZNSTUHmrg6LoObR3MA0GCyqGJAIBAQEBAwEBBEBrv/h3WZdN\nnJufUXJfaEXQLpBWGzC2Acvf5XBKQjyfZN7zwzDaDfOKqBT5kT1uIrSiA+Uf\nF2JrDUvRPu8EYgZ1\n","signed_content_encoding":"base64"}


полный ответ
{"meta":{"url":"http://demo.ehealth.world/api/legal_entities","type":"object","request_id":"t8ak17flvtcudho0bultsdbh4tt3mj2u","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"invalid","params":[],"description":"not a base64 string"}],"entry_type":"json_data_property","entry":"$.signed_content"}]}}

**Comment by Charly3X** [comment]
Все получилось. Оказывается Бейс64 с лишними переносами был.

**Comment by pzhuk** [comment]
Тут сразу много ошибок

Например, 
1) medical_service_provider.accreditation.category - полученое значение не соответствует ожидаемому в enum
                  "params":[  
                     "FIRST",
                     "HIGHEST",
                     "NO_ACCREDITATION",
                     "SECOND"
                  ],


2) medical_service_provider.licenses.[0].order_no - отсутствует поле "номер приказа" в лицензии

3) .owner.birth_date - неверный формат даты (ожидается YYYY-MM-DD)

4) .owner.position- значение не соответствует ожидаемому в enum

                  "params":[  
                     "P1",
                     "P10",
                     "P11",
                     "P12",
                     "P13",
                     "P14",
                     "P15",
                     "P16",
                     "P17",
                     "P18",
                     "P19",
                     "P2",
                     "P3",
                     "P4",
                     "P5",
                     "P6",
                     "P7",
                     "P8",
                     "P9"
                  ], 


убедитесь, что вы пользуетесь последней версией спецификации
http://docs.ehealthmisapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer
