### ISSUE TITLE
Поиск населенных пунктов

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#149]
Почему при гет запросе 
http://demo.ehealth.world/api/uaddresses/settlements?region=Київ
(http://demo.ehealth.world/api/uaddresses/settlements?region=%D0%9A%D0%B8%D1%97%D0%B2)

получают пустой ответ?
{"paging":{"size":null,"limit":10,"has_more":false,"cursors":{"starting_after":null,"ending_before":null}},"meta":{"url":"http://demo.ehealth.world/settlements","type":"list","request_id":"75p0el4cmjd2l0d3anmv8dbsd4ic0e7s","code":200},"data":[]}

**Comment by pzhuk** [comment]
Тому що правильний region(область) для Києва "М.КИЇВ" згідно КОАТУУ

Приклад

```
GET /api/uaddresses/search/settlements?name=КИЇВ&amp;region=М.КИЇВ HTTP/1.1
Host: demo.ehealth.world
Authorization: Bearer scope_address
Cache-Control: no-cache
Postman-Token: 00f9fd65-ec35-eba0-ebbf-b53ea08693b4
```

**Comment by Charly3X** [comment]
Спасибо за быстрые ответы... 
Ещё есть вопрос 
"invalid":[{"rules":[{"rule":"invalid","params":[],"description":"invalid area value"}]

  "addresses": [
    {
      "type": "REGISTRATION",
      "country": "UA",
      "area": "Житомирська",
      "region": "Бердичівський",
      "settlement": "Київ",
      "settlement_type": "CITY",
      "settlement_id": "adaa4abf-f530-461c-bcbf-a0ac210d955b",
      "street_type": "STREET",
      "street": "вул. Ніжинська",
      "building": "15",
      "apartment": "23",
      "zip": "02090"
    }

Почему инвалид адреа? Где можно узнать список всех ареа?
