### ISSUE TITLE
Legal Entity licenses - obsolete and missed fields

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#15]
In Legal Entity licenses:

1) `kved` - is obsolete, should be removed
2) one more DATE type fieild is required  - `active_from_date`, because `active_from_date` in regular practice is different from `issued_date`

          "issued_date": "2017",
          "expiry_date": "2017",

**Comment by pzhuk** [comment]
Also,

3. expiry_date - has to be optional

**Comment by lymychp** [comment]
@pzhuk 
1. `licenses.kved` - it is optional now
2. license attributes has been discussed in details with the PO team. [MM](https://docs.google.com/document/d/1VwLZbVU_4PUN_c-EUCpJbD1U0_h5AqGaa6AcROXwJHM/edit) it is not a big deal to add new field, anyway we don't use it, but please double check with your team.
Thanks.

**Comment by kmakarenko** [comment]
The changes described above approved by Iryna Shevchenko and Kateryna Makarenko

**Comment by lymychp** [comment]
should it be mandatory?

**Comment by kmakarenko** [comment]
active_from_date - should be mandatory

**Comment by warehousman** [comment]
Change approved - Task Created: #330
