### ISSUE TITLE
Регистрация отделения

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#150]
Подскажите пожалуйста что обозначает эта ошибка?

"description":"one and only one registration address is required"

ЖСОН:

{
    "name": "Бориспільське відділення Клініки Борис",
    "addresses": [
        {
            "type": "RESIDENCE",
            "country": "UA",
            "area": "М.КИЇВ",
            "region": "КИЇВСЬКА ОБЛАСТЬ/М.КИЇВ",
            "settlement": "Київ",
            "settlement_type": "CITY",
            "settlement_id": "adaa4abf-f530-461c-bcbf-a0ac210d955b",
            "street_type": "STREET",
            "street": "вул. Ніжинська",
            "building": "15",
            "apartment": "23",
            "zip": "02090"
        }
    ],
    "phones": [
        {
            "type": "MOBILE",
            "number": "+380503410870"
        }
    ],
    "email": "kinovhod@gmail.com",
    "type": "CLINIC"
}

ПОСТ запрос по урлу
http://demo.ehealth.world/api/divisions

**Comment by pzhuk** [comment]
Ошибка означает, что обязательно должен быть адрес типа "REGISTRATION", а Вас его нет
