### ISSUE TITLE
Ошибка 403 в employee_request

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#152]
На предпроде делаем employee_request. Запрос ниже:
```
Content-Type:application/json
Authorization:Bearer a0p5RUhjSTJnZ3BEYktWSC8rb3pDUT09

{
	"employee_request": {
		"party": {
			"last_name": "root",
			"first_name": "root",
			"second_name": "root",
			"birth_date": "2000-12-12",
			"gender": "FEMALE",
			"phones": [{
				"type": "MOBILE",
				"number": "+380634784409"
			}],
			"documents": [{
				"type": "NATIONAL_ID",
				"number": "12312"
			}],
			"email": "kmoyseenko@hotmail.com",
			"tax_id": "3067305998",
			"start_date": ""
		},
		"status": "NEW",
		"position": "P8",
		"employee_type": "ADMIN",
		"start_date": "2000-12-12",
		"division_id": "60286d9a-cb9f-40f7-81df-90ba787565a6"
	}
}
```
Получаем:
```
{
    "meta": {
        "url": "http://demo.ehealth.world/api/employee_requests/e0fa1edd-7ef8-4d4a-8d20-93c45142d768",
        "type": "object",
        "request_id": "qo9rtt0la8e4dvj4el872r0elgpeg58o",
        "code": 403
    },
    "error": {
        "type": "forbidden",
        "message": "You are not authorized or your token can not be resolved to scope"
    }
}
```

**Comment by lymychp** [comment]
токена `a0p5RUhjSTJnZ3BEYktWSC8rb3pDUT09 ` не існує

**Comment by cshevchukod** [comment]
В дополнение:

[createAndUpdateEmployee.txt](https://github.com/ehealth-ua/api-spec/files/1441735/createAndUpdateEmployee.txt)

**Comment by lymychp** [comment]
Так ви і запит на демо відправляєте. 
Ви впевнені, що з препродом працюєте?

**Comment by cshevchukod** [comment]
Оба запроса выполняются с одним и тем же токеном на одном и том же сервере. "Создание" работает, а "Обновление" - нет.

**Comment by lymychp** [comment]
Дайте curl реквестів і респонси

**Comment by lymychp** [comment]
Усі запити з вашого файлу відправляються на демо

**Comment by cshevchukod** [comment]
Да, отправляются на демо. Но эта проблема воспроизводится как на демо, так и на предпроде.

**Comment by pzhuk** [comment]
@cshevchukod  у вас в последнем запросе, где обновление происходит нету правильного legal_entity_id
"legal_entity_id\":\"<<undefined>>\"

**Comment by cshevchukod** [comment]
1. Похоже есть баг. В обоих запросах нет легал_ид - можно создавать врачей так, как было описано в файле.
2. Это не помогло совсем. Заменили на нужный легал_ид и ничего не изменилось.

**Comment by pzhuk** [comment]
1. Это не баг, а фича, поле опциональное
2. Я и не говорил, что поможет - пока анализруем, просто констатирую факт

**Comment by cshevchukod** [comment]
Прошу переоткрыть тикет. Проблема всё ещё актуальна.

**Comment by pzhuk** [comment]
Давайте логи, или хотя бы request_id

**Comment by cshevchukod** [comment]
"request_id": "qo9rtt0la8e4dvj4el872r0elgpeg58o"

**Comment by cshevchukod** [comment]
Можно закрывать.
