### ISSUE TITLE
 Допоможіть розібратись. Що мені слід зробити з scope, щоб отримати доступ до division:write

### ISSUE THREAD

**Issue by romanm** [ehealth-ua/api-spec#153]
Доброго дня,
MSP зареєстровано 
legal_entity_id:	"bf48fba2-e4e8-4a06-aeaa-345d8346d7bb"

На реєстрацію підрозділу отримую:

{
	"meta": {
		"url": "http://demo.ehealth.world/api/divisions",
		"type": "object",
		"request_id": "7eoievd58bkcj2h21q7bhq2ej002rj5d",
		"code": 403
	},
	"error": {
		"type": "forbidden",
		"message": "Your scope does not allow to access this resource. Missing allowances: division:write"
	}
}

Допоможіть розібратись. Що мені слід зробити з scope, щоб отримати доступ до division:write

**Comment by pzhuk** [comment]
Використовуєте невірний токен - маєте авторизуватись як owner

**Comment by romanm** [comment]
що означає
client_id: `mis-001`
https://github.com/ehealth-ua/api-spec/blob/master/apiary.apib
я повинен зарееструвати спочатку свою MIS і отримати для неї client_id ?

**Comment by pzhuk** [comment]
client_id  - видається після реєстрації Legal Entity

**Comment by romanm** [comment]
так дійсно цей єтап я пройшов.
