### ISSUE TITLE
Запрос регионов с пагинацией.

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#155]
Как получить все регионы?
1. Выполняю
http://demo.ehealth.world/api/uaddresses/regions
Получаю первые 10.

2. Выполняю
https://demo.ehealth.world/api/uaddresses/regions?starting_after=b392aad2-988b-4452-851c-766d48fc94c6

и пустой ответ.
почему?

**Comment by pzhuk** [comment]
Старая пагинация имела ряд недостатков, и в часности этот, о котом Вы пишете.
Мы устранили это в новой версии

**Comment by pzhuk** [comment]
Также, в ответ на ваш вопрос, все регионы в старой версии можно получить так

curl https://demo.ehealth.world/api/uaddresses/regions?limit=100
