### ISSUE TITLE
Текстовка в листі, при оновленні даних по співробітнику

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#156]
Прохання змінити текстовку в листі який надсилається при оновленні даних по співробітнику (передано параметр employee_id). 
![image](https://user-images.githubusercontent.com/29060924/32492974-cf2a56f2-c3c4-11e7-846a-b8c2e2654be4.png)
Текст "для вас створено обліковий запис з роллю" - заплутує кінцевого користувача

**Comment by pzhuk** [comment]
@sreva можеш запропонувати кращий варіант, будь-ласка? Щось, що не запутує користувача

**Comment by sreva** [comment]
@pzhuk 
Вітаємо!
У Вашому обліковому запису ........  відбулось оновлення даних.
Для підтвердження процесу оновлення перейдіть за посиланням «…»

**Comment by lymychp** [comment]
deployed to prod
