### ISSUE TITLE
Ошибка при SIGN DECLARATION (предпрод)

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#158]
## Steps to Reproduce (Repro steps)
Делаем GET DECTARATION BY ID и получаем ответ без ошибок.
Далее SIGN DECLARATION и воспроизводится ошибка.
[dec_sign_error.txt](https://github.com/ehealth-ua/api-spec/files/1454645/dec_sign_error.txt)

## Actual result
Ошибка в SIGN DECLARATION
Пишет о проблеме в валидации в поле статус, на который мы не влияем

## Expected result
Декларация успешно подписана

**Comment by lymychp** [comment]
перед підписанням декларація повинна бути [підтверджена](https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/approve-declaration-request)
