### ISSUE TITLE
demo oAuth ошибка URI при обмене code на token

### ISSUE THREAD

**Issue by KazakovArthur** [ehealth-ua/api-spec#160]
legal entity id 8baca363-8d9d-44d7-9a59-5f447039e5af

1) инициализируем окно oauth

http://auth.demo.ehealth.world/sign-in?client_id=8baca363-8d9d-44d7-9a59-5f447039e5af&redirect_uri=http://maximumroyal.vikisoft.kiev.ua/client/demo_nhealth/toothfairy/services/oa/59e5ca91852a8/&scope=employee:write employee:details employee:deactivate employee_request:approve employee_request:read employee_request:write employee_request:reject legal_entity:read declaration:read declaration_request:read declaration_request:write declaration_request:approve declaration_request:reject otp:write otp:read division:read division:write division:details division:activate division:deactivate&email=arthur.kazakov@vikisoft.kiev.ua

2) авторизируемся
3) получаем code
4) меняем его на токен

{"token":{"client_id":"8baca363-8d9d-44d7-9a59-5f447039e5af","client_secret":"OWhFN1J4YWFZTDd0cDhKNVJCS2g1UT09","code":"YlFTYm9vdWpFU1JnS0NFdHpRcm1MQT09","grant_type":"authorization_code","redirect_uri":"http://maximumroyal.vikisoft.kiev.ua","scope":"employee:write employee:details employee:deactivate employee_request:approve employee_request:read employee_request:write employee_request:reject legal_entity:read declaration:read declaration_request:read declaration_request:write declaration_request:approve declaration_request:reject otp:write otp:read division:read division:write division:details division:activate division:deactivate"}}

5) получаем ошибку не совпадения uri, все запросы идут с http://maximumroyal.vikisoft.kiev.ua

{"meta":{"url":"http://demo.ehealth.world/oauth/tokens","type":"object","request_id":"kc966i0lf94mmooong74578kos3o16mt","code":401},"error":{"invalid_client":"The redirection URI provided does not match a pre-registered value."}}

**Comment by pzhuk** [comment]
1) При регистрации MSP - redirect_uri был установлен  "http://maximumroyal.vikisoft.kiev.ua"  -- тут проблем нет

2) При инициализации аутентификации передали redirect_uri = http://maximumroyal.vikisoft.kiev.ua/client/demo_nhealth/toothfairy/services/oa/59e5ca91852a8/  -- тут тоже все ок

3) А при обмене гранта на токен, снова  "http://maximumroyal.vikisoft.kiev.ua"   -- это проблема, тут должен быть тот же uri что и был на шаге 2
