### ISSUE TITLE
Проэкспарились тестовые токены

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#161]
Где можно получить токены для регистрации медзаклада для работы с демо сервером?

**Comment by pzhuk** [comment]
С чего вы взяли, что токены проэкспайрились? Покажите лог, пожалуйста

**Comment by Charly3X** [comment]
все работало хорошо и в один момент стало ругатся 401 ошибкой. не авторизовано

**Comment by pzhuk** [comment]
Ну так в этом логе четко видна причина, и никакого отношения  к token expiry она не имеет. Причина - отсутствует HTTP Header API-KEY
В этом хедере как раз и должен передаваться токен MIS для всех вызовов.
Это новая функциональность, присутствует только на демо пока. 

Об этом сообщалось в slack канале, а также есть в последней спецификации по Reimbursement
https://uaehealthapi.docs.apiary.io/#reference/public.-reimbursement/

**Comment by Charly3X** [comment]
А как можно подписаться на ваш slack канал?

**Comment by pzhuk** [comment]
В данном случае серкретом будет - b960d5667cda2ccb5aca19ba98a5a46c
В слак канал приглашены все участники, которые подписали Меморандум о сотрудничестве

**Comment by Charly3X** [comment]
Не помогает
  headers = {
      "Content-Type"  => 'application/json',
      "Authorization" => 'Bearer b960d5667cda2ccb5aca19ba98a5a46c',
      'API-key' => 'b960d5667cda2ccb5aca19ba98a5a46c'
  }

{"meta"=>{"url"=>"http://demo.ehealth.world/api/legal_entities", "type"=>"object", "request_id"=>"5lvk52is64ookavsmddl9u20ujndh29e", "code"=>401}, "error"=>{"type"=>"access_denied", "message"=>"API-KEY header is invalid."}}

**Comment by pzhuk** [comment]
Да, прошу прощения - я Вас дезинформировал. 
API-key это отдельный секрет, который будет выдаваться вместе с access_token МИСам.

Я обновил таблицу и информацию по токенам в тестовой документации.
https://docs.google.com/document/d/1pi40OZQ3ajKHmXHFHApoJiVRLLgx4iJVl8bNi93qzW8/edit?usp=sharing

Работающий пример

```
curl -X GET \
  http://demo.ehealth.world/api/legal_entities \
  -H 'api-key: 7e3d7caee0bb522a5079' \
  -H 'authorization: Bearer 256e839faf5ac39d17b8a768aa5ea268' \
```

**Comment by Charly3X** [comment]
Спасибо. Увидел обновленный док. Все заработало.

**Comment by pzhuk** [comment]
Спасибо за тест! :)
