### ISSUE TITLE
Помилка при логіні

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#162]
При логіні на http://auth.demo.ehealth.world отримуємо помилку
<img width="1680" alt="2017-11-15 14 43 55" src="https://user-images.githubusercontent.com/29060924/32836862-ef46126e-ca13-11e7-9ac9-8ad1b5e5e360.png">

Підкажіть, будь ласка, помилка на нашій стороні чи ні? І якщо на нашій то в який конкретно запит потрібно додати api_key?

**Comment by pzhuk** [comment]
@lymychp this looks like our frontend bug

**Comment by lymychp** [comment]
under investigation

**Comment by Charly3X** [comment]
Тоже точно такая же ошибка.

**Comment by sreva** [comment]
Працює, дякую
