### ISSUE TITLE
preprod doesnt return any legal entities?

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#164]
No any LE returned on preprod
Something is broken recently

curl -X GET \
  https://api.ehealth.world/api/legal_entities \
  -H 'api-key: d036273f779b1741dcf0' \
  -H 'authorization: Bearer c490c936651a0f6badeb426721076437' \

**Comment by lymychp** [comment]
the reason why response is empty - wrong client_type.
It was `MSP`. I have changed the client_type to `MIS` for all the test MIS clients.
Now it should work.
