### ISSUE TITLE
Не прийшли листи для підтверження реєстрації (employee_request)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#165]
## Респонси по заявкам

  "meta": {
    "url": "http://api.ehealth-ukraine.org/api/employee_requests",
    "type": "object",
    "request_id": "o8cjhq4v0n6fba34gjr9flbqidjm0h4k",
    "code": 200
  },

  "meta": {
    "url": "http://api.ehealth-ukraine.org/api/employee_requests",
    "type": "object",
    "request_id": "114sknsk4m2e4oikvos2eos4df504q57",
    "code": 200
  },

**Comment by pzhuk** [comment]
обидва були доставлені
