### ISSUE TITLE
Verify Legal Entity by MIS

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#166]
При PATCH запросе получаю ответ:

 {"meta"=>
  {"url"=>
    "http://demo.ehealth.world/api/legal_entities/310f5ba3-05c9-4927-9f42-e90f731345bd/actions/mis_verify",
   "type"=>"object",
   "request_id"=>"na3pghnohbhogc9trjopo8scmffdesud",
   "code"=>403},
 "error"=>
  {"type"=>"forbidden",
   "message"=>
    "Your scope does not allow to access this resource. Missing allowances: legal_entity:mis_verify"}}

Хеадер
{ "Content-Type"  => 'application/json',
        "Authorization" => 'Bearer b960d5667cda2ccb5aca19ba98a5a46c',
        'API-key' => '9cea483e5eb8af18a598' }

Что надо сделать чтобы проверить?

**Comment by pzhuk** [comment]
Исправили, попробуйте еще раз

**Comment by pzhuk** [comment]
Спасибо, что сообщили! :)
