### ISSUE TITLE
Как выбрать улицы города?

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#167]
Пробую Харьков...

http://demo.ehealth.world/api/uaddresses/streets?settlement_id=1241d1f9-ae81-4fe5-b614-f4f780a5acf0
{"meta"=>{"url"=>"http://demo.ehealth.world/streets", "type"=>"object", "request_id"=>"iq1p8cnvg3j7t0hh1k2eb96llgt9u7cn", "code"=>422}, "error"=>{"type"=>"validation_failed", "message"=>"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.", "invalid

если по имени
http://demo.ehealth.world/api/uaddresses/streets?name=%D0%A5%D0%90%D0%A0%D0%9A%D0%86%D0%92
{"meta"=>{"url"=>"http://demo.ehealth.world/streets", "type"=>"object", "request_id"=>"r0qpgkjt6te4u2nsnh1i5thc8u252ll0", "code"=>422}, "error"=>{"type"=>"validation_failed", "message"=>"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.", "invalid"=>[{"rules"=>[{"rule"=>"required", "params"=>[], "description"=>"can't be blank"}], "entry_type"=>"json_data_property", "entry"=>"$.settlement_id"}]}}

**Comment by pzhuk** [comment]
Пример

```
GET /api/uaddresses/streets?settlement_id=1241d1f9-ae81-4fe5-b614-f4f780a5acf0&amp;type=STREET HTTP/1.1
Host: demo.ehealth.world
```
