### ISSUE TITLE
Ошибка ЄДРПОУ

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#168]
Тестируем с реальным медзакладом... Жсон:

{"name":"КОМУНАЛЬНИЙ ЗАКЛАД ОХОРОНИ ЗДОРОВ'Я \"ХАРКІВСЬКА МІСЬКА ДИТЯЧА ПОЛІКЛІНІКА №14 \"","short_name":"ХАРКІВСЬКА МІСЬКА ДИТЯЧА ПОЛІКЛІНІКА №14","public_name":"ДИТЯЧА ПОЛІКЛІНІКА №14","type":"MSP","owner_property_type":"STATE","legal_form":"425","edrpou":"03293936","kveds":["86.21"],"addresses":

Получаем ответ:
[{"rules"=>[{"rule"=>"inclusion", "params"=>["03293936"], "description"=>"is invalid"}], "entry_type"=>"json_data_property", "entry"=>"$.edrpou"}]

Что не так в определении ЄДРПОУ? Ведь оно реальное.

**Comment by pzhuk** [comment]
Значение ЕДРПОУ совпадает со значением ЕДРПОУ в сертификате ЕЦП ?

**Comment by Charly3X** [comment]
Нет не совпадает... На демо тоже должно совпадать?

**Comment by pzhuk** [comment]
Да, должно совпадать, в т.ч. на демо

**Comment by Charly3X** [comment]
Так подписывать надо ключем организации или таки ключем керивныка?

**Comment by pzhuk** [comment]
Нет такого понятия, как ключ организации. 
Есть ЕЦП физ лица сотрудника компании, и есть ЕЦП физ лица (отдельно от компании)
Заявку на создание Legal Entity надо подписывать ключем  сотрудника компании, руководителя
