### ISSUE TITLE
Ошибка при авторизации на ехелсе

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#169]
После регистрации медзаклада и получения приглашения на емеил авторизируюсь на сайте ехелса и получаю ошибку

Помилка:
API-KEY header required. (api_key)

**Comment by sreva** [comment]
+1 ![nvixnuzaspojjwcgo09m1w](https://user-images.githubusercontent.com/29060924/33122823-0074b046-cf81-11e7-9320-6ebd85a14862.png)

**Comment by lymychp** [comment]
fixed on demo (wrong version has been deployed)
