### ISSUE TITLE
Формат дат для полів

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#17]
Добрий день.

Хотів уточнити, який формат дат буде використовуватись для полів з JSON.

Дякую.

**Comment by AlekzandrV** [comment]
Доброго дня.
Поля дат - це строкові типи у форматі дати ISO 8601
Як приклад `2017-06-02`. Тому в JSON в реквестах ми очіуємо саме такий формат

В респонсах ви можете отримати ось такий формат дати `2017-06-01T16:44:58.156592`
Це системні атрибути дати-часу вставки/модифікації запису
