### ISSUE TITLE
Ошибка при регистрации employee

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#171]
POST запрос на "http://demo.ehealth.world/api/employee_requests"

```json
{
  "position": "P1",
  "start_date": "2017-03-02T10:45:16.000Z",
  "status": "NEW",
  "employee_type": "HR",
  "person": {
    "first_name": "Аропро",
    "last_name": "Проро",
    "birth_date": "2017-11-07",
    "birth_country": "Україна",
    "birth_settlement": "Вінниця",
    "tax_id": "345346346",
    "gender": "FEMALE",
    "email": "fghgh@ffff.ru",
    "secret": "secret",
    "addresses": [
      {
        "type": "REGISTRATION",
        "country": "UA",
        "area": "ХАРКІВСЬКА",
        "settlement": "ХАРКІВ",
        "settlement_type": "CITY",
        "settlement_id": "1241d1f9-ae81-4fe5-b614-f4f780a5acf0",
        "street_type": "BOULEVARD",
        "street": "бульвар Перемоги",
        "building": "1"
      },
      {
        "type": "RESIDENCE",
        "country": "UA",
        "area": "ХАРКІВСЬКА",
        "settlement": "ХАРКІВ",
        "settlement_type": "CITY",
        "settlement_id": "1241d1f9-ae81-4fe5-b614-f4f780a5acf0",
        "street_type": "BOULEVARD",
        "street": "бульвар Перемоги",
        "building": "1"
      }
    ],
    "documents": [
      {
        "type": "NATIONAL_ID",
        "number": "вророрп"
      }
    ],
    "phones": [
      {
        "type": "LAND_LINE",
        "number": "+380555234534"
      }
    ]
  }
}
```

хедер:
```json
{
  "Content-Type": "application/json",
  "Authorization": "Bearer N09Hd0Q2UDVBMUw2bjJZL1BKUHpsUT09",
  "API-key": "9cea483e5eb8af18a598"
}
```

ответ от сервера 500-я ошибка:
```
{"errors"=>{"detail"=>"Internal server error"}}
```

что не так?

**Comment by vicusik** [comment]
запрос имеет вид:
{
  "employee_request": {....<то что у Вас> }
}

**Comment by Charly3X** [comment]
Большое спасибо. А не подскажите что за часть **party** при регистрации **employee**

**Comment by vicusik** [comment]
Так party и есть персональные данные доктора

**Comment by vicusik** [comment]
Вернее, надо помнить, что регистрировать могут не только доктора, но и "вспомогательный" персонал. Секция doctor передается только для докторов

**Comment by Charly3X** [comment]
А если это не доктор? А отдел кадров. Все одно требует часть party

**Comment by vicusik** [comment]
Я посмотрел внимательно Ваш оригинальный запрос и уверен что Вам нужно внимательнее изучить структуру данных, передаваемых в запросе:

https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/employee-requests/create-employee-request

**Comment by Charly3X** [comment]
Читал документацию, но нигде не расписано что обозначает часть "party". у доктора есть своя часть doctor.

**Comment by Charly3X** [comment]
Ай... Сам виноват. Спасибо. перепутал party с person. Просто написано очень странно. Person Info это оказывается party :)
