### ISSUE TITLE
By division save come 422 "one and only one registration address is required"

### ISSUE THREAD

**Issue by romanm** [ehealth-ua/api-spec#173]
При збережені даних division отримую відповідь 422
"one and only one registration address is required"
данні division і отримана відповідь  в комміт
https://github.com/romanm/algoritmed-mvp1-ehealth/commit/76c057ef3deae963c7da9c9fdf1445d492226782

Що не так в адресі?

**Comment by pzhuk** [comment]
У вас в запиті є адреса типу "type": "RESIDENCE", але немає "REGISTRATION", яка є обовʼязковою

**Comment by romanm** [comment]
Dankeschön
