### ISSUE TITLE
помилка при логіні 

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#174]
При логіні на продакшені отримуємо http://prntscr.com/hfqtjf

**Comment by lymychp** [comment]
який користувач логіниться?
на якому кроці отримуєте помилку (який сервіс викликаєте)?

**Comment by sreva** [comment]
Овнер вводить логін пароль і нажимає http://prntscr.com/hfqcsb після чого отримує помилку на обміні гранда
