### ISSUE TITLE
Ошибка ЄДРПОУ

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#176]
ПРи регистрации медзаклада на демо ругается
 
 [{"rules"=>[{"rule"=>"required", "params"=>[], "description"=>"can't be blank"}], "entry_type"=>"json_data_property", "entry"=>"$.edrpou"}]

код едрпоу указан как инн... подпись получали в привате на тот же инн....

В чем может быть затык?

ЖСОН:

{:name=>
  "комунальний заклад охорони здоров'я \"харківська міська клінічна лікарня №27\"",
 :short_name=>"кзоз \"хмкл №27\"",
 :type=>"MSP",
 :owner_property_type=>"STATE",
 :legal_form=>"430",
 :edrpou=>"3372901787",
 :kveds=>["86.10"],

**Comment by pzhuk** [comment]
Дайте полный лог, пожалуйста
