### ISSUE TITLE
500 при перереєстрації МСП (demo)

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#177]
## Steps to Reproduce (Repro steps)

- [ ] http://demo.ehealth.world/api/legal_entities
- [ ] МСП було зареєстровано, перереєстровуємо

## Actual result
- [ ]   ```{
            "meta" : {
                "url" : "http://demo.ehealth.world/api/legal_entities",
                "type" : "object",
                "request_id" : "74e62qqs0kmb5eodlof9lnl8r372dal6",
                "code" : 500
            },
            "error" : {
                "errors" : {
                    "detail" : "Internal server error"
                }
            }
        }```

## Expected result
- [ ] успішна реєстрація

**Comment by lymychp** [comment]
was related to the deployment issue.
fixed
