### ISSUE TITLE
http 500 при авторизації

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#178]
## Steps to Reproduce (Repro steps)

- [ ] http://auth.demo.ehealth.world
- [ ] проходимо процес авторизації і отримуємо http 500

## Actual result
- [ ] http://prntscr.com/hgnuhy

## Expected result
- [ ] проходимо аторизацію успішно

**Comment by EdwardVoloshin** [comment]
Добрий день. 
@sreva cпробуйте пройти авторизацию ще раз будь ласка.

**Comment by sreva** [comment]
все ок, дякую.
