### ISSUE TITLE
Помилка реєстрації юр. особи

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#18]
`{
  "meta": {
    "url": "http://api-svc.il/api/legal_entities",
    "type": "object",
    "request_id": "lkrv5kmtherhd2fgiquffjjab8kjtk76",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": "invalid",
            "params": [
              "signed_content"
            ],
            "description": "not a base64 string"
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.signed_content"
      }
    ]
  }
}`

**Comment by lymychp** [comment]
@pieskov 
*Please make sure these boxes are checked before submitting new issue.
It will significantly speed up the issue resolving process and also make our team a little bit happier.
Thanks!*

## Steps to Reproduce (Repro steps)

- [ ] endpoint address
- [ ] preconditions if any
- [ ] sequence of actions that should be taken to reproduce the behavior.
- [ ] test data, requests examples, json files, curl requests etc

## Actual result
- [ ] response example (*.json file)

## Expected result
- [ ] description of the expected system behavior.

**Comment by pieskov** [comment]
Як Ви бачите(або не бачите), тут проблема не в тому що якісь поля не заповнені. Тут проблема декодування строки Base64 на Вашій стороні, до перевірки валідності даних навіть не доходить.

**Comment by lymychp** [comment]
@pieskov надайте плз request json з base64

**Comment by pieskov** [comment]
`PUT /api/legal_entities HTTP/1.1
Host: demo.ehealth.world
Authorization: Bearer a34c97b5a297d8d84f31c0b966206560
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 4ff25551-433f-7fe6-a951-30145890f0fc

{"signed_legal_entity_request":"MIISQAYJKoZIhvcNAQcCoIISMTCCEi0CAQExDjAMBgoqhiQCAQEBAQIBMIIFKAYJKoZIhvcNAQcB
oIIFGQSCBRV7Im5hbWUiOiAiRG1vbiB0ZXN0IiwgInNob3J0X25hbWUiOiAiRG1vbiB0ZXN0Iiwg
InB1YmxpY19uYW1lIjogIkRtb24gdGVzdCIsICJ0eXBlIjogIk1TUCIsICJvd25lcl9wcm9wZXJ0
eV90eXBlIjogIlBSSVZBVEUiLCAibGVnYWxfZm9ybSI6ICIxNTAiLCAiZWRycG91IjogIjAyMDA0
OTgyIiwgImVtYWlsIjogImRteXRyb3BpZXNrb3ZAZ21haWwuY29tIiwgImt2ZWRzIjogWyI4Ni4x
MCJdLCAiYWRkcmVzc2VzIjogW3sidHlwZSI6ICJSRUdJU1RSQVRJT04iLCAiY291bnRyeSI6ICJV
QSIsICJhcmVhIjogIsKz7e3o9vzq4CDu4evg8fL8IiwgInJlZ2lvbiI6ICLCs+3t6Pb86uAg7uHr
4PHy/CIsICJzZXR0bGVtZW50IjogIsro5eIiLCAic2V0dGxlbWVudF90eXBlIjogIkNJVFkiLCAi
c2V0dGxlbWVudF9pZCI6ICI0MzQzMjQzMiIsICJzdHJlZXRfdHlwZSI6ICJTVFJFRVQiLCAic3Ry
ZWV0IjogIszg6uDw7uLx6uD/IiwgImJ1aWxkaW5nIjogIjEyIiwgImFwYXJ0bWVudCI6ICIxMiIs
ICJ6aXAiOiAiMDQxMDcifV0sICJwaG9uZXMiOiBbeyJ0eXBlIjogIkxBTkRfTElORSIsICJudW1i
ZXIiOiAiKzM4MDY3NDAyMzY1MCJ9XSwgIm93bmVyIjogeyJmaXJzdF9uYW1lIjogIkZpcnN0Iiwg
Imxhc3RfbmFtZSI6ICJMYXN0IiwgInNlY29uZF9uYW1lIjogIlNlY29uZCIsICJ0YXhfaWQiOiAi
MTExMTExMTExMSIsICJiaXJ0aF9kYXRlIjogIjE4OTktMTItMzAiLCAiYmlydGhfcGxhY2UiOiAi
YmlydGhfcGxhY2UiLCAiZ2VuZGVyIjogIk1BTEUiLCAiZW1haWwiOiAiZG15dHJvcGllc2tvdkBn
bWFpbC5jb20iLCAicG9zaXRpb24iOiAiUDMifSwgIm1lZGljYWxfc2VydmljZV9wcm92aWRlciI6
IHsibGljZW5zZXMiOiBbeyJsaWNlbnNlX251bWJlciI6ICJMaWMxIiwgImlzc3VlZF9ieSI6ICJp
c3N1ZWRfYnkiLCAiaXNzdWVkX2RhdGUiOiAiMjAxNC0wMS0wMSIsICJleHBpcnlfZGF0ZSI6ICIy
MDIwLTAxLTAxIiwgImt2ZWQiOiAiODYuMTAiLCAid2hhdF9saWNlbnNlZCI6ICJ3aGF0X2xpY2Vu
c2VkIn1dLCAiYWNjcmVkaXRhdGlvbiI6IHsiY2F0ZWdvcnkiOiAiRklSU1QiLCAiaXNzdWVkX2Rh
dGUiOiAiMjAxNC0wMS0wMSIsICJleHBpcnlfZGF0ZSI6ICIyMDIwLTAxLTAxIiwgIm9yZGVyX25v
IjogIjEyMzV3ZSIsICJvcmRlcl9kYXRlIjogIjIwMjAtMDEtMDEifX0sICJzZWN1cml0eSI6IHsi
cmVkaXJlY3RfdXJpIjogImh0dHBzOlwvXC9nb29nbGUuY29tLnVhIn0sICJwdWJsaWNfb2ZmZXIi
OiB7ImNvbnNlbnQiOiBmYWxzZSwgImNvbnNlbnRfdGV4dCI6ICJjb25zZW50X3RleHQifX0NCqCC
BiIwggYeMIIFmqADAgECAhRRc6sGAAAAAAAAAAAAAAAAAAAAATANBgsqhiQCAQEBAQMBATCCARwx
WzBZBgNVBAMMUtCQ0KbQodCaINCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDR
htGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxETAPBgNVBAcMCNCa0LjRl9CyMRkw
FwYDVQQFDBBVQS0zNjg2NTc1My0wMTE0MVIwUAYDVQQKDEnQotCe0JIgItCm0LXQvdGC0YAg0YHQ
tdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C90LAiMS4wLAYD
VQQLDCXQktGW0LTQtNGW0Lsg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXMQswCQYDVQQGDAJVQTAe
Fw0xNzAxMjAwNzM2NDBaFw0xNzA2MjIyMDU5NTlaMIIBlzEgMB4GA1UEAwwX0KDQvtGB0LrQvtC/
0ZbQvSDQni7QnC4xGzAZBgNVBAgMEtCn0JXQoNCa0JDQodCs0JrQkDEiMCAGA1UEBwwZ0LzRltGB
0YLQviDQp9CV0KDQmtCQ0KHQmDEOMAwGA1UEEQwFMTgwMDUxRzBFBgNVBAkMPtCy0YPQu9C40YbR
jyDQkifRj9GH0LXRgdC70LDQstCwINCn0L7RgNC90L7QstC+0LvQsCwg0LHRg9C0LiAxMRkwFwYD
VQQMDBDQtNC40YDQtdC60YLQvtGAMRkwFwYDVQQEDBDQoNC+0YHQutC+0L/RltC9MSgwJgYDVQQq
DB/QntC70LXQsyDQnNC40LrQvtC70LDQudC+0LLQuNGHMRQwEgYDVQQFDAsyMzI4OTEzMjU3RDFW
MFQGA1UECgxN0JrQndCfICLQlNCg0KPQk9CY0Jkg0KfQldCg0JrQkNCh0KzQmtCY0Jkg0JzQhtCh
0KzQmtCY0Jkg0KbQldCd0KLQoCDQn9Cc0KHQlCIxCzAJBgNVBAYMAlVBMEYwHgYLKoYkAgEBAQED
AQEwDwYNKoYkAgEBAQEDAQECBgMkAAQhrszXZs00LHvbcPfvhKh2LjKHHA826AQPHPwWVzV1PwAB
o4ICSTCCAkUwQwYDVR0JBDwwOjAaBgwqhiQCAQEBCwEEAgExChMIMDIwMDQ5ODIwHAYMKoYkAgEB
AQsBBAEBMQwTCjIzMjg5MTMyNTcwGwYDVR0RBBQwEoEQMDU1Mjk2OTFAbWV0YS51YTApBgNVHQ4E
IgQglr/yeH6FgpgMLuM4aIiL/65nvFMHIXj2oJRCdffuBpIwKwYDVR0jBCQwIoAgsSjTVHQnl6Lv
ic3TLqVAMZ9ff84euOoz9WR29Zw8gKEwDgYDVR0PAQH/BAQDAgDAMBgGA1UdJQQRMA8GDSqGJAIB
AQELkcqNWQEwGQYDVR0gAQH/BA8wDTALBgkqhiQCAQEBAgIwMgYIKwYBBQUHAQMBAf8EIzAhMAsG
CSqGJAIBAQECATASBgMEAAIwCxMDVUFIAgEBAgEGMDMGA1UdLgQsMCowKKAmoCSGImh0dHA6Ly91
YWtleS5jb20udWEvbGlzdC1kZWx0YS5jcmwwLQYDVR0fBCYwJDAioCCgHoYcaHR0cDovL3Vha2V5
LmNvbS51YS9saXN0LmNybDA9BggrBgEFBQcBCwQxMC8wLQYIKwYBBQUHMAOGIWh0dHA6Ly91YWtl
eS5jb20udWEvc2VydmljZXMvdHNwLzBtBggrBgEFBQcBAQRhMF8wLQYIKwYBBQUHMAKGIWh0dHA6
Ly91YWtleS5jb20udWEvdWFrZXljZXJ0LnA3YjAuBggrBgEFBQcwAYYiaHR0cDovL3Vha2V5LmNv
bS51YS9zZXJ2aWNlcy9vY3NwLzANBgsqhiQCAQEBAQMBAQNvAARsyuVcuJZY7Zw5zIrng9eGAa77
RQC0bi7EbWiZCxwN9Ya7dxbCcJ0VYQPRId1FDw78WpFqjaoNmAjplNdJefL63HFkgyA002UZKmwv
fpavZRR/GRHQN9DgxzmREkhUt9mn0rrh0kftaeRJYdUdMYIGxDCCBsACAQEwggE2MIIBHDFbMFkG
A1UEAwxS0JDQptCh0Jog0KLQntCSICLQptC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbR
lyDQutC70Y7Rh9GW0LIgItCj0LrRgNCw0ZfQvdCwIjERMA8GA1UEBwwI0JrQuNGX0LIxGTAXBgNV
BAUMEFVBLTM2ODY1NzUzLTAxMTQxUjBQBgNVBAoMSdCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDR
gtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxLjAsBgNVBAsM
JdCS0ZbQtNC00ZbQuyDRgdC10YDRgtC40YTRltC60LDRhtGW0ZcxCzAJBgNVBAYMAlVBAhRRc6sG
AAAAAAAAAAAAAAAAAAAAATAMBgoqhiQCAQEBAQIBoIIFIDAYBgkqhkiG9w0BCQMxCwYJKoZIhvcN
AQcBMBwGCSqGSIb3DQEJBTEPFw0xNzA2MDExMjAzMTVaMC8GCSqGSIb3DQEJBDEiBCAo09SoCNaH
MWOlYjQSzmKXcgcgF+ZVQnd/+0M5xalMpjCCAY8GCyqGSIb3DQEJEAIvMYIBfjCCAXowggF2MIIB
cjAMBgoqhiQCAQEBAQIBBCDcDYMBAaAuLXnNbXevnOwQsDAb0YR0yG269xEH3tvz3TCCAT4wggEk
pIIBIDCCARwxWzBZBgNVBAMMUtCQ0KbQodCaINCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC4
0YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxETAPBgNVBAcMCNCa
0LjRl9CyMRkwFwYDVQQFDBBVQS0zNjg2NTc1My0wMTE0MVIwUAYDVQQKDEnQotCe0JIgItCm0LXQ
vdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C9
0LAiMS4wLAYDVQQLDCXQktGW0LTQtNGW0Lsg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXMQswCQYD
VQQGDAJVQQIUUXOrBgAAAAAAAAAAAAAAAAAAAAEwggMgBgsqhkiG9w0BCRACFDGCAw8wggMLBgkq
hkiG9w0BBwKgggL8MIIC+AIBAzEOMAwGCiqGJAIBAQEBAgEwaQYLKoZIhvcNAQkQAQSgWgRYMFYC
AQEGCCsGAQUFBwMIMDAwDAYKKoYkAgEBAQECAQQgKNPUqAjWhzFjpWI0Es5il3IHIBfmVUJ3f/tD
OcWpTKYCBAbAkBoYDzIwMTcwNjAxMTIwMjMyWjGCAnYwggJyAgEBoCIEIAL/Z+cUTz5Hmug+cOpy
p2pbB1+bEsiaGI4rl4l3i5rvMAwGCiqGJAIBAQEBAgGgggG8MC8GCSqGSIb3DQEJBDEiBCCCboiM
+7ueAbHXgEYykUh2tycFxGzdZCxhzve9eCXICzAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQw
ggFrBgsqhkiG9w0BCRACLzGCAVowggFWMIIBUjCCAU4wDAYKKoYkAgEBAQECAQQgHaK5FE8dZoGU
lbL+tAU/+6pPgtBIR2i6hU4FoS642w4wggEaMIIBAKSB/TCB+jE/MD0GA1UECgw20JzRltC90ZbR
gdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQ
kNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3R
gtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9
MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDEyMQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX
0LICFDAEdR3vLHiuAgAAAAEAAAAJAAAAMA0GCyqGJAIBAQEBAwEBBGziVacU5vNZkUFlo7ZRqF/W
nbbqhGG+1hNv9n15X84pCeMVtE8LpiYUuq6rKGjWCTRFm+NznhCK+2hqPGn7V4aAuRTNyop5DPz/
5VHjy0VC0bEgb4Y1b6yhrXdb/NknHN+O7k9lwsZaDkQU5jUwDQYLKoYkAgEBAQEDAQEEQB5ktkoQ
7jaE7LeLd7nNMNVBZ33WUZUYvRq+V9ZOeTYDfVW/xqetMqRRUpuOvRKzG1lW8hz2BPXG+uNh6HuL
KEU=","signed_content_encoding":"base64"}`

**Comment by DPashchenko** [comment]
@pieskov Доброго времени суток!
1. Как вы видите, сервис вернул Вам:
```
"description": "not a base64 string"
```
Никакой ошибки в этом нет, дело в том, что Вы неправильно сформировали запрос. Уберите переносы в b64 строке и тогда получится валидная строка.
2. Данные, которые вы подписывали, также сформированы некорректно. Кодировка должна быть utf-8. У Вас в объекте адрес не utf-8 кодировка.
```
{"name": "Dmon test", "short_name": "Dmon test", "public_name": "Dmon test", "type": "MSP", "owner_property_type": "PRIVATE", "legal_form": "150", "edrpou": "02004982", "email": "dmytropieskov@gmail.com", "kveds": ["86.10"], "addresses": [{"type": "REGISTRATION", "country": "UA", "area": "³������� �������", "region": "³������� �������", "settlement": "����", "settlement_type": "CITY", "settlement_id": "43432432", "street_type": "STREET", "street": "�����������", "building": "12", "apartment": "12", "zip": "04107"}], "phones": [{"type": "LAND_LINE", "number": "+380674023650"}], "owner": {"first_name": "First", "last_name": "Last", "second_name": "Second", "tax_id": "1111111111", "birth_date": "1899-12-30", "birth_place": "birth_place", "gender": "MALE", "email": "dmytropieskov@gmail.com", "position": "P3"}, "medical_service_provider": {"licenses": [{"license_number": "Lic1", "issued_by": "issued_by", "issued_date": "2014-01-01", "expiry_date": "2020-01-01", "kved": "86.10", "what_licensed": "what_licensed"}], "accreditation": {"category": "FIRST", "issued_date": "2014-01-01", "expiry_date": "2020-01-01", "order_no": "1235we", "order_date": "2020-01-01"}}, "security": {"redirect_uri": "https:\/\/google.com.ua"}, "public_offer": {"consent": false, "consent_text": "consent_text"}}
```
Если возникнут дополнительные вопросы - обращайтесь.
Спасибо!

**Comment by pieskov** [comment]
1. Переносов в строке нет, это тут так отображается.
2. Какая разнаца какая кодировка? даже если все данный будут на английском. то все равно будет такая ошибка. Ошибка состоит в том, что ваш метод не может декодировать втроку base64.

**Comment by DPashchenko** [comment]
@pieskov 
1. Ваша строка b64 в редакторе Sublime Text:
<img width="1680" alt="screen shot 2017-06-02 at 2 05 01 pm" src="https://cloud.githubusercontent.com/assets/19431920/26723376/ef0a9c38-479c-11e7-8224-83bb1c69e24e.png">
Отображение символа переноса строки:
<img width="1680" alt="screen shot 2017-06-02 at 2 05 08 pm" src="https://cloud.githubusercontent.com/assets/19431920/26723422/1d1572ba-479d-11e7-9203-f7781a8b2cc4.png">
B64 без переноса строки:
<img width="1680" alt="screen shot 2017-06-02 at 2 05 11 pm" src="https://cloud.githubusercontent.com/assets/19431920/26723440/388786b4-479d-11e7-8580-624f34c9dde5.png">
2. Уберите переносы и сервис будет нормально декодировать строку. Данный пример содержит невалидную b64 строку и некорректную кодировку.

**Comment by pieskov** [comment]
Да действительно были переносы. Но мне не  понятно, почему вчера работало с преносами, а сегодня переносы стали вдруг мешать. Кстати все мотоды которые кодируют строки в Base64 ставят переносы (независимо от языка программирования). Поэтому приходится дополнительно проверять свормированную строку и "вычищать" ее.
