### ISSUE TITLE
Регистрация доктора с емеилом от другого employee

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#180]
Регистрация доктора проходит успешно.
Перехожу по приглашению от Ехелса заполняю пароль нажимаю ПОДТВЕРДИТЬ.
Ничего не происходит. В консоле бразуера пишет
http://demo.ehealth.world/api/employee_requests/73c8d311-3841-40ea-8898-58b98ca3d257/approve 409 (Conflict)
type":"request_conflict","message":"Email is already used by another person

ИМХО если емеил уже гдето используется надо не давать регистрировать доктора на первом этапе отсылке данных в Ехелс.

**Comment by pzhuk** [comment]
@lymychp  can you please confirm why this employee request is even possible, while actual employee request never can be approved?

**Comment by lymychp** [comment]
there is a check: one email should be linked with one party only. At the same time one party can have multiple emails.
user* -- 1party
This check is performed only on the employee_request approval step.
