### ISSUE TITLE
Помилка при авторизації на пре-прод

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#182]
## Steps to Reproduce (Repro steps)

- [ ] `http://auth.ehealth.world/accept?client_id=0651e111-82fd-4f52-a921-a5835eef266e&email=thesakharov%2B070%40gmail.com&redirect_uri=https%3A%2F%2Fstagingreform.helsi.me%2Fuser%2Fauth&request_type=code&scope=employee%3Aread+employee%3Awrite+employee_request%3Aapprove+employee_request%3Aread+employee_request%3Awrite+employee_request%3Areject+legal_entity%3Aread+declaration_request%3Aread+declaration_request%3Awrite+otp%3Awrite+otp%3Aread+division%3Aread+division%3Awrite+employee%3Adeactivate+employee%3Awrite+declaration%3Aread+declaration_request%3Areject+employee%3Adetails+division%3Adetails+division%3Aactivate+division%3Adeactivate+declaration_request%3Aapprove`

- [ ] при авторизації 
![image](https://user-images.githubusercontent.com/29060924/33429293-e7c2a06c-d5d4-11e7-9486-89679dc31e11.png) отримуємо на етапі підтвердження 422

## Actual result
- [ ] `{"meta":{"url":"http://api.ehealth.world/oauth/apps/authorize","type":"object","request_id":"8cb9nti9a85fvmdfp5slh4hh24nv0s71","code":422},"error":{"type":"request_malformed","message":"User requested scope that is not allowed by role based access policies.","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}`

## Expected result
- [ ] логінимся успішно

**Comment by svetavedmed** [comment]
The problem is on helsi site. You have an answer 204 and then you are redirecting to `https://stagingreform.helsi.me/user/auth?code=R3ZwU2dZalZZTXBzUWUzRmZsU0t2dz09`
