### ISSUE TITLE
При запиті деталей співробітника повертаються не всі дані

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#184]
При створенні співробітника блог party має вигляд
`"party":{
    "first_name":"Іванов",
    "last_name":"Іванович",
    "second_name":"Іван",
    "birth_date":"1982-03-01",
    "gender":"MALE",
    "tax_id":"3001017550",
    "email":"pieskov.do@hotmail.com",
    "documents":[
        {
            "type":"PASSPORT",
            "number":"СК111111"
        }
    ],
    "phones":[
        {
            "type":"MOBILE",
            "number":"+380673452323"
        }
    ]

}`

а при запиті деталей співробітника блок party вже має такий вигляд:
`"party": {
            "tax_id": "3001017550",
            "second_name": "Іван",
            "phones": [
                {
                    "type": "MOBILE",
                    "number": "+380673452323"
                }
            ],
            "last_name": "Іванович",
            "id": "6be97fd5-3564-49a6-9d7e-3349d056a735",
            "gender": "MALE",
            "first_name": "Іванов",
            "documents": [
                {
                    "type": "PASSPORT",
                    "number": "СК111111"
                }
            ],
            "birth_date": "1982-03-01"
        }`

Чому не повертаеться email?

**Comment by lymychp** [comment]
it work as it should according to the spec.
`email`- not a party attribute. It is attribute of the user entity
