### ISSUE TITLE
Ошбика при создании Подразделение на демо

### ISSUE THREAD

**Issue by KazakovArthur** [ehealth-ua/api-spec#185]
отправляем 
{"legal_entity_id":"8baca363-8d9d-44d7-9a59-5f447039e5af","name":"Подразделение 1","addresses":[{"type":"REGISTRATION","country":"UA","area":"КИЇВСЬКА","region":"ВАСИЛЬКІВСЬКИЙ","settlement":"ВАСИЛЬКІВ","settlement_type":"CITY","settlement_id":"2564ff1f-6659-4af3-98bc-e74d6e49660d","street_type":"BLIND_STREET","street":"Тупик","building":"1","apartment":"1","zip":"08600"}],"phones":[{"type":"MOBILE","number":"+380953659425"}],"email":"arthur.kazakov@vikisoft.kiev.ua","external_id":3,"location":{"latitude":"1.000000","longitude":"1.000000"}}

ответ если используем полученный access token owner'а

{"meta":{"url":"http://demo.ehealth.world/api/divisions","type":"object","request_id":null,"code":500},"error":{"type":"internal_error"}}

наш запрос
$authorization = "Authorization: Bearer SHI5TkdhcTZMMitwYmhlZk5UMTFoQT09";
$apikey = "api-key:  OWhFN1J4YWFZTDd0cDhKNVJCS2g1UT09";

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "http://demo.ehealth.world/api/divisions");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POSTFIELDS, $json);
curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json' , $authorization, $apikey ));
curl_exec($ch);

ответ если используем тестовый  access token, ну тут понятно
{"meta":{"url":"http://demo.ehealth.world/api/divisions","type":"object","request_id":"k8q68b6h7r8l2chuo0ug1bt6qhg5i6dl","code":403},"error":{"type":"forbidden","message":"Your scope does not allow to access this resource. Missing allowances: division:write"}}

**Comment by lymychp** [comment]
помилка на демо не відтворюється.
щойно спробував створити підрозділ з Вашим датасетом, отримав 422 з купою помилок валідації.
```
{
    "meta": {
        "url": "http://demo.ehealth.world/api/divisions",
        "type": "object",
        "request_id": "csofmhptokuanrbnub9mhce57oakifp5",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "cast",
                        "params": [
                            "string"
                        ],
                        "description": "type mismatch. Expected String but got Integer"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.external_id"
            },
            {
                "rules": [
                    {
                        "rule": "cast",
                        "params": [
                            "number"
                        ],
                        "description": "type mismatch. Expected Number but got String"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.location.latitude"
            },
            {
                "rules": [
                    {
                        "rule": "cast",
                        "params": [
                            "number"
                        ],
                        "description": "type mismatch. Expected Number but got String"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.location.longitude"
            },
            {
                "rules": [
                    {
                        "rule": "required",
                        "params": [],
                        "description": "required property type was not present"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.type"
            }
        ]
    }
}
```

**Comment by KazakovArthur** [comment]
ну у нас приходит {"meta":{"url":"http://demo.ehealth.world/api/divisions","type":"object","request_id":null,"code":500},"error":{"type":"internal_error"}}
т.е. с аксесс токеном все в порядке?

**Comment by KazakovArthur** [comment]
через постман таже проблема

curl -X POST \
  http://demo.ehealth.world/api/divisions \
  -H 'api-key: OWhFN1J4YWFZTDd0cDhKNVJCS2g1UT09' \
  -H 'authorization: Bearer SHI5TkdhcTZMMitwYmhlZk5UMTFoQT09' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: 32e78ceb-ddb5-050f-0ae1-ea0e947918de' \
  -d '{"legal_entity_id":"8baca363-8d9d-44d7-9a59-5f447039e5af","name":"Подразделение 1","addresses":[{"type":"REGISTRATION","country":"UA","area":"КИЇВСЬКА","region":"ВАСИЛЬКІВСЬКИЙ","settlement":"ВАСИЛЬКІВ","settlement_type":"CITY","settlement_id":"2564ff1f-6659-4af3-98bc-e74d6e49660d","street_type":"BLIND_STREET","street":"Тупик","building":"1","apartment":"1","zip":"08600"}],"phones":[{"type":"MOBILE","number":"+380953659425"}],"email":"arthur.kazakov@vikisoft.kiev.ua","external_id":3,"location":{"latitude":"1.000000","longitude":"1.000000"}}'

**Comment by lymychp** [comment]
у Вас з хедерами якась каша.
`api-key` - тут має бути секрет МІСа
`authorization ` - має бути `access_token` користувача, отриманий по oauth 2.0 flow.

**Comment by KazakovArthur** [comment]
та вроде все ок, попробовал заново создать легалентети и получить новый акссетокен.
зарегистрировал повторон, получил письмо зашел все подтвердил, теперь на этапе оавторизации при нажатии на кнопку продолжить ничего не происходит
![2017-12-01_16-42-01](https://user-images.githubusercontent.com/1842573/33487687-bd8eeff2-d6b6-11e7-873c-661014a9a619.png)

**Comment by lymychp** [comment]
покажіть, будь ласка, лог консолі. Аутентифікація `взагалі` працює, тільки що перевірив.

**Comment by KazakovArthur** [comment]
да там была у нас проблемка, ну суть в том что полуисл новый акссестокен и все равно

Authorization: Bearer ejVLUXA3L1hYTzNxU1VoS2YzR0VkUT09

api-key: OWhFN1J4YWFZTDd0cDhKNVJCS2g1UT09

{"legal_entity_id":"8baca363-8d9d-44d7-9a59-5f447039e5af","name":"Подразделение 1","addresses":[{"type":"REGISTRATION","country":"UA","area":"КИЇВСЬКА","region":"ВАСИЛЬКІВСЬКИЙ","settlement":"ВАСИЛЬКІВ","settlement_type":"CITY","settlement_id":"2564ff1f-6659-4af3-98bc-e74d6e49660d","street_type":"BLIND_STREET","street":"Тупик","building":"1","apartment":"1","zip":"08600"}],"phones":[{"type":"MOBILE","number":"+380953659425"}],"email":"arthur.kazakov@vikisoft.kiev.ua","external_id":3,"location":{"latitude":"1.000000","longitude":"1.000000"}}

{"meta":{"url":"http://demo.ehealth.world/api/divisions","type":"object","request_id":null,"code":500},"error":{"type":"internal_error"}}

**Comment by lymychp** [comment]
api-key: OWhFN1J4YWFZTDd0cDhKNVJCS2g1UT09
неправильний

**Comment by KazakovArthur** [comment]
"user_id":"2d2577f7-cdfa-4e94-b758-acb9372d81c2"
,"request_id":"6keibjleg8g88t8na0rm9d98dkuhkpqu"
при получении акссетокена,

**Comment by KazakovArthur** [comment]
вот что пришло при регистрации легалентети

{"urgent":{"security":{"redirect_uri":"http://maximumroyal.vikisoft.kiev.ua","client_secret":"OWhFN1J4YWFZTDd0cDhKNVJCS2g1UT09","client_id":"8baca363-8d9d-44d7-9a59-5f447039e5af"},"employee_request_id":"2ddc039a-d83e-4649-9272-f1daa365e500"},"meta":{"url":"http://demo.ehealth.world/api/legal_entities","type":"object","request_id":"7u8uhnfa88ka47frn0qqjt0ri24h9adp","code":200},"data":{"updated_by":"7dfa0a74-f2c8-4063-b92f-691178d0af1d","updated_at":"2017-12-01T14:34:01.298869","type":"MSP","status":"ACTIVE","short_name":"VikiSoft","public_name":"Компанія ВікіСофт","phones":[{"type":"LAND_LINE","number":"+380953659425"},{"type":"MOBILE","number":"+384441111166"}],"owner_property_type":"PRIVATE","nhs_verified":false,"name":"ПП ВікіСофт22","mis_verified":"NOT_VERIFIED","medical_service_provider":{"licenses":[{"what_licensed":"sadsa sda ","order_no":"ВА43231","license_number":"fd12123123","issued_date":"2017-06-01","issued_by":"asdsa sad asd a","expiry_date":"2017-06-30","active_from_date":"2017-06-01"}],"accreditation":{"order_no":"fd13332223","order_date":"2017-06-02","issued_date":"2017-06-02","expiry_date":"2017-06-30","category":"FIRST"}},"legal_form":"120","kveds":["86.10"],"is_active":true,"inserted_by":"7dfa0a74-f2c8-4063-b92f-691178d0af1d","inserted_at":"2017-10-31T12:10:26.577090","id":"8baca363-8d9d-44d7-9a59-5f447039e5af","email":"cto@vikisoft.kiev.ua","edrpou":"37153175","addresses":[{"zip":"03187","type":"REGISTRATION","street_type":"STREET","street":"Декабристів","settlement_type":"CITY","settlement_id":"2564ff1f-6659-4af3-98bc-e74d6e49660d","settlement":"ВАСИЛЬКІВ","region":"ВАСИЛЬКІВСЬКИЙ","country":"UA","building":"12","area":"КИЇВСЬКА","apartment":"1"}]}}

**Comment by lymychp** [comment]
це секрет legal_entity. А в `api_key` треба передавати  секрет MISа.

**Comment by KazakovArthur** [comment]
а чтоб его получить он приходит при оавторизации на мис?

**Comment by pzhuk** [comment]
Всі тестові дані тут
https://docs.google.com/document/d/1pi40OZQ3ajKHmXHFHApoJiVRLLgx4iJVl8bNi93qzW8/edit?usp=sharing

**Comment by KazakovArthur** [comment]
есть пошло закрываю
