### ISSUE TITLE
Failed to create employee because LE UUID is not accepted?

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#186]
Environment: demo
Problem: employee request failing
Expected result: successful registration

```
{
    "meta": {
        "url": "http://demo.ehealth.world/api/employee_requests",
        "type": "object",
        "request_id": "46auu0p77jriaekn7qp75cutek9fkv7b",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "format",
                        "params": [
                            "^[0-9a-f]{8}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{12}$"
                        ],
                        "description": "string does not match pattern \"^[0-9a-f]{8}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{12}$\""
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.employee_request.legal_entity_id"
            }
        ]
    }
}
```

**Comment by svetavedmed** [comment]
Is this error actual as I can not reproduce this employee request failing

**Comment by lymychp** [comment]
@pzhuk please share the request data.

**Comment by MarkInvince** [comment]
Request Body:
{
  "employee_request": {
    "position": "P1",
    "start_date": "2017-03-02",
    "end_date": "2018-03-02",
    "status": "NEW",
    "employee_type": "DOCTOR",
    "party": {
      "first_name": "Тест",
      "last_name": "Лікар",
      "second_name": "Тестович",
      "birth_date": "1991-08-19",
      "gender": "MALE",
      "tax_id": "3126509816",
      "email": "markijan9891@gmail.com",
      "documents": [
        {
          "type": "PASSPORT",
          "number": "77777"
        }
      ],
      "phones": [
        {
          "type": "MOBILE",
          "number": "+380000000001"
        }
      ]
    },
    "doctor": {
      "educations": [
        {
          "country": "UA",
          "city": "Київ",
          "institution_name": "Академія Тест",
          "issued_date": "2017-01-01",
          "diploma_number": "DD123543",
          "degree": "MASTER",
          "speciality": "Педіатр"
        }
      ],
      "qualifications": [
        {
          "type": "SPECIALIZATION",
          "institution_name": "Академія Тест",
          "speciality": "Педіатр",
          "issued_date": "2017-01-01",
          "certificate_number": "2017",
          "valid_to": "2018-01-01",
          "additional_info": "додаткова інофрмація"
        }
      ],
      "specialities": [
        {
          "speciality": "THERAPIST",
          "speciality_officio": true,
          "level": "FIRST",
          "qualification_type": "AWARDING",
          "attestation_name": "Академія Тест",
          "attestation_date": "2017-01-01",
          "valid_to_date": "2020-01-01",
          "certificate_number": "AB/21331"
        }
      ],
      "science_degree": {
        "country": "UA",
        "city": "Львів",
        "degree": "CANDIDATE_OF_SCIENCE",
        "institution_name": "Академія Тест",
        "diploma_number": "DD756473",
        "speciality": "Педіатр",
        "issued_date": "2017-01-01"
      }
    }
  }
}

Headers:
[{"key":"Authorization","value":"Bearer c490c936651a0f6badeb426721076437","description":"","enabled":true},{"key":"Content-Type","value":"application/json","description":"","enabled":true}]

**Comment by svetavedmed** [comment]
with this request I have error with Tax_id. I validate it, it is wrong - `ИНН 3126509816 – недействителен!`. If I replace not valid tax_id with valid, in response I receive 200 and created employee request. So, I still can not reproduce an error.

**Comment by pzhuk** [comment]
thanks @svetavedmed 

can't reproduce
