### ISSUE TITLE
400 при створенні МСП

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#187]
## Steps to Reproduce (Repro steps)

- [ ] api.ehealth.world/api/legal_entities
- [ ] [MSP.txt](https://github.com/ehealth-ua/api-spec/files/1527628/MSP.txt)

## Actual result
- [ ] ```{
            "meta" : {
                "url" : "http://api.ehealth.world/api/legal_entities",
                "type" : "object",
                "request_id" : "pbionkr16sp52vcodi7c99aj4hdm76ob",
                "code" : 400
            },
            "error" : {
                "type" : "request_malformed",
                "message" : "Signed request data is invalid",
                "invalid" : [ 
                    {
                        "rules" : [ 
                            {
                                "rule" : "json"
                            }
                        ],
                        "entry_type" : "request"
                    }
                ]
            }
        }```

## Expected result
- [ ] МСП зареєстровано

**Comment by pzhuk** [comment]
@svetavedmed would you please kindly test if issue persist with new certificates for ACSK Ukraine?
https://drive.google.com/open?id=1CuwSUM1CL_knP2dTH-a5fUqYrAt1y9yI

**Comment by svetavedmed** [comment]
Unfortunately, with new certificates I have the same error 
```
{
    "meta": {
        "url": "http://api.ehealth.world/api/legal_entities",
        "type": "object",
        "request_id": "tpjl0hk54b96881rctng51k53fe8hd1l",
        "code": 400
    },
    "error": {
        "type": "request_malformed",
        "message": "Signed request data is invalid",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "json"
                    }
                ],
                "entry_type": "request"
            }
        ]
    }
}
```

**Comment by sreva** [comment]
@pzhuk @svetavedmed  з ЕПЦ інших АЦСК реєстрація проходить успішно, ну це так для довіднки :)

**Comment by lymychp** [comment]
@sreva is it reproducible?

**Comment by evgenkai** [comment]
Доброго дня. а на даний момент підписом від АЦСК "Україна" можна працювати з E-Health? Маю такий же респонс як і тут...
