### ISSUE TITLE
E-mail в get employee details

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#188]
*Не нашёл способ получить e-mail уже ранее зарегистрированного врача. Можно ли добавить e-mail в get employee details? Есть ли другой простой способ получить e-mail какого-либо employee, не используя employee request?*

## Steps to Reproduce (Repro steps)

Сейчас в get employee details нет e-mail.

## Actual result
- Нет e-mail.

## Expected result
- Есть e-mail.

**Comment by svetavedmed** [comment]
duplicate #238
