### ISSUE TITLE
Not a valid utf8 string (prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#189]
* Доброго дня, подивіться будь-ласка по request_id, що саме не так у запиті ,вертає помилку (not a valid utf8 string), коли підписували json відповідно (дані та підпис в одному контейнері) - респонс *

{
   "meta": {
       "url": "http://api.ehealth-ukraine.org/api/legal_entities",
       "type": "object",
       "request_id": "u7lnc2da4n9b7gg11l9tpt7n1eno7k4t",
       "code": 422
   },
   "error": {
       "type": "validation_failed",
       "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
       "invalid": [
           {
               "rules": [
                   {
                       "rule": "invalid",
                       "params": [],
                       "description": "not a valid utf8 string"
                   }
               ],
               "entry_type": "json_data_property",
               "entry": "$.content"
           }
       ]
   }
}

## Actual result
- [ ] not a valid utf8 string

## Expected result
- [ ] responce 200

**Comment by pzhuk** [comment]
Неправильно подписанный обьект, нету тела обьекта json
Судя по всему, подписано было методом "подпись в отдельном файле"
