### ISSUE TITLE
Довідник адрес

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#19]
## Steps to Reproduce (Repro steps)

- [x] endpoint address - http://demo.ehealth.world/api/uaddresses/search/settlements?settlement_name=Славутич&region=Київська 

- [x] sequence of actions that should be taken to reproduce the behavior. - запросити інфу по andPoint вище
- [x] test data, requests examples, json files, curl requests etc
1. region=Київська   settlement_name=Славутич 
2. region=Луганська  settlement_name=Станиця Луганська
3. region=Дніпропетровськ district=Дніпровський settlement_name=Підгородне

## Actual result
- в respons.zip **[respons.zip](https://github.com/ehealth-ua/api-spec/files/1047933/respons.zip)**
і да по Славутичу, він у Вас в Чернігівській області
## Expected result
- повернення id населеного пункту

**Comment by pzhuk** [comment]
@lymychp, це на додачу до задачі про чистку словника з населенними пунктами

**Comment by pzhuk** [comment]
@sreva , дякую за інфо - будемо виправляти

**Comment by AlekzandrV** [comment]
@sreva Закрываем тикет?
Есть связанный тикет где идет обсуждение структуры ответа и параметров фильтрации #27 

Что касается описанных тут проблем - они исправлены. За исключением кейса 3. Н.п. Підгородне находится в Межівський район

```
{
      "type": "VILLAGE",
      "settlement_name": "НОВОПІДГОРОДНЕ",
      "region": "ДНІПРОПЕТРОВСЬКА",
      "parent_settlement": "РАЙПОЛЕ",
      "mountain_group": "false",
      "koatuu": "1222687706",
      "id": "59df1f21-224e-433e-a320-8ce0b7414070",
      "district": "МЕЖІВСЬКИЙ"
    }
```
