### ISSUE TITLE
Змінити валідацію номеру будинку

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#190]
Потрібно змінити валідацію номеру будинку для адреси пацієнта в декларації. На даний момент приймається лише 3 цифри, але є номера будинків з 4 цифр, а також в номері будинку можуть бути присутні більше 1 буки. Наприклад валідні номера, які зараз не проходять:
1) 1020 корпус 2
2) 1515/82
3) 111  корп.15

**Comment by pzhuk** [comment]
Already on track 
https://github.com/edenlabllc/ehealth.api/issues/1580

**Comment by lymychp** [comment]
deployed to prod
