### ISSUE TITLE
500 при створенні МСП Пре-прод

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#192]
## Steps to Reproduce (Repro steps)

- [ ] api.ehealth.world/api/legal_entities
- [ ] request_data
[request_data.txt](https://github.com/ehealth-ua/api-spec/files/1534419/request_data.txt)

- [ ] signedRequestData
[signedRequestData.txt](https://github.com/ehealth-ua/api-spec/files/1534420/signedRequestData.txt)

## Actual result
- [ ] 
[відповідь.txt](https://github.com/ehealth-ua/api-spec/files/1534421/default.txt)

## Expected result
- [ ] точно не 500

**Comment by gmile** [comment]
@sreva Сергей, попробуйте, пожалуйста, еще раз. 500 должна пропасть.

**Comment by sreva** [comment]
дякую
