### ISSUE TITLE
403 при отриманні скоупів на Пре-прод

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#193]
- [ ] https://api.ehealth.world/
- [ ] ```curl -X GET \
  https://api.ehealth.world/admin/roles \
  -H 'api-key: d036273f779b1741dcf0' \
  -H 'authorization: Bearer f26454e8f3c0568a6258c3c125852d5d' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 389d3d92-bd16-625e-f7ca-ddedcbdddd2c'```

## Actual result
- [ ] ```{
    "meta": {
        "url": "https://api.ehealth.world:443/admin/roles",
        "type": "object",
        "request_id": "o1onn7ge3f8oc3jag64ge3mmvjij2k50",
        "code": 403
    },
    "error": {
        "type": "forbidden",
        "message": "Your scope does not allow to access this resource. Missing allowances: role:read"
    }
}```

## Expected result
- [ ] http 200

**Comment by sreva** [comment]
Аналогічну проблему сьогодні вже правили на проді

**Comment by lymychp** [comment]
fixed.
