### ISSUE TITLE
Не могу восстановить пароль пользователя на проде

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#194]
Для пользователя с почтой dmytropieskov@gmail.com не могу восстановить пароль.
Ссылки на изменение приходят. Меняю, но потом залогиниться все равно не могу.

**Comment by lymychp** [comment]
отримуєте помилку?

**Comment by pieskov** [comment]
нет. пишет что пароль изменен. но под новым паролем авторизация не проходит. Пишет "неверный логин или пароль"
