### ISSUE TITLE
Token expired message (prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#195]
Доброго дня, подивіться будь-ласка до  "request_id": "8hn3qk3j5l8k69plsmi6h2p5nh1tp48t", токен був отриманий 2017-12-05 15:16:48.250, зараз на verify повертає (Token expired or client approval was revoked.) і я не можу його оновити через refresh token, вертає (Token expired.)

## Actual result
- [ ] Token expired or client approval was revoked

## Expected result
- [ ] Token data

**Comment by pzhuk** [comment]
про який саме токен йде мова, уточніть-будь ласка? токен доктора?

**Comment by superjonh** [comment]
@pzhuk це токен керівника (owner)
