### ISSUE TITLE
Ошибка при вводе телефона на етапе геристрации юзера

### ISSUE THREAD

**Issue by Zillot** [ehealth-ua/api-spec#197]
## Steps to Reproduce (Repro steps)
стреда http://auth.demo.ehealth.world

1. заводим клинику (legal entity)
2. переходим по ссылке из почты
3. вводит пароль, еще раз пароль, нажимаем кнопку
4. нас просят ввести телефон, вводим, нажимаем кнопку
5. ошибка, респонс ниже (код из консоли)

## Actual result 
```
 {
    "meta": {
        "url": "http://demo.ehealth.world/oauth/users/actions/init_factor",
        "type": "object",
        "request_id": "260pe8ohh3marhc131ikh204ad2b45o9",
        "code": 404
    },
    "error": {
        "type": "not_found"
    }
} 
```

## Expected result
номер сохраняеться в систему, регистрация закончена

## Additional info
 после неудачной попытки, пекрешли по ссылке еще раз, номер телефона система не запрашивала, регистрация прошла успешно

**Comment by svetavedmed** [comment]
fixed on Demo.

**Comment by pzhuk** [comment]
@lymychp can you please chechule this fix in all environments (if needed) ?

BR, Pavel V. Zhuk


2017-12-11 14:32 GMT+02:00 svetavedmed <notifications@github.com>:

**Comment by lymychp** [comment]
it was caused by the env. config. Preprod/prod not affected.
