### ISSUE TITLE
Employee_request reject (prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#198]
Trying to reject employee_request with wrong edited email

##Token info

"id": "97d4e3cd-72cb-4cb1-9c61-01755ccdc0d4",
"request_id": "5h67b86hin61t36mgp71n56hgmp2kj5s"
"scope": "legal_entity:read employee_request:read employee_request:write employee_request:approve employee_request:reject employee:read employee:write employee:details employee:deactivate division:write division:read division:details division:activate division:deactivate declaration_request:write declaration_request:approve declaration_request:reject declaration_request:read declaration:read otp:read otp:write"

## Request

https://api.ehealth-ukraine.org/api/employee_requests/REQUEST_ID_HERE/reject

Headers:
    api-key MIS_KEY
    Authorization   Bearer TOKEN_HERE
    Content-Type application/json

##Response
"request_id":"gj3qnth1n4fhlj6uuadtmt41r3bv9bnv","code":403},"error":{"type":"forbidden"}

## Expected result
- Rejected request

**Comment by pzhuk** [comment]
@superjonh Функція reject не може бути виконана від користувача MIS. 
Це може зробити тільки користувач, за відповідним листом, який прийшов йому на пошту.
Поки що, для запрошень з невірним email не передбачено функції видалення, але можна дочекатись закінчення строку дії employee request

**Comment by superjonh** [comment]
@pzhuk Зрозуміло, не підкажете який його термін дії, це такий самий, як і у заявки декларації??  І чи буде доцільно давати у такому випадку посилання на підтвердження/скасування реєстрації користувачу який власне вводить дані по працівниках
