### ISSUE TITLE
Проблема с разбором подписанного ЭЦП контента. 

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#199]
При регистрации юр. лица
на проде выдает ошибку: Signed request data is invalid
а на препроде все ок.

Base64 строка:
MIIpvgYJKoZIhvcNAQcCoIIprzCCKasCAQExDjAMBgoqhiQCAQEBAQIBMIINYQYJKoZIhvcNAQcBoIINUgSCDU57Im5hbWUiOiJ0ZXN0Iiwic2hvcnRfbmFtZSI6InRlc3QiLCJwdWJsaWNfbmFtZSI6InRlc3QiLCJ0eXBlIjoiTVNQIiwib3duZXJfcHJvcGVydHlfdHlwZSI6IlNUQVRFIiwibGVnYWxfZm9ybSI6IjQyNSIsImVkcnBvdSI6IjIxNTYwMDQ1IiwiZW1haWwiOiJtYXJrbEB1a3IubmV0Iiwia3ZlZHMiOlsiMDEuMTUiXSwiYWRkcmVzc2VzIjpbeyJ0eXBlIjoiUkVHSVNUUkFUSU9OIiwiY291bnRyeSI6IlVBIiwiYXJlYSI6ItCcLtCa0JjQh9CSIiwic2V0dGxlbWVudCI6ItCa0JjQh9CSIiwic2V0dGxlbWVudF90eXBlIjoiQ0lUWSIsInNldHRsZW1lbnRfaWQiOiJhZGFhNGFiZi1mNTMwLTQ2MWMtYmNiZi1hMGFjMjEwZDk1NWIiLCJzdHJlZXRfdHlwZSI6IlNUUkVFVCIsInN0cmVldCI6InRlc3QiLCJidWlsZGluZyI6IjExIiwiemlwIjoiMDEwMDEifV0sInBob25lcyI6W3sidHlwZSI6Ik1PQklMRSIsIm51bWJlciI6IiszODAyMzU0MjEzNDUifV0sIm93bmVyIjp7ImZpcnN0X25hbWUiOiJ0ZXN0IiwibGFzdF9uYW1lIjoidGVzdCIsInNlY29uZF9uYW1lIjoidGVzdCIsInRheF9pZCI6IjMwMDEwMTc1NTAiLCJiaXJ0aF9kYXRlIjoiMTk4Mi0wMy0wMSIsImdlbmRlciI6Ik1BTEUiLCJlbWFpbCI6Im1hcmtsQHVrci5uZXQiLCJwb3NpdGlvbiI6IlA1IiwiZG9jdW1lbnRzIjpbeyJ0eXBlIjoiUEFTU1BPUlQiLCJudW1iZXIiOiJ2ZiAxMjM0NTYifV0sInBob25lcyI6W3sidHlwZSI6Ik1PQklMRSIsIm51bWJlciI6IiszODA0NTYzNDU2MzQifV19LCJtZWRpY2FsX3NlcnZpY2VfcHJvdmlkZXIiOnsibGljZW5zZXMiOlt7ImxpY2Vuc2VfbnVtYmVyIjoiMSIsImlzc3VlZF9ieSI6IjExMTEiLCJpc3N1ZWRfZGF0ZSI6IjIwMTctMTEtMjciLCJleHBpcnlfZGF0ZSI6IjIwMTctMTEtMjciLCJhY3RpdmVfZnJvbV9kYXRlIjoiMjAxNy0xMS0yNyIsIndoYXRfbGljZW5zZWQiOiJEY3ZTRCIsIm9yZGVyX25vIjoiMSJ9XSwiYWNjcmVkaXRhdGlvbiI6eyJjYXRlZ29yeSI6IlNFQ09ORCIsImlzc3VlZF9kYXRlIjoiMjAxNy0xMS0yNyIsImV4cGlyeV9kYXRlIjoiMjAxNy0xMi0yMCIsIm9yZGVyX25vIjoiMTEiLCJvcmRlcl9kYXRlIjoiMjAxNy0xMS0yNyJ9fSwic2VjdXJpdHkiOnsicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly8xOTIuMTY4LjEwMC41OCJ9LCJwdWJsaWNfb2ZmZXIiOnsiY29uc2VudCI6dHJ1ZSwiY29uc2VudF90ZXh0Ijoi0JLRltC00L/QvtCy0ZbQtNC90L4g0LTQviDQl9Cw0LrQvtC90YMg0KPQutGA0LDRl9C90LggXCLQn9GA0L4g0LfQsNGF0LjRgdGCINC/0LXRgNGB0L7QvdCw0LvRjNC90LjRhSDQtNCw0L3QuNGFXCIg0Lcg0LzQtdGC0L7RjiDQstC10LTQtdC90L3RjyDRgNC10ZTRgdGC0YDRltCyINC10LvQtdC60YLRgNC+0L3QvdC+0Zcg0YHQuNGB0YLQtdC80Lgg0L7RhdC+0YDQvtC90Lgg0LfQtNC+0YDQvtCyJ9GPINGC0LAg0LfQsNCx0LXQt9C/0LXRh9C10L3QvdGPINGX0Zcg0YTRg9C90LrRhtGW0L7QvdGD0LLQsNC90L3RjyDRgyDQtNC+0YHQu9GW0LTQvdGW0Lkg0LXQutGB0L/Qu9GD0LDRgtCw0YbRltGXINC90LDQtNCw0Y4g0LfQs9C+0LTRgyDQvtCx0YDQsNC90L7QvNGDINC+0L/QtdGA0LDRgtC+0YDRgyDRgtCwINCw0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGA0YMg0LXQu9C10LrRgtGA0L7QvdC90L7RlyDRgdC40YHRgtC10LzQuCDQvtGF0L7RgNC+0L3QuCDQt9C00L7RgNC+0LIn0Y8g0L3QsCDQvtCx0YDQvtCx0LrRgyDQvNC+0ZfRhSDQv9C10YDRgdC+0L3QsNC70YzQvdC40YUg0LTQsNC90LjRhSDQtyDQv9C10YDQstC40L3QvdC40YUg0LTQttC10YDQtdC7LCDQsCDRgtCw0LrQvtC2INC90LAg0LfQtNGW0LnRgdC90LXQvdC90Y8g0LTRltC5INC/0L7QsifRj9C30LDQvdC40YUg0LfRliDQt9Cx0LjRgNCw0L3QvdGP0LwsINGA0LXRlNGB0YLRgNCw0YbRltGU0Y4sINC90LDQutC+0L/QuNGH0LXQvdC90Y/QvCwg0LfQsdC10YDRltCz0LDQvdC90Y/QvCwg0LDQtNCw0L/RgtGD0LLQsNC90L3Rj9C8LCDQt9C80ZbQvdC+0Y4sINC/0L7QvdC+0LLQu9C10L3QvdGP0LwsINCy0LjQutC+0YDQuNGB0YLQsNC90L3Rj9C8LCDQv9C+0YjQuNGA0LXQvdC90Y/QvCwg0YDQvtC30L/QvtCy0YHRjtC00LbQtdC90L3Rj9C8LCDRgNC10LDQu9GW0LfQsNGG0ZbRlNGOLCDQv9C10YDQtdC00LDRh9C10Y4sINC30L3QtdC+0YHQvtCx0LvQtdC90L3Rj9C8LCDQt9C90LjRidC10L3QvdGP0Lwg0LHRg9C00Ywt0Y/QutC40YUg0LLRltC00L7QvNC+0YHRgtC10LkuINCU0L7QtNCw0YLQutC+0LLQviDQvdCw0LTQsNGOINC30LPQvtC00YMg0L3QsCDQtNC+0YHRgtGD0L8g0LTQviDQvNC+0ZfRhSDQv9C10YDRgdC+0L3QsNC70YzQvdC40YUg0LTQsNC90LjRhSDRg9C/0L7QstC90L7QstCw0LbQtdC90LjRhSDRgtGA0LXRgtGW0YUg0L7RgdGW0LEsINGJ0L4g0LLQuNC30L3QsNGH0LDRlCDQtNGW0Zcg0L7Qv9C10YDQsNGC0L7RgNCwINCc0IbQoSDRgtCwINCw0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGA0LAg0YMg0YDQsNC30ZYg0L7RgtGA0LjQvNCw0L3QvdGPINC30LDQv9C40YLRgyDQstGW0LQg0YPQv9C+0LLQvdC+0LLQsNC20LXQvdC+0Zcg0YLRgNC10YLRjNC+0Zcg0L7RgdC+0LHQuCDRidC+0LTQviDQvdCw0LTQsNC90L3RjyDQtNC+0YHRgtGD0L/RgyDQtNC+INC/0LXRgNGB0L7QvdCw0LvRjNC90LjRhSDQtNCw0L3QuNGFLiDQn9GW0LTRgtCy0LXRgNC00LbRg9GOINC00L7RgdGC0L7QstGW0YDQvdGW0YHRgtGMINCy0LrQsNC30LDQvdC40YUg0LzQvdC+0Y4g0LTQsNC90LjRhSDRgtCwINC00L7QsdGA0L7QstGW0LvRjNC90ZbRgdGC0Ywg0L3QsNC00LDQvdC90Y8g0YbQuNGFINC00LDQvdC40YUg0LTQviDQtdC70LXQutGC0YDQvtC90L3QvtGXINGB0LjRgdGC0LXQvNC4INC+0YXQvtGA0L7QvdC4INC30LTQvtGA0L7QsifRjywg0YnQviDQv9GA0LDRhtGO0ZQg0YMg0LTQvtGB0LvRltC00L3RltC5INC10LrRgdC/0LvRg9Cw0YLQsNGG0ZbRly4g0KPRgdCy0ZbQtNC+0LzQu9GO0Y4sINGJ0L4g0YMg0LLQuNC/0LDQtNC60YMg0L3QsNC00LDQvdC90Y8g0LzQvdC+0Y4g0L3QtdCy0ZbRgNC90L7RlyDRltC90YTQvtGA0LzQsNGG0ZbRlywg0LzQtdC90ZYg0LzQvtC20LUg0LHRg9GC0Lgg0LLRltC00LzQvtCy0LvQtdC90L4g0LIg0YDQtdGU0YHRgtGA0LDRhtGW0Zcg0LIg0LXQu9C10LrRgtGA0L7QvdC90ZbQuSDRgdC40YHRgtC10LzRliDQvtGF0L7RgNC+0L3QuCDQt9C00L7RgNC+0LIn0Y8uINCX0L7QsdC+0LIn0Y/Qt9GD0Y7RgdGMINC00L7RgtGA0LjQvNGD0LLQsNGC0LjRgdGMINCg0LXQs9C70LDQvNC10L3RgtGDINGE0YPQvdC60YbRltC+0L3Rg9Cy0LDQvdC90Y8g0LXQu9C10LrRgtGA0L7QvdC90L7RlyDRgdC40YHRgtC10LzQuCDQvtGF0L7RgNC+0L3QuCDQt9C00L7RgNC+0LIn0Y8uIn19oIIH9TCCB/EwggeZoAMCAQICFDO2y3v3IbnOBAAAACgPJAD6NFUAMA0GCyqGJAIBAQEBAwEBMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjAeFw0xNzAzMTQyMjAwMDBaFw0xOTAzMTQyMjAwMDBaMIIBsjFWMFQGA1UECgxN0J/Rg9Cx0LvRltGH0L3QtSDQsNC60YbRltC+0L3QtdGA0L3QtSDRgtC+0LLQsNGA0LjRgdGC0LLQviAi0KPQutGA0L/QvtGI0YLQsCIxdjB0BgNVBAsMbdCj0L/RgNCw0LLQu9GW0L3QvdGPINGA0L7Qt9Cy0LjRgtC60YMg0LHQsNC3INC00LDQvdC40YUg0YLQsCDRltC90YLQtdCz0YDQsNGG0ZbRlyDQv9GA0L7Qs9GA0LDQvC4g0LfQsNCx0LXQty4xTTBLBgNVBAwMRNCd0LDRh9Cw0LvRjNC90LjQuiDQstGW0LTQtNGW0LvRgyDRgNC+0LfQstC40YLQutGDINCx0LDQtyDQtNCw0L3QuNGFMR4wHAYDVQQDDBXQm9C+0LHQsNC90L7QsiDQnC7Qki4xFzAVBgNVBAQMDtCb0L7QsdCw0L3QvtCyMSYwJAYDVQQqDB3QnNCw0YDQuiDQktGW0LrRgtC+0YDQvtCy0LjRhzEQMA4GA1UEBQwHMjM2MzE3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyMIHyMIHJBgsqhiQCAQEBAQMBATCBuTB1MAcCAgEBAgEMAgEABCEQvuPbauqeH4ZXjEXBJZT/lCOUp9c4+Rh+ZRUBcpT0zgECIQCAAAAAAAAAAAAAAAAAAAAAZ1khOvGC6YfT4XcUkH1HDQQhtg/S2NzoqTQjxhAbypHEegB+bDALJs1VbJsOfSDvKSoABECp1utF8TxwgoDElnsjH16t9ljrpMA3KR042WvwJcpOF/jpcg3GFbQ6KJdfC8Heo2Q4tWTqLBef0BI+bbj6xXkEAyQABCFOUxdNwfKXyamGh300HPm4VjbsFllnp69ZUEPNQQesHQGjggNMMIIDSDApBgNVHQ4EIgQg/VYUrHouw1USeQ9hkxzFSz2KZ6iXODjkmkoD6n9xMK0wKwYDVR0jBCQwIoAgM7bLe/chuc7u494uYv7qO3AaS2dgvBwvzzVlFrUOvKowLwYDVR0QBCgwJqARGA8yMDE3MDMxNDIyMDAwMFqhERgPMjAxOTAzMTQyMjAwMDBaMA4GA1UdDwEB/wQEAwIGwDAZBgNVHSABAf8EDzANMAsGCSqGJAIBAQECAjAMBgNVHRMBAf8EAjAAMDcGCCsGAQUFBwEDAQH/BCgwJjALBgkqhiQCAQEBAgEwFwYGBACORgECMA0TA1VBSAIDD0JAAgEAMIGkBgNVHREEgZwwgZmgQwYMKwYBBAGBl0YBAQQCoDMMMTAxMDAxLCDQvC4g0JrQuNGX0LIsINCy0YPQuy4g0KXRgNC10YnQsNGC0LjQuiwgMjKgJgYMKwYBBAGBl0YBAQQBoBYMFCszOCAoMCA0NCkgMjc4LTc5LTY5gRVvZmZpY2VsQHVrcnBvc2h0YS5jb22gEwYKKwYBBAGCNxQCA6AFDAMzNjEwSAYDVR0fBEEwPzA9oDugOYY3aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NybHMvQUNTS0lERERGUy1GdWxsLmNybDBJBgNVHS4EQjBAMD6gPKA6hjhodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxvYWQvY3Jscy9BQ1NLSUREREZTLURlbHRhLmNybDCBiAYIKwYBBQUHAQEEfDB6MDAGCCsGAQUFBzABhiRodHRwOi8vYWNza2lkZC5nb3YudWEvc2VydmljZXMvb2NzcC8wRgYIKwYBBQUHMAKGOmh0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jZXJ0aWZpY2F0ZXMvYWxsYWNza2lkZC5wN2IwPwYIKwYBBQUHAQsEMzAxMC8GCCsGAQUFBzADhiNodHRwOi8vYWNza2lkZC5nb3YudWEvc2VydmljZXMvdHNwLzBDBgNVHQkEPDA6MBoGDCqGJAIBAQELAQQCATEKEwgyMTU2MDA0NTAcBgwqhiQCAQEBCwEEAQExDBMKMjU3MDYxNzE5OTANBgsqhiQCAQEBAQMBAQNDAARAW2MlhIwwvUeArukBr4aluBmN5ctujOzyWHqrN5hJJXleDtWM/6tALgnLy2fDabZn2Ckg0HuJBY5QfRiVBe2PBjGCFDYwghQyAgEBoCIEIP1WFKx6LsNVEnkPYZMcxUs9imeolzg45JpKA+p/cTCtMAwGCiqGJAIBAQEBAgGgggrqMC8GCSqGSIb3DQEJBDEiBCC1JjQ3R4K+4ZrWol7KBDuHVixf/ZR8qP+xehsFO0dhkTAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMIIBwwYLKoZIhvcNAQkQAi8xggGyMIIBrjCCAaowggGmMAwGCiqGJAIBAQEBAgEEIMKYojg5e6xOx6fM9alzEbMn7MB0fa3SrAztzcGajm4JMIIBcjCCAVikggFUMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUM7bLe/chuc4EAAAAKA8kAPo0VQAwHAYJKoZIhvcNAQkFMQ8XDTE3MTIwODA5NTYzNFowggi2BgsqhkiG9w0BCRACFDGCCKUwggihBgkqhkiG9w0BBwKgggiSMIIIjgIBAzEOMAwGCiqGJAIBAQEBAgEwaQYLKoZIhvcNAQkQAQSgWgRYMFYCAQEGCCsGAQUFBwMIMDAwDAYKKoYkAgEBAQECAQQgtSY0N0eCvuGa1qJeygQ7h1YsX/2UfKj/sXobBTtHYZECBA6dnCsYDzIwMTcxMjA4MDk1NjM0WqCCBb4wggW6MIIFNqADAgECAhQ9tz578NV1sgIAAAABAAAAhAAAADANBgsqhiQCAQEBAQMBATCB+jE/MD0GA1UECgw20JzRltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDE3MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIwHhcNMTcxMTAxMTQ0OTAwWhcNMjIxMTAxMTQ0OTAwWjCCAS0xbDBqBgNVBAMMY1RTUC3RgdC10YDQstC10YAg0JDQptCh0Jog0KLQntCSICLQptC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgItCj0LrRgNCw0ZfQvdCwIjERMA8GA1UEBwwI0JrQuNGX0LIxGTAXBgNVBAUMEFVBLTM2ODY1NzUzLTAyMTcxUjBQBgNVBAoMSdCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxLjAsBgNVBAsMJdCS0ZbQtNC00ZbQuyDRgdC10YDRgtC40YTRltC60LDRhtGW0ZcxCzAJBgNVBAYMAlVBMIHyMIHJBgsqhiQCAQEBAQMBATCBuTB1MAcCAgEBAgEMAgEABCEQvuPbauqeH4ZXjEXBJZT/lCOUp9c4+Rh+ZRUBcpT0zgECIQCAAAAAAAAAAAAAAAAAAAAAZ1khOvGC6YfT4XcUkH1HDQQhtg/S2NzoqTQjxhAbypHEegB+bDALJs1VbJsOfSDvKSoABECp1utF8TxwgoDElnsjH16t9ljrpMA3KR042WvwJcpOF/jpcg3GFbQ6KJdfC8Heo2Q4tWTqLBef0BI+bbj6xXkEAyQABCEisZjKJWQ34C1VM43U+oIC49FbE7JwJN/J+ZvfWAlZ2QCjggHFMIIBwTAOBgNVHQ8BAf8EBAMCBsAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwGQYDVR0gAQH/BA8wDTALBgkqhiQCAQEBAgIwHgYIKwYBBQUHAQMBAf8EDzANMAsGCSqGJAIBAQECATApBgNVHQ4EIgQgZuzrjmRV2EI5y9+1euE4/pc33APvaufXCYEsCCF6Jc0wLwYDVR0QBCgwJqARGA8yMDE3MTEwMTE0NDkwMFqhERgPMjAyMjExMDExNDQ5MDBaMCsGA1UdIwQkMCKAIL23Pnvw1XWySAJ4PZ4FqVCXdsF196yBdnQIB5Z6NCAUMAwGA1UdEwEB/wQCMAAwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2N6by5nb3YudWEvZG93bmxvYWQvY3Jscy9DWk8tMjAxNy1GdWxsLmNybDBDBgNVHS4EPDA6MDigNqA0hjJodHRwOi8vY3pvLmdvdi51YS9kb3dubG9hZC9jcmxzL0NaTy0yMDE3LURlbHRhLmNybDA8BggrBgEFBQcBAQQwMC4wLAYIKwYBBQUHMAGGIGh0dHA6Ly9jem8uZ292LnVhL3NlcnZpY2VzL29jc3AvMA0GCyqGJAIBAQEBAwEBA28ABGwz9UUWMeS9ZvwZqEIzzbDeN6iFJlSXpWoNwv3nPQADdUhqRmJzGT64FFIlypIps4p+4OzhKQgrgeYQqPwQnCv3P7gvsL8hC3dAxhHp9eYAcyDhbQ/pbJX5mOxW36+Q7Am2LTIeYF8rWsT5RwgxggJKMIICRgIBAaAiBCBm7OuOZFXYQjnL37V64Tj+lzfcA+9q59cJgSwIIXolzTAMBgoqhiQCAQEBAQIBoIIBvDAvBgkqhkiG9w0BCQQxIgQgEDTGj33nwaDaCEb9nFQW1/7fbV5U4nRVT9X8BdRxGykwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMIIBawYLKoZIhvcNAQkQAi8xggFaMIIBVjCCAVIwggFOMAwGCiqGJAIBAQEBAgEEIMqQQwm7phbbjDbygs/lE678giqfaLJ0IqAGqUFCl/LKMIIBGjCCAQCkgf0wgfoxPzA9BgNVBAoMNtCc0ZbQvdGW0YHRgtC10YDRgdGC0LLQviDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotChINCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQstGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEtMDAwMTU2MjItMjAxNzELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQ9tz578NV1sgIAAAABAAAAhAAAADANBgsqhiQCAQEBAQMBAQRAKAGdyBJ3U23HVQWvefafji/0mVrL+poTI+sETREkVRFa344rBJOdDO1NNRBGv8vNNaGuwRJcyiif16soF0mbDjANBgsqhiQCAQEBAQMBAQRAbim/sfRut9cpCaUxDRaGvzvsKkHRSoh0WsiNifGjcxGRcEhi/er7qvdTIPRLdwVowsTEhmCpHk7b4oDDClXsTaGCCLowggi2BgsqhkiG9w0BCRACDjGCCKUwggihBgkqhkiG9w0BBwKgggiSMIIIjgIBAzEOMAwGCiqGJAIBAQEBAgEwaQYLKoZIhvcNAQkQAQSgWgRYMFYCAQEGCCsGAQUFBwMIMDAwDAYKKoYkAgEBAQECAQQgcippm9uWjb1izuqAGikBnegeTrUVj5IxrFTfWRnVEPQCBA+dnCsYDzIwMTcxMjA4MDk1NjM0WqCCBb4wggW6MIIFNqADAgECAhQ9tz578NV1sgIAAAABAAAAhAAAADANBgsqhiQCAQEBAQMBATCB+jE/MD0GA1UECgw20JzRltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDE3MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIwHhcNMTcxMTAxMTQ0OTAwWhcNMjIxMTAxMTQ0OTAwWjCCAS0xbDBqBgNVBAMMY1RTUC3RgdC10YDQstC10YAg0JDQptCh0Jog0KLQntCSICLQptC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgItCj0LrRgNCw0ZfQvdCwIjERMA8GA1UEBwwI0JrQuNGX0LIxGTAXBgNVBAUMEFVBLTM2ODY1NzUzLTAyMTcxUjBQBgNVBAoMSdCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxLjAsBgNVBAsMJdCS0ZbQtNC00ZbQuyDRgdC10YDRgtC40YTRltC60LDRhtGW0ZcxCzAJBgNVBAYMAlVBMIHyMIHJBgsqhiQCAQEBAQMBATCBuTB1MAcCAgEBAgEMAgEABCEQvuPbauqeH4ZXjEXBJZT/lCOUp9c4+Rh+ZRUBcpT0zgECIQCAAAAAAAAAAAAAAAAAAAAAZ1khOvGC6YfT4XcUkH1HDQQhtg/S2NzoqTQjxhAbypHEegB+bDALJs1VbJsOfSDvKSoABECp1utF8TxwgoDElnsjH16t9ljrpMA3KR042WvwJcpOF/jpcg3GFbQ6KJdfC8Heo2Q4tWTqLBef0BI+bbj6xXkEAyQABCEisZjKJWQ34C1VM43U+oIC49FbE7JwJN/J+ZvfWAlZ2QCjggHFMIIBwTAOBgNVHQ8BAf8EBAMCBsAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgwGQYDVR0gAQH/BA8wDTALBgkqhiQCAQEBAgIwHgYIKwYBBQUHAQMBAf8EDzANMAsGCSqGJAIBAQECATApBgNVHQ4EIgQgZuzrjmRV2EI5y9+1euE4/pc33APvaufXCYEsCCF6Jc0wLwYDVR0QBCgwJqARGA8yMDE3MTEwMTE0NDkwMFqhERgPMjAyMjExMDExNDQ5MDBaMCsGA1UdIwQkMCKAIL23Pnvw1XWySAJ4PZ4FqVCXdsF196yBdnQIB5Z6NCAUMAwGA1UdEwEB/wQCMAAwQgYDVR0fBDswOTA3oDWgM4YxaHR0cDovL2N6by5nb3YudWEvZG93bmxvYWQvY3Jscy9DWk8tMjAxNy1GdWxsLmNybDBDBgNVHS4EPDA6MDigNqA0hjJodHRwOi8vY3pvLmdvdi51YS9kb3dubG9hZC9jcmxzL0NaTy0yMDE3LURlbHRhLmNybDA8BggrBgEFBQcBAQQwMC4wLAYIKwYBBQUHMAGGIGh0dHA6Ly9jem8uZ292LnVhL3NlcnZpY2VzL29jc3AvMA0GCyqGJAIBAQEBAwEBA28ABGwz9UUWMeS9ZvwZqEIzzbDeN6iFJlSXpWoNwv3nPQADdUhqRmJzGT64FFIlypIps4p+4OzhKQgrgeYQqPwQnCv3P7gvsL8hC3dAxhHp9eYAcyDhbQ/pbJX5mOxW36+Q7Am2LTIeYF8rWsT5RwgxggJKMIICRgIBAaAiBCBm7OuOZFXYQjnL37V64Tj+lzfcA+9q59cJgSwIIXolzTAMBgoqhiQCAQEBAQIBoIIBvDAvBgkqhkiG9w0BCQQxIgQgTk9q8OwbxO3azDqcYhRigFBtYwbo5/w/fUhoy8dsVJwwGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMIIBawYLKoZIhvcNAQkQAi8xggFaMIIBVjCCAVIwggFOMAwGCiqGJAIBAQEBAgEEIMqQQwm7phbbjDbygs/lE678giqfaLJ0IqAGqUFCl/LKMIIBGjCCAQCkgf0wgfoxPzA9BgNVBAoMNtCc0ZbQvdGW0YHRgtC10YDRgdGC0LLQviDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotChINCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQstGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEtMDAwMTU2MjItMjAxNzELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQ9tz578NV1sgIAAAABAAAAhAAAADANBgsqhiQCAQEBAQMBAQRAZbXKHfE10v7KVXZgr/PGlcZ3KvnUH0eQKWlF/MfgdSOVG69CiU+oyikP1d+eHKZo630WyMNtuMe8M2Bg3UNfUg==

**Comment by pzhuk** [comment]
Tested: in dev- digital_signature verificaion works
In demo - fails to verify

```
        "message": "Signed request data is invalid",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "json"
                    }
                ],
                "entry_type": "request"
            }
        ]

```

[Test.txt](https://github.com/ehealth-ua/api-spec/files/1555167/Test.txt)

**Comment by pzhuk** [comment]
@svetavedmed could you please help to verify it? Seems like digital signature is ok, but still registration fails

**Comment by svetavedmed** [comment]
fixed on demo

**Comment by pzhuk** [comment]
@pieskov should be finally fixed on demo, pls retest?
