### ISSUE TITLE
Прохання додати end point

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#20]
Суть end point: Ми вам на вхід подаємо json підписаний ЕЦП в base64 (в base64 лише тому, що решта end point які приймають зашифрований контент приймають саме так), а на виході від вас ми отримуємо true / false. 
true - якщо можете зняти ЕЦП, тобто дане ЕЦП підтримується вашим сервісом;
false - якщо НЕ можете зняти ЕЦП, тобто дане ЕЦП НЕ підтримується вашим сервісом;

**Comment by pieskov** [comment]
put на http://demo.ehealth.world/api/legal_entities і отримуєте повідомлення типу "Sign is invalid"

**Comment by sreva** [comment]
@pieskov я вірно розумію, що у випадку якщо ЕЦП не підтримується Вашим сервісом відповідь буде "Sign is invalid", а у іншому помилка буде іншою, вірно?

**Comment by pieskov** [comment]
Я не розробник ehealth, але перевіряю ЕЦП саме так.

**Comment by warehousman** [comment]
@pzhuk Если необходим публичный эндпоинт для проверки подписи прошу зарегестрировать CR
