### ISSUE TITLE
Creating declaration_request(prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#200]
Trying to create declaration, using doctor employee_id in request, token is valid ("scope": "legal_entity:read employee_request:approve employee_request:reject employee:read division:read declaration_request:write declaration_request:sign declaration_request:approve declaration_request:read declaration:read otp:read otp:write")

Doctor has already signed one declaration, now there are such response

## Actual result

```json
{
  "meta": {
    "url": "http://api.ehealth-ukraine.org/api/declaration_requests",
    "type": "object",
    "request_id": "ju343r7tp7hmdfn3hp06hnmme9t312s2",
    "code": 500
  },
  "error": {
    "errors": {
      "detail": "Internal server error"
    }
  }
}
```

## Expected result
- [ ] response 200

**Comment by gmile** [comment]
@superjonh please try again, it should work now.

**Comment by superjonh** [comment]
@gmile Thanks, works
