### ISSUE TITLE
Ошибка при подписании декларации

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#201]
подпись декларации возвращает вот такое

"{"meta"=>{"url"=>"http://api.ehealth.world/api/declaration_requests/1183a3b1-6606-4540-970f-88043f48a798/actions/sign", "type"=>"object", "request_id"=>"jmm12dmv39fkqrneio5n827bfbv8f7um", "code"=>500}, "error"=>{"errors"=>{"detail"=>"Internal server error"}}}"
как понять что не так?

**Comment by pzhuk** [comment]
@svetavedmed could you please check it? why is it 500?

**Comment by svetavedmed** [comment]
Should be fixed now. Could you, please, check it?

**Comment by pzhuk** [comment]
closing since no respose
