### ISSUE TITLE
Ошибка верификации телефона на демо

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#202]
Врачу на мыло приходит приглашение он переходит по нему, задает пароль, просят телефон. Задает телефон. Следующий шаг - просят ввести номер из СМС... 
СМС на номер не приходит.

**Comment by pzhuk** [comment]
Пожалуйста, дайте все детали - какой линк, как пользователь, какой телефон,
скриншоты и логи по возможности

BR, Pavel V. Zhuk


2017-12-14 13:37 GMT+02:00 Charly3X <notifications@github.com>:

**Comment by Charly3X** [comment]
Ссылка из приглашения
http://auth.demo.ehealth.world/invite?invite=51e64b25-393b-4b6c-aca2-7a0b5f2cc41a

**Comment by Charly3X** [comment]
вводится номер телефон и смс не приходит

**Comment by pzhuk** [comment]
Пожалуйста, дайте все детали - какой линк, как пользователь, какой телефон,
скриншоты и логи по возможности

**Comment by Charly3X** [comment]
Линк... http://auth.demo.ehealth.world/invite?invite=51e64b25-393b-4b6c-aca2-7a0b5f2cc41a
Задаем пароль
Просит телефон..
Указываем +380996631175
Ждем СМС долго

**Comment by Charly3X** [comment]
какие логи надо?

**Comment by pzhuk** [comment]
@svetavedmed  I could reproduce it

Log on 2fac request:

`{"urgent":{"next_step":"APPROVE_FACTOR"},"meta":{"url":"http://demo.ehealth.world/oauth/users/actions/init_factor","type":"object","request_id":"mnbja18d4dbavremh53iglmipd4cv06c","code":201},"data":{"value":"c0RiODYxSCtWSUllOVFtNXlhZ1YwQT09","user_id":"ee4d17f4-2ef7-4340-baff-1b09ee2f1afa","name":"2fa_access_token","id":"f1c8ba3c-bee5-4c05-9d5a-93586583867b","expires_at":1515933110}}`


user: yermolenko.l.p@gmail.com
phone: +380996631175

SMS is not even being sent - can't see anything neither in sms_logs table, nor in verifications 
However, mithril otp seems to have a new record

**Comment by svetavedmed** [comment]
At the moment sms are not send on Demo. If you need them for testing, we can switch them on.

**Comment by pzhuk** [comment]
let's just disable 2fac authentication, because any new user is getting enrolled into 2fac, and can't receive sms @svetavedmed

**Comment by svetavedmed** [comment]
Done, only for users which already have registered with 2fa and have authentication_factors.is_active=true it will be checked, so that you need to switch it off in DB.

**Comment by pzhuk** [comment]
@svetavedmed  thanks a lot!

@Charly3X please try now. password for user mentioned in this task has been changed  to 123123123
