### ISSUE TITLE
Incorrect broker settings (pre-prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#204]
Що може бути коли вертає (Incorrect broker settings.), при запиті , і також коли пробую перевірити токен

## Actual result
- [ ] {
   "meta": {
       "url": "http://api.ehealth.world/admin/tokens/VlRydmd0NjAzRzhtbWRpQjhsMW5PUT09/verify",
       "type": "object",
       "request_id": "v16npna7ctpi4iue0f8qsc83ssui9rll",
       "code": 422
   },
   "error": {
       "type": "request_malformed",
       "message": "Incorrect broker settings.",
       "invalid": [
           {
               "rules": [
                   {
                       "rule": "json"
                   }
               ],
               "entry_type": "request"
           }
       ]
   }
}

## Expected result
- [ ] token info

**Comment by pzhuk** [comment]
Який токен ви використовуєте при надсиланні запиту?

**Comment by superjonh** [comment]
@pzhuk legal_entity secret in api-key header

**Comment by superjonh** [comment]
And in other requests (Authorization: Bearer VlRydmd0NjAzRzhtbWRpQjhsMW5PUT09)

**Comment by pzhuk** [comment]
заголовок api-key має завжди містити секрет рівня MIS. у вашому випадку - ви пробуєте передати секрет рівня MSP

**Comment by superjonh** [comment]
Зрозуміло, не міг найти вірний API-KEY демо і пре проду

**Comment by pzhuk** [comment]
@superjonh використовуйте client_secret з тестових даних
https://docs.google.com/document/d/1pi40OZQ3ajKHmXHFHApoJiVRLLgx4iJVl8bNi93qzW8/edit?usp=sharing

**Comment by superjonh** [comment]
@pzhuk Так дякую, вже найшов
