### ISSUE TITLE
Declaration sign (DEMO)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#205]
Раніше підписував ключами від Приват працювало, зараз такий респонс

## Steps to Reproduce (Repro steps)

токен має права на declaration_request:sign

## Actual result
- [ ] Error:

```<error><code>BadRequest</code><description>BadRequest</description><body>{
  "meta": {
    "url": "http://demo.ehealth.world/api/declaration_requests/ad3070f5-fcef-4e8d-a77d-b535f3271fc9/actions/sign",
    "type": "object",
    "request_id": "nd8018qqvh29au2o9b2gdoohioals39f",
    "code": 400
  },
  "error": {
    "type": "request_malformed",
    "message": "Signed request data is invalid",
    "invalid": [
      {
        "rules": [
          {
            "rule": "json"
          }
        ],
        "entry_type": "request"
      }
    ]
  }
}</body></error>
```

## Expected result
- [ ] signed declaration

## Signed content  
[fileToSign_.zip](https://github.com/ehealth-ua/api-spec/files/1568874/fileToSign_.zip)

**Comment by pzhuk** [comment]
схоже на ту саму проблему - декларація підписана Приват
