### ISSUE TITLE
Не можна змінити пароль користувача на препроді

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#206]
Зміна пароля на препроді не працює.

**Comment by lymychp** [comment]
прошу надати інформацію по тікету згідно шаблону

**Comment by pieskov** [comment]
Что предоставить?
1. Захожу по ссылке https://auth.ehealth.world/sign-in/
2. Нажимаю "Забкли пароль?" и ввожу почту.
3. Перехожу по ссылке и меняю пароль.
4. Авторизироваться по новому паролю не могу.

**Comment by lymychp** [comment]
яку помилку отримуєте при авторизації, на якому етапі?

ЗІ: щойно змінив пароль і успішно залогінився на препроді

**Comment by pieskov** [comment]
401 - User blocked. dmytropieskov@gmail.com

**Comment by pzhuk** [comment]
unblocked
