### ISSUE TITLE
Ошибка подписания декларации приватовским ключем на предпроде

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#207]
Весь лог приложил в файле

https://drive.google.com/file/d/17TkUl4emZDxEDf1Kwvd8PcKpJZGzjLLl/view?usp=sharing

**Comment by pzhuk** [comment]
@svetavedmed we need a help here

Env: preprod

Tested on /digital_signatures on dev - seems signature is properly validated

**Comment by superjonh** [comment]
"error":{"type":"request_malformed","message":"Signed request data is invalid","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}

**Comment by svetavedmed** [comment]
tested in dev, error with OCSP certificate. The same error with #205

**Comment by Charly3X** [comment]
Are you trying to fix it or what should we do?

**Comment by lymychp** [comment]
There is sn issue with the cert server of privat . Ehealth cannot verify the validity of the signer certificate. Have contacted the support service of privat to solve this issue.

**Comment by lymychp** [comment]
fixed and deployed to prod
