### ISSUE TITLE
Ошибка 500 при регистрации мед. учреждения

### ISSUE THREAD

**Issue by dorado2012** [ehealth-ua/api-spec#208]
Добрый день!

подписал данный пример запроса с помощью ЭЦП:
```json
{
  "name": "Клініка Адоніс21",
  "short_name": "Адоніс21",
  "public_name": "Адоніс21",
  "type": "MSP",
  "owner_property_type": "STATE",
  "legal_form": "140",
  "edrpou": "2870213998",
  "kveds": [
    "86.10"
  ],
  "addresses": [
    {
      "type": "REGISTRATION",
      "country": "UA",
      "area": "Волинська область",
      "region": "Бердичівський",
      "settlement": "Київ",
      "settlement_type": "CITY",
      "settlement_id": "43432432",
      "street_type": "STREET",
      "street": "вул. Ніжинська",
      "building": "15",
      "apartment": "23",
      "zip": "02090"
    }
  ],
  "phones": [
    {
      "type": "MOBILE",
      "number": "+380503410870"
    }
  ],
  "email": "sp.virny+100@gmail.com",
  "owner": {
    "first_name": "Петро",
    "last_name": "Іванов",
    "second_name": "Миколайович",
    "tax_id": "3015492565",
    "birth_date": "1985-06-16",
    "birth_place": "Вінниця, Україна",
    "gender": "FEMALE",
    "email": "sp.virny+100@gmail.com",
    "documents": [
      {
        "type": "PASSPORT",
        "number": "120518"
      }
    ],
    "phones": [
      {
        "type": "MOBILE",
        "number": "+380503410870"
      }
    ],
    "position": "P1"
  },
  "medical_service_provider": {
    "licenses": [
      {
        "license_number": "fd123443",
        "issued_by": "Кваліфікацйна комісія",
        "issued_date": "1991-08-19",
        "expiry_date": "1991-08-19",
        "active_from_date": "1991-08-19",
        "what_licensed": "реалізація наркотичних засобів",
        "order_no": "K-123"
      }
    ],
    "accreditation": {
      "category": "FIRST",
      "issued_date": "1991-08-19",
      "expiry_date": "1991-08-19",
      "order_no": "fd123443",
      "order_date": "1991-08-19"
    }
  },
  "security": {
    "redirect_uri": "http://example2.com"
  },
  "public_offer": {
    "consent": true,
    "consent_text": "Consent text"
  }
}
```

получилось:
MIIOfwYJKoZIhvcNAQcCoIIOcDCCDmwCAQExDjAMBgoqhiQCAQEBAQIBMIIHjQYJKoZIhvcNAQcBoIIHfgSCB3p7CiAgIm5hbWUiOiAiyuuz7bPq4CDA5O7ts/EyMSIsCiAgInNob3J0X25hbWUiOiAiwOTu7bPxMjEiLAogICJwdWJsaWNfbmFtZSI6ICLA5O7ts/EyMSIsCiAgInR5cGUiOiAiTVNQIiwKICAib3duZXJfcHJvcGVydHlfdHlwZSI6ICJTVEFURSIsCiAgImxlZ2FsX2Zvcm0iOiAiMTQwIiwKICAiZWRycG91IjogIjI4NzAyMTM5OTgiLAogICJrdmVkcyI6IFsKICAgICI4Ni4xMCIKICBdLAogICJhZGRyZXNzZXMiOiBbCiAgICB7CiAgICAgICJ0eXBlIjogIlJFR0lTVFJBVElPTiIsCiAgICAgICJjb3VudHJ5IjogIlVBIiwKICAgICAgImFyZWEiOiAiwu7r6O3x/OrgIO7h6+Dx8vwiLAogICAgICAicmVnaW9uIjogIsHl8OTo97Pi8fzq6OkiLAogICAgICAic2V0dGxlbWVudCI6ICLK6L/iIiwKICAgICAgInNldHRsZW1lbnRfdHlwZSI6ICJDSVRZIiwKICAgICAgInNldHRsZW1lbnRfaWQiOiAiNDM0MzI0MzIiLAogICAgICAic3RyZWV0X3R5cGUiOiAiU1RSRUVUIiwKICAgICAgInN0cmVldCI6ICLi8+suIM2z5ujt8fzq4CIsCiAgICAgICJidWlsZGluZyI6ICIxNSIsCiAgICAgICJhcGFydG1lbnQiOiAiMjMiLAogICAgICAiemlwIjogIjAyMDkwIgogICAgfQogIF0sCiAgInBob25lcyI6IFsKICAgIHsKICAgICAgInR5cGUiOiAiTU9CSUxFIiwKICAgICAgIm51bWJlciI6ICIrMzgwNTAzNDEwODcwIgogICAgfQogIF0sCiAgImVtYWlsIjogInNwLnZpcm55KzEwMEBnbWFpbC5jb20iLAogICJvd25lciI6IHsKICAgICJmaXJzdF9uYW1lIjogIs/l8vDuIiwKICAgICJsYXN0X25hbWUiOiAisuLg7e7iIiwKICAgICJzZWNvbmRfbmFtZSI6ICLM6Oru6+Dp7uLo9yIsCiAgICAidGF4X2lkIjogIjMwMTU0OTI1NjUiLAogICAgImJpcnRoX2RhdGUiOiAiMTk4NS0wNi0xNiIsCiAgICAiYmlydGhfcGxhY2UiOiAiwrPt7ej2/ywg0+rw4L/t4CIsCiAgICAiZ2VuZGVyIjogIkZFTUFMRSIsCiAgICAiZW1haWwiOiAic3AudmlybnkrMTAwQGdtYWlsLmNvbSIsCiAgICAiZG9jdW1lbnRzIjogWwogICAgICB7CiAgICAgICAgInR5cGUiOiAiUEFTU1BPUlQiLAogICAgICAgICJudW1iZXIiOiAiMTIwNTE4IgogICAgICB9CiAgICBdLAogICAgInBob25lcyI6IFsKICAgICAgewogICAgICAgICJ0eXBlIjogIk1PQklMRSIsCiAgICAgICAgIm51bWJlciI6ICIrMzgwNTAzNDEwODcwIgogICAgICB9CiAgICBdLAogICAgInBvc2l0aW9uIjogIlAxIgogIH0sCiAgIm1lZGljYWxfc2VydmljZV9wcm92aWRlciI6IHsKICAgICJsaWNlbnNlcyI6IFsKICAgICAgewogICAgICAgICJsaWNlbnNlX251bWJlciI6ICJmZDEyMzQ0MyIsCiAgICAgICAgImlzc3VlZF9ieSI6ICLK4uDrs/Sz6uD26e3gIOru7LPxs/8iLAogICAgICAgICJpc3N1ZWRfZGF0ZSI6ICIxOTkxLTA4LTE5IiwKICAgICAgICAiZXhwaXJ5X2RhdGUiOiAiMTk5MS0wOC0xOSIsCiAgICAgICAgImFjdGl2ZV9mcm9tX2RhdGUiOiAiMTk5MS0wOC0xOSIsCiAgICAgICAgIndoYXRfbGljZW5zZWQiOiAi8OXg67Pn4Paz/yDt4PDq7vLo9+3o9SDn4PHu4bPiIiwKICAgICAgICAib3JkZXJfbm8iOiAiSy0xMjMiCiAgICAgIH0KICAgIF0sCiAgICAiYWNjcmVkaXRhdGlvbiI6IHsKICAgICAgImNhdGVnb3J5IjogIkZJUlNUIiwKICAgICAgImlzc3VlZF9kYXRlIjogIjE5OTEtMDgtMTkiLAogICAgICAiZXhwaXJ5X2RhdGUiOiAiMTk5MS0wOC0xOSIsCiAgICAgICJvcmRlcl9ubyI6ICJmZDEyMzQ0MyIsCiAgICAgICJvcmRlcl9kYXRlIjogIjE5OTEtMDgtMTkiCiAgICB9CiAgfSwKICAic2VjdXJpdHkiOiB7CiAgICAicmVkaXJlY3RfdXJpIjogImh0dHA6Ly9leGFtcGxlMi5jb20iCiAgfSwKICAicHVibGljX29mZmVyIjogewogICAgImNvbnNlbnQiOiB0cnVlLAogICAgImNvbnNlbnRfdGV4dCI6ICJDb25zZW50IHRleHQiCiAgfQp9CgoxggbEMIIGwAIBATCCATYwggEcMVswWQYDVQQDDFLQkNCm0KHQmiDQotCe0JIgItCm0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C90LAiMREwDwYDVQQHDAjQmtC40ZfQsjEZMBcGA1UEBQwQVUEtMzY4NjU3NTMtMDExNDFSMFAGA1UECgxJ0KLQntCSICLQptC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgItCj0LrRgNCw0ZfQvdCwIjEuMCwGA1UECwwl0JLRltC00LTRltC7INGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlzELMAkGA1UEBgwCVUECFNFYogYAAAAAAAAAAAAAAAAAAAABMAwGCiqGJAIBAQEBAgGgggT0MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE3MTIyMjE4NTY1MFowLwYJKoZIhvcNAQkEMSIEIFoXzk2OcnsUuabfqvcgixsUifkP6f0DfOZE4/YUeUQKMIIBjwYLKoZIhvcNAQkQAi8xggF+MIIBejCCAXYwggFyMAwGCiqGJAIBAQEBAgEEINn+Pjj2FSHs/hw+uthb2UrpPRJXqLK7drJH1+5MD4ePMIIBPjCCASSkggEgMIIBHDFbMFkGA1UEAwxS0JDQptCh0Jog0KLQntCSICLQptC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgItCj0LrRgNCw0ZfQvdCwIjERMA8GA1UEBwwI0JrQuNGX0LIxGTAXBgNVBAUMEFVBLTM2ODY1NzUzLTAxMTQxUjBQBgNVBAoMSdCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxLjAsBgNVBAsMJdCS0ZbQtNC00ZbQuyDRgdC10YDRgtC40YTRltC60LDRhtGW0ZcxCzAJBgNVBAYMAlVBAhTRWKIGAAAAAAAAAAAAAAAAAAAAATCCAvQGCyqGSIb3DQEJEAIUMYIC4zCCAt8GCSqGSIb3DQEHAqCCAtAwggLMAgEDMQ4wDAYKKoYkAgEBAQECATBpBgsqhkiG9w0BCRABBKBaBFgwVgIBAQYIKwYBBQUHAwgwMDAMBgoqhiQCAQEBAQIBBCBaF85NjnJ7FLmm36r3IIsbFIn5D+n9A3zmROP2FHlECgIEAN2iLRgPMjAxNzEyMjIxODU2NTBaMYICSjCCAkYCAQGgIgQgZuzrjmRV2EI5y9+1euE4/pc33APvaufXCYEsCCF6Jc0wDAYKKoYkAgEBAQECAaCCAbwwLwYJKoZIhvcNAQkEMSIEIOMjHCTUwaILXeDtm812nUwIMf3X53Qv3/uFoQMShmMaMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDCCAWsGCyqGSIb3DQEJEAIvMYIBWjCCAVYwggFSMIIBTjAMBgoqhiQCAQEBAQIBBCDKkEMJu6YW24w28oLP5ROu/IIqn2iydCKgBqlBQpfyyjCCARowggEApIH9MIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTcxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUPbc+e/DVdbICAAAAAQAAAIQAAAAwDQYLKoYkAgEBAQEDAQEEQKIZwjzbvA3OAyTwUqqZ7zCRCk+Xjw5zFXkKYGtNhDd5R5r9jfc02ic054LZ9vdJTZXWg3r1DpplymIy87Nj2jQwDQYLKoYkAgEBAQEDAQEEbKWU5PHc7j8DczMIhCMmARg2RemLZMV4x33hghXkXgUGCF5BFdhdFp3O9jmCGHus0eONHCTSGhIQ9EzD2QiruDWTCCl0f9uQaflE4gVMEi4YcxjaXsSxhJfVYkpDZFqVg0oKAmCtWutLYx5vHw==

отправил на демо:
WinHttp.Open("PUT","http://demo.ehealth.world/api/legal_entities",0);

ПараметрJSON = "{""signed_legal_entity_request"":""" + Данные + """";	   
ПараметрJSON = ПараметрJSON	+ ",""signed_content_encoding"":""base64"""+ "}";
			   
WinHttp.Send(ПараметрJSON);	

получаю ошибку:
{"meta":{"url":"http://api-svc.il/api/legal_entities","type":"object","request_id":"f54fa2bd-60e2-4496-815e-1548e380d9b2#759","code":500},"error":{"errors":{"detail":"Internal server error"}}}

- если отправляю не JSON - ответ 422 - неверный формат 
- если отправляю не подписанные данные - ответ 422 - не base64

а вот почему 500 и как с ней бороться подскажите плиз...

**Comment by dorado2012** [comment]
ключ подписи от uakey.com.ua

**Comment by svetavedmed** [comment]
Добрый день. После декодировки подписанных данных видно кодировка русских символов неверная. Json должен быть в utf8 кодировке. @dorado2012 Можете перепроверить, пожалуйста, кодировку Ваших данных?

**Comment by dorado2012** [comment]
Спасибо, сейчас перепроверю29 дек. 2017 г. 1:53 ПП пользователь svetavedmed <notifications@github.com> написал:Добрый день. После декодировки подписанных данных видно кодировка русских символов неверная. Json должен быть в utf8 кодировке. @dorado2012 Можете перепроверить, пожалуйста, кодировку Ваших данных?

**Comment by dorado2012** [comment]
кодировка была win-1251

**Comment by gmile** [comment]
@dorado2012 удалось создать мед учереждение?
