### ISSUE TITLE
Помилка реєстрації юр. особи

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#21]
Добрий день.

Вчора з'явилась помилка при реєстрації юр. особи. По логіці public_offer.consent має бути true/false.

`{
  "meta": {
    "url": "http://api-svc.il/api/legal_entities",
    "type": "object",
    "request_id": "70d2k7e32o53ggudgl3qdfumd0uifok4",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": "inclusion",
            "params": [
              true
            ],
            "description": "value is not allowed in enum"
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.public_offer.consent"
      }
    ]
  }
}` 

Дякую.

**Comment by lymychp** [comment]
@pieskov @pzhuk даний тікет не буде розглядатись поки не буде оформлений по правилах.
Прошу надати  json реквесту.

**Comment by pieskov** [comment]
[test_base.txt](https://github.com/ehealth-ua/api-spec/files/1057138/test_base.txt)

**Comment by lymychp** [comment]
"$.public_offer.consent" - false, має бути true

**Comment by pieskov** [comment]
За що відповідає дане поле?
замість > false, має бути true
Чому? Можна якесь роз'яснення.

**Comment by pzhuk** [comment]
@pieskov це поле, яке підтверджує що користувач погодився з consent.
В народі - це checkbox (а-ля "галочка")

**Comment by lymychp** [comment]
@pieskov пропоную закрити тікет
