### ISSUE TITLE
Смс-код підтведження (Декларації) Prod

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#210]
=== Доброго дня, подивіться будь-ласка чи проходить запит з вашої сторони, кажуть що не надходить смс з кодом, оператор '050' , причому замітив що інший оператор для прикладу '099' все ок, так як код після запиту підтверджують  ====  
  

## Респонс на запит

  "meta": {
    "url": "http://api.ehealth-ukraine.org/verifications",
    "type": "object",
    "request_id": "sk28evt5n83fi4rqmqqmviuc90neii4b",
    "code": 201
  },
і дата 

## Actual result
- [ ] не приходить код

## Expected result
- [ ] смс-код

**Comment by pzhuk** [comment]
доброго дня, вибачте за затримку з відповіддю.
Напишіть будь-ласка чи проблема все ще спостерігається і список номерів телефонів
дякую
На 050 доставляється нормально

**Comment by superjonh** [comment]
Наразі не замічав повторення даного інциденту, виглядає все в порядку
