### ISSUE TITLE
Отсутствует public_offer в response при создании legal_entity

### ISSUE THREAD

**Issue by oshklyarova** [ehealth-ua/api-spec#211]
===NO SECRET INFORMATION FROM PRODUCTION SHOULD BE DISCLOSED IN THIS REPO. IT IS PUBLIC====  
  
*Please make sure these boxes are checked before submitting new issue.
It will significantly speed up the issue resolving process and also make our team a little bit happier.
Thanks!*

## Steps to Reproduce (Repro steps)

- [ ] endpoint address
- [ ] preconditions if any
- [ ] sequence of actions that should be taken to reproduce the behavior.
- [ ] test data, requests examples, json files, curl requests etc

## Actual result
- [ ] response example (*.json file)

## Expected result
- [ ] description of the expected system behavior.

**Comment by lymychp** [comment]
@AlekzandrV it looks like specification should be updated

**Comment by svetavedmed** [comment]
Specification is updated
