### ISSUE TITLE
Відміна Declaration Requests

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#212]
@pzhuk  В продовження нашої розмови по Declaration Requests на Продакшен:
Допоможи, будь ласка, розібратись яка була послідовність і дій і чи валідні наступні кейси.
 є 6 Declaration Requests: 
1)  40ac3efd-9c4e-421c-b104-a797262ab954  створена 2017-12-12 11:17:33.980095 і відмінена 2018-01-15 14:38:39.557744 - тобто прожила майже місяць
2) 474fbe84-0134-4659-955c-c44208f99b2e створена 2017-12-15 10:12:29.680025 і відмінена 2017-12-15 10:12:30.515037- тобто через 1 секунду
3) 5a8ada7e-e7b7-46fa-972f-360cbb2fd9f4 створена 2018-01-04 15:50:55.218961 і відмінена 2018-01-15 14:38:39.557744- тобто через 11 днів
4) a2110f32-bc10-4d3a-931b-effccc6c5105 створена 2018-01-15 14:51:22.881598 і відмінена 2018-01-15 14:51:38.822369- тобто через 16 секунд

5) 4e7a5135-dfc3-4a28-996b-14a532bc89b0
6) c66ec7cf-73f5-477f-a27d-e29c14863d37
Створено і відмінено одим і тим же користувачем "employee_id" : "1c83e3bf-2981-4551-a9af-2cc2e0239d9d".

**Comment by pzhuk** [comment]
@lymychp any chance we could help on it?

**Comment by lymychp** [comment]
You can try to use logs to investigate

**Comment by sreva** [comment]
@lymychp можеш допомогти з цим таском, відміни виглядають досить дивними.

**Comment by lymychp** [comment]
а є свіжіший приклад?

**Comment by sreva** [comment]
нажаль поки що немає, як з'являться я сюди напишу.
