### ISSUE TITLE
Відміна Declaration Requests на ПРЕ-ПРОД 

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#213]
## Steps to Reproduce (Repro steps)

- [ ] POST https://api.ehealth.world/api/declaration_requests
- [ ] Створюємо декл.реквест для користувача без ІПН 63a3128c-cbbf-4398-a5ba-2598cf83f80e , не підтверджуємо його і потім зразу ж створюємо для іншого також без ІПН 6e2c79f5-b699-472e-969a-2ebee0700aa8. У них різні ПІБ, дати народження і стать. В результаті створення другої переша стає CANCELLED employee_id a1d9ddf1-8cab-4671-80e0-811f5a63df8d
[Запит і відповідь по 63a3128c-cbbf-4398-a5ba-2598cf83f80e.txt](https://github.com/ehealth-ua/api-spec/files/1635036/63a3128c-cbbf-4398-a5ba-2598cf83f80e.txt)
[Запит і відповідь по 6e2c79f5-b699-472e-969a-2ebee0700aa8.txt](https://github.com/ehealth-ua/api-spec/files/1635037/6e2c79f5-b699-472e-969a-2ebee0700aa8.txt)

## Actual result
- [ ] 63a3128c-cbbf-4398-a5ba-2598cf83f80e - перейшла в статус CANCELLED 

## Expected result
- [ ] 63a3128c-cbbf-4398-a5ba-2598cf83f80e - залишилась в статусі NEW

**Comment by svetavedmed** [comment]
fixed on preprod
