### ISSUE TITLE
Проблеми при логіні на пре-прод

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#217]
## Steps to Reproduce (Repro steps)

- [ ]http://auth.ehealth.world
`http://auth.ehealth.world/sign-in?request_type=code&email=o.zakusylo%2B1%40helsi.me&redirect_uri=https%3A%2F%2Fstagingreform.helsi.me%2Fuser%2Fauth&client_id=08db1dc9-bd5e-4e0e-8df7-abea1fe0226d&scope=legal_entity%3Aread+employee_request%3Aapprove+employee_request%3Areject+employee%3Aread+division%3Aread+declaration_request%3Awrite+declaration_request%3Asign+declaration_request%3Aapprove+declaration_request%3Aread+declaration%3Aread+otp%3Aread+otp%3Awrite+medication_request_request%3Awrite+medication_request_request%3Aread+medication_request_request%3Asign+medication_request_request%3Areject+medication_dispense%3Aread+drugs%3Aread+medication_request%3Aread+medication_request%3Adetails+medication_request%3Areject+medication_request%3Aresend+person%3Aread` 
- [ ]  вводимо логін і пароль з яким вчора логінились успішно отримуємо 
![image](https://user-images.githubusercontent.com/29060924/35324038-3286f0dc-00f8-11e8-9a36-c2d8a3c9133e.png)
{"message":"no API found with those values"}

## Actual result
- [ ] {"message":"no API found with those values"}

## Expected result
- [ ] успішний логін

**Comment by lymychp** [comment]
looks like this is the result of the yesterday's updates. will check it

**Comment by svetavedmed** [comment]
@sreva, please, try one more time to log in. Should work now.

**Comment by sreva** [comment]
Дякую. Працює
