### ISSUE TITLE
Обновление Employee на предпроде. Ошибка 501

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#218]
D, [2018-01-27T15:26:50.648931 #115076] DEBUG -- : [httplog] Connecting: api.ehealth.world:443
D, [2018-01-27T15:26:50.796041 #115076] DEBUG -- : [httplog] Sending: POST http://api.ehealth.world:443/api/employee_requests
D, [2018-01-27T15:26:50.796199 #115076] DEBUG -- : [httplog] Header: content-type: application/json
D, [2018-01-27T15:26:50.796239 #115076] DEBUG -- : [httplog] Header: authorization: Bearer TjFUTm9TQitZUlZwRzdzVVRxVVVNQT09
D, [2018-01-27T15:26:50.796262 #115076] DEBUG -- : [httplog] Header: api-key: 9cea483e5eb8af18a598
D, [2018-01-27T15:26:50.796283 #115076] DEBUG -- : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2018-01-27T15:26:50.796302 #115076] DEBUG -- : [httplog] Header: accept: */*
D, [2018-01-27T15:26:50.796321 #115076] DEBUG -- : [httplog] Header: user-agent: Ruby
D, [2018-01-27T15:26:50.796339 #115076] DEBUG -- : [httplog] Header: connection: close
D, [2018-01-27T15:26:50.796398 #115076] DEBUG -- : [httplog] Data: {"employee_request":{"position":"P1","start_date":"2018-01-01","status":"NEW","employee_type":"HR","party":{"first_name":"Варпварпварпварп","last_name":"Рварварп","second_name":"Варпварпварп","birth_date":"2018-01-11","birth_country":"UA","birth_settlement":"АБРАМОК","tax_id":"3491701789","gender":"FEMALE","email":"jsean.hyde@zebra.email","addresses":[{"type":"REGISTRATION","country":"UA","area":"ХАРКІВСЬКА","settlement":"ІЗЮМ","settlement_type":"CITY","settlement_id":"79f07f7e-81a6-41b7-9dfe-5b90bdc562e8","street_type":"STREET","street":"Першотравнева","building":"2"},{"type":"RESIDENCE","country":"UA","area":"ХАРКІВСЬКА","settlement":"ІЗЮМ","settlement_type":"CITY","settlement_id":"79f07f7e-81a6-41b7-9dfe-5b90bdc562e8","street_type":"STREET","street":"Першотравнева","building":"2"}],"documents":[{"type":"NATIONAL_ID","number":"УКПРКПКПЦУКП"}],"phones":[{"type":"MOBILE","number":"+380661661988"}]},"legal_entity_id":"aa15a1f0-54a0-45b7-a777-5f7fb7d368d5","employee_id":"2e597362-4763-4690-a087-8e8fad26276d"}}
D, [2018-01-27T15:26:51.057664 #115076] DEBUG -- : [httplog] Status: 501
D, [2018-01-27T15:26:51.058194 #115076] DEBUG -- : [httplog] Header: access-control-allow-origin: *
D, [2018-01-27T15:26:51.058337 #115076] DEBUG -- : [httplog] Header: cache-control: max-age=0, private, must-revalidate
D, [2018-01-27T15:26:51.058402 #115076] DEBUG -- : [httplog] Header: content-length: 177
D, [2018-01-27T15:26:51.058449 #115076] DEBUG -- : [httplog] Header: content-type: application/json; charset=utf-8
D, [2018-01-27T15:26:51.058495 #115076] DEBUG -- : [httplog] Header: date: Sat, 27 Jan 2018 13:26:51 GMT
D, [2018-01-27T15:26:51.058538 #115076] DEBUG -- : [httplog] Header: server: Cowboy
D, [2018-01-27T15:26:51.058580 #115076] DEBUG -- : [httplog] Header: vary: Accept-Encoding
D, [2018-01-27T15:26:51.058620 #115076] DEBUG -- : [httplog] Header: via: kong/0.12.1
D, [2018-01-27T15:26:51.058660 #115076] DEBUG -- : [httplog] Header: x-content-type-options: nosniff
D, [2018-01-27T15:26:51.058741 #115076] DEBUG -- : [httplog] Header: x-frame-options: SAMEORIGIN
D, [2018-01-27T15:26:51.058785 #115076] DEBUG -- : [httplog] Header: x-kong-proxy-latency: 16
D, [2018-01-27T15:26:51.058824 #115076] DEBUG -- : [httplog] Header: x-kong-upstream-latency: 54
D, [2018-01-27T15:26:51.058864 #115076] DEBUG -- : [httplog] Header: x-ratelimit-limit-minute: 9000
D, [2018-01-27T15:26:51.058903 #115076] DEBUG -- : [httplog] Header: x-ratelimit-remaining-minute: 8996
D, [2018-01-27T15:26:51.058942 #115076] DEBUG -- : [httplog] Header: x-request-id: 48236d08-d692-4d7a-851e-45bb7ecbb799#81047
D, [2018-01-27T15:26:51.058982 #115076] DEBUG -- : [httplog] Header: x-xss-protection: 1; mode=block
D, [2018-01-27T15:26:51.059056 #115076] DEBUG -- : [httplog] Header: connection: close
D, [2018-01-27T15:26:51.059242 #115076] DEBUG -- : [httplog] Response:
{"meta":{"url":"http://api-svc.il/api/employee_requests","type":"object","request_id":"48236d08-d692-4d7a-851e-45bb7ecbb799#81047","code":501},"error":{"type":"internal_error"}}

Что не так?

**Comment by lymychp** [comment]
fixed on preprod. please try again.

**Comment by Charly3X** [comment]
done. thank you.
