### ISSUE TITLE
Регистрация декларации на предпроде Ошибка 500

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#219]
D, [2018-01-27T15:32:02.268081 #115076] DEBUG -- : [httplog] Connecting: api.ehealth.world:443
D, [2018-01-27T15:32:02.417508 #115076] DEBUG -- : [httplog] Sending: POST http://api.ehealth.world:443/api/declaration_requests
D, [2018-01-27T15:32:02.417632 #115076] DEBUG -- : [httplog] Header: content-type: application/json
D, [2018-01-27T15:32:02.417665 #115076] DEBUG -- : [httplog] Header: authorization: Bearer NnV5NTJhcFRRWGxxZk5wTWZRRU9mQT09
D, [2018-01-27T15:32:02.417839 #115076] DEBUG -- : [httplog] Header: api-key: 9cea483e5eb8af18a598
D, [2018-01-27T15:32:02.417910 #115076] DEBUG -- : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2018-01-27T15:32:02.417933 #115076] DEBUG -- : [httplog] Header: accept: */*
D, [2018-01-27T15:32:02.417950 #115076] DEBUG -- : [httplog] Header: user-agent: Ruby
D, [2018-01-27T15:32:02.417967 #115076] DEBUG -- : [httplog] Header: connection: close
D, [2018-01-27T15:32:02.418024 #115076] DEBUG -- : [httplog] Data: {"declaration_request":{"person":{"first_name":"Иван","last_name":"Иванько","birth_date":"2017-12-26","birth_country":"UA","birth_settlement":"АБРАМОК","gender":"FEMALE","secret":"апваправпр","addresses":[{"type":"REGISTRATION","country":"UA","area":"ХАРКІВСЬКА","settlement":"ІЗЮМ","settlement_type":"CITY","settlement_id":"79f07f7e-81a6-41b7-9dfe-5b90bdc562e8","street_type":"STREET","street":"Перемоги","building":"1"},{"type":"RESIDENCE","country":"UA","area":"ХАРКІВСЬКА","settlement":"ІЗЮМ","settlement_type":"CITY","settlement_id":"79f07f7e-81a6-41b7-9dfe-5b90bdc562e8","street_type":"STREET","street":"Перемоги","building":"1"}],"patient_signed":false,"process_disclosure_data_consent":true,"emergency_contact":{"first_name":"ввапрварпварп","last_name":"варпвар","phones":[{"type":"MOBILE","number":"+380661669460"}]},"authentication_methods":[{"type":"OTP"}],"documents":[{"type":"NATIONAL_ID","number":"АПКЕУНГКНКУЕН"}]},"employee_id":"55a4f743-4955-4303-bb18-4857f61ce0ee","scope":"family_doctor","division_id":"a0293856-e0af-4581-9a3d-d87de4342f35"}}
D, [2018-01-27T15:32:02.630691 #115076] DEBUG -- : [httplog] Status: 500
D, [2018-01-27T15:32:02.630840 #115076] DEBUG -- : [httplog] Header: cache-control: max-age=0, private, must-revalidate
D, [2018-01-27T15:32:02.630889 #115076] DEBUG -- : [httplog] Header: content-length: 200
D, [2018-01-27T15:32:02.630958 #115076] DEBUG -- : [httplog] Header: content-type: text/plain; charset=UTF-8
D, [2018-01-27T15:32:02.631006 #115076] DEBUG -- : [httplog] Header: date: Sat, 27 Jan 2018 13:32:03 GMT
D, [2018-01-27T15:32:02.631027 #115076] DEBUG -- : [httplog] Header: server: Cowboy
D, [2018-01-27T15:32:02.631057 #115076] DEBUG -- : [httplog] Header: vary: Accept-Encoding
D, [2018-01-27T15:32:02.631073 #115076] DEBUG -- : [httplog] Header: via: kong/0.12.1
D, [2018-01-27T15:32:02.631087 #115076] DEBUG -- : [httplog] Header: x-content-type-options: nosniff
D, [2018-01-27T15:32:02.631100 #115076] DEBUG -- : [httplog] Header: x-frame-options: SAMEORIGIN
D, [2018-01-27T15:32:02.631114 #115076] DEBUG -- : [httplog] Header: x-kong-proxy-latency: 26
D, [2018-01-27T15:32:02.631127 #115076] DEBUG -- : [httplog] Header: x-kong-upstream-latency: 58
D, [2018-01-27T15:32:02.631141 #115076] DEBUG -- : [httplog] Header: x-ratelimit-limit-minute: 9000
D, [2018-01-27T15:32:02.631154 #115076] DEBUG -- : [httplog] Header: x-ratelimit-remaining-minute: 8999
D, [2018-01-27T15:32:02.631167 #115076] DEBUG -- : [httplog] Header: x-request-id: cf5677dd-5843-4b6a-afcf-8337bc0e65b6#84324
D, [2018-01-27T15:32:02.631181 #115076] DEBUG -- : [httplog] Header: x-xss-protection: 1; mode=block
D, [2018-01-27T15:32:02.631195 #115076] DEBUG -- : [httplog] Header: connection: close
D, [2018-01-27T15:32:02.631250 #115076] DEBUG -- : [httplog] Response:
{"meta":{"url":"http://api-svc.il/api/declaration_requests","type":"object","request_id":"cf5677dd-5843-4b6a-afcf-8337bc0e65b6#84324","code":500},"error":{"errors":{"detail":"Internal server error"}}}

**Comment by lymychp** [comment]
взяли в роботу

**Comment by svetavedmed** [comment]
The problem is doctor's speciality. Doctor with ID='55a4f743-4955-4303-bb18-4857f61ce0ee' has speciality 'PHARMACIST2'. We will describe this error and add new validation.

**Comment by svetavedmed** [comment]
creating employees with correct speciality - https://github.com/edenlabllc/ehealth.api/issues/1832

**Comment by svetavedmed** [comment]
fixed on preprod
