### ISSUE TITLE
Час дії Refresh token

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#22]
Прохання збільшити час дії Refresh token до 60 днів.

**Comment by pzhuk** [comment]
@sreva можете обгрунтувати цей запит детальніше, будь-ласка?

**Comment by sreva** [comment]
Так, звичайно.
Це потрібно для того щоб ми не змушували наших користувачів постійно, два рази авторизуватися (з декількома редіректами), один раз у нас, а потім і на стороні eHealth. 

При наявності Refresh token валідного на протязі 60 днів, ми будемо редіректити користувача для авторизації на стороні eHealth в наступних випадках:
1.  Пройшло 60 днів з моменту крайньої авторизації в eHealth
2.  Користувач змінив пароль у нашій системі
3.  Було оновленні, будь які дані по співробітнику

Якщо бачите ще якісь варіанти, коли потрібно змішувати користувача проходити авторизацію на стороні eHealth прошу доповнити.

**Comment by pzhuk** [comment]
Конфігурація токенів буде встановлена наступним чином, з міркувань безпеки, зручності і навантаження на систему:

access_token = 8 hours
refresh_token = 30 days

**Comment by sreva** [comment]
Дякую
