### ISSUE TITLE
Token - exchange refresh token (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#221]
===Token exchange====  

Доброго дня, цікавить питання на рахунок продовження дії токена, який поточний його термін дії ??

## Так, як на запит  
- [ ] https://api.ehealth-ukraine.org/admin/tokens/TOKEN_HERE/verify 

## Actual result
- [ ] повертає інформацію по даному токену
- [ ] отриманий 2018-01-02 22:38:44.857 , "expires_at": 1517517526,

## Коли пробую зробити exchange refresh token по запиту
- [ ] https://api.ehealth-ukraine.org/oauth/tokens

## Actual result
- [ ] <error><code>Unauthorized</code><description>Unauthorized</description><body>{"meta":{"url":"http://api-svc.mithril/oauth/tokens","type":"object","request_id":"bead1590-e3c3-4621-ac63-199ca2953347#58075","code":401},"error":{"type":"invalid_grant","message":"Token expired."}}</body></error>

## Expected result
- [ ] token exchange info.

**Comment by lymychp** [comment]
можна отримати новий refresh_token з використанням валідного (не простроченого) refresh_token. Якщо токен вже прострочений, то тільки через проходження oauth flow.
Refresh_token по дефолту видаєтсья на місяць

**Comment by superjonh** [comment]
@lymychp  Зрозуміло, тільки дивно те, що отримати інформацію по токену можна, а зробити рефреш ні, на демо якщо не помиляюсь раніше було відразу на перевірці токена ерора ('token_expired')
