### ISSUE TITLE
Не пришло приглашение к системе eHealth.

### ISSUE THREAD

**Issue by Olexandrit** [ehealth-ua/api-spec#222]
Реєструю аптеку на препроді!(http://api.ehealth.world/api/legal_entities, відповідь: перелік мед. закладів. Наш заклад присутній в переліку(http://prntscr.com/i8njm4)). Не прийшло запрошення до системи еХелс. Яким чином можна повторно відправити запрошення?

При спробі відновити пароль через веб(https://auth.ehealth.world/reset) отримую "Користувача з таким email не існує"(https://prnt.sc/i8nkn7)

**Comment by lymychp** [comment]
1) у відповідь на реєстрацію аптеки повертається датасет тільки з Вашим закладом, ніякого переліку
2) на який  email реєструєтесь?

**Comment by Olexandrit** [comment]
1. Результат api/legal_entities(https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity)
[request_legal_entities.txt](https://github.com/ehealth-ua/api-spec/files/1685753/request_legal_entities.txt)
[response_legal_entities.txt](https://github.com/ehealth-ua/api-spec/files/1685754/response_legal_entities.txt)
2. itvisa1c@gmail.com (http://prntscr.com/i8o65s)

**Comment by Olexandrit** [comment]
Є якийсь результат сприводу проблеми?

**Comment by svetavedmed** [comment]
Ви маєте використовувати https а не http. Помилку з редіректом ми виправимо.

**Comment by Olexandrit** [comment]
Дякую. Проблему вирішено. Користуюсь документом https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity. Описано як http://ehealth.com/api/legal_entities....
