### ISSUE TITLE
501 при запиті на оновлення даних по співробітнику

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#224]
## Steps to Reproduce (Repro steps)

- [ ] POST http://demo.ehealth.world/api/employee_requests
- [ ] `{
                    "division_id" : "28bdd87d-5c43-48db-847e-412b04d26f13",
                    "doctor" : {
                        "educations" : [ 
                            {
                                "city" : "ааааааа",
                                "country" : "UA",
                                "degree" : "BACHELOR",
                                "diploma_number" : "12123",
                                "institution_name" : "ввввввввв",
                                "issued_date" : "2010-11-20",
                                "speciality" : "Лікарська справа"
                            }
                        ],
                        "specialities" : [ 
                            {
                                "attestation_date" : "2015-12-12",
                                "attestation_name" : "КК",
                                "certificate_number" : "12",
                                "level" : "FIRST",
                                "qualification_type" : "DEFENSE",
                                "speciality" : "FAMILY_DOCTOR",
                                "speciality_officio" : true,
                                "valid_to_date" : "2020-12-12"
                            }
                        ]
                    },
                    "employee_type" : "DOCTOR",
                    "party" : {
                        "birth_date" : "1989-11-01",
                        "documents" : [ 
                            {
                                "number" : "СІ6555",
                                "type" : "PASSPORT"
                            }
                        ],
                        "email" : "yuriy.akht+likar@helsi.me",
                        "first_name" : "Юрій",
                        "gender" : "MALE",
                        "last_name" : "Кіндратов",
                        "phones" : [ 
                            {
                                "number" : "+380444444444",
                                "type" : "MOBILE"
                            }
                        ],
                        "second_name" : "перун",
                        "no_tax_id" : false,
                        "tax_id" : "3281211774"
                    },
                    "position" : "P7",
                    "start_date" : "2011-11-11",
                    "status" : "NEW",
                    "legal_entity_id" : "5907aac1-6452-4a6c-b63d-4352d1bc992f",
                    "employee_id" : "523420aa-5b88-4f9e-8d39-a5ef2f33edd6"
                }`

## Actual result
- [ ] `"body" : {
                "meta" : {
                    "url" : "http://api-svc.il/api/employee_requests",
                    "type" : "object",
                    "request_id" : "f81b493d-d5a9-4da9-942a-a4a136221062#7721",
                    "code" : 501
                },
                "error" : {
                    "type" : "internal_error"
                }
            }`

## Expected result
- [ ] код менший від 500

**Comment by svetavedmed** [comment]
ошибка 501, т.к. вы отправляете "employee_id" : "523420aa-5b88-4f9e-8d39-a5ef2f33edd6" в запросе на создание employee. 
На дев это уже исправлено.

**Comment by sreva** [comment]
Відправляємо employee_id, так як хочемо оновити дані по цьому співробітнику

**Comment by svetavedmed** [comment]
Да все верно, дожен обновлятся employee. Извините, дезинформировала. Ошибка на демо - исправим.

**Comment by ybod** [comment]
Ошибка была была связана с настройками сервиса [Man](https://github.com/edenlabllc/man.api) на `Demo` среде. На данный момент проблема на `Demo` среде решена.

**Comment by svetavedmed** [comment]
Fixed on Demo
