### ISSUE TITLE
Скоуп employee_request:read для типу співробітника DOCTOR

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#225]
Чому при запиті скупів для типу співробітника DOCTOR в переліку прибрали employee_request:read?

**Comment by svetavedmed** [comment]
Добрый день. У доктора не должно быть скоупа employee_request:read. 
И согласно https://edenlab.atlassian.net/wiki/spaces/EH/pages/2004415/Scopes+model его и нет.

**Comment by pieskov** [comment]
Как теперь проверить, подтвердил сотрудник заявку или нет?
