### ISSUE TITLE
Скоуп employee_request:read для типу співробітника DOCTOR

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#226]
Чому при запиті скупів для типу співробітника DOCTOR в переліку прибрали employee_request:read?
Как теперь проверить, подтвердил сотрудник заявку или нет?

**Comment by pieskov** [comment]
Чому при запиті скупів для типу співробітника DOCTOR в переліку прибрали employee_request:read?
Как теперь проверить, подтвердил сотрудник заявку или нет?

**Comment by AlekzandrV** [comment]
1) Повернули `employee_request:read` для DOCTOR, ADMIN
2) Додали `employee_id` до events API
