### ISSUE TITLE
Для HR i ADMIN ідентичні скоупи

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#227]
## Steps to Reproduce (Repro steps)

- [ ] https://api.ehealth-ukraine.org/admin/roles і https://auth.ehealth.world/admin/roles
- [ ] для HR i ADMIN повертаються ідентичні скоупи, а мають різні

## Actual result
- [ ] `{
            "scope": "division:activate division:deactivate division:details division:read division:write employee:deactivate employee:details employee:read employee:write employee_request:approve employee_request:read employee_request:reject employee_request:write legal_entity:read",
            "name": "ADMIN",
            "id": "9b72879c-d3ef-472b-9ada-d074349049f0"
        }`
`        {
            "scope": "legal_entity:read employee_request:read employee_request:write employee_request:approve employee_request:reject employee:read employee:write employee:details employee:deactivate division:write division:read division:details division:activate division:deactivate ",
            "name": "HR",
            "id": "a9f4da40-8bb6-4d27-8745-d81c531c9344"
        }`

## Expected result
- [ ] в ADMIN  має бути набір скоупів точно не дозволяє створювати і оновлювати співробітників і підроздили.

**Comment by svetavedmed** [comment]
@vsirius, please, update scopes for admin on prod
```
update roles
set scope=('legal_entity:read employee_request:approve employee_request:reject employee:read division:read division:details declaration_request:write declaration_request:approve declaration_request:reject declaration_request:read declaration:read otp:read otp:write declaration_request:sign employee_request:read') 
```

**Comment by vsirius** [comment]
`sql> update roles
set scope=('legal_entity:read employee_request:approve employee_request:reject employee:read division:read division:details declaration_request:write declaration_request:approve declaration_request:reject declaration_request:read declaration:read otp:read otp:write declaration_request:sign employee_request:read')`

`2018-02-09 18:08:57] 14 rows affected in 69ms `
