### ISSUE TITLE
Не має інформації по власнику.

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#23]
Добрий день.

Роблю GET запит на http://demo.ehealth.world/api/legal_entities. В списку 3-ри юр. особи (2-ві з них створені мною). Але по жодній немає інформації про власника. Хоча при створенні інформація була.

Підкажіть як отримати відповідь з власником.

Дякую.

**Comment by lymychp** [comment]
@pieskov якщо коротко, то ніяк. Структура відповіді по legal_entity описана в [специфікації](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/persons/get-legal-entity-by-id). Даних по власнику там не має бути. Для отримання даних усіх співробітників, в тому числі власника, використовуйте endoint [employee](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/get-employees-list)

**Comment by pieskov** [comment]
Делаю запрос юр. лица http://demo.ehealth.world/api/legal_entities?edrpou=38469862
`{
  "paging": {
    "size": null,
    "limit": 50,
    "has_more": false,
    "cursors": {
      "starting_after": "f08bfd18-0c41-4a35-8c2e-24cad20a6c12",
      "ending_before": null
    }
  },
  "meta": {
    "url": "http://api-svc.il/api/legal_entities",
    "type": "list",
    "request_id": "1gfcs7llqd81t34oij7ejhek1f23l8bm",
    "code": 200
  },
  "data": [
    {
      "updated_by": "b59c511a-db02-40fb-a438-e7d2ee93ff4f",
      "type": "MSP",
      "status": "VERIFIED",
      "short_name": "КНП „Перший Черкаський міський ЦПМСД”",
      "public_name": "КНП „Перший Черкаський міський центр первинної медико-санітарної допомоги”",
      "phones": [
        {
          "type": "LAND_LINE",
          "number": "+380674023650"
        }
      ],
      "owner_property_type": "PRIVATE",
      "name": "КНП „Перший Черкаський міський центр первинної медико-санітарної допомоги”",
      "medical_service_provider": {
        "licenses": [
          {
            "what_licensed": "what_licensed",
            "license_number": "Lic",
            "issued_date": "2014-01-01",
            "issued_by": "issued_by",
            "expiry_date": "2020-01-01",
            "active_from_date": "2020-01-01"
          },
          {
            "what_licensed": "what_licensed2",
            "license_number": "Lic2",
            "issued_date": "2014-01-02",
            "issued_by": "issued_by2",
            "expiry_date": "2020-01-02",
            "active_from_date": "2020-01-02"
          }
        ],
        "accreditation": {
          "order_no": "1235we",
          "order_date": "2020-01-03",
          "issued_date": "2014-01-03",
          "expiry_date": "2020-01-03",
          "category": "FIRST"
        }
      },
      "legal_form": "150",
      "kveds": [
        "86.10"
      ],
      "is_active": true,
      "inserted_by": "b59c511a-db02-40fb-a438-e7d2ee93ff4f",
      "id": "f08bfd18-0c41-4a35-8c2e-24cad20a6c12",
      "email": "dmytropieskov@gmail.com",
      "edrpou": "38469862",
      "addresses": [
        {
          "type": "REGISTRATION",
          "street_type": "STREET",
          "street": "Дахнівська",
          "settlement_type": "CITY",
          "settlement_id": "43432432",
          "settlement": "Черкаси",
          "region": "Черкаська область",
          "country": "UA",
          "building": "34",
          "area": "Черкаська область"
        },
        {
          "type": "RESIDENCE",
          "street_type": "STREET",
          "street": "Дахнівська",
          "settlement_type": "CITY",
          "settlement_id": "43432432",
          "settlement": "Черкаси",
          "region": "Черкаська область",
          "country": "UA",
          "building": "34",
          "area": "Черкаська область"
        }
      ]
    }
  ]
}`

Потом пытаюсь получить его сотрудников http://demo.ehealth.world/api/employees?division_id=f08bfd18-0c41-4a35-8c2e-24cad20a6c12

`{
  "paging": {
    "size": null,
    "limit": 50,
    "has_more": false,
    "cursors": {
      "starting_after": null,
      "ending_before": null
    }
  },
  "meta": {
    "url": "http://api-svc.prm/api/employees",
    "type": "list",
    "request_id": "o8baeno65ftjov9v1li70q2l1gjcttpt",
    "code": 200
  },
  "data": []
}`

**Comment by lymychp** [comment]
employee endpoints ще не видані на демо.
крім того, 
```
http://demo.ehealth.world/api/employees?division_id=f08bfd18-0c41-4a35-8c2e-24cad20a6c12
```
поверне усіх співробітників з division_id=`f08bfd18-0c41-4a35-8c2e-24cad20a6c12`
Але наразі немає division з таким ID. `f08bfd18-0c41-4a35-8c2e-24cad20a6c12` - legal_entity_id
Отримати список employee можна тільки з access_token співробітника. Тобто після проходження oauth flow

**Comment by pieskov** [comment]
Получается следующее.
1. При регистрации я должен заполнить "Owner" структуру, потому что без нее регистрация не пройдет.
2. При редактировании я запрашиваю информацию по юр. лицу, но без "Owner". "Owner"а - я должен получить отдельно по access_token сотрудника, но не понятно каким образом (http://demo.ehealth.world/api/employees выдает сотрудников по division, а не по legal_entity).

Впрос. Как редактировать юр. лицо?

**Comment by pzhuk** [comment]
2. division здесь как вспомогательный фильтр (опциональный). Можно и другой фильтр использовать - например type=ADMIN. В случае использования токена сотрудника, вернутся данные только из конкретного Legal Entity где этот сотрудник зарегистрирован

> Впрос. Как редактировать юр. лицо?
Или постоянно вводить новые данные об Owner , или получить данные об Owner через доступ с токеном сотрудника


> Получение access_token сотрудника oauth работает?

Нет, еще не работает
