### ISSUE TITLE
После создания Legal Entity в респонсе отсутствует часть с данными owner

### ISSUE THREAD

**Issue by vsmihaylovsky** [ehealth-ua/api-spec#230]
## Steps to Reproduce (Repro steps)

- [ ] http://demo.ehealth.world/api/legal_entities

## Actual result
- [ ] `{
    "urgent": {
        "security": {
            "redirect_uri": "https:\/\/ehealth.infomed.ck.ua",
            "client_secret": "eWpZSDJzSVYreVlmTHpmRVhyTEpIdz09",
            "client_id": "2abf0421-229d-4063-8532-793b9e4a5404"
        },
        "employee_request_id": "bbc1b9c3-b6b7-4863-bbb7-c249731cb8b5"
    },
    "meta": {
        "url": "http:\/\/api-svc.il\/api\/legal_entities",
        "type": "object",
        "request_id": "e89715c9-d2ef-467a-b09a-419ca3888902#12984",
        "code": 200
    },
    "data": {
        "website": null,
        "updated_by": "55d565c7-db49-4a03-8b7c-f476247e3a73",
        "updated_at": "2018-01-22T14:06:32.785104",
        "type": "MSP",
        "status": "ACTIVE",
        "short_name": "\u041a\u0417 \u0414\u041c\u0420 \"\u0426\u0435\u043d\u0442\u0440 \u041f\u041c\u0421\u0414\"",
        "receiver_funds_code": null,
        "public_name": "\u041a\u0417 \u0414\u041c\u0420 \"\u0426\u0435\u043d\u0442\u0440 \u041f\u041c\u0421\u0414\"",
        "phones": [
            {
                "type": "LAND_LINE",
                "number": "+380385831546"
            }
        ],
        "owner_property_type": "STATE",
        "nhs_verified": false,
        "name": "\u041a\u043e\u043c\u0443\u043d\u0430\u043b\u044c\u043d\u0438\u0439 \u0437\u0430\u043a\u043b\u0430\u0434 \u0414\u0443\u043d\u0430\u0454\u0432\u0435\u0446\u044c\u043a\u043e\u0457 \u043c\u0456\u0441\u044c\u043a\u043e\u0457 \u0440\u0430\u0434\u0438 \"\u0426\u0435\u043d\u0442\u0440 \u043f\u0435\u0440\u0432\u0438\u043d\u043d\u043e\u0457 \u043c\u0435\u0434\u0438\u043a\u043e-\u0441\u0430\u043d\u0456\u0442\u0430\u0440\u043d\u043e\u0457 \u0434\u043e\u043f\u043e\u043c\u043e\u0433\u0438\"",
        "mis_verified": "NOT_VERIFIED",
        "medical_service_provider": {
            "licenses": [
                {
                    "what_licensed": "rrrrrrrrr",
                    "order_no": "1212",
                    "license_number": "23432",
                    "issued_date": "2014-01-17",
                    "issued_by": "dddddddd",
                    "expiry_date": "2018-01-17",
                    "active_from_date": "2014-01-17"
                },
                {
                    "what_licensed": "rrrrrrrrr",
                    "order_no": "1215",
                    "license_number": "23432-3",
                    "issued_date": "2017-01-17",
                    "issued_by": "dddddddd",
                    "expiry_date": "2020-01-17",
                    "active_from_date": "2018-01-17"
                }
            ],
            "accreditation": {
                "order_no": "19",
                "order_date": "2017-01-31",
                "issued_date": "2017-02-21",
                "expiry_date": "2020-01-30",
                "category": "FIRST"
            }
        },
        "legal_form": "425",
        "kveds": [
            "86.10",
            "01.24"
        ],
        "is_active": true,
        "inserted_by": "55d565c7-db49-4a03-8b7c-f476247e3a73",
        "inserted_at": "2018-01-22T14:06:32.785095",
        "id": "2abf0421-229d-4063-8532-793b9e4a5404",
        "email": "vsmihaylovsky@ukr.net",
        "edrpou": "33006821",
        "beneficiary": null,
        "archive": null,
        "addresses": [
            {
                "zip": "32400",
                "type": "REGISTRATION",
                "street_type": "STREET",
                "street": "\u0413\u043e\u0440\u044c\u043a\u043e\u0433\u043e",
                "settlement_type": "TOWNSHIP",
                "settlement_id": "da15b03f-9f0b-4684-af34-a18ef256ed07",
                "settlement": "\u0414\u0443\u043d\u0430\u0457\u0432\u0446\u0456",
                "region": "\u0414\u0443\u043d\u0430\u0454\u0432\u0435\u0446\u044c\u043a\u0438\u0439",
                "country": "UA",
                "building": "7",
                "area": "\u0425\u043c\u0435\u043b\u044c\u043d\u0438\u0446\u044c\u043a\u0430"
            }
        ]
    }
}`

## Expected result
- [ ] Хочется видеть часть owner, как описано тут: https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity

На самом деле мне нужен email главврача. Раньше я его брал из employee request, но теперь для МИС это закрыто. Буду рад предложениям где его достать.

**Comment by svetavedmed** [comment]
Добрый день. Вам следует воспользоваться event manager. Тут вы можете посмотреть employee_id и через get employee by ID проверить данные конкретного сотрудника.

**Comment by vsmihaylovsky** [comment]
Я не нахожу способа получить email сотрудника даже обладая employee_id.

**Comment by svetavedmed** [comment]
да, к сожалению, email действительно возвращается только через employee_request. Доступ к employee_request есть у hr.

**Comment by vsmihaylovsky** [comment]
В employee нет ссылки на employee_request, я там могу найти нужный мне имейл разве что вручную.

**Comment by lymychp** [comment]
@vsmihaylovsky рекомендую будувати процес на стороні МІСів відштовхуючись від специфікації АПІ. Наразі блок owner у відповіді на POST /legal_entities не передбачено

**Comment by vsmihaylovsky** [comment]
А то на, что я привел ссылку выше это не спецификация? Там блок овнер есть.
