### ISSUE TITLE
Валідація ІПН при створенні заявки на декларацію

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#231]
ІПН на початку з "0" не пропускаються валідацією, так як не відповідають патерну  "^[1-9]([0-9]{7}|[0-9]{9})$" 
## Actual result
- [ ] не пропускаються валідацією

## Expected result
- [ ] пропускаються, так як "0" на початку ІПН - валідний кейс.

**Comment by svetavedmed** [comment]
fixed on preprod

**Comment by svetavedmed** [comment]
done on prod
