### ISSUE TITLE
Отсутствует текст декларации в реквесте после регистрации самой декларации

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#232]
Есть декларация на предпроде. Подписанная.
Хочу вытащить её текст в виде хтмл.. Делаю запрос на declaration_request. Поле content отсутствует в выдаче.
Логи прилагаю

# Logfile created on 2018-02-09 15:17:23 +0200 by logger.rb/56815
D, [2018-02-09T15:17:23.939721 #44839] DEBUG -- : [httplog] Connecting: metadata.google.internal:80
D, [2018-02-09T15:17:24.041958 #44839] DEBUG -- : [httplog] Connecting: 169.254.169.254:80
D, [2018-02-09T15:19:31.373769 #44839] DEBUG -- : [httplog] Connecting: api.ehealth.world:443
D, [2018-02-09T15:19:31.673750 #44839] DEBUG -- : [httplog] Sending: GET http://api.ehealth.world:443/api/declarations/24479d5e-43ce-47cc-a350-2f9510b1ea89
D, [2018-02-09T15:19:31.673923 #44839] DEBUG -- : [httplog] Header: content-type: application/json
D, [2018-02-09T15:19:31.673956 #44839] DEBUG -- : [httplog] Header: authorization: Bearer dVpYZkV6TnVpZmZLUU43bit3Sm15QT09
D, [2018-02-09T15:19:31.673974 #44839] DEBUG -- : [httplog] Header: api-key: 9cea483e5eb8af18a598
D, [2018-02-09T15:19:31.673989 #44839] DEBUG -- : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2018-02-09T15:19:31.674004 #44839] DEBUG -- : [httplog] Header: accept: */*
D, [2018-02-09T15:19:31.674086 #44839] DEBUG -- : [httplog] Header: user-agent: Ruby
D, [2018-02-09T15:19:31.674115 #44839] DEBUG -- : [httplog] Header: x-newrelic-id: VQcOUFNUGwIAUFRXAwcHUQ==
D, [2018-02-09T15:19:31.674130 #44839] DEBUG -- : [httplog] Header: x-newrelic-transaction: PxQGBwJUDQoFBVgGUgQEUVMJFB8EBw8RVU4aU15cAwcKUFhYVQQGUVMBD0NKQV0HCAFRAVRQFTs=
D, [2018-02-09T15:19:31.674178 #44839] DEBUG -- : [httplog] Header: connection: close
D, [2018-02-09T15:19:31.674229 #44839] DEBUG -- : [httplog] Data: 
D, [2018-02-09T15:19:31.934858 #44839] DEBUG -- : [httplog] Status: 200
D, [2018-02-09T15:19:31.935003 #44839] DEBUG -- : [httplog] Header: cache-control: max-age=0, private, must-revalidate
D, [2018-02-09T15:19:31.935035 #44839] DEBUG -- : [httplog] Header: content-type: application/json; charset=utf-8
D, [2018-02-09T15:19:31.935052 #44839] DEBUG -- : [httplog] Header: date: Fri, 09 Feb 2018 13:19:32 GMT
D, [2018-02-09T15:19:31.935066 #44839] DEBUG -- : [httplog] Header: server: Cowboy
D, [2018-02-09T15:19:31.935080 #44839] DEBUG -- : [httplog] Header: vary: Accept-Encoding
D, [2018-02-09T15:19:31.935093 #44839] DEBUG -- : [httplog] Header: via: kong/0.12.1
D, [2018-02-09T15:19:31.935106 #44839] DEBUG -- : [httplog] Header: x-content-type-options: nosniff
D, [2018-02-09T15:19:31.935119 #44839] DEBUG -- : [httplog] Header: x-frame-options: SAMEORIGIN
D, [2018-02-09T15:19:31.935132 #44839] DEBUG -- : [httplog] Header: x-kong-proxy-latency: 65
D, [2018-02-09T15:19:31.935192 #44839] DEBUG -- : [httplog] Header: x-kong-upstream-latency: 50
D, [2018-02-09T15:19:31.935222 #44839] DEBUG -- : [httplog] Header: x-request-id: eb9b2368-6887-4a2a-bcc8-5d26f92df9f4#47684
D, [2018-02-09T15:19:31.935238 #44839] DEBUG -- : [httplog] Header: x-xss-protection: 1; mode=block
D, [2018-02-09T15:19:31.935250 #44839] DEBUG -- : [httplog] Header: content-length: 1510
D, [2018-02-09T15:19:31.935263 #44839] DEBUG -- : [httplog] Header: connection: close
D, [2018-02-09T15:19:31.935348 #44839] DEBUG -- : [httplog] Response:
{"meta":{"url":"http://api-svc.il/api/declarations/24479d5e-43ce-47cc-a350-2f9510b1ea89","type":"object","request_id":"eb9b2368-6887-4a2a-bcc8-5d26f92df9f4#47684","code":200},"data":{"updated_at":"2018-02-08T06:51:50.842071Z","status":"active","start_date":"2018-02-08","signed_at":"2018-02-08T06:51:50.794325Z","scope":"family_doctor","person":{"tax_id":null,"second_name":null,"phones":[{"type":"MOBILE","number":"+380661669460"}],"last_name":"Ррррреее","id":"90b3cf64-4d78-4bda-94b5-f0a122010687","first_name":"Керкеркер","emergency_contact":{"phones":[{"type":"MOBILE","number":"+380661669460"}],"last_name":"атватватват","first_name":"втвтватвапт"},"confidant_person":[{"secret":"іріріваіівап","relation_type":"PRIMARY","last_name":"Іріукпцукп","gender":"FEMALE","first_name":"Цукпцукпцукпцуп","documents_relationship":[{"type":"CONFIDANT_CERTIFICATE","number":"4454545"}],"documents_person":[{"type":"PASSPORT","number":"555555"}],"birth_settlement":"АБРАМІВСЬКА ДОЛИНА","birth_date":"1978-11-13","birth_country":"UA"}],"birth_settlement":"АБРАМІВСЬКА ДОЛИНА","birth_date":"2018-01-29"},"legal_entity":{"updated_at":"2018-02-07T10:04:49.401241","status":"ACTIVE","short_name":"tyuktyktyk","public_name":"utykyuk","phones":[{"type":"MOBILE","number":"+380661669460"}],"name":"Пеер","legal_form":"231","inserted_at":"2017-12-13T12:12:18.836090","id":"aa15a1f0-54a0-45b7-a777-5f7fb7d368d5","email":"kinovhod@gmail.com","edrpou":"2880614310","addresses":[{"type":"REGISTRATION","street_type":"STREET","street":"Переяславська","settlement_type":"CITY","settlement_id":"1241d1f9-ae81-4fe5-b614-f4f780a5acf0","settlement":"ХАРКІВ","country":"UA","building":"8","area":"ХАРКІВСЬКА"},{"type":"RESIDENCE","street_type":"STREET","street":"Переяславська","settlement_type":"CITY","settlement_id":"1241d1f9-ae81-4fe5-b614-f4f780a5acf0","settlement":"ХАРКІВ","country":"UA","building":"8","area":"ХАРКІВСЬКА"}]},"inserted_at":"2018-02-08T06:51:50.842063Z","id":"24479d5e-43ce-47cc-a350-2f9510b1ea89","end_date":"2021-02-08","employee":{"status":"APPROVED","start_date":"2018-01-29","position":"P3","party":{"tax_id":"2880614310","second_name":"Ивания","phones":[{"type":"MOBILE","number":"+380661669460"}],"last_name":"Павапрвапр","id":"5c4eb57d-d346-48ab-9375-56364a537210","first_name":"Вапрвапрвар"},"legal_entity_id":"aa15a1f0-54a0-45b7-a777-5f7fb7d368d5","id":"18eb4057-090e-4da4-967a-508916071c85","end_date":null,"employee_type":"DOCTOR","doctor":{"specialities":[{"valid_to_date":"2018-03-11","speciality_officio":false,"speciality":"FAMILY_DOCTOR","qualification_type":"DEFENSE","level":"HIGHEST","certificate_number":"345345","attestation_name":"керкрукрукр","attestation_date":"2018-02-08"}],"educations":[{"speciality":"вапрвапрвар","issued_date":"2018-01-30","institution_name":"првапрапра","diploma_number":"вапрвапр","degree":"MASTER","country":"UA","city":"АБАЗІВКА"}]},"division_id":"e2b14e97-1d2a-46e7-8ba0-7e00858ced70"},"division":{"type":"AMBULANT_CLINIC","phones":[{"type":"MOBILE","number":"+380661669460"}],"name":"Новий","mountain_group":false,"legal_entity_id":"aa15a1f0-54a0-45b7-a777-5f7fb7d368d5","id":"e2b14e97-1d2a-46e7-8ba0-7e00858ced70","email":"kino@fff.ru","addresses":[{"type":"REGISTRATION","street_type":"STREET","street":"Перекопська","settlement_type":"CITY","settlement_id":"1241d1f9-ae81-4fe5-b614-f4f780a5acf0","settlement":"ХАРКІВ","country":"UA","building":"6","area":"ХАРКІВСЬКА"},{"type":"RESIDENCE","street_type":"STREET","street":"Перекопська","settlement_type":"CITY","settlement_id":"1241d1f9-ae81-4fe5-b614-f4f780a5acf0","settlement":"ХАРКІВ","country":"UA","building":"6","area":"ХАРКІВСЬКА"}]},"declaration_request_id":"a18dd64b-508b-45c0-849c-486f98e30e16"}}

**Comment by svetavedmed** [comment]
текcт декларации не возвращается на GET https://api.ehealth.world/api/declarations/id
только на GET https://api.ehealth.world/api/declaration_requests/id
