### ISSUE TITLE
Повертати ЕМаил в ендпоинтах GetEmployeesList та GetEmployeeDetails

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#237]
приклад: Лікарня зареєструвала себе в одному МІСі, а потім переходить в інший МІС. Щоб не перереєстровувати лікарів потрібно знати ЕМаіл.

**Comment by pieskov** [comment]
А можно ссылку на описение?

**Comment by kostikehealth** [comment]
@pieskov є загальнодоступна технічна документація, Ви про неї?
