### ISSUE TITLE
Malformed request. Probably, you have sent corrupted JSON

### ISSUE THREAD

**Issue by Olexandrit** [ehealth-ua/api-spec#239]
Добрий день! Відправляю запит з 1С на реєстрацію аптеки(https://api.ehealth.world/api/legal_entities).

У відповідь отримую:
{
    "type": "request_malformed",
    "message": "Malformed request. Probably, you have sent corrupted JSON.",
    "invalid": [
        {
            "entry_type": "request",
            "rules": [
                {
                    "rule": "json"
                }
            ]
        }
    ]
}

Якщо код згенерований в 1С вставити у програму postman, то запит виконається успішно...

Чи можете сказати що отримує сервер препрод на мій запит? Fiddler також мені не допоміг.
Реєстрація йшла на пошту itvisa1c@gmail.com. ДатаЧас відправлення запиту  20/02/2018 12:55...

**Comment by svetavedmed** [comment]
Добрый день. К сожлаению, мы не лоигруем post параметры.

**Comment by Olexandrit** [comment]
дякую.
