### ISSUE TITLE
Declaration sign (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#240]
Перевірте будь-ласка запит по підписанню декларацій, вчора все ок працювало , зараз повертає наступну помилку

## Request

- [ ] url: https://api.ehealth-ukraine.org/api/declaration_requests/ID_HERE/actions/sign

## Actual result
- [ ] {
  "meta": {
    "url": "http://api-svc.il/api/declaration_requests/ID_HERE/actions/sign",
    "type": "object",
    "request_id": "ee3eea17-d11c-47ce-a008-ec7538dd0e28#47681",
    "code": 400
  },
  "error": {
    "type": "request_malformed",
    "message": "matching TSP certificate not found",
    "invalid": [
      {
        "rules": [
          {
            "rule": "json"
          }
        ],
        "entry_type": "request"
      }
    ]
  }
}

## Expected result
- [ ] signed declaration

Якщо потрібно можу надати додаткові логи!

**Comment by vsmihaylovsky** [comment]
Такая же ошибка на препроде при изменении Legal Entity. Хотя вчера его создавал, файл был с такой же подписью.

**Comment by svetavedmed** [comment]
помилка пов'язана з тим, що оновили сертифікати АЦСК ДФС https://acskidd.gov.ua/news

**Comment by Charly3X** [comment]
Такая же ошибка.

**Comment by svetavedmed** [comment]
Ошибку исправили на проде
