### ISSUE TITLE
Проблема с ОТР-верификацией

### ISSUE THREAD

**Issue by mishenya** [ehealth-ua/api-spec#242]
Добрый день. Есть вопрос по смскам по верификации телефона (ОТР-верификация). Отправляем запрос, получаем ответ от сервера: {"meta":{"url":"http://api-svc.verification/verifications","type":"object","request_id":"5aad74f8-7e48-4576-b65e-9839d95d3021#5474","code":201},"data":{"status":"new","id":"4fa7e6dd-28b8-4680-92d8-de69c92d4009","code_expired_at":"2018-02-21T13:18:58.702961Z","active":true}} Но на номер телефона код не приходит. В чем может быть проблема? Как ее решить? Спасибо. (edited)

**Comment by lymychp** [comment]
смс відправляються тільки на препроді
