### ISSUE TITLE
Проблема с айдишками (изменяются со временем или сразу неверные)

### ISSUE THREAD

**Issue by mishenya** [ehealth-ua/api-spec#243]
При регистрации пользователя не совпадает ид который возвращается в респонсе, либо ид меняется со временем.

Как определили: сохранили локально ИД при регистрации легалэнтети, возвращает ИД овнера либо при регистрации эмплоера, либо со временем, либо сразу возвращает неверный ИД. когда выбираем список эмплоеров и в списке совсем другие ИД которые являются рабочими. Просьба помочь разобраться, в причине такой ошибки. Проблема на демо.

**Comment by lymychp** [comment]
надайте, будь ласка, приклад

**Comment by lymychp** [comment]
no feedback provided
