### ISSUE TITLE
Не могу перерегистрировать учреждение

### ISSUE THREAD

**Issue by mishenya** [ehealth-ua/api-spec#244]
Добрый день. Не могу перерегистрировать учреждение на демо. Выдает "matching ROOT certificate not found".
![default](https://user-images.githubusercontent.com/36700676/36538374-df04853c-17db-11e8-88be-2b8b7e49cc87.jpg)

**Comment by svetavedmed** [comment]
дубль от https://github.com/ehealth-ua/api-spec/issues/240
Исправлено
