### ISSUE TITLE
Declaration statistics on site

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#245]
*Not shown declaration counter*
url: https://portal.ehealth-ukraine.org/#statistic

![image](https://user-images.githubusercontent.com/24266717/36538688-0ead0d58-17dd-11e8-9fde-1570d6b2b642.png)
 

divisionRef:  4ceb2938-0428-4185-b462-e193d1c011df
In details location is :
"location": {
      "longitude": 24.1425,
      "latitude": 49.835
    }
On map also shown: 
![image](https://user-images.githubusercontent.com/24266717/36539018-0ca22740-17de-11e8-9a86-eb3835ff599d.png)

@lymychp few declaration guids sended private in slack which are addicted to that division

**Comment by svetavedmed** [comment]
fixed on prod
