### ISSUE TITLE
Ошибка подписания декларации на проде

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#247]
Возвращает вот такую ошибку

{
  "meta": {
    "url": "http://api-svc.il/api/declaration_requests/26b07bc1-3e17-44b4-9330-4eac808bb17b/actions/sign",
    "type": "object",
    "request_id": "82ab5ac1-2866-48e4-8309-dddc9b0e38a4#222735",
    "code": 400
  },
  "error": {
    "type": "request_malformed",
    "message": "matching ROOT certificate not found",
    "invalid": [
      {
        "rules": [
          {
            "rule": "json"
          }
        ],
        "entry_type": "request"
      }
    ]
  }
}

**Comment by lymychp** [comment]
Яким сертифікатом підписуєте?

**Comment by svetavedmed** [comment]
Исправлено на проде
