### ISSUE TITLE
Не створюється мед заклад з файлу, що підписується підписом АЦСК "Україна" 

### ISSUE THREAD

**Issue by evgenkai** [ehealth-ua/api-spec#248]
Доброго дня! Намаюсь вперше надіслати запит на стрворення медичного закладу на demo. Але нічого не виходить. Підписую JSON файл підписом АЦСК "Україна"  
        У відповідь маю "{\"meta\":{\"url\":\"http://api-svc.il/api/legal_entities\",\"type\":\"object\",\"request_id\":\"9909c2ae-2ecf-4b98-9690-83568ed1610c#615\",\"code\":400},\"error\":{\"type\":\"request_malformed\",\"message\":\"error processing signed data\",\"invalid\":[{\"rules\":[{\"rule\":\"json\"}],\"entry_type\":\"request\"}]}}"
        Зараз респонс також видає Headers    {Connection: keep-alive
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Kong-Proxy-Latency: 103
X-Kong-Upstream-Latency: 110
X-Ratelimit-Limit-Minute: 9000
X-Ratelimit-Remaining-Minute: 8999
X-Request-Id: 9909c2ae-2ecf-4b98-9690-83568ed1610c#615
X-Xss-Protection: 1; mode=block
CF-RAY: 3f6bc01ef4719c95-AMS
Cache-Control: must-revalidate, max-age=0, private
Date: Mon, 05 Mar 2018 10:03:03 GMT
Set-Cookie: __cfduid=da592a77e056cfa5b51ccd8b2b467ad611520244182; expires=Tue, 05-Mar-19 10:03:02 GMT; path=/; domain=.ehealth.world; HttpOnly
Server: cloudflare
Via: kong/0.12.1.

Дякую за співпрацю #
Вот уже подписанный файл. может в нем что-то не так... [https://www.dropbox.com/s/p22e8c0icshmjzn/reestrHospital.json.p7s?dl=0](url)

**Comment by lymychp** [comment]
прошу надати наступну інформацію
## Steps to Reproduce (Repro steps)
- [ ] endpoint address, environment
- [ ] test data, requests examples, json files, curl requests etc

**Comment by evgenkai** [comment]
підписаний json додав

**Comment by evgenkai** [comment]
Не знаю як видалити звідси запис... Все працює. розібрався.. Дякую за співпрацю.
