### ISSUE TITLE
Employee tax_id

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#249]
Доброго дня, можете прокоментувати на рахунок ІПН:
  
## Question
- [ ] який вигляд має бути у json структурі для реєстрації employee без ІПН, ставлю no_tax_id: true, але все-одно вимагає ввести ІПН, так як це обовязкове поле! (підказали, що -> насколько я помню в этом случае в поле IПН - серия и номер паспорта без пробела.)

## Actual result
- [ ] employee is registered
- [ ] testing declaration signing on demo, response result -> 

{"meta":{"url":"http://api-svc.il/api/declaration_requests/3e619797-894b-4e03-9f88-4593e5014e67/actions/sign","type":"object","request_id":"9909c2ae-2ecf-4b98-9690-83568ed1610c#647","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"invalid","params":[],"description":"Does not match the signer drfo"}],"entry_type":"json_data_property","entry":"$.token.consumer_id"}]}}

**Comment by lymychp** [comment]
Все правильно вам підказали. Все рівно не получається?

**Comment by superjonh** [comment]
@lymychp Лікаря дозволяє зареєструвати, тут все ОК, вирішив ще попробувати підписати декларацію на DEMO, там повертає описану вище ерору, не зовсім розумію в чому все-таки проблема, показує поле: $.token.consumer_id

**Comment by lymychp** [comment]
Рекомендую тестуватись на препроді. На демо середовищі може бути функціонал, якого немає на проді.

**Comment by superjonh** [comment]
Гаразд, тоді закриваю ісю.
