### ISSUE TITLE
Ошибка tax_id

### ISSUE THREAD

**Issue by vakafonic** [ehealth-ua/api-spec#250]
Пытаюсь подписать тестовые данные, процедура проходит успешно, едрпоу беру из сертификата, который совпадает с едрпоу при проверке по ссылке https://ca.informjust.ua/verify.

Согласно логике, описанной в [документации](https://edenlab.atlassian.net/wiki/spaces/EH/pages/1112394/IL.Create+Update+Legal+Entity#IL.Create/UpdateLegalEntity-ValidateTaxID)

> EDRPOU in Certificate details is equal to EDRPOU in Legal Entity payload

... что можно увидеть в json_request файлах и подписанных данных, но получаю ошибку tax_id invalid tax_id value. Почему?

Лог запрос\ответ\данные-сертификата [tests.zip](https://github.com/ehealth-ua/api-spec/files/1803856/tests.zip)

**Comment by svetavedmed** [comment]
ЕДРПОУ должен бытьтакой, как в вашем сертификате = 11111112
А ИНН owner должен быть таким, который бы прошел проверку, например на этом сайте - http://ur.biz.ua/ru/services/%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%B8%D0%BD%D0%BD-%D1%83%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0-%D0%BE%D0%BD%D0%BB%D0%B0%D0%B9%D0%BD
Возьмите к примеру свой.

**Comment by vakafonic** [comment]
@svetavedmed  спасибо, получилось с реальным ипн
Хотел бы получить ответ на следующий вопрос - если у меня ключ и физ и юр лица, в поле tax_id в любом случае идет ИПН?

**Comment by svetavedmed** [comment]
да, просто если бы у вас была настоящая подпись, то в ключе физ лица был бы ваш(или чей-то) ИНН и он бы проходил нашу проверку

**Comment by vakafonic** [comment]
@svetavedmed  Понял, Спасибо, issue можно закрывать.
