### ISSUE TITLE
Division search on site (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#251]
Доброго дня, подивіться будь-ласка до пошуку на порталі, стосується відділень. Для прикладу якщо вибрати Вінницю в пошуку, то показує тільки 4 відділення, хоча зареєстровано і відповідно на мапі їх більше.

## Steps to Reproduce (Repro steps)

- [ ] url: https://portal.ehealth-ukraine.org/divisions.html#/?settlement=%D0%92%D0%86%D0%9D%D0%9D%D0%98%D0%A6%D0%AF&area=%D0%92%D0%86%D0%9D%D0%9D%D0%98%D0%A6%D0%AC%D0%9A%D0%90&page=1

![image](https://user-images.githubusercontent.com/24266717/37453955-f512d196-2841-11e8-8464-324065f0ed74.png)

- [ ] actual result on map: 

![image](https://user-images.githubusercontent.com/24266717/37454068-37233b8e-2842-11e8-8e98-af8ef77dc1ad.png)

**Comment by svetavedmed** [comment]
is connected with #1877

**Comment by svetavedmed** [comment]
fixed on prod
