### ISSUE TITLE
Помилка при підтвердженні співробітника на https://denovo.ehealth.world/ 

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#252]
## Steps to Reproduce (Repro steps)

- [ ] https://denovo.ehealth.world/ 
- [ ]створюємо заявку на стіорення співробітника, на email отримуємо посилання https://auth.ehealth.world/invite?invite=NVFjZ3AwYVRqSHJPWU9TUmUlMkJsYzFwVnclMkJybklkUTF4bEp2UVIlMkZUUjRtTEtrSlRtUHZITmNJUnp0UUJIc1BLeQ==%D1%83
переходимо по мисиланню отримуємо помилку http://prntscr.com/irzd6w

## Actual result
- [ ] запрошення не знайдено

## Expected result
- [ ] запрошення знайдено

**Comment by svetavedmed** [comment]
fixed
