### ISSUE TITLE
Авторизация пользователя на прод

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#255]
При попытке входа в систему выдает ошибку, что неверный логин или пароль.

При детальном изучении вопроса было выявлено следующее.

Зарегистрировался пользователь с логином Test@gmail.com.
1. При входе в систему с логином test@gmail.com - вход проходит нормально.
2. При входе в систему с логином Test@gmail.com - ошибка, неверный логин или пароль.

**Comment by svetavedmed** [comment]
fixed on preprod, will be delivered to prod with the next release

**Comment by svetavedmed** [comment]
fixed on prod
