### ISSUE TITLE
Declaration sign (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#258]
Доброго дня, подивіться будь-ласка в чому проблема підписання декларації. Лікар був зареєстрований без ІПН, employee_id = "ffa5fab5-e6c3-41e7-86ae-7922cb98bd32"

## Signing declaration

- [ ] url: https://api.ehealth-ukraine.org/api/declaration_requests/{DECLARATION_REF_HERE}/actions/sign
- [ ] PATCH

## Actual result
- [ ] {
  "meta": {
    "url": "http://api-svc.il/api/declaration_requests/{DECLARATION_REF_HERE}/actions/sign",
    "type": "object",
    "request_id": "7be92435-514a-4cba-bdf8-70b7d8f89f88#609120",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": "invalid",
            "params": [
              
            ],
            "description": "Does not match the signer drfo"
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.content.employee.party.tax_id"
      }
    ]
  }
}

## Expected result
- [ ] signed responce

Якщо потрібні логи запиту надішлю в пп.

**Comment by svetavedmed** [comment]
Дело в том, что она действительно заведена у нас без ИНН (tax_id=ВА305754), однако в подписи у нее есть ИНН ( “drfo”: “1858010407")
