### ISSUE TITLE
Перевод сотрудника в другое подразделение.

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#259]
1. При смене подразделения сотрудника(в данных ничего не менялось) переходя по ссылке мы видим подразделения пользователя. Можно ли добавить эту информацию?
2. Можно ли, каким либо образом, удалить принадлежность сотрудника к подразделению?

**Comment by lymychp** [comment]
1. Змінити підрозділ можна через  employee_request, передавши на вхід `employee_id`
2. проапдейтити в null
