### ISSUE TITLE
валідація наданих кведів

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#26]
## Steps to Reproduce (Repro steps)

- [*] endpoint address: 
http://demo.ehealth.world/api/legal_entities

- [*] preconditions if any: 
new clinic registration or updating existing LE

- [* ] sequence of actions that should be taken to reproduce the behavior.
register LE with a list of KVEDs,  where one of the KVEDs is not in allowed KVEDs list

- [*] test data, requests examples, json files, curl requests etc
[test_le.json.txt](https://github.com/ehealth-ua/api-spec/files/1068018/test_le.json.txt)

## Actual result
Validation error, HTTP/422, because 86.90 is not in the list of allowed KVEDs

## Expected result
- [* ] description of the expected system behavior.

Kved validation must be less strict.  Instead of checking that all KVEDs are allowed to be reststered, system should check that AT LEAST ONE of the KVEDs is allowed for registration

**Comment by pzhuk** [comment]
Expected result has been confirmed with PM and PO in general

**Comment by AlekzandrV** [comment]
@pzhuk @IrynaShevch 
Provide please:
1. LIST of the KVEDs allowed for registration
2. LIST or RULES for KVED validation (КВЕД-2010, КВЕД-2012, КВЕД-2013, КВЕД-2014, КВЕД-2015, КВЕД-2017?)

**Comment by pzhuk** [comment]
Closing this, because issue is tracked as change request out of operations issue tracker
