### ISSUE TITLE
Валидация емеила при входе в кабинет eHealth [prod]

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#260]
АПИ пропустило, а в кабинет не дает зайти

https://drive.google.com/file/d/1xoDC-gxyxjFnDSQxHK8FaUY7rDv_zSS4/view?usp=sharing

**Comment by svetavedmed** [comment]
fixed on preprod, will be delivered to prod with the next release

**Comment by svetavedmed** [comment]
Данный email валидный, ошибку воспроизвести не удается. Возможно сотрудник ввел некоторые буквы кирилицей. Может ли сотрудник проверить еще раз?

**Comment by svetavedmed** [comment]
@Charly3X скажите, пожалуйста, повторилась ли ошибка?
