### ISSUE TITLE
Подтверждение регистрации клиники (PROD)

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#261]
При регистрации клиники пользователь получил e-mail от e Health для подтверждения клиники и переходит по ссылке в нём.

## Steps to Reproduce (Repro steps)

- [ ] Отправить подписанные данные клиники и в реестр и получить e-mail для подтверждения регистрации
- [ ] Перейти по ссылке в e-mail

## Actual result
- [ ] 
![image](https://user-images.githubusercontent.com/20535372/37827074-a01ed456-2e9e-11e8-97eb-c580a309e006.png)
![image](https://user-images.githubusercontent.com/20535372/37827084-adbd07f4-2e9e-11e8-87e2-9b9a12c45ae1.png)

## Expected result
- [ ] Успешное подтверждение

## Additional information
Аналогичная проблема периодически возникает при подтверждении регистрации врачей.

**Comment by svetavedmed** [comment]
Выглядит так, что в первом случвае вы отправляете повторно accept на invite. А во втором, вы поличили access_token для другого польтзователя. 
Можете все перепроверить, пожалуйта.
И если повторится, хотелось бы больше данных по запросам и ответам)

**Comment by svetavedmed** [comment]
@cshevchukod Скажите, удалось ли решить проблему?

**Comment by cshevchukod** [comment]
Проверили... Проблема всё ещё возникает.

**Comment by lymychp** [comment]
@cshevchukod any updates?

**Comment by cshevchukod** [comment]
Вот что получили недавно при регистрации клиники.
Со слов: Ранее регистрировались в одной из МИС, теперь хотят перерегистрироваться у нас и продолжить работу.

`{"owner":{"gender":"FEMALE","phones":[{"type":"MOBILE","number":"+380508044384"}],"documents":[{"type":"PASSPORT","number":"АС 126845"}],"last_name":"Лєщинська","first_name":"Оксана","second_name":"Петрівна","position":"P3","birth_date":"1970-12-10","tax_id":"2591107846","email":"kzdp.lutsk@gmail.com","birth_place":"Луцьк, Україна"},"medical_service_provider":{"accreditation":{"category":"HIGHEST","order_no":"02/6","issued_date":"2015-12-15","order_date":"2015-06-05","expiry_date":"2018-06-05"},"licenses":[{"license_number":"459668","order_no":"342","issued_date":"2014-05-21","active_from_date":"2014-05-21","what_licensed":"Медична практика","issued_by":"Міністерство охорони здоров'я України"}]},"addresses":[{"settlement":"ЛУЦЬК","settlement_type":"CITY","settlement_id":"2029f5e9-0682-4ecf-b4c3-605a9ef800ca","street_type":"STREET","street":"Вячеслава Чорновола","building":"1","zip":"43024","type":"REGISTRATION","apartment":"0","country":"UA","area":"ВОЛИНСЬКА"}],"phones":[{"type":"LAND_LINE","number":"+380332716976"}],"kveds":["86.21"],"edrpou":"04543022","name":"КОМУНАЛЬНИЙ ЗАКЛАД \"ЛУЦЬКА МІСЬКА ДИТЯЧА ПОЛІКЛІНІКА\"","short_name":"КЗ ЛМДП","legal_form":"430","public_name":"ЛУЦЬКА МІСЬКА ДИТЯЧА ПОЛІКЛІНІКА","email":"kzdp.lutsk@gmail.com","owner_property_type":"STATE","type":"MSP","security":{"redirect_uri":"https://newmedicine.com.ua"},"public_offer":{"consent":true,"consent_text":"Відповідно до Закону України “Про захист персональних даних” з метою ведення реєстрів електронної системи охорони здоров’я та забезпечення її функціонування у дослідній експлуатації надаю згоду обраному оператору та адміністратору електронної системи охорони здоров’я на обробку моїх персональних даних з первинних джерел, а також на здійснення дій пов’язаних зі збиранням, реєстрацією, накопиченням, зберіганням, адаптуванням, зміною, поновленням, використанням, поширенням, розповсюдженням, реалізацією, передачею, знеособленням, знищенням будь-яких відомостей. Додатково надаю згоду на доступ до моїх персональних даних уповноважених третіх осіб, що визначає дії оператора МІС та адміністратора у разі отримання запиту від уповноваженої третьої особи щодо надання доступу до персональних даних. Підтверджую достовірність вказаних мною даних та добровільність надання цих даних до електронної системи охорони здоров’я, що працює у дослідній експлуатації. Усвідомлюю, що у випадку надання мною невірної інформації, мені може бути відмовлено в реєстрації в електронній системі охорони здоров’я. Зобов’язуюсь дотримуватись Регламенту функціонуваня електронної системи охорони здоров’я."}}`

Ссылка по которой переходят (из письма):
 https://auth.ehealth-ukraine.org/invite?invite=aTFUUSUyRnREMVM4aHhXU0paSXdkN0glMkZtbVJlcUYlMkY3V1lYdkhwcDdtd1pYaGRtd1djalVuUHRtbFpTb0xHbkp3TQ==
Далее вводят логин и пароль руководителя, и попадают на страницу на скриншоте:
![error](https://user-images.githubusercontent.com/20535372/38392521-7678bf80-3930-11e8-89ab-9934b9103b69.jpg)

**Comment by svetavedmed** [comment]
вы не передаете client_id

**Comment by cshevchukod** [comment]
Указывали client_id, просто тут не видно его. В ближайшее время отправлю весь запрос в base64.

**Comment by svetavedmed** [comment]
Зарегистрирована ли клиника?
