### ISSUE TITLE
помилка при підписанні декларації. майданчик ДеНово

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#262]
## Steps to Reproduce (Repro steps)

- [ ] https://api.ehealth.world/api/declaration_requests/e6842de6-3dbf-4fbd-8bc9-f8865cab0f75/actions/sign
- [ ] створили declaration_requests, успішно верифікували його - "request_id":"3670099c-f231-4d23-b000-03f0f6bb3bf9#2"
- [ ] запит 
[declaration_sign.txt](https://github.com/ehealth-ua/api-spec/files/1841862/declaration_sign.txt)

## Actual result
- [ ]  ``` "body" : {
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests/e6842de6-3dbf-4fbd-8bc9-f8865cab0f75/actions/sign",
                    "type" : "object",
                    "request_id" : "3670099c-f231-4d23-b000-03f0f6bb3bf9#23",
                    "code" : 422
                },
                "error" : {
                    "type" : "validation_failed",
                    "message" : "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
                    "invalid" : [ 
                        {
                            "rules" : [ 
                                {
                                    "rule" : "invalid",
                                    "params" : [],
                                    "description" : "incorrect status"
                                }
                            ],
                            "entry_type" : "json_data_property",
                            "entry" : "$.status"
                        }
                    ]
                }
            }```
## Expected result
- [ ] декларація створена

**Comment by svetavedmed** [comment]
Ошибка исправлена.
