### ISSUE TITLE
Помилка при resend_otp

### ISSUE THREAD

**Issue by oshklyarova** [ehealth-ua/api-spec#266]
[416854_Full.txt](https://github.com/ehealth-ua/api-spec/files/1847476/416854_Full.txt)
Steps to Reproduce (Repro steps)
POST /api/declaration_requests/a6b73e77-fd23-4d73-8b71-b0971b15ac00/actions/resend_otp

Actual result
{"meta":{"url":"http://api-svc.il/api/declaration_requests/a6b73e77-fd23-4d73-8b71-b0971b15ac00/actions/resend_otp","type":"object","request_id":"48cf83b2-56e9-456a-addf-e346e2d5151e#5912","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"invalid","params":[],"description":"Auth method is not OTP"}],"entry_type":"json_data_property","entry":"$.authentication_method_current"}]}}

Expected result
 смс відправлено

**Comment by lymychp** [comment]
@oshklyarova на якому середовищі проявляється?

**Comment by oshklyarova** [comment]
на препроді

**Comment by svetavedmed** [comment]
Это первая декларация данного человека, и authentication_method_current = NA. 
Отправка OTP на declaration_requests - это подтверждение изменения данных по пациенту. Ваш пациент не только не найден в базе, но еще и не создан, поэтому нет изменений, которые необходимо было бы подтвердить.

**Comment by oshklyarova** [comment]
Подскажите пожалуйста, что нужно сделать для того чтобы пациент был создан? недостаточно отправить его данные при Create Declaration Request?

**Comment by lymychp** [comment]
@oshklyarova основна ідея в тому, що `authorization_type` для конкретної декларації визначається автоматично системою на основі того, що проходить в payload і даних в реєстрі.
