### ISSUE TITLE
Фільтрація по ПІБ пацієнта в GET /api/declarations

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#269]
Прохання додати фільтрацію по ПІБ пацієнта в GET /api/declarations, потрібно для зручнішої роботи з списком декларацій.

**Comment by ioleksiy** [comment]
Якщо по протокулу безпеки питань немає - ми апрувимо задачу.

**Comment by lymychp** [comment]
Будуть питання по продуктивності. Плюс є окремий ендпойнт пошуку поцієнтів, можна по ПІБ

**Comment by ioleksiy** [comment]
@sreva, в цілях безпеки, використовується алгоритм, при якому пошук ведеться тільки по даним які є у того, хто шукає. це прийнята практика для подібних систем. Інакше, можна "подивитися" всіх по прізвищу.

з приводу продуктивності - ми її відносимо до питання технічної безпеки та стабільності ЦБД, тому поки вимушені відкласти цю задачу.

можливо, ви можете запропонувати функціонал, який вам підійде, і що не використовує повнотекстовий пошук?

дякую.

**Comment by Trickstersmind** [comment]
@ioleksiy, ми пропонуємо зробити більш зручний пошук тільки по деклараціям, що заключені із даним лікарем - пошук по своїм деклараціям.
Лікар у будь якому випадку має доступ до цих декларацій через список.
Але пошук потрібної через наявні єдпоїнти (список, без можливості фільтрувати, та пошук за чотирма обов'яковими полями) не зручний.

**Comment by ioleksiy** [comment]
Ви можете доповнювати пошук на своїй стороні. Пошук на стороні ЦБД проблемний, коли у справу вступає функція LIKE
