### ISSUE TITLE
Search Regions / List Of Regions By Search Params PROBLEM

### ISSUE THREAD

**Issue by dmmat** [ehealth-ua/api-spec#27]
I try to get all regions by this endpoint address `http://demo.ehealth.world/api/uaddresses/regions`

but I get the error:
```

{  
   "meta":{  
      "url":"http://api-svc.uaddresses/regions",
      "type":"object",
      "request_id":"tgb0bq3tiio156ceed2p6gahrdn04qfg",
      "code":404
   },
   "error":{  
      "type":"not_found"
   }
}

```

but it worked before
PLESE FIX THIS!!!!!!!!!

**Comment by ytrrty** [comment]
@AlekzandrV When will it work? Our registration form is broken while this error exists.

**Comment by pzhuk** [comment]
there's an ongoing dictionaries update, should be updated in 1 hour

**Comment by AlekzandrV** [comment]
We've fixed this problem:

**Try this:**
Get regions: 
```
curl http://demo.ehealth.world/api/uaddresses/search/regions
```
Get districts by region: 
```
curl 'http://demo.ehealth.world/api/uaddresses/search/districts?region=%D0%92%D0%BE%D0%BB%D0%B8%D0%BD%D1%81%D1%8C%D0%BA%D0%B0'
```
Search settlement: 
```
curl 'http://demo.ehealth.world/api/uaddresses/search/settlements?settlement_name=%D0%91%D0%BB%D0%B0%D0%B3%D0%BE%D0%B4%D0%B0%D1%82%D0%BD%D0%B5&region=%D0%92%D0%BE%D0%BB%D0%B8%D0%BD%D1%81%D1%8C%D0%BA%D0%B0'
```

**Comment by AlekzandrV** [comment]
I'll update apiary spec ASAP

**Comment by pieskov** [comment]
Будет ли теперь в структуре адреса  cuntry_id, region_id, area_id?

**Comment by ytrrty** [comment]
@AlekzandrV 
також не повертаються назви районів обласних центрів
тобто, якщо робити запит на 
`http://demo.ehealth.world/api/uaddresses/search/districts?region=ЛЬВІВСЬКА`
львівський район не повертається, відповідно не можна далі обрати місто Львів

**Comment by AlekzandrV** [comment]
Районы есть - их можно получить несколькими способами.
Тот, насколько я понял, который пытаетесь использовать Вы (по ИД) имеет другую структуру

```
curl 'http://demo.ehealth.world/api/uaddresses/details/region/b392aad2-988b-4452-851c-766d48fc94c6/districts?limit=30'
```

Детали конкретного района:
```
curl 'http://demo.ehealth.world/api/uaddresses/districts/9b0f8a14-09c1-4a9c-b9d7-d0cf3bb6b04a'
```
В объектах каждого уровня есть ИД объекта, к которому они относятся. За исключением страны. Тут только Украина

**Comment by AlekzandrV** [comment]
@ytrrty 
что касается Вашего запроса, то Львовский район не возвращается, так как его нет в структуре [КОАТУУ](http://dovidnyk.in.ua/directories).
А что касается самих областных центров и того, как их искать, через поисковый запрос по области
```
curl 'http://demo.ehealth.world/api/uaddresses/search/settlements?region=%D0%9B%D1%8C%D0%B2%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B0&settlement_name=%D0%9B%D1%8C%D0%B2%D1%96%D0%B2'
```
[Тут](http://docs.ehealthmisapi.apiary.io/#reference/0/uadresses/list-of-regions-by-search-params) можно посмотреть спецификацию сервисов

**Comment by pieskov** [comment]
Как выбрать все нас. пункты в region?

**Comment by AlekzandrV** [comment]
Предполагается, что населенные пункты ищутся поисковым запросом. Можете привести use case, где необходимо получение ВСЕХ населенных пунктов области?

**Comment by pieskov** [comment]
1. Запрос такого типа http://demo.ehealth.world/api/uaddresses/search/settlements?region=ЛЬВІВСЬКА&limit=10000 может усечь кол-во элементов нас. пунктами у которых "district": null.
2. http://demo.ehealth.world/api/uaddresses/search/settlements?region=ЛЬВІВСЬКА&district=СОКАЛЬСЬКИЙ&settlement_name=ЛЬВІВ - возвращает нас. пункты с привязкой к области и району.
http://demo.ehealth.world/api/uaddresses/search/settlements?region=ЛЬВІВСЬКА&settlement_name=ЛЬВІВ - возвращает нас. пункты с привязкой к области и району и **только к области**. Но это логически неправильно. Если я не указал район, то и хочу получить нас. пункты области.
3. Пользователю будет легче выбрать нас. пункт из списка, чем проводить манипуляции с поиском

**Comment by pieskov** [comment]
Какой будет структура адреса в JSON для г.Киева и как отличить программно, что мы выбрали М.КИІВ, а не "ЛЬВІВСЬКА". Надо признак что это город, не область.

`{"type": "REGISTRATION", 
				 "country": "UA", 
				 "area": "ДАРНИЦЬКИЙ", 
				 "region": "М.КИЇВ", 
				 "settlement": "??? - что тут", 
				 "settlement_type": "??? - что тут", 
				 "settlement_id": "??? - что тут", 
				 "street_type": "STREET", 
				 "street": "Дахнівська", 
				 "building": "34"}`

**Comment by AlekzandrV** [comment]
@pieskov 
Структура для Киева и Севастополя, такая же как и для городов

Request:
```
curl 'http://demo.ehealth.world/api/uaddresses/search/settlements?region=%D0%BC.%D0%BA%D0%B8%D1%97%D0%B2&settlement_name=%D0%BA%D0%B8%D1%97%D0%B2'
```

Response:
```
{
  "paging": {
    "size": null,
    "limit": 10,
    "has_more": false,
    "cursors": {
      "starting_after": "adaa4abf-f530-461c-bcbf-a0ac210d955b",
      "ending_before": null
    }
  },
  "meta": {
    "url": "http://api-svc.uaddresses/search/settlements",
    "type": "list",
    "request_id": "97138sv009nvf1t16qf9aef833d5fr85",
    "code": 200
  },
  "data": [
    {
      "type": "CITY",
      "settlement_name": "КИЇВ",
      "region": "М.КИЇВ",
      "parent_settlement": null,
      "mountain_group": "false",
      "koatuu": "8000000000",
      "id": "adaa4abf-f530-461c-bcbf-a0ac210d955b",
      "district": null
    }
  ]
}
```

**Comment by pieskov** [comment]
Как можно было закрыть вопрос не ответив на него?

2. http://demo.ehealth.world/api/uaddresses/search/settlements?region=ЛЬВІВСЬКА&district=СОКАЛЬСЬКИЙ&settlement_name=ЛЬВІВ - возвращает нас. пункты с привязкой к области и району.
http://demo.ehealth.world/api/uaddresses/search/settlements?region=ЛЬВІВСЬКА&settlement_name=ЛЬВІВ - возвращает нас. пункты с привязкой к области и району и только к области. Но это логически неправильно. Если я не указал район, то и хочу получить нас. пункты области.

**Comment by AlekzandrV** [comment]
@pieskov Создайте для этого отдельный тикет и опишите потребность.
Спасибо!

**Comment by AlekzandrV** [comment]
Что касается поиска населенных пунктов - то все query params уточняют или ужесточают поиск. Но не управляют логикой.
Все н.п. привязанные к области а не к области - можно найти поисковым запросом где `"district":null`
