### ISSUE TITLE
Скоуп declaration_request:reject в DOCTOR

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#270]
Прохання повернути співробітнику з типом DOCTOR скоуп declaration_request:reject

**Comment by svetavedmed** [comment]
скоуп declaration_request:reject есть у Admin и Owner только

**Comment by sreva** [comment]
Раніше був і у DOCTOR, тепер же лякарю щоб відмінити declaration_request потрібно звертатись до реєстратора чи керівника МСП

**Comment by superjonh** [comment]
Можете якось попередньо інформувати про зміни скоупів, в слаку чи на гітхабі, було б зручно моніторити

**Comment by sreva** [comment]
Надходили скарги від лікарів по цьому питанню, дуже просять повернути їм дану функцію
