### ISSUE TITLE
Employee approve email (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#271]
===Доброго дня, подивіться будь-ласка чи все в порядку з розсилкою запрошень, не приходять листи, домен зновштаки ukr.net , але для прикладу не прийшов лист на оновлення існуючого працівника, де вже була така пошта! ====  
  

## Post Request https://api.ehealth-ukraine.org/api/employee_requests
- [ ] employee body and headers

## Actual result code 200
- [ ]    "meta": {
    "url": "http://api-svc.il/api/employee_requests",
    "type": "object",
    "request_id": "76ea2f42-a207-4038-9376-17ab6560e377#784632",
    "code": 200
  },

"meta": {
    "url": "http://api-svc.il/api/employee_requests",
    "type": "object",
    "request_id": "a59ac1de-7493-42a1-946e-6bddbce6ad70#122250",
    "code": 200
  },

- [ ] mail was not received

## Expected result
- [ ] verification mail.

**Comment by superjonh** [comment]
Можете добавити ендпоінт, щоб мати змогу перевірити чи мейл заблокований, чи ні?? Або іншу альтернативу, бо так не можливо дізнатись чому запрошення в окремих випадках не приходять, респонс вертає код 200.

**Comment by lymychp** [comment]
@superjonh напишіть плз user email  в ЛС

**Comment by superjonh** [comment]
@lymychp Вже помоєму вирішили дане питання, наразі проблем з доставкою листів не спостерігав!
