### ISSUE TITLE
Какая процедура получения данных рецепта по номеру рецепта?

### ISSUE THREAD

**Issue by Olexandrit** [ehealth-ua/api-spec#272]
Здраствуйте! 
1. Каким образом можна получить данные рецепта по номеру? В док. https://ehealthmisapi1.docs.apiary.io/#reference/public.-reimbursement/medication-request/get-drugs-list есть только по ИД.
2. Есть скоуп drugs:read. Разрешите пожалуйста для PHARMACY_OWNER и PHARMACIST. Для фарм. фильтры по номенклатуре имеет важное значение.

**Comment by Olexandrit** [comment]
Я так понимаю вотетой функцией можна получить рецепт по номеру рецепта
/api/medication_requests?legal_entity_id=d290f1ee-6c54-4b01-90e6-d701748f0851&employee_id=7124259c-eeb1-4cbb-acac-ada2162675d1&person_id=d290f1ee-6c54-4b01-90e6-d701748f0851&status=ACTIVE&request_number=0000-243P-1X53-EH38&created_from=2017-08-17&created_to=2017-08-30&medication_id=b075f148-7f93-4fc2-b2ec-2d81b19a9b5b&page=2&page_size=50

**Comment by ioleksiy** [comment]
Чи актуальне ще питання?

**Comment by Olexandrit** [comment]
Так

**Comment by svetavedmed** [comment]
1. fixed on dev

**Comment by svetavedmed** [comment]
done on demo
