### ISSUE TITLE
Employee tax_id (question)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#273]
*Доброго дня, настільки я розумію, поміняти поле tax_id існуючого працівника не передбачено системою, так як повертає наступну помилку 'tax_id doesnt match'??

## Post request to update employee
- [ ] employee data and headers

## Actual result
- [ ] {"meta":{"url":"http://api-svc.il/api/employee_requests","type":"object","request_id":"3a42ab4f-2177-4635-94b7-4290723b020c#26108","code":409},"error":{"type":"request_conflict","message":"tax_id doesn't match"}}

**Comment by lymychp** [comment]
абсолютно вірно, і дату народження також не можна міняти

**Comment by superjonh** [comment]
Дякую!
