### ISSUE TITLE
Смена типа населенного пункта

### ISSUE THREAD

**Issue by Hamiltone** [ehealth-ua/api-spec#276]
http://zakon0.rada.gov.ua/laws/show/2185-19 
Согласно этой постанове, прошу изменить тип населенного пункта.
## Actual result
-   "type" : "TOWNSHIP",
    "region" : "ПОЛТАВСЬКА",
     "name" : "РЕШЕТИЛІВКА",
     "district" : "РЕШЕТИЛІВСЬКИЙ",

## Expected result
-    "type" : "CITY",
     "region" : "ПОЛТАВСЬКА",
     "name" : "РЕШЕТИЛІВКА",
     "district" : "РЕШЕТИЛІВСЬКИЙ",.

**Comment by svetavedmed** [comment]
fixed on dev

**Comment by lymychp** [comment]
delivered to prod
