### ISSUE TITLE
Statistic on portal

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#278]
===Доброго дня, подивіться будь-ласка до статистики декларацій, цікавить Закарпатська область , ,буквально вчора було 20тис.+ декларацій, зараз біля 12тис., такі зміни взагалі реальні? ====  
  
## Steps to Reproduce (Repro steps)
- [ ] endpoint address: https://portal.ehealth-ukraine.org/#statistic

![image](https://user-images.githubusercontent.com/24266717/38078257-5c50432c-3344-11e8-974b-2b1a27e73101.png)

**Comment by lymychp** [comment]
такі зміни малоймовірні. Ви впевнені, що вчора було 20+ тисяч?

**Comment by superjonh** [comment]
@lymychp так, можу надати ідентифікатори підписаних декларацій, якщо потрібно!

**Comment by lymychp** [comment]
20+ тисяч ІД? Я маю на увазі будь-які докази, що на сайті була вказана цифра 20+ тисяч?

**Comment by superjonh** [comment]
@lymychp Скріна за вчора немаю, але їх явно було біля 20, зараз ще перевірю через постмен.

**Comment by superjonh** [comment]
@lymychp  

url: https://api.ehealth-ukraine.org/api/declarations

response: 

 "paging": {
        "total_pages": 415,
        "total_entries": 20740,
        "page_size": 50,
        "page_number": 1
    },
    "meta": {
        "url": "http://api-svc.il/api/declarations",
        "type": "list",
        "request_id": "f919bc7f-fc89-4ae9-a5bd-540d4d78f214#31962",
        "code": 200
    },

**Comment by lymychp** [comment]
Тут можуть бути як неактивні декларації, так і декларації різних підрозділів з різними адресами. Напишіть плз в ЛС від імені якого користувача викликається запит?

**Comment by superjonh** [comment]
@lymychp Відписав в слаку!

**Comment by lymychp** [comment]
fixed on preprod, will be delivered to prod with the next release

**Comment by lymychp** [comment]
delivered to prod
