### ISSUE TITLE
тест2 /api/legal_entities накладання ЕЦП і відправка Статус http 422 замість 200

### ISSUE THREAD

**Issue by romanm** [ehealth-ua/api-spec#28]
Статус http 422 замість 200 при передачі даних підготовлених в medic.algoritmed.com .
-----------------
issue здубльований https://github.com/romanm/algoritmed-mvp1-ehealth/issues/4
Данні збережених як файл registry_MSP_157.json, підписаних ЕЦП Key-6.dat з тестових даних за допомогою http://czo.gov.ua/sign (результатативний фай registry_MSP_157.json.p7s), закодований base64, base64 стрічка запакована в відповідний формат і відправлена HttpClient PUT http://demo.ehealth.world/api/legal_entities .

## Actual result
- [https://github.com/romanm/algoritmed-mvp1-ehealth/blob/master/src/main/resources/test2_api__legal_entities/registry_MSP_157_response.json ] response example (*.json file)

## Steps to Reproduce (Repro steps)

Папка з файлами даних https://github.com/romanm/algoritmed-mvp1-ehealth/tree/master/src/main/resources/test2_api__legal_entities
від первинних даних 
https://github.com/romanm/algoritmed-mvp1-ehealth/blob/master/src/main/resources/test2_api__legal_entities/registry_MSP_157.json
до https://github.com/romanm/algoritmed-mvp1-ehealth/blob/master/src/main/resources/test2_api__legal_entities/registry_MSP_157_response.json .

Тестовий сервер з вказаним випадком:
http://medic.algoritmed.com/v/testMvpMedic?doc_id=157
Передача p7s даних кліент бровзер
https://github.com/romanm/algoritmed-mvp1-ehealth/blob/master/src/main/resources/static/f/mvp1/medic/msp/msp_registry_data_digitalsign.html#L31
Прийом p7s даних сервер
https://github.com/romanm/algoritmed-mvp1-ehealth/blob/master/src/main/java/org/algoritmed/mvp1/medic/EhealthUaRegistryFileUploadRest.java#L20
Кодування base64
https://github.com/romanm/algoritmed-mvp1-ehealth/blob/master/src/main/java/org/algoritmed/mvp1/medic/EhealthUaRegistryFileUploadRest.java#L25
Підготовка request контайнера поетапно:
https://github.com/romanm/algoritmed-mvp1-ehealth/blob/master/src/main/java/org/algoritmed/mvp1/medic/EhealthUaRegistryFileUploadRest.java#L29
https://github.com/romanm/algoritmed-mvp1-ehealth/blob/master/src/main/java/org/algoritmed/mvp1/util/EhealthUaRegistryWebClient.java#L25

## Expected result
- [ ] description of the expected system behavior.

**Comment by pieskov** [comment]
Структура JSON не соответствует заявленной в документации. 
Вот это лишнее, возможно из за этого и возникает ошибка:
`"doctype": 12,
	"doc_id": 157,
	"parent_id": 157,
	"created": 1497077049611,
	"docbody_id": 157,
"updated": 1497077049611`

**Comment by DPashchenko** [comment]
@romanm доброго времени суток!
Проверьте сериализацию JSON'а.
Данные которые вы подписываете выглядят следующим образом:
`\ufeff{\n\t\"name\": \"Hello World! - Клініка Адоніс 123\",\n\t\"short_name\": \"Адоніс\",\n\t\"public_name\": \"Адоніс\",\n\t\"type\": \"MSP\",\n\t\"owner_property_type\": \"STATE\",\n\t\"legal_form\": \"140\",\n\t\"edrpou\": \"1560503515\",\n\t\"kveds\": [\n\t\t\"86.10\"\n\t],\n\t\"addresses\": [\n\t\t{\n\t\t\t\"type\": \"RESIDENCE\",\n\t\t\t\"country\": \"UA\",\n\t\t\t\"area\": \"Житомирська\",\n\t\t\t\"region\": \"Бердичівський\",\n\t\t\t\"settlement\": \"Київ\",\n\t\t\t\"settlement_type\": \"CITY\",\n\t\t\t\"settlement_id\": \"43432432\",\n\t\t\t\"street_type\": \"STREET\",\n\t\t\t\"street\": \"вул. Ніжинська\",\n\t\t\t\"building\": \"15\",\n\t\t\t\"apartment\": \"23\",\n\t\t\t\"zip\": \"02090\"\n\t\t}\n\t],\n\t\"phones\": [\n\t\t{\n\t\t\t\"type\": \"MOBILE\",\n\t\t\t\"number\": \"+380503410870\"\n\t\t}\n\t],\n\t\"email\": \"m.miliaieva@gmail.com\",\n\t\"owner\": {\n\t\t\"first_name\": \"Петро\",\n\t\t\"last_name\": \"Іванов\",\n\t\t\"second_name\": \"Миколайович\",\n\t\t\"tax_id\": \"3015492565\",\n\t\t\"birth_date\": \"1991-08-19\",\n\t\t\"birth_place\": \"Вінниця, Україна\",\n\t\t\"gender\": \"MALE\",\n\t\t\"email\": \"m.miliaieva@gmail.com\",\n\t\t\"documents\": [\n\t\t\t{\n\t\t\t\t\"type\": \"PASSPORT\",\n\t\t\t\t\"number\": \"120518\"\n\t\t\t}\n\t\t],\n\t\t\"phones\": [\n\t\t\t{\n\t\t\t\t\"type\": \"MOBILE\",\n\t\t\t\t\"number\": \"+380503410870\"\n\t\t\t}\n\t\t],\n\t\t\"position\": \"Голова правління\"\n\t},\n\t\"medical_service_provider\": {\n\t\t\"licenses\": [\n\t\t\t{\n\t\t\t\t\"license_number\": \"fd123443\",\n\t\t\t\t\"issued_by\": \"Кваліфікацйна комісія\",\n\t\t\t\t\"issued_date\": \"1991-08-19\",\n\t\t\t\t\"expiry_date\": \"1991-08-19\",\n\t\t\t\t\"kved\": \"86.10\",\n\t\t\t\t\"what_licensed\": \"реалізація наркотичних засобів\"\n\t\t\t}\n\t\t],\n\t\t\"accreditation\": {\n\t\t\t\"category\": \"FIRST\",\n\t\t\t\"issued_date\": \"1991-08-19\",\n\t\t\t\"expiry_date\": \"1991-08-19\",\n\t\t\t\"order_no\": \"fd123443\",\n\t\t\t\"order_date\": \"1991-08-19\"\n\t\t}\n\t},\n\t\"security\": {\n\t\t\"redirect_uri\": \"redirect_uri\"\n\t},\n\t\"public_offer\": {\n\t\t\"consent\": true,\n\t\t\"consent_text\": \"Consent text\"\n\t},\n\t\"doctype\": 12,\n\t\"doc_id\": 157,\n\t\"parent_id\": 157,\n\t\"created\": 1497077049611,\n\t\"docbody_id\": 157,\n\t\"updated\": 1497077049611\n}`
Переносы и табуляция скорей всего пройдут, но как минимум `\ufeff` необходимо убрать.
http://www.charbase.com/feff-unicode-zero-width-no-break-space

**Comment by romanm** [comment]
Дійсно символ  \ufeff був винний, який створювався FileSaver.saveAs . 
Можна обійтись і без нього 
			var a = document.createElement("a");
			document.body.appendChild(a);
			a.style = "display: none";
			a.download = this.registryMspFileName();
			var dataJson = $scope.api__legal_entities;
			['doc_id','doctype','parent_id','created','docbody_id','updated'].forEach(function(k){
				delete dataJson[k]
			});
			var json = JSON.stringify(dataJson),
				blob = new Blob([json], {type: "octet/stream"}),
			url = window.URL.createObjectURL(blob);
			a.href = url;
			a.click();
			window.URL.revokeObjectURL(url);

Дякую всім за допомогу.
