### ISSUE TITLE
Invalid_user (type)

### ISSUE THREAD

**Issue by ndoctor** [ehealth-ua/api-spec#280]
Пользователь не может пройти подтверждение

employee_request: bf3b3131-eabb-43ea-9bc9-fcadcfa8df82

![viber image](https://user-images.githubusercontent.com/37897104/38079376-64e84afe-3347-11e8-86e0-a8920a0b47ba.jpg)

**Comment by lymychp** [comment]
Судячи зі скріншоту користувач намагається залогінитись, а не прийняти запрошення на приєднання. Тому відповідь коректна. Поки користувач не прийме запрошення, він не зможе залогінитись

**Comment by superjonh** [comment]
@lymychp Є ще два кейси з такою помилкою, лікарі вже підтвердили свою реєстрацію: 

employee_id : bc3cad09-a40a-4a3f-b872-123753ecb907,
request_id:      0b695596-4c7e-420b-aef4-1812dab0908a

employee_id : 8623517f-6b86-4c50-bd5d-95304f934d50
request_id:      b3ee045c-26a8-4541-9731-d98b687f7c2b
