### ISSUE TITLE
500 при завантаженні доків на майданчик ДеНово

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#283]
## Steps to Reproduce (Repro steps)

Пробуємо завантажити доки на
` https://storage.ehealth.world/declaration-requests-preprod/602fd200-e76b-4772-8e10-cd7fa2c4e003/declaration_request_person.TEMPORARY_CERTIFICATE.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=rDvxr6eBALBNbH%2F20180329%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180329T134140Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=6d79f63ef76eed7608551db08836b93f8464965a3f51454df3051678b7259ebe`

отримуємо відповідь:

"status":"error","statusCode":500,"data":"Server error: `PUT https:\/\/storage.ehealth.world\/declaration-requests-preprod\/602fd200-e76b-4772-8e10-cd7fa2c4e003\/declaration_request_person.TEMPORARY_CERTIFICATE.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=rDvxr6eBALBNbH%2F20180329%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180329T134140Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=6d79f63ef76eed7608551db08836b93f8464965a3f51454df3051678b7259ebe` resulted in a `500 Internal Server Error` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InternalError<\/Code><Message>We encountered an internal error, pleas (truncated...)\n"}

**Comment by lymychp** [comment]
на Деново є проблеми з інфраструктурою, які впливають на Мініо. Рішаєм з техпідтримкою Деново

**Comment by lymychp** [comment]
should work now

**Comment by sreva** [comment]
Дякую
