### ISSUE TITLE
Ошибка при отправке подписанной декларации PROD (content.employee.party.tax_id)

### ISSUE THREAD

**Issue by Evgeniy0119** [ehealth-ua/api-spec#287]
[Не подписанный.txt](https://github.com/ehealth-ua/api-spec/files/1863531/default.txt)
[Подписанный.txt](https://github.com/ehealth-ua/api-spec/files/1863532/default.txt)

При отправки подписанной декларации падает ошибка: content.employee.party.tax_id

ЕЦП выдан по серии номеру паспорта АА528328, 
employee заполнен с теми же данными: employee_id: b8cbe27d-2230-4c9b-93e8-eb64cc99907e
declaration_request id: 93724391-d411-4d70-b5b7-c4167e3f3779

кодировку проверили, совпадает

Прилагаю json

**Comment by lymychp** [comment]
прошу вислати підписаний контент в ПП

**Comment by Evgeniy0119** [comment]
выслал

**Comment by Evgeniy0119** [comment]
2018-03-30 15:28 GMT+03:00 lymychp <notifications@github.com>:

**Comment by lymychp** [comment]
серія паспорту в  employee вказана кирилицею,
а в ЕЦП - латиниця
