### ISSUE TITLE
PREDPROD Подписание декларации

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#288]
После последнего обновления потеряли возможность подписания деклараций. Ранее всё работало, теперь получаем ошибку.

## Steps to Reproduce (Repro steps)

- [ ] отправляем подписанные данные в ЦК

## Actual result
Получаем:

```
{
  "message": "success",
  "responce": {
    "meta": {
      "url": "http://api-svc.il/api/declaration_requests/683da785-c87d-4539-9e09-783b8521a0fe/actions/sign",
      "type": "object",
      "request_id": "494718ab-26fa-4cf7-bf04-e8bdbc24b2f9#365205",
      "code": 422
    },
    "error": {
      "type": "validation_failed",
      "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
      "invalid": [{
        "rules": [{
          "rule": "invalid",
          "params": [],
          "description": "Signed content does not match the previously created content"
        }],
        "entry_type": "json_data_property",
        "entry": "$.content"
      }]
    }
  }
}
```

## Expected result
- [ ] Уведомление об успешном подписании.

**Comment by svetavedmed** [comment]
Добрый день. Пришлите, пожлауйста, данные которые отправляете.

**Comment by cshevchukod** [comment]
Без проблем. Сегодня проблема повторяется.

`{"message":"success","responce":{"meta":{"url":"http://api-svc.il/api/declaration_requests/b532ab16-a648-4e4f-89ae-3c7d84704114/actions/sign","type":"object","request_id":"cfdae1e6-4185-4303-9001-2881b79b6a62#128069","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"invalid","params":[],"description":"incorrect status"}],"entry_type":"json_data_property","entry":"$.status"}]}}}`

**Comment by svetavedmed** [comment]
если расшифровать данные из подписанного контента, но у вас передается не верный статус - {"status":"SIGNED","start_date":"2018-04-02",... а также и ид другая - "declaration_id":"59384cf6-4bf4-47b1-84fb-33014df80c72"
Потому и ошибка.

**Comment by cshevchukod** [comment]
@svetavedmed, т.е. если я верно понял, то статус для новых деклараций должен быть другой (только для обновления декларации статус SIGNED), а start_date только сегодня?

**Comment by svetavedmed** [comment]
Статус заявок на декларацию(declaration_request) должен быть sign, после того, как эту заявку подписали и создали по ней декларацию. Но те declaration_requests, которые вы отправляете на `api/declaration_requests/declaration_request_id/actions/sign` должны быть в статусе Approved
