### ISSUE TITLE
Емеил врача в декларации (деново)

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#289]
У врача был один емеил, потом его сменили. Вход в Ехелс уже с новым емеилом. Однако при заключении декларации в тексте самой декларации пишется старый емеил.

**Comment by Hamiltone** [comment]
Такая же ситуация с номером телефона, в печатной декларации пишется старый номер. Ошибка со старыми эл. адресами и телефонами присуща не только для employees, но и для departments. Окружение - PROD

**Comment by lymychp** [comment]
@Charly3X please check comment to ticket #354 
@Hamiltone прошу зареєструвати тікет по Вашій проблемі з деталями, щоб було зрозуміло як відтворити пробьлему

**Comment by svetavedmed** [comment]
email та телефон лікаря в декларації змінені на email та телефон відділення
