### ISSUE TITLE
Помилка обовязковості $.public_name і $.short_name

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#29]
===NO SECRET INFORMATION FROM PRODUCTION SHOULD BE DISCLOSED IN THIS REPO. IT IS PUBLIC====  
  
Виникає помилка при реєстрації МСП, якщо не обовязкові поля пусті. При цьому вони не передаються.
## Steps to Reproduce (Repro steps)

- [ ]  /api/legal_entities
- [ ] запити у файлі

[Посмилка реэстрацыъ мсп.zip](https://github.com/ehealth-ua/api-spec/files/1071261/default.zip)

## Expected result
- помилки не має бути

**Comment by AlekzandrV** [comment]
@sreva Дайте, пожалуйста, request_id из meta

**Comment by sreva** [comment]
вибачаюсь що так довго "request_id" : "f2rrpf7nnnm56ggo8ju4i0dsn8a60liu"

**Comment by AlekzandrV** [comment]
@sreva 
і я вибачаюсь що так довго
на ваш запит ви отримали наступний Response, що говорить про не коректну структуру об'єкту address

```
{
  "meta": {
    "url": "http://dev.ehealth.world/api/legal_entities",
    "type": "object",
    "request_id": "5hvu4odntglfp8nsh103pmjvbddok4q2",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": "required",
            "params": [],
            "description": "required property settlement was not present"
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.addresses.[0]"
      },
      {
        "rules": [
          {
            "rule": "required",
            "params": [],
            "description": "required property settlement was not present"
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.addresses.[1]"
      }
    ]
  }
}
```

**Comment by sreva** [comment]
Дивно, так як відповідь у мене відрізнялась. я її прикріпляв

**Comment by AlekzandrV** [comment]
тогда пардон, разбираемся

**Comment by AlekzandrV** [comment]
@sreva Проблему идентифицировано и уже исправлено

**Comment by AlekzandrV** [comment]
Попробуйте воспроизвести. Проблема не должна повторяться
