### ISSUE TITLE
Ошибка при отправке подписанной декларации PROD (content.employee.party.tax_id) #287

### ISSUE THREAD

**Issue by Evgeniy0119** [ehealth-ua/api-spec#290]
Ошибка: content.employee.party.tax_id #287 актуально.

Как поступать в таких случаях?
Вы говорите что ЕЦП выдан на Латинице, выдачей ключей занимаются сертифицированные организации.

Что в таком случае делать пользователям? 
у Вас не предусмотрена возможность делать mapping между данными указанными в employee и в подписанном контенте, в тоже время Вы не регистрируете employee если Серия паспорта указанна на Латинице. Дайте ответ

**Comment by lymychp** [comment]
це не помилка. Згідно чинної нормативки, за умови відсутності ІПН, в даному полі вказуєтсья серія-номер паспорту. Серія-номер паспорту в паспорті завжди вказується в кирилиці. Ми проконсультувались з E&Y щодо цього питання. Як результат - правила валідації будуть пом'якшені. Літери латиниці будуть мапитись на кирилицю за можливості.

**Comment by Evgeniy0119** [comment]
Сроки реализации можете назвать?! У нас пользователи те которые без ИНН сейчас не могут делать декларации, а глав. врачи с них спрашивают почему ни одной декларации нет. На вчера было 2 таких обращения: content.employee.party.tax_id.

**Comment by Evgeniy0119** [comment]
Правильно ли я понял, ЕЦП менять не нужно? 

Разговаривал с специалистом который выдавал ключ врачу без ИНН, он уверяет, что при выдачи ключа используют кирилецу,

**Comment by lymychp** [comment]
конкретно в цьому випадку в ЕЦП вказана латиниця. По строках - не раніше ніж наступного тижня.

**Comment by lymychp** [comment]
delivered to prod
