### ISSUE TITLE
При регистрации учрежедения ошибка 422

### ISSUE THREAD

**Issue by dorado2012** [ehealth-ua/api-spec#296]
Подписываю образец запроса из документации в формате JSON, кодировка UTF8 - ошибка 422, образцы в файлах, подскажите в чем проблема плиз? лишних символов из сообщения #246 - нет

**Comment by dorado2012** [comment]
{
"namae": "Клініка Адоніс21",
"short_name": "Адоніс21",
"public_name": "Адоніс21",
"type": "MSP",
"owner_property_type": "STATE",
"legal_form": "140",
"edrpou": "2870213998",
"kveds": [
"86.10"
],
"addresses": [
{
"type": "REGISTRATION",
"country": "UA",
"area": "Волинська область",
"region": "Бердичівський",
"settlement": "Київ",
"settlement_type": "CITY",
"settlement_id": "43432432",
"street_type": "STREET",
"street": "вул. Ніжинська",
"building": "15",
"apartment": "23",
"zip": "02090"
}
],
"phones": [
{
"type": "MOBILE",
"number": "+380503410870"
}
],
"email": "sp.virny+100@gmail.com",
"owner": {
"first_name": "Петро",
"last_name": "Іванов",
"second_name": "Миколайович",
"tax_id": "3015492565",
"birth_date": "1985-06-16",
"birth_place": "Вінниця, Україна",
"gender": "FEMALE",
"email": "sp.virny+100@gmail.com",
"documents": [
{
"type": "PASSPORT",
"number": "120518"
}
],
"phones": [
{
"type": "MOBILE",
"number": "+380503410870"
}
],
"position": "P1"
},
"medical_service_provider": {
"licenses": [
{
"license_number": "fd123443",
"issued_by": "Кваліфікацйна комісія",
"issued_date": "1991-08-19",
"expiry_date": "1991-08-19",
"active_from_date": "1991-08-19",
"what_licensed": "реалізація наркотичних засобів",
"order_no": "K-123"
}
],
"accreditation": {
"category": "FIRST",
"issued_date": "1991-08-19",
"expiry_date": "1991-08-19",
"order_no": "fd123443",
"order_date": "1991-08-19"
}
},
"security": {
"redirect_uri": "http://example2.com"
}
}

**Comment by dorado2012** [comment]
Malformed encoded content. Probably, you have encoded corrupted JSON. Error: {:invalid, <<255>>, 0}

{"meta":{"url":"http://api-svc.il/api/legal_entities","type":"object","request_id":"367d1ca8-d3b4-4c1a-b51d-e360836fcda3#37663","code":422},"error":{"type":"request_malformed","message":"Malformed encoded content. Probably, you have encoded corrupted JSON. Error: {:invalid, <<255>>, 0}","invalid":[{"rules":[{"rule":"json","params":{"content":"{\r\n  \"name\": \"Клініка Адоніс21\",\r\n  \"short_name\": \"Адоніс21\",\r\n  \"public_name\": \"Адоніс21\",\r\n  \"type\": \"MSP\",\r\n  \"owner_property_type\": \"STATE\",\r\n  \"legal_form\": \"140\",\r\n  \"edrpou\": \"2870213998\",\r\n  \"kveds\": [\r\n    \"86.10\"\r\n  ],\r\n  \"addresses\": [\r\n    {\r\n      \"type\": \"REGISTRATION\",\r\n      \"country\": \"UA\",\r\n      \"area\": \"Волинська область\",\r\n      \"region\": \"Бердичівський\",\r\n      \"settlement\": \"Київ\",\r\n      \"settlement_type\": \"CITY\",\r\n      \"settlement_id\": \"43432432\",\r\n      \"street_type\": \"STREET\",\r\n      \"street\": \"вул. Ніжинська\",\r\n      \"building\": \"15\",\r\n      \"apartment\": \"23\",\r\n      \"zip\": \"02090\"\r\n    }\r\n  ],\r\n  \"phones\": [\r\n    {\r\n      \"type\": \"MOBILE\",\r\n      \"number\": \"+380503410870\"\r\n    }\r\n  ],\r\n  \"email\": \"sp.virny+100@gmail.com\",\r\n  \"owner\": {\r\n    \"first_name\": \"Петро\",\r\n    \"last_name\": \"Іванов\",\r\n    \"second_name\": \"Миколайович\",\r\n    \"tax_id\": \"3015492565\",\r\n    \"birth_date\": \"1985-06-16\",\r\n    \"birth_place\": \"Вінниця, Україна\",\r\n    \"gender\": \"FEMALE\",\r\n    \"email\": \"sp.virny+100@gmail.com\",\r\n    \"documents\": [\r\n      {\r\n        \"type\": \"PASSPORT\",\r\n        \"number\": \"120518\"\r\n      }\r\n    ],\r\n    \"phones\": [\r\n      {\r\n        \"type\": \"MOBILE\",\r\n        \"number\": \"+380503410870\"\r\n      }\r\n    ],\r\n    \"position\": \"P1\"\r\n  },\r\n  \"medical_service_provider\": {\r\n    \"licenses\": [\r\n      {\r\n        \"license_number\": \"fd123443\",\r\n        \"issued_by\": \"Кваліфікацйна комісія\",\r\n        \"issued_date\": \"1991-08-19\",\r\n        \"expiry_date\": \"1991-08-19\",\r\n        \"active_from_date\": \"1991-08-19\",\r\n        \"what_licensed\": \"реалізація наркотичних засобів\",\r\n        \"order_no\": \"K-123\"\r\n      }\r\n    ],\r\n    \"accreditation\": {\r\n      \"category\": \"FIRST\",\r\n      \"issued_date\": \"1991-08-19\",\r\n      \"expiry_date\": \"1991-08-19\",\r\n      \"order_no\": \"fd123443\",\r\n      \"order_date\": \"1991-08-19\"\r\n    }\r\n  },\r\n  \"security\": {\r\n    \"redirect_uri\": \"http://example2.com\"\r\n  }\r\n}"}}],"entry_type":"content"}]}}

**Comment by dorado2012** [comment]
Re: [ehealth-ua/api-spec] При регистрации учрежедения ошибка 422 (#296)



Здравствуйте, svetavedmed.

Вы писали 5 апреля 2018 г., 10:24:17:





Добрый день. Все есть лишний символ - \uFEFF, но похоже что и с подписью может быть проблема.
а можете подписать еще раз, но другим софтом, например ?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



я раскодирую и у меня нет лишних символов, а каким другим, например?

-- 
С уважением,
 Ukr.net                          mailto:rkuzienkov@ukr.net

**Comment by svetavedmed** [comment]
например, тут - https://czo.gov.ua/sign
и пришлите, пожалуйста, подписанные данные. Спасибо
