### ISSUE TITLE
PROD Отсутствует авторизация после авторизации

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#298]
Пользователь авторизуется, но далее при любой операции реестр его воспринимает, как не авторизованного пользователя.

## Steps to Reproduce (Repro steps)

- [ ] Авторизоваться, как врач
- [ ] Попробовать произвести какую-либо операцию. Например, подтвердить декларацию.

## Actual result
- [ ] response

`{"message":"success","responce":{"meta":{"url":"http://api.ehealth-ukraine.org:8000/api/declaration_requests/3bafc83d-1c50-46bd-bf28-d30ef60a69a9/actions/approve?Authorization=Bearer%20Rnc2RGtwSi9jejRNNUprUFB4UUdpdz09","code":401,"request_id":"6beac2fa-c5a4-4b6c-9a9a-0887368c6979#63614","type":"object"},"error":{"message":"Authorization header is not set or doesn't contain Bearer token","type":"access_denied"}}}
`

## Expected result
- [ ] Успешное выполнение операции.

**Comment by lymychp** [comment]
1. Authorization=Bearer треба передавати в headers, а не в параметрах
2. токен користувача - приватна інформація, його не варто публікувати на публічних ресурсах.

**Comment by lymychp** [comment]
скомпроментований токен видалено

**Comment by cshevchukod** [comment]
Спасибо. И прошу прощения. Буду в дальнейшем внимателенее.
