### ISSUE TITLE
PROD 500 при створенні declaration_requests

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#299]
## Steps to Reproduce (Repro steps)

- [ ] https://api.ehealth-ukraine.org/api/declaration_requests

## Actual result
- [ ]  ```{
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests",
                    "type" : "object",
                    "request_id" : "48e69a6e-181e-470b-ba5f-068a5b25c9da#34018",
                    "code" : 500
                },
                "error" : {
                    "errors" : {
                        "detail" : "Internal server error"
                    }
                }
            }```

## Expected result
- [ ] не http 500

**Comment by lymychp** [comment]
fixed on prod
