### ISSUE TITLE
PROD 500 на GET /api/declarations/

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#300]
## Steps to Reproduce (Repro steps)

- [ ] https://api.ehealth-ukraine.org/api/declarations/e0a6295e-99a9-4f43-a8a4-48f65bd090c3

## Actual result
- [ ]  ```{
                            "meta" : {
                                "url" : "http://api-svc.il/api/declarations/e0a6295e-99a9-4f43-a8a4-48f65bd090c3",
                                "type" : "object",
                                "request_id" : "6e21bb0c-6d15-4930-a943-a67825a94dad#72753",
                                "code" : 500
                            },
                            "error" : {
                                "errors" : {
                                    "detail" : "Internal server error"
                                }
                            }
                        }```

## Expected result
- [ ] не 500

**Comment by lymychp** [comment]
fix has been delivered to prod. Please let us know in case if it happens again.
