### ISSUE TITLE
PROD 500 при GET api/declaration_requests

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#301]
## Steps to Reproduce (Repro steps)

- [ ] https://api.ehealth-ukraine.org/api/declaration_requests/0c77c492-8cc6-4906-bd42-f1fc670188d1

## Actual result
- [ ] ```{
                            "meta" : {
                                "url" : "http://api-svc.il/api/declaration_requests/0c77c492-8cc6-4906-bd42-f1fc670188d1",
                                "type" : "object",
                                "request_id" : "78f6fe9f-7aea-46c9-a3d7-c78b4687de9d#22230",
                                "code" : 500
                            },
                            "error" : {
                                "errors" : {
                                    "detail" : "Internal server error"
                                }
                            }
                        }```

## Expected result
- [ ] якась інша відповідь крім 500

**Comment by pavel-yablonskiy** [comment]
тоже иногда на прод получаем 500 ошибку на запросе /declaration_requests

```json
{
    "meta": {
        "url": "http://api-svc.il/api/declaration_requests", 
        "code": 500, 
        "type": "object", 
        "request_id": "e005f563-7dc8-467b-a3c1-46c2c471a5ca#10342"
    }, 
    "error": {
        "errors": {
            "detail": "Internal server error"
        }
    }
}
```

**Comment by AlexKovalevych** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2104
