### ISSUE TITLE
Більше 10 секунд не отримуємо відповідь на підписанні

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#302]
- [ ] https://api.ehealth-ukraine.org/api/declaration_requests/ /actions/sign
- [ ] По наступним запитам не отримали відповід довше 10 секунд
1.  https://api.ehealth-ukraine.org/api/declaration_requests/d43b93b5-11f4-429b-afff-662b2e1210c8/actions/sign
2. https://api.ehealth-ukraine.org/api/declaration_requests/cb9c0bb2-d374-44e6-8c86-0a3c4739a9ed/actions/sign

## Actual result
- [ ]відповіді не отримали

**Comment by lymychp** [comment]
https://github.com/edenlabllc/ehealth.api/issues/2084

**Comment by lymychp** [comment]
аналіз показав, що в деяких випадках (вказний в тікеті якраз з цього списку) час збереження підписаного контенту в GCS займає більше 10 сек. 
Так як сьогодні планується міграція в Деново і заміна GCS на Minio, то немає змісту займатись подальшим аналізом та оптимізацією роботи з GCS. Будемо моніторити ситуацію після міграції. Якщо проблеми будуть повторюватись, реєструйте новий тікет.
