### ISSUE TITLE
http 429 без перевищення лімітів по кількості запитів

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#303]
за цей період ні одного разу **в хвилину**  не дійшли до ліміта в секунду, але отримували наступні відповіді на наступні типи запитів 
1 . Запит : https://api.ehealth-ukraine.org/api/declaration_requests/82b118f6-ff53-46dd-864e-eb5f902756cd/actions/sign
 Відповідь: ``` {
            "status" : "error",
            "message" : "Too Many Requests",
            "statusCode" : 429,
            "headers" : {
                "Date" : "Wed, 04 Apr 2018 10:47:55 GMT",
                "Content-Type" : "text/html; charset=UTF-8",
                "Transfer-Encoding" : "chunked",
                "Connection" : "close",
                "Set-Cookie" : "__cfduid=dfcffd336655530f5e3c25323a35540b81522838875; expires=Thu, 04-Apr-19 10:47:55 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure",
                "Retry-After" : "60",
                "Cache-Control" : "no-cache",
                "X-Frame-Options" : "SAMEORIGIN",
                "Expect-CT" : "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
                "Server" : "cloudflare",
                "CF-RAY" : "4063331a7a698ac2-KBP"
            },
            "body" : null
        }
    }```

2. Запит: https://api.ehealth-ukraine.org/api/declaration_requests/78979408-4272-412f-8a00-3a7ba6d89329/actions/approve
 Відповідь:  ```{
            "status" : "error",
            "message" : "Too Many Requests",
            "statusCode" : 429,
            "headers" : {
                "Date" : "Thu, 05 Apr 2018 07:17:35 GMT",
                "Content-Type" : "text/html; charset=UTF-8",
                "Transfer-Encoding" : "chunked",
                "Connection" : "close",
                "Set-Cookie" : "__cfduid=d5e86c577d50ad38a6b28b147808e51ce1522912655; expires=Fri, 05-Apr-19 07:17:35 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure",
                "Retry-After" : "37",
                "Cache-Control" : "no-cache",
                "X-Frame-Options" : "SAMEORIGIN",
                "Expect-CT" : "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
                "Server" : "cloudflare",
                "CF-RAY" : "406a3c62fe0a83f4-KBP"
            },
            "body" : null
        }```
3. Запит: https://api.ehealth-ukraine.org/api/declaration_requests
   Відповідь: ```{
            "status" : "error",
            "message" : "Too Many Requests",
            "statusCode" : 429,
            "headers" : {
                "Date" : "Thu, 05 Apr 2018 07:17:47 GMT",
                "Content-Type" : "text/html; charset=UTF-8",
                "Transfer-Encoding" : "chunked",
                "Connection" : "close",
                "Set-Cookie" : "__cfduid=de0c80a0f83f684fa07f26051d06338821522912667; expires=Fri, 05-Apr-19 07:17:47 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure",
                "Retry-After" : "25",
                "Cache-Control" : "no-cache",
                "X-Frame-Options" : "SAMEORIGIN",
                "Expect-CT" : "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
                "Server" : "cloudflare",
                "CF-RAY" : "406a3cadbb0783f4-KBP"
            },
            "body" : null
        }```

**Comment by lymychp** [comment]
please check comment in the linked ticket
https://github.com/edenlabllc/ehealth.api/issues/2084

**Comment by sreva** [comment]
Дякую
