### ISSUE TITLE
Approve invite (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#304]
Доброго дня, що може означати наступна помилка, пароль на портал приймає, проте наступна ерора на підтвердженні?
  

## Steps tp reproduce

{"meta":{"url":"http://api.ehealth-ukraine.org:8000/api/employee_requests/67c3cf85-e418-4b3c-a084-789282b0ebb8/approve","code":401,"request_id":"6e21bb0c-6d15-4930-a943-a67825a94dad#145362","type":"object"},"error":{"message":"Invalid access token","type":"access_denied"}}

![image](https://user-images.githubusercontent.com/24266717/38359153-23bf5e58-38d0-11e8-9869-a7b6bae9e0b1.png)

## Actual result
- [ ] Invalid access token

## Expected result
- [ ] approved user

**Comment by svetavedmed** [comment]
Дата помилка через те, что ви ввели нові дані по користувачу і старий email. Але для одного email можливий лише один користувач, тобто вам необхідно ввести або старі дані, або новий email.
