### ISSUE TITLE
Ошибка загрузки документов ПРОД

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#306]
Connecting: storage.ehealth-ukraine.org:443
D, [2018-04-06T10:11:29.310513 #2004] DEBUG -- : [httplog] Sending: PUT http://storage.ehealth-ukraine.org:443/declaration-requests/22be60e5-e23d-4588-800a-cd7ae1983603/declaration_request_person.SSN.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=QBUj69Ukz9CqGN%2F20180406%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180406T071117Z&X-Amz-Expires=7200&X-Amz-Signature=5c61a627789f4c8b9b39acddfcc66fb6a68d271118518b3e0cfd2dfdd13ae018&X-Amz-SignedHeaders=host
D, [2018-04-06T10:11:29.310627 #2004] DEBUG -- : [httplog] Header: content-type: image/jpeg
D, [2018-04-06T10:11:29.310656 #2004] DEBUG -- : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2018-04-06T10:11:29.310676 #2004] DEBUG -- : [httplog] Header: accept: */*
D, [2018-04-06T10:11:29.310693 #2004] DEBUG -- : [httplog] Header: user-agent: Ruby
D, [2018-04-06T10:11:29.310711 #2004] DEBUG -- : [httplog] Header: x-newrelic-id: VQ8FWFBbDxABVFJVDwACUVE=
D, [2018-04-06T10:11:29.310728 #2004] DEBUG -- : [httplog] Header: x-newrelic-transaction: PxQAV1VTWlJUAVRWVlICUAFQFB8EBw8RVU4aVQ4LBFBSAVxUBQBQV1JTVkNKQV4FBAYEVQ9TFTs=
D, [2018-04-06T10:11:29.310745 #2004] DEBUG -- : [httplog] Header: connection: close
D, [2018-04-06T10:11:29.318689 #2004] DEBUG -- : [httplog] Data: ����^@^PJFIF^@
..........
D, [2018-04-06T10:11:29.407684 #2004] DEBUG -- : [httplog] Status: 200
D, [2018-04-06T10:11:29.407839 #2004] DEBUG -- : [httplog] Header: date: Fri, 06 Apr 2018 07:11:29 GMT

ДАЛЕЕ АПРУВ

D, [2018-04-06T10:11:29.419031 #2004] DEBUG -- : [httplog] Connecting: api.ehealth-ukraine.org:443
D, [2018-04-06T10:11:29.481526 #2004] DEBUG -- : [httplog] Sending: PATCH http://api.ehealth-ukraine.org:443/api/declaration_requests/22be60e5-e23d-4588-800a-cd7ae1983603/actions/approve
D, [2018-04-06T10:11:29.481647 #2004] DEBUG -- : [httplog] Header: content-type: application/json
D, [2018-04-06T10:11:29.481677 #2004] DEBUG -- : [httplog] Header: authorization: Bearer Ym1ReGtidmxHTVI5YmtWQW1EWmRNUT09
D, [2018-04-06T10:11:29.481697 #2004] DEBUG -- : [httplog] Header: api-key: RUhadTQrcXpGclNINm5iREtRKzFKUT09
D, [2018-04-06T10:11:29.481716 #2004] DEBUG -- : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2018-04-06T10:11:29.481733 #2004] DEBUG -- : [httplog] Header: accept: */*
D, [2018-04-06T10:11:29.481749 #2004] DEBUG -- : [httplog] Header: user-agent: Ruby
D, [2018-04-06T10:11:29.481778 #2004] DEBUG -- : [httplog] Header: x-newrelic-id: VQ8FWFBbDxABVFJVDwACUVE=
D, [2018-04-06T10:11:29.481816 #2004] DEBUG -- : [httplog] Header: x-newrelic-transaction: PxQAV1VTWlJUAVRWVlICUAFQFB8EBw8RVU4aVQ4LBFBSAVxUBQBQV1JTVkNKQV4FBAYEVQ9TFTs=
D, [2018-04-06T10:11:29.481840 #2004] DEBUG -- : [httplog] Header: connection: close
D, [2018-04-06T10:11:29.481877 #2004] DEBUG -- : [httplog] Data: 
D, [2018-04-06T10:11:29.578785 #2004] DEBUG -- : [httplog] Status: 409
D, [2018-04-06T10:11:29.579067 #2004] DEBUG -- : [httplog] Header: date: Fri, 06 Apr 2018 07:11:29 GMT
D, [2018-04-06T10:11:29.579381 #2004] DEBUG -- : [httplog] Header: content-type: application/json; charset=utf-8
D, [2018-04-06T10:11:29.579414 #2004] DEBUG -- : [httplog] Header: content-length: 301
D, [2018-04-06T10:11:29.579434 #2004] DEBUG -- : [httplog] Header: connection: close
D, [2018-04-06T10:11:29.579453 #2004] DEBUG -- : [httplog] Header: set-cookie: __cfduid=da1812218e337082736e2d1a8573113f61522998689; expires=Sat, 06-Apr-19 07:11:29 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure
D, [2018-04-06T10:11:29.579471 #2004] DEBUG -- : [httplog] Header: cache-control: max-age=0, private, must-revalidate
D, [2018-04-06T10:11:29.579488 #2004] DEBUG -- : [httplog] Header: vary: Accept-Encoding
D, [2018-04-06T10:11:29.579505 #2004] DEBUG -- : [httplog] Header: via: kong/0.12.1
D, [2018-04-06T10:11:29.579522 #2004] DEBUG -- : [httplog] Header: x-content-type-options: nosniff
D, [2018-04-06T10:11:29.579540 #2004] DEBUG -- : [httplog] Header: x-download-options: noopen
D, [2018-04-06T10:11:29.579557 #2004] DEBUG -- : [httplog] Header: x-frame-options: SAMEORIGIN
D, [2018-04-06T10:11:29.579573 #2004] DEBUG -- : [httplog] Header: x-kong-proxy-latency: 28
D, [2018-04-06T10:11:29.579590 #2004] DEBUG -- : [httplog] Header: x-kong-upstream-latency: 62
D, [2018-04-06T10:11:29.579748 #2004] DEBUG -- : [httplog] Header: x-permitted-cross-domain-policies: none
D, [2018-04-06T10:11:29.579769 #2004] DEBUG -- : [httplog] Header: x-ratelimit-limit-minute: 9000
D, [2018-04-06T10:11:29.579824 #2004] DEBUG -- : [httplog] Header: x-ratelimit-remaining-minute: 8990
D, [2018-04-06T10:11:29.579848 #2004] DEBUG -- : [httplog] Header: x-request-id: 5cddbfa7-6809-4f18-b920-89a021b988a4#65903
D, [2018-04-06T10:11:29.579866 #2004] DEBUG -- : [httplog] Header: x-xss-protection: 1; mode=block
D, [2018-04-06T10:11:29.579884 #2004] DEBUG -- : [httplog] Header: expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
D, [2018-04-06T10:11:29.579900 #2004] DEBUG -- : [httplog] Header: server: cloudflare
D, [2018-04-06T10:11:29.579917 #2004] DEBUG -- : [httplog] Header: cf-ray: 407270d14fc183f4-KBP
D, [2018-04-06T10:11:29.579969 #2004] DEBUG -- : [httplog] Response:
{"meta":{"url":"http://api-svc.il/api/declaration_requests/22be60e5-e23d-4588-800a-cd7ae1983603/actions/approve","type":"object","request_id":"5cddbfa7-6809-4f18-b920-89a021b988a4#65903","code":409},"error":{"type":"request_conflict","message":"Documents person.PASSPORT, person.SSN is not uploaded"}}

**Comment by lymychp** [comment]
fixed, please try again.
