### ISSUE TITLE
PROD Ошибка при подтверждении декларации

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#307]
Не понимаем в чем проблема. Вроде декларацию можно отправить, но похоже при подтверждении проходит дополнительная проверка и там чего-то не хватает. Типа, забыли какое-то обязательное поле, но такого быть не должно ведь это отсеевается на создании декларации.

## Steps to Reproduce (Repro steps)

``
{"message":"success","responce":"{\"urgent\":{\"authentication_method_current\":{\"type\":\"OTP\",\"number\":\"+38093*****66\"}},\"meta\":{\"url\":\"http://api-svc.il/api/declaration_requests\",\"type\":\"object\",\"request_id\":\"bcbf0f4e-739d-4524-853d-ea04c9114a24#36492\",\"code\":200},\"data\":{\"status\":\"NEW\",\"start_date\":\"2018-04-06\",\"seed\":\"\\\\x9970c86762212151cb0c609e9f96004ca2365d21cd602ec5cf0c421360868293c54d452b48f8793d0c428704b4b1bd9314cd3b7f822ddeac1a883b81df3c18cb\",\"scope\":\"family_doctor\",\"person\":{\"secret\":\"Шульга\",\"second_name\":\"Олександрович\",\"process_disclosure_data_consent\":true,\"patient_signed\":false,\"last_name\":\"Масановець\",\"gender\":\"MALE\",\"first_name\":\"Дмитро\",\"emergency_contact\":{\"second_name\":\"Сергіївна\",\"phones\":[{\"type\":\"MOBILE\",\"number\":\"+380934620166\"}],\"last_name\":\"Масановець\",\"first_name\":\"Наталія\"},\"email\":null,\"documents\":[{\"type\":\"NATIONAL_ID\",\"number\":\"000815446\"}],\"birth_settlement\":\"Чернігів\",\"birth_date\":\"2001-07-01\",\"birth_country\":\"Україна\",\"authentication_methods\":[{\"type\":\"OTP\",\"phone_number\":\"+380633059611\"}],\"addresses\":[{\"zip\":\"14021\",\"type\":\"REGISTRATION\",\"street_type\":\"STREET\",\"street\":\"Глібова\",\"settlement_type\":\"CITY\",\"settlement_id\":\"01022759-b478-4952-97f2-cbada0045fee\",\"settlement\":\"ЧЕРНІГІВ\",\"country\":\"UA\",\"building\":\"74\",\"area\":\"ЧЕРНІГІВСЬКА\",\"apartment\":\"0\"},{\"zip\":\"14021\",\"type\":\"RESIDENCE\",\"street_type\":\"STREET\",\"street\":\"Глібова\",\"settlement_type\":\"CITY\",\"settlement_id\":\"01022759-b478-4952-97f2-cbada0045fee\",\"settlement\":\"ЧЕРНІГІВ\",\"country\":\"UA\",\"building\":\"74\",\"area\":\"ЧЕРНІГІВСЬКА\",\"apartment\":\"0\"}]},\"legal_entity\":{\"short_name\":\"ЧМЛ № 1\",\"public_name\":\"ЧЕРНІГІВСЬКА МІСЬКА ЛІКАРНЯ № 1 ЧЕРНІГІВСЬКОЇ МІСЬКОЇ РАДИ\",\"phones\":[{\"type\":\"LAND_LINE\",\"number\":\"+380462941727\"}],\"name\":\"ЧЕРНІГІВСЬКА МІСЬКА ЛІКАРНЯ № 1 ЧЕРНІГІВСЬКОЇ МІСЬКОЇ РАДИ\",\"licenses\":[{\"what_licensed\":\"Медична практика\",\"order_no\":\"36\",\"license_number\":\"063069\",\"issued_date\":\"2012-11-07\",\"issued_by\":\"МОЗ України\",\"active_from_date\":\"2012-08-30\"}],\"legal_form\":\"430\",\"id\":\"ab312647-d2a9-43fc-8905-39a25392dfe0\",\"email\":\"1ml@chernigiv-rada.gov.ua\",\"edrpou\":\"02006596\",\"addresses\":[{\"zip\":\"14000\",\"type\":\"REGISTRATION\",\"street_type\":\"AVENUE\",\"street\":\"Миру\",\"settlement_type\":\"CITY\",\"settlement_id\":\"01022759-b478-4952-97f2-cbada0045fee\",\"settlement\":\"ЧЕРНІГІВ\",\"country\":\"UA\",\"building\":\"44\",\"area\":\"ЧЕРНІГІВСЬКА\",\"apartment\":\"0\"}],\"accreditation\":{\"order_no\":\"47\",\"order_date\":\"2015-02-23\",\"issued_date\":\"2015-02-16\",\"expiry_date\":\"2018-02-16\",\"category\":\"FIRST\"}},\"id\":\"e932dad8-2bdd-401c-8877-d13375510e2a\",\"end_date\":\"2019-06-30\",\"employee\":{\"position\":\"P7\",\"party\":{\"tax_id\":\"2470412443\",\"second_name\":\"Володимирівна\",\"phones\":[{\"type\":\"MOBILE\",\"number\":\"+380962609743\"}],\"last_name\":\"Запека\",\"id\":\"54669179-8b12-44a8-89b4-0ec4235ca309\",\"first_name\":\"Лілія\",\"email\":\"verbena967@gmail.com\"},\"id\":\"67cced0f-c296-409d-9a9b-d5ef9c8410e4\"},\"division\":{\"type\":\"CLINIC\",\"phones\":[{\"type\":\"LAND_LINE\",\"number\":\"+380462941722\"}],\"name\":\"Поліклініка №3\",\"legal_entity_id\":\"ab312647-d2a9-43fc-8905-39a25392dfe0\",\"id\":\"2815088e-25d6-4f23-825b-16bcc6ef370d\",\"external_id\":\"3\",\"email\":\"1ml@chernigiv-rada.gov.ua\",\"addresses\":[{\"zip\":\"14000\",\"type\":\"RESIDENCE\",\"street_type\":\"AVENUE\",\"street\":\"Миру\",\"settlement_type\":\"CITY\",\"settlement_id\":\"01022759-b478-4952-97f2-cbada0045fee\",\"settlement\":\"ЧЕРНІГІВ\",\"country\":\"UA\",\"building\":\"44\",\"area\":\"ЧЕРНІГІВСЬКА\",\"apartment\":\"0\"}]},\"declaration_number\":\"0000-X8PH-T7KK\",\"declaration_id\":\"9e4d8e0c-a3d8-41c1-96ad-1c32d853d373\",\"content\":\"<!DOCTYPE html> <html xmlns=\\\"http://www.w3.org/1999/xhtml\\\"> <head> <meta charset=\\\"utf-8\\\"> <style>*{margin:0;padding:0;box-sizing:border-box}body{width:1074px;margin:70pt 60pt;font-family:serif;color:#201600}p{margin:0;padding:0}h1{line-height:1.5em;margin-bottom:30px}h2{line-height:2em}@media print{body{margin:0;white-space:normal}@page{size:auto;margin-top:25mm;margin-bottom:22mm;white-space:normal;word-break:break-all;hyphens:auto}.page{-webkit-print-color-adjust:exact;color-adjust:exact;page-break-after:always;white-space:normal}}.header{margin-bottom:8em;display:block}.header__in{float:right;font-size:20pt}.header::after{content:\\\"\\\";display:table;clear:both}.items{column-count:2;column-width:10cm;column-gap:1cm}.el{display:block;line-height:1.5em;margin-bottom:10px;break-inside:avoid-column}.el__header{text-transform:uppercase;font-weight:700;font-size:1.2em}.el__data{font-size:1.1em;box-shadow:inset 0 0 0 1px;padding:0 1mm}.sign{margin-top:5pt;height:40pt;width:100%;border:1px solid #000}.border{box-shadow:inset 0 0 0 1px;padding:1mm}.small{line-height:1em;text-align:justify}</style> </head> <body> <section class=\\\"page\\\"> <div class=\\\"header\\\"> <div class=\\\"header__in\\\"> ЗАТВЕРДЖЕНО <br> Наказ Міністерства<br> охорони здоров’я України<br> 19.03.2018 № 503 </div> </div> <div> <h1 align=\\\"center\\\"> ДЕКЛАРАЦІЯ № <span class=\\\"border\\\"> 0000-X8PH-T7KK</span> </h1> <h1 align=\\\"center\\\"> ПРО ВИБІР ЛІКАРЯ, ЯКИЙ НАДАЄ ПЕРВИННУ МЕДИЧНУ ДОПОМОГУ </h1> </div> <div class=\\\"items\\\"> <div class=\\\"el\\\"> <div class=\\\"el__header\\\"> 1. Пацієнт </div> <div class=\\\"el__title\\\"> <b>1.1. </b> Прізвище </div> <div class=\\\"el__data\\\"> Масановець </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>1.2. </b> Ім'я </div> <div class=\\\"el__data\\\"> Дмитро </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>1.3. </b> По-батькові </div> <div class=\\\"el__data\\\"> Олександрович </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>1.4. </b> Дата народження </div> <div class=\\\"el__data\\\"> 01.07.2001 </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>1.5. </b> Місце народження </div> <div class=\\\"el__data\\\"> Чернігів, Україна </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>1.6. </b> Стать </div> <div class=\\\"el__data\\\">  чоловіча   </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>1.7. Контактні дані</b> </div> <div> 1.7.1. Контактний номер телефону </div> <div class=\\\"el__data\\\"> –– </div> </div> <div class=\\\"el\\\"> <div> 1.7.2. Адреса електронної пошти <i>(за наявності)</i> </div> <div class=\\\"el__data\\\"> –– </div> </div> <div class=\\\"el\\\"> <div> 1.7.3. Бажаний спосіб зв'язку </div> <div class=\\\"el__data\\\"> –– </div> </div> <div class=\\\"el\\\"> <div> <b> 1.8. Документ, що посвідчує особу*: </b> </div> </div> <div class=\\\"el\\\"> <div> 1.8.1.Тип документа: </div> <div class=\\\"el__data\\\"> Біометричний паспорт </div> </div> <div class=\\\"el\\\"> <div> 1.8.2. Серія (за наявності), номер, дата та орган видачі документа, термін дії документа (за наявності). </div> <div class=\\\"el__data\\\"> 000815446  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.8.3. <b> Реєстраціний номер облікової картки платника податків (далі - РНОКПП) або серія та номер паспорта </b> <i> (для фізичних осіб, які через релігійні переконання відмовляються від прийняття РНОКПП та повідомили про це відповідний контролюючий орган і мають відмітку в паспорті) </i> </div> <div class=\\\"el__data\\\"> –– </div> <div> <i> * Зазначаються реквізити документів, які використовувалися під час самостійного подання Декларації через електронну систему охорони здоров‘я або пред’являлися уповноваженій особі надавача ПМД. </i> </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b> 1.9. Унікальний номер запису в Єдиному державному демографічному реєстрі (у разі наявності) </b> </div> <div class=\\\"el__data\\\"> –– </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b> 1.10. Адреса місця фактичного проживання або перебування</b> <i> (для надання допомоги за місцем проживання або перебування та листування)</i> </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.10.1. Поштовий індекс </div> <div class=\\\"el__data\\\"> 14021  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.10.2. Тип та назва вулиці </div> <div class=\\\"el__data\\\"> вулиця Глібова  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.10.3. Будинок </div> <div class=\\\"el__data\\\"> 74  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.10.4. Квартира </div> <div class=\\\"el__data\\\"> 0  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.10.5. Тип та назва населеного пункту </div> <div class=\\\"el__data\\\"> місто ЧЕРНІГІВ </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.10.6. Район <i>(не заповнюється для міст обласного значення)</i> </div> <div class=\\\"el__data\\\">   ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.10.7 Область <i> (не заповнюється для міст Києва та Севастополя) </i> </div> <div class=\\\"el__data\\\"> ЧЕРНІГІВСЬКА  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b> 1.11. Адреса зареєстрованого місця проживання пацієнта </b> <i> (не заповнюється, якщо збігається з адресою фактичного місця проживання) </i> </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.11.1. Тип та назва вулиці </div> <div class=\\\"el__data\\\"> вулиця Глібова  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.11.2. Будинок </div> <div class=\\\"el__data\\\"> 74 </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.11.3. Квартира </div> <div class=\\\"el__data\\\"> 0  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.11.4. Тип та назва населеного пункту </div> <div class=\\\"el__data\\\"> місто ЧЕРНІГІВ </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.11.5. Район <i> (не заповнюється для міст обласного значення) </i> </div> <div class=\\\"el__data\\\">   ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.11.6. Область <i> (не заповнюється для міст Києва та Севастополя) </i> </div> <div class=\\\"el__data\\\"> ЧЕРНІГІВСЬКА  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b> 1.12. Довірена особа пацієнта для повідомлення у разі настанні екстреного випадку з пацієнтом (для осіб віком від 14 до 18 років обов'язково зазначається один з батьків) </b> </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.12.1. Прізвище, ім’я, по-батькові </div> <div class=\\\"el__data\\\"> Наталія Сергіївна Масановець </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 1.12.2. Контактний номер телефону </div> <div class=\\\"el__data\\\"> +380934620166 </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__header\\\"> 2. ЛІКАР, ЯКИЙ НАДАЄ ПМД </div> <div> <b>2.1. </b> Прізвище, ім’я, по-батькові </div> <div class=\\\"el__data\\\"> Лілія Володимирівна Запека </div> </div> <div class=\\\"el\\\"> <div> <b>2.2. </b> Контактний номер телефону лікаря </div> <div class=\\\"el__data\\\"> +380962609743 </div> </div> <div class=\\\"el\\\"> <div> <b>2.3. </b> Адреса електронної пошти лікаря </div> <div class=\\\"el__data\\\"> verbena967@gmail.com </div> </div> <div class=\\\"el\\\"> <div> <b> 2.4. </b> Посада лікаря-спеціаліста </div> <div class=\\\"el__data\\\"> Сімейний лікар </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__header\\\"> 3. НАДАВАЧ ПМД </div> <div> <b>3.1. </b>Повне найменування / П.І.Б. </div> <div class=\\\"el__data\\\"> ЧЕРНІГІВСЬКА МІСЬКА ЛІКАРНЯ № 1 ЧЕРНІГІВСЬКОЇ МІСЬКОЇ РАДИ </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>3.2.</b> Код ЄДРПОУ/РНОКПП або серія та номер паспорта (для фізичних осіб, які через релігійні переконання відмовляються від прийняття РНОКПП та повідомили про це відповідний контролюючий орган і мають відмітку в паспорті) </div> <div class=\\\"el__data\\\"> 02006596 </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>3.3.</b> Контактний номер телефону </div> <div class=\\\"el__data\\\"> +380462941727 </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>3.4.</b> Адреса електронної пошти </div> <div class=\\\"el__data\\\"> 1ml@chernigiv-rada.gov.ua </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b> 3.5. </b> Адреса місця надання медичних послуг ПМД лікарем, який надає ПМД </div> <div class=\\\"el__title\\\"> 3.5.1. Тип та назва вулиці </div> <div class=\\\"el__data\\\"> проспект Миру  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 3.5.2. Будинок </div> <div class=\\\"el__data\\\"> 44 </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 3.5.3. Тип та назва населеного пункту </div> <div class=\\\"el__data\\\"> місто ЧЕРНІГІВ </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 3.5.4. Район <i> (не заповнюється для міст обласного значення) </i> </div> <div class=\\\"el__data\\\">   ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> 3.5.5. Область <i> (не заповнюється для міст Києва та Севастополя) </i> </div> <div class=\\\"el__data\\\"> ЧЕРНІГІВСЬКА  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__header\\\"> 4. ЗАКОННИЙ ПРЕДСТАВНИК ПАЦІЄНТА </div> <div> <i> (не заповнюється у разі подання Декларації пацієнтом - дієздатною особою після досягнення 14-річного віку) </i> </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>4.1. </b> Прізвище, ім’я, по-батькові </div> <div class=\\\"el__data\\\">   ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>4.2. </b> Дата народження </div> <div class=\\\"el__data\\\">   ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>4.3. </b> Унікальний номер запису в Єдиному державному демографічному реєстрі (у разі наявності) </div> <div class=\\\"el__data\\\">   ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>4.4. </b> Тип, серія (за наявності), номер, дата та орган видачі документа, що посвідчує особу законного представника </div> <div class=\\\"el__data\\\">     ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>4.5. </b> Тип документа, що посвідчує повноваження законного представника </div> <div class=\\\"el__data\\\">   ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>4.6. </b> Серія (за наявності), номер, дата та орган видачі, термін дії документа (за наявності), що засвідчує повноваження законного представника </div> <div class=\\\"el__data\\\">    ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>4.7. </b> Контактний номер телефону </div> <div class=\\\"el__data\\\">   ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__title\\\"> <b>4.8. </b> Адреса електронної пошти (за наявності) </div> <div class=\\\"el__data\\\">   ––  </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__header\\\"> 5. ЗГОДА НА ЗБІР ТА ОБРОБКУ ПЕРСОНАЛЬНИХ ДАНИХ </div> <div class=\\\"el__title\\\"> Своїм підписом я, </div> <div class=\\\"el__data\\\">   Дмитро Олександрович Масановець  </div> <div class=\\\"small\\\"> надаю згоду на збір, зберігання, передачу, знеособлення моїх (пацієнта, законним представником якого я є) персональних даних, зазначених в цій Декларації, та інформації, необхідної в цілях охорони здоров‘я, встановлення медичного діагнозу, для забезпечення піклування чи лікування або надання ПМД, функціонування електронної системи охорони здоров‘я, володільцю і розпоряднику – Національній службі здоров‘я України, адміністратору центральної бази даних електронної системи охорони здоров‘я, надавачу ПМД та лікарю, які зазначені в цій Декларації, за умови, що такі дані обробляються медичними працівниками або іншими уповноваженими особами надавача ПМД та Національної служби здоров‘я України, на яких покладено обов‘язки щодо забезпечення захисту персональних даних, з метою здійснення медичного обслуговування, надання лікарських засобів, функціонування електронної системи охорони здоров’я. </div> <div class=\\\"small\\\"> Підписуючи цю Декларацію, я надаю згоду на доступ до перегляду даних про мене (пацієнта, законним представником якого я є), що містяться в електронній системі охорони здоров’я, лікарю, який надає ПМД, зазначеному в цій Декларації, а також іншим лікарям, які надаватимуть мені (пацієнту, законним представником якого я є) медичну допомогу, в межах, необхідних для надання такої допомоги. </div> <div> <div class=\\\"small\\\"> Підпис пацієнта (його законного представника) <i>(у разі заповнення у паперовій формі)</i> </div> <div class=\\\"sign\\\"></div> </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__header\\\"> <b>6. Підпис пацієнта (його законного представника)</b> </div> <div class=\\\"small\\\"> Своїм підписом підтверджую добровільний вибір лікаря, який надає первинну медичну допомогу, що зазначений в розділі 2 цієї Декларації, а також достовірність наданих мною даних. </div> <div> <div class=\\\"sign\\\"></div> </div> </div> <div class=\\\"el\\\"> <div class=\\\"el__header\\\"> <b>7. Дата подання</b> </div> <div class=\\\"el__data\\\"> 06.04.2018 </div> </div> </div> </section> </body> </html>\",\"channel\":\"MIS\"}}"}
``

## Actual result
`
{"message":"success","responce":{"meta":{"url":"http://api-svc.il/api/declaration_requests/e932dad8-2bdd-401c-8877-d13375510e2a/actions/approve","type":"object","request_id":"24a38332-2b78-4d9c-a1a9-544997b5aea0#55275","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"cast","params":["number"],"description":"type mismatch. Expected Number but got Null"}],"entry_type":"json_data_property","entry":"$.code"}]}}}
`
## Expected result
- [ ] Успех

**Comment by svetavedmed** [comment]
нужно внести код, который был отправлен пациенту на телефон

**Comment by cshevchukod** [comment]
Нет, баг не в этом. Пациент уже подтвердил свой номер.

```
{
    "meta": {
        "url": "http://api-svc.verification/verifications/+380633059611",
        "type": "object",
        "request_id": "449d35b3-2e40-4a3a-9485-ba4225a05785#30896",
        "code": 200
    },
    "data": {
        "phone_number": "+380633059611"
    }
}
```

**Comment by lymychp** [comment]
це не баг, а некоректна реалізація на Вашій стороні.
В даному випадку approve declaration_request повинен відбуватись з OTP. Про це явно вказано в респонсі на create declaration request і у відповіді з помилкою на approve
