### ISSUE TITLE
Не отримуємо відповідь на завантаженні файлів протягом 10 секунд

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#308]
Завантажуємо док на посилання:
```https://storage.ehealth-ukraine.org/declaration-requests/eeda0720-c3c7-413e-9cb9-a318dd8cc461/declaration_request_person.SSN.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=QBUj69Ukz9CqGN%2F20180406%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180406T092903Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=036cc9520c52c2c7405d00818d1df8362a6db0748d9f843743118bb00f9e492e```

відповідь

```
    "res_code" : 0,
    "res_message" : "cURL error 28: Connection timed out after 10001 milliseconds (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"
```

**Comment by superjonh** [comment]
в мене на завантаженні вертає <error>Unable to connect to the remote server</error>, почалось з 10-46

**Comment by lymychp** [comment]
@superjonh дайти плз вої логи. Не факт, що це така ж проблема

**Comment by superjonh** [comment]
@lymychp створив тікет https://github.com/ehealth-ua/api-spec/issues/310

**Comment by sreva** [comment]
@lymychp  після зміни rp_filter=0 
![rp_filter_0_curl](https://user-images.githubusercontent.com/29060924/38429798-1f71c98c-39c8-11e8-81f7-da107373f957.png)
Змін не відбулось

**Comment by gmile** [comment]
Вы можете как-то гарантировано проверить что изменения точно применились и
имеют эффект?

**Comment by gmile** [comment]
@sreva @dmmat не могли бы вы показать результат команды `mtr` с серверов, с которых происходит запрос на загрузку?

Сергей, ранее ваш коллега показывал вывод команды traceroute. И хотя разницы с `mtr` быть не должно, не могли бы вы показать именно результат выполнения `mtr`?

**Comment by ytrrty** [comment]
@gmile 
`mtr storage.ehealth.world`

![screenshot from 2018-04-09 17-47-42](https://user-images.githubusercontent.com/7595232/38504772-3f8589cc-3c1e-11e8-903a-df1e0e27bcd2.png)

**Comment by ytrrty** [comment]
@gmile  при тому всьому сервер пінгується нормально

![screenshot from 2018-04-11 17-47-18](https://user-images.githubusercontent.com/7595232/38624313-7409aa6e-3db0-11e8-858f-a0c847d04ba5.png)

**Comment by ytrrty** [comment]
@gmile так, проблема досі є. IP - 51.137.102.185

**Comment by gmile** [comment]
@ytrrty вы могли бы попробовать загрузить документы командой `curl`, и показать вывод? Пример я описал тут https://github.com/ehealth-ua/api-spec/issues/310#issuecomment-379281452

**Comment by ytrrty** [comment]
@gmile дивно, через `curl` працює 
```
curl -v -X PUT -H 'Content-Type: image/jpeg' 'https://storage.ehealth.world/declaration-requests-preprod/1c492fbd-5e52-444a-9860-b12893256484/declaration_request_person.PASSPORT.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=rDvxr6eBALBNbH%2F20180412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180412T085052Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=fc925f2b3f719226c7181025105a9c7b4856a3f8e8f50c7ee5e7b749e9b229be' -d @/home/ubuntu/file.png 
*   Trying 185.9.41.28...
* Connected to storage.ehealth.world (185.9.41.28) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 594 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: *.ehealth.world (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: OU=Domain Control Validated,OU=PositiveSSL Wildcard,CN=*.ehealth.world
* 	 start date: Fri, 16 Jun 2017 00:00:00 GMT
* 	 expire date: Sat, 16 Jun 2018 23:59:59 GMT
* 	 issuer: C=GB,ST=Greater Manchester,L=Salford,O=COMODO CA Limited,CN=COMODO RSA Domain Validation Secure Server CA
* 	 compression: NULL
* ALPN, server accepted to use http/1.1
> PUT /declaration-requests-preprod/1c492fbd-5e52-444a-9860-b12893256484/declaration_request_person.PASSPORT.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=rDvxr6eBALBNbH%2F20180412%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180412T085052Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=fc925f2b3f719226c7181025105a9c7b4856a3f8e8f50c7ee5e7b749e9b229be HTTP/1.1
> Host: storage.ehealth.world
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: image/jpeg
> Content-Length: 727
> 
* upload completely sent off: 727 out of 727 bytes
< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Length: 0
< Content-Type: text/plain; charset=utf-8
< Date: Thu, 12 Apr 2018 08:53:16 GMT
< Etag: "3e710790fe17457f5a1935301365feac"
< Server: Minio/RELEASE.2018-03-12T21-25-28Z (linux; amd64)
< Vary: Accept-Encoding
< Vary: Origin
< X-Amz-Bucket-Region: us-east-1
< X-Amz-Request-Id: 1524A4467917E107
< 
* Connection #0 to host storage.ehealth.world left intact
```

**Comment by gmile** [comment]
@ytrrty т.к. curl и ping у вас работают, выглядит что проблема на уровне выше, например на уровне кода. А пока я закрываю issue.
