### ISSUE TITLE
Ошибка при регистрации декларации (500) ПРОД

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#309]
[httplog] Data: {"declaration_request":{"person":{"first_name":"Людмила","last_name":"Шенберєва","second_name":"Володимирівна","birth_date":"1959-05-04","birth_country":"UA","birth_settlement":"ХАРКІВ","tax_id":"2167302360","gender":"FEMALE","secret":"Шенбереєва","addresses":[{"type":"REGISTRATION","country":"UA","area":"ХАРКІВСЬКА","settlement":"ХАРКІВ","settlement_type":"CITY","settlement_id":"1241d1f9-ae81-4fe5-b614-f4f780a5acf0","street_type":"STREET","street":"Старопрудна","building":"6","apartment":"55","zip":"61177"},{"type":"RESIDENCE","country":"UA","area":"ХАРКІВСЬКА","settlement":"ХАРКІВ","settlement_type":"CITY","settlement_id":"1241d1f9-ae81-4fe5-b614-f4f780a5acf0","street_type":"STREET","street":"Старопрудна","building":"6","apartment":"55","zip":"61177"}],"patient_signed":false,"process_disclosure_data_consent":true,"emergency_contact":{"first_name":"Ганна","last_name":"Шенбереєва","phones":[{"type":"MOBILE","number":"+380986073272"}]},"authentication_methods":[{"type":"OTP","phone_number":"+380989116577"}],"documents":[{"type":"PASSPORT","number":"МН980672"}],"phones":[{"type":"MOBILE","number":"+380989116577"}]},"employee_id":"25199383-3298-4fa6-a9c8-836cc08d5d58","scope":"family_doctor","division_id":"d334c60f-94c9-42c4-bec0-1b4c30f936d3"}}
D, [2018-04-06T10:10:43.758844 #2004] DEBUG -- : [httplog] Status: 500
D, [2018-04-06T10:10:43.759152 #2004] DEBUG -- : [httplog] Header: date: Fri, 06 Apr 2018 07:10:43 GMT
D, [2018-04-06T10:10:43.759221 #2004] DEBUG -- : [httplog] Header: content-type: text/plain; charset=UTF-8
D, [2018-04-06T10:10:43.759261 #2004] DEBUG -- : [httplog] Header: content-length: 200
D, [2018-04-06T10:10:43.759296 #2004] DEBUG -- : [httplog] Header: connection: close
D, [2018-04-06T10:10:43.759330 #2004] DEBUG -- : [httplog] Header: set-cookie: __cfduid=de59501d97ec1cf51c05eed438d0b37f21522998643; expires=Sat, 06-Apr-19 07:10:43 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure
D, [2018-04-06T10:10:43.759365 #2004] DEBUG -- : [httplog] Header: cache-control: max-age=0, private, must-revalidate
D, [2018-04-06T10:10:43.759397 #2004] DEBUG -- : [httplog] Header: vary: Accept-Encoding
D, [2018-04-06T10:10:43.759568 #2004] DEBUG -- : [httplog] Header: via: kong/0.12.1
D, [2018-04-06T10:10:43.759615 #2004] DEBUG -- : [httplog] Header: x-content-type-options: nosniff
D, [2018-04-06T10:10:43.759676 #2004] DEBUG -- : [httplog] Header: x-download-options: noopen
D, [2018-04-06T10:10:43.759716 #2004] DEBUG -- : [httplog] Header: x-frame-options: SAMEORIGIN
D, [2018-04-06T10:10:43.759750 #2004] DEBUG -- : [httplog] Header: x-kong-proxy-latency: 7
D, [2018-04-06T10:10:43.759781 #2004] DEBUG -- : [httplog] Header: x-kong-upstream-latency: 107
D, [2018-04-06T10:10:43.759812 #2004] DEBUG -- : [httplog] Header: x-permitted-cross-domain-policies: none
D, [2018-04-06T10:10:43.759843 #2004] DEBUG -- : [httplog] Header: x-ratelimit-limit-minute: 9000
D, [2018-04-06T10:10:43.759875 #2004] DEBUG -- : [httplog] Header: x-ratelimit-remaining-minute: 8981
D, [2018-04-06T10:10:43.759915 #2004] DEBUG -- : [httplog] Header: x-request-id: c2236580-3dd9-4d32-81cf-8ebbd1196593#51157
D, [2018-04-06T10:10:43.759962 #2004] DEBUG -- : [httplog] Header: x-xss-protection: 1; mode=block
D, [2018-04-06T10:10:43.759988 #2004] DEBUG -- : [httplog] Header: expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
D, [2018-04-06T10:10:43.760014 #2004] DEBUG -- : [httplog] Header: server: cloudflare
D, [2018-04-06T10:10:43.760039 #2004] DEBUG -- : [httplog] Header: cf-ray: 40726fb2acd68ac2-KBP
D, [2018-04-06T10:10:43.760108 #2004] DEBUG -- : [httplog] Response:
{"meta":{"url":"http://api-svc.il/api/declaration_requests","type":"object","request_id":"c2236580-3dd9-4d32-81cf-8ebbd1196593#51157","code":500},"error":{"errors":{"detail":"Internal server error"}}}

**Comment by lymychp** [comment]
hotfix delivered to prod
