### ISSUE TITLE
provide settlement filtering by null disctrict

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#31]
Прошу создать end point "Settlements by region" - нас. пункты привязанные **_только_** к региону.

http://demo.ehealth.world/api/uaddresses/search/settlements?region=ЛЬВІВСЬКА&district=СОКАЛЬСЬКИЙ&settlement_name=ЛЬВІВ - возвращает нас. пункты с привязкой к области и району.
http://demo.ehealth.world/api/uaddresses/search/settlements?region=ЛЬВІВСЬКА&settlement_name=ЛЬВІВ - возвращает нас. пункты с привязкой к области и району и только к области. Но это логически неправильно. Если я не указал район, то и хочу получить нас. пункты области.

**Comment by AlekzandrV** [comment]
Если мы говорим про кеширование, то тогда предложение следующее. 
Полагаю, что поиск н.п. через регион не удобно для этого использовать.
1. В сервисе `http://demo.ehealth.world/api/uaddresses/search/settlements` region делаем не обязательным, что позволит выбирать все. 
2. Добавляем в response объект id всех сущностей

**Comment by pieskov** [comment]
Нет это не для кэширования.
Я сегодня в Хангаут объяснял.

Пример: есть 2- нес. пункта с одинаковым названием и одного типа. Один принадлежит области, а другой и области и району в этой области.
При выполнении 
http://demo.ehealth.world/api/uaddresses/search/settlements?region=<Region_Name>&settlement_name=<settl_name>? мы получим 2-ва этих нас. пункта, но в одном случае надо заполнять район в JSON и отображать район пользователю, а в другом нет.

**Comment by pzhuk** [comment]
@pieskov считаю утверждение "Если я не указал район, то и хочу получить нас. пункты области" в корне не верным с т.з. работы API.

Если район в запросе не указан, то это означает только то, что он не указан, и никак не то, что нужен поиск населенного пункта не привязанного административно к району.  

Но в данном случае, если наше понимание отличается, я не вижу проблемы реализовать ваш подход на уровне UI фильтрации. Если Вы считаете, что в данном случае, пункты без района не должны отображаться - реализуйте это с помощью фильтрации по полю `"district": null`

Пример объекта, который должен быть отфильтрован

 ```
   {
      "type": "CITY",
      "settlement_name": "ЛЬВІВ",
      "region": "ЛЬВІВСЬКА",
      "parent_settlement": null,
      "mountain_group": "false",
      "koatuu": "4610100000",
      "id": "26b390f1-0a31-47fa-8c1b-328b833729fc",
      **"district": null**
    },
```

**Comment by pieskov** [comment]
По Вашему лучше вытянуть 10000() нас. пунктов, а потом на клиенте фильтровать. Чем сразу вытянуть 1000 того что мне нужно, и не делать дополнительной нагрузки?

**Comment by pzhuk** [comment]
@warehousman , прошу поставить в беклог - фильтр по null полю district
