### ISSUE TITLE
Завантаження документів(Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#310]
## Request

https://storage.ehealth-ukraine.org/declaration-requests/f6ca10fb-6579-467a-9064-8b55fb9ab384/declaration_request_person.SSN.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=QBUj69Ukz9CqGN%2F20180406%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180406T103039Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=d989bc32049b5444339e758a8a08f87410c1a336a5240ad8186376f7e795fda8

## Responce
- [ ] <error>Unable to connect to the remote server</error>

До 10:46 повертався код 200, зараз такий респонс

**Comment by gmile** [comment]
@superjonh ваша проблема стабильно повторяется? Или это было временно?

Вы не могли бы приложить полную версию запроса? Идеально - в виде команды `curl` со всеми необходимыми параметрами.

Например:

```
curl -v -X PUT -H 'Content-Type: image/png' 'https://storage.ehealth-ukraine.org/issue-reproduction-bucket/1/abc.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=QBUj69Ukz9CqGN%2F20180406%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20180406T101705Z&X-Amz-Expires=7200&X-Amz-SignedHeaders=host&X-Amz-Signature=1fa361a6ded2aaa0ff008dafd5833cc2c3f600ca7d015af64dcca18a55d94279' -d @/Users/gmile/Downloads/22048046_10155430139778859_5078974392850399090_o.jpg
```

**Comment by superjonh** [comment]
@gmile @lymychp перевірте будь-ласка маршрут, чомусь тільки з деново показує таймаут, локально пробували з інших машин, таких проблем немає

![image](https://user-images.githubusercontent.com/24266717/38549983-f9c33a88-3cbd-11e8-899c-6e47917d9405.png)

**Comment by gmile** [comment]
@superjonh попробуйте, пожалуйста, еще раз

**Comment by gmile** [comment]
@superjonh какой айпи вашего сервера?

**Comment by superjonh** [comment]
@gmile 185.9.40.132

**Comment by gmile** [comment]
@superjonh попробуйте пожалуйста еще раз

**Comment by superjonh** [comment]
@gmile так, зараз працює
