### ISSUE TITLE
PROD помилка при підписанні

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#315]
## Steps to Reproduce (Repro steps)

- [ ] https://api.ehealth-ukraine.org/api/declaration_requests/af65484d-43c3-47c8-a0ac-2b530d17c609/actions/sign

## Actual result
- [ ] ```{
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests/af65484d-43c3-47c8-a0ac-2b530d17c609/actions/sign",
                    "type" : "object",
                    "request_id" : "f542b835-6efe-42a0-80f1-2c0af56a64ec#228761",
                    "code" : 422
                },
                "error" : {
                    "type" : "validation_failed",
                    "message" : "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
                    "invalid" : [ 
                        {
                            "rules" : [ 
                                {
                                    "rule" : null,
                                    "params" : [],
                                    "description" : "has already been taken"
                                }
                            ],
                            "entry_type" : "json_data_property",
                            "entry" : "$.id"
                        }
                    ]
                }
            }```

## Expected result
- [ ] перший раз отримуємо таку помилку, підажіть будь ласка, в чому проблема

**Comment by svetavedmed** [comment]
ошибка говорит, что уже есть декларация по данному declaration_request. 
Скорее всего из-за медленной работы digital_sign статус declaration_request не был изменен на signed
