### ISSUE TITLE
PROD помилка при логіні користувача

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#316]
користувачі при логіні отримують наступну помилку

![image 3](https://user-images.githubusercontent.com/29060924/38544928-77ec1c48-3cb1-11e8-91a9-764076460af9.png)

Нажаль детального логу дати не можемо

**Comment by lymychp** [comment]
була проблема з ресурсами - переконфігурили, має допомогти.

**Comment by sreva** [comment]
дякую
