### ISSUE TITLE
PROD помилка при логіні

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#317]
## Steps to Reproduce (Repro steps)

- [ ] https://auth.ehealth-ukraine.org
- [ ] користувач вводить логін + пароль, натискає "Далі" . Отримує відповідь http 304 і його сторінка просто перезагружається. 
Скрін скинув особистим повідомленням

**Comment by lymychp** [comment]
очистка кеша в клієнтському браузері має допомогти
