### ISSUE TITLE
PROD http 400 при підписанні декларації

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#318]
## Steps to Reproduce (Repro steps)

- [ ]https://api.ehealth-ukraine.org/api/declaration_requests/b5324a80-b833-4f13-b0f7-c584b53b5ca2/actions/sign

Отримали сьогодні першу таку помилку сьогодні в 2018-04-10 19:17:48.000

## Actual result
- [ ] ```{
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests/b5324a80-b833-4f13-b0f7-c584b53b5ca2/actions/sign",
                    "type" : "object",
                    "request_id" : "2329fb5d-8e35-45e8-9c46-020d288ec33d#123734",
                    "code" : 400
                },
                "error" : {
                    "type" : "request_malformed",
                    "message" : "loading information about the response with a timestamp failed",
                    "invalid" : [ 
                        {
                            "rules" : [ 
                                {
                                    "rule" : "json"
                                }
                            ],
                            "entry_type" : "request"
                        }
                    ]
                }
            }```

**Comment by gmile** [comment]
Закрываю, в чате получено подтверждение что все ОК.
