### ISSUE TITLE
PROD 503 або timed out  при POST /api/verifications/

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#320]
## Steps to Reproduce (Repro steps)

- [ ] https://api.ehealth-ukraine.org/api/verifications/

## Actual result
`{
                "meta" : {
                    "url" : "http://api-svc.verification/verifications/",
                    "type" : "object",
                    "request_id" : "0c0850fe-25c3-4cfd-bafb-4cc8b9ffa7bb#281492",
                    "code" : 503
                },
                "error" : {
                    "type" : "internal_error"
                }
            }
        }`

`{
            "status" : "error",
            "message" : "cURL error 28: Operation timed out after 10000 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",
            "statusCode" : 0
        }`

**Comment by lymychp** [comment]
sms service service has been restored
