### ISSUE TITLE
Валидация номера дома

### ISSUE THREAD

**Issue by Hamiltone** [ehealth-ua/api-spec#323]
## Steps to Reproduce (Repro steps)
При добавлении адреса ввести любой номер дома с буквой "і" 

## Actual result
- Не вірний формат номер будинку. Можливі формати: 25, 30А, 52-Б

## Expected result
- адрес успешно добавлен

**Comment by sreva** [comment]
Туди ж можна віднести 2-6/32, 26/30а корпус 2

**Comment by svetavedmed** [comment]
fix on dev

**Comment by svetavedmed** [comment]
fixed on prod
