### ISSUE TITLE
PROD Ошибка при отправке декларации (Does not match the signer DRFO)

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#324]
Ошибка при подписании: Does not match the signer DRFO

## Steps to Reproduce (Repro steps)

- [ ] Запрос:

[1 (2).txt](https://github.com/ehealth-ua/api-spec/files/1899081/1.2.txt)

## Actual result
- [ ] response:

![image](https://user-images.githubusercontent.com/20535372/38621004-9500b026-3da8-11e8-8961-13849ece7be8.png)

## Expected result
- [ ] Успех.

**Comment by svetavedmed** [comment]
Could you, please, send full log of request?

**Comment by lymychp** [comment]
@cshevchukod прошу надати докази, що ДРФО з ЕЦП повністю співпадає з ІПН користувача, який підписує декларацію

**Comment by cshevchukod** [comment]
Всё проверили. Спасибо за пояснения. С проблемой разобрались.
