### ISSUE TITLE
Не найдена декларация на ПРОДе

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#326]
D, [2018-04-12T11:28:03.033621 #6853] DEBUG -- : [httplog] Sending: GET http://api.ehealth-ukraine.org:443/api/declaration_requests/e1254c2f-48e4-4b2d-a1f1-98a9b6bb8503
D, [2018-04-12T11:28:03.033765 #6853] DEBUG -- : [httplog] Header: content-type: application/json
D, [2018-04-12T11:28:03.033799 #6853] DEBUG -- : [httplog] Header: authorization: Bearer ****************
D, [2018-04-12T11:28:03.033841 #6853] DEBUG -- : [httplog] Header: api-key: ******************
D, [2018-04-12T11:28:03.033865 #6853] DEBUG -- : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2018-04-12T11:28:03.033885 #6853] DEBUG -- : [httplog] Header: accept: */*
D, [2018-04-12T11:28:03.033905 #6853] DEBUG -- : [httplog] Header: user-agent: Ruby
D, [2018-04-12T11:28:03.033925 #6853] DEBUG -- : [httplog] Header: x-newrelic-id: VQ8FWFBbDxABVFJVDwACUVE=
D, [2018-04-12T11:28:03.033973 #6853] DEBUG -- : [httplog] Header: connection: close
D, [2018-04-12T11:28:03.034017 #6853] DEBUG -- : [httplog] Data: 
D, [2018-04-12T11:28:03.042860 #6853] DEBUG -- : [httplog] Status: 404

**Comment by svetavedmed** [comment]
данный  declaration_requests есть в базе в статусе signed. declaration_id = 3208cbc5-7034-4c27-b5d1-d45cc68e949a
