### ISSUE TITLE
Дублирование деклараций на ДЕНОВО

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#327]
Есть 2 декларации

0000-X8E6-A6P6
0000-P5XK-K26P

Обе активны. ИНН + документы + дата рождения - совпадают. Отличается только ИМЯ ибо в первой ошиблись.

**Comment by lymychp** [comment]
пошук відбуваєтсья якраз по комбінації ПІБ/ІПН/Дата народження
