### ISSUE TITLE
400 при регистрации медучреждения [PROD]

### ISSUE THREAD

**Issue by Hamiltone** [ehealth-ua/api-spec#328]
Регистрируем МСП и получаем следующее:
- {
           "meta" : {
               "url" : "http://api-svc.il/api/legal_entities",
               "type" : "object",
               "request_id" : "a4326d97-50b7-4b96-a521-549c8f7b186a#18517",
               "code" : 400
           },
           "error" : {
               "type" : "request_malformed",
               "message" : "OCSP certificate verificaton failed",
               "invalid" : [
                   {
                       "rules" : [
                           {
                               "rule" : "json"
                           }
                       ],
                       "entry_type" : "request"
                   }
               ]
           }
       }

Подписанный контент скинул @svetavedmed в личку

**Comment by dmmat** [comment]
У нас також така проблема можна деталі???

**Comment by dmmat** [comment]
@svetavedmed, @lymychp У нас також така проблема можна деталі???

**Comment by svetavedmed** [comment]
ошибка в том, что в самой подписи не верно указан URL для проверки OCSP сертификата `http://uakey.com.ua` а должна быть `http://uakey.com.ua/services/ocsp/`
