### ISSUE TITLE
Особый тип города Киев и поиск settlement

### ISSUE THREAD

**Issue by Zillot** [ehealth-ua/api-spec#33]
## Steps to Reproduce (Repro steps)

1. Выполнить поиск регионов
http://demo.ehealth.world/api/uaddresses/search/regions

2. Выполнить поиск районов
http://demo.ehealth.world/api/uaddresses/search/districts?region=М.КИЇВ

3. Выполнить поиск насенных пунктов по заранее заданым региону и району
http://demo.ehealth.world/api/uaddresses/search/settlements?region=М.КИЇВ&district=ГОЛОСІЇВСЬКИЙ

## Actual result
пустой список населенных пунктов

## Expected result
список доступних наленных пунктов, в этом кейсе только один, КИЕВ

Я понимаю что это кажеться не логичным, но для всех остальных районов это нормальный сценарий, например ВІННИЦЬКА -> ОРАТІВСЬКИЙ -> (много различних населенных пунктов)
http://demo.ehealth.world/api/uaddresses/search/settlements?region=ВІННИЦЬКА&district=ОРАТІВСЬКИЙ

Можно ли поменить такие регионы флагом говорящим о том что поиск по районам не даст результатов? Или во время поиска по районам отдавать населенные пункти у которых district == request.district && district == null даже если в параметрах запроса указан конкретный дистрикт?

**Comment by Zillot** [comment]
в добавление не смог найти город Днепр, думаю я что не так делаю(

**Comment by lymychp** [comment]
У м. Києва немає району
правильний пошук:
```
{{host}}/api/uaddresses/search/settlements?settlement_name=Київ&region=м.Київ
```

**Comment by lymychp** [comment]
приклад запиту для пошуку м. Дніпро
```
{{host}}/api/uaddresses/search/settlements?settlement_name=Дніпро&region=ДНІПРОПЕТРОВСЬКА&limit=50
```

**Comment by boris-lapouga** [comment]
Поддерживаю, в корне неверно возвращать пустое значение только для города Киев, когда выбран район.
У меня таким образом пришлось отказаться от фильтрации списка городов по району, потому что Киев вымудренный.

**Comment by Zillot** [comment]
из того что я понял большие города, в роде Днепра или Киева не имеют district, а значит бы их найти нужно НЕ указывать district в запросе, а так как выяснить какой город ищет пользователь, большой или поменьше не получиться, то выходит что district вообще нельзя использовать в запросе uaddresses/search/settlements иначе верных данных не получишь

и в добавок что тогда оставить в запросе api/legal_entities для например Днепра
...
			"settlement_type": "CITY",
			"settlement_id": "ee73597c-273d-457c-a01a-5c86f2904db4",
			"settlement": "ДНІПРО",
			"region": "ДНІПРОПЕТРОВСЬКА",
			"area": "???",  (area это тот же district в сервисе uaddresses)
...

**Comment by Zillot** [comment]
посмотрел в описание АПИ, area не обязательное поле, settlement_name в uaddresses/search/settlements может работать по частичному совпадению. Похоже я прост не буду использовать district

**Comment by lymychp** [comment]
пропоную закрити тікет

**Comment by pzhuk** [comment]
+

BR, Pavel V. Zhuk


2017-06-30 17:32 GMT+03:00 lymychp <notifications@github.com>:
