### ISSUE TITLE
pre-prod denovo http 500 при підписанні декларації

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#335]
## Steps to Reproduce (Repro steps)

- [ ] https://denovo.ehealth.world/api/declaration_requests/91b6d03c-de1d-4800-879c-2d46e8684cfc/actions/sign

[91b6d03c-de1d-4800-879c-2d46e8684cfc.txt](https://github.com/ehealth-ua/api-spec/files/1914125/91b6d03c-de1d-4800-879c-2d46e8684cfc.txt)

## Actual result
- [ ]  ```{
            "status" : "error",
            "message" : "Internal Server Error",
            "statusCode" : 500,
            "headers" : {
                "Cache-Control" : "max-age=0, private, must-revalidate",
                "Content-Length" : "249",
                "Content-Type" : "text/plain; charset=UTF-8",
                "Date" : "Fri, 13 Apr 2018 14:19:30 GMT",
                "Server" : "Cowboy",
                "Vary" : "Accept-Encoding",
                "Via" : "kong/0.12.1",
                "X-Content-Type-Options" : "nosniff",
                "X-Frame-Options" : "SAMEORIGIN",
                "X-Kong-Proxy-Latency" : "8",
                "X-Kong-Upstream-Latency" : "287",
                "X-Ratelimit-Limit-Minute" : "9000",
                "X-Ratelimit-Remaining-Minute" : "8994",
                "X-Request-Id" : "aa7cdc04-08a1-4089-bbab-35d4d136228a#4855",
                "X-Xss-Protection" : "1; mode=block"
            },
            "body" : {
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests/91b6d03c-de1d-4800-879c-2d46e8684cfc/actions/sign",
                    "type" : "object",
                    "request_id" : "aa7cdc04-08a1-4089-bbab-35d4d136228a#4855",
                    "code" : 500
                },
                "error" : {
                    "errors" : {
                        "detail" : "Internal server error"
                    }
                }
            }
        }
    }```

## Expected result
- [ ] відповідь відмінна від http 500

**Comment by lymychp** [comment]
should be fixed now
