### ISSUE TITLE
Declaration sign (token.consumer_id)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#336]
*Доброго дня, при підписанні декларації повертає наступну помилку, в лікаря серія та номер паспорту в полі tax_id.*

## Patch request to https://api.ehealth-ukraine.org/api/declaration_requests/{declaration_request_guid}/actions/sign

- [ ] data looks okay

## Actual result
- [ ] {"meta":{"url":"http://api-svc.il/api/declaration_requests/{declaration_request_guid}/actions/sign","type":"object","request_id":"e790a3bd-30ee-4c2f-b8de-d58264a3bd14#14286","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"invalid","params":[],"description":"Does not match the signer drfo"}],"entry_type":"json_data_property","entry":"$.token.consumer_id"}]}}

## Expected result
- [ ] signed declaration

More request data can sent private.

**Comment by svetavedmed** [comment]
error "Does not match the signer drfo" mean that person who is logged in to the system and is trying signing declaration_request and the person whose digital signature is used are two different persons.

**Comment by superjonh** [comment]
@svetavedmed дякую зрозуміло, перевірю запит в себе

**Comment by superjonh** [comment]
@svetavedmed перевірив токен запиту він власне відноситься до того лікаря і ЕЦП також виглядає відповідний, чи потрібні ще додаткові логи бо помилку вертає таку саму?
