### ISSUE TITLE
422: validation_failed

### ISSUE THREAD

**Issue by dmmat** [ehealth-ua/api-spec#337]
## Steps to Reproduce (Repro steps)

- [ ] `https://api.ehealth-ukraine.org/api/declaration_requests/7f80efeb-6149-4ce7-b2da-23e4fb353316/actions/sign`

- [ ] при цьому в реквесті є статус APPROVED, 
 
- [ ] request_id: `40ce0ccc-fa24-429d-b8e1-02f94690f12e#61574`

- [ ] При підписі декларації отримуємо: 

## Actual result
```JSON
"error": {
  "invalid": [{
    "entry": "$.status", 
    "entry_type": "json_data_property", 
    "rules": [{"description": "incorrect status", "params": [], "rule": "invalid"}]
  }]
}
```

## Expected result
 200

**Comment by svetavedmed** [comment]
ваш declaration_request в статусе SIGNED
Потому нельзя подписать ее второй раз
