### ISSUE TITLE
Declaration approve

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#338]
*Доброго дня, при підтвердженні заявки декларації отримую наступну помилку!*

Відповідно попередньо код прийшов і був підтверджений: 

{"meta":{"url":"http://api-svc.verification/verifications","type":"object","request_id":"0961ee7f-78ef-4786-b7cf-7967ea34ce06#67749","code":201},"data":{"status":"new","id":"f4f2dae3-ab3c-44e5-8a5b-b6eb6a37dce1","code_expired_at":"2018-04-16T13:09:34.295481Z","active":true}}

## Patch request to approve declaration 
- [ ] https://api.ehealth-ukraine.org/api/declaration_requests/{GUID_HERE}/actions/approve
- [ ] body with verification code

## Actual result
- [ ]{"meta":{"url":"http://api-svc.il/api/declaration_requests/{GUID_HERE}/actions/approve","type":"object","request_id":"e1db7d7a-9fa2-430a-9a2c-4d106a674e16#184874","code":403},"error":{"type":"forbidden","message":"Invalid verification code"}}

## Expected result
- [ ] approved declaration

**Comment by superjonh** [comment]
@svetavedmed тобто на approve declaration відповідно треба цей новий код, я так розумію??

**Comment by svetavedmed** [comment]
да, на апрув, если человек найден и authentication_methods=OTP, тогда поциенту на номер authentication_methods придет смс-ка, которую нужно ввести на апруве

**Comment by superjonh** [comment]
Гаразд, дякую.
