### ISSUE TITLE
[PROD] Проблема с апосрофом

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#339]
Проблема с апосрофом.

## Steps to Reproduce (Repro steps)

- [ ] Запрос на создание декларации

[129.txt](https://github.com/ehealth-ua/api-spec/files/1915692/129.txt)

## Actual result
- [ ] response
`
{"meta":{"url":"http://api-svc.il/api/declaration_requests","type":"object","request_id":"b8bceaad-5f7f-461e-a1cd-3ec6b1283c64#316186","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"format","params":["^(?!.*[ЫЪЭЁыъэё@%&$^#])[А-ЯҐЇІЄа-яґїіє\\'\\- ]+$"],"description":"string does not match pattern \"^(?!.*[ЫЪЭЁыъэё@%&$^#])[А-ЯҐЇІЄа-яґїіє\\\\'\\\\- ]+$\""}],"entry_type":"json_data_property","entry":"$.declaration_request.person.first_name"}]}}
`
## Expected result
- [ ] Успех.

**Comment by svetavedmed** [comment]
К сожалению, в приложеном вами файле из-за кодировки не видно, что именно вы передаете, но мы принимаем только апостроф в украинской раскладке - U+0027

**Comment by cshevchukod** [comment]
Всё именно так и передаём.

**Comment by svetavedmed** [comment]
а можете прислать лог запроса, подалуйста
