### ISSUE TITLE
Валідація аккредитації при створенні медичного закладу

### ISSUE THREAD

**Issue by ytrrty** [ehealth-ua/api-spec#34]
При створенні медичного закладу можна обрати пункт `без аккредитації`, але при цьому поле `order_no` є обов'язковим. Потрібно при створенні медичного закладу без аккредитації забирати валідацію на всі зв'язані з нею поля.

## Actual result
- `validation error: "equired property order_no was not present"`

## Expected result
- збереження медичного закладу без помилки

**Comment by AlekzandrV** [comment]
Дайте, пожалуйста, request_id

**Comment by ytrrty** [comment]
@AlekzandrV  
`jer5e3clejo2cukcp4ej6gmh99lu24v2`

**Comment by AlekzandrV** [comment]
Вы передаете объект аккредитация:
```
"accreditation": {
                    "category": "NO_ACCREDITATION"
                }
```

Но это не валидный объект аккредитации, так как обязательно кроме категории требуется номер.

Но вижу проблему связанную с наличием категории NO_ACCREDITATION, что противоречит со структурой.

Из справочника категорий это значение будет удалено.

В случае отсутствия аккредитации - не передавайте объект аккредитация

**Comment by pzhuk** [comment]
@lymychp please update spec according to this response. Accreditation is optional now?

**Comment by AlekzandrV** [comment]
I've updated scec. Accreditation is optional
