### ISSUE TITLE
403 при подтверждении декларации [PROD]

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#342]
Воспроизводится через раз. В основном у пациентов, у которых ранее уже был верифицирован номер телефона.

1. InitializeVerificationByPhone?phone=%2B38067XXXXX69

2. CompletePhoneVerification?phone=%2B38067XXXXX69&sms=XXXX

Ответ:
`
{"message":"success","responce":{"meta":{"url":"http://api-svc.verification/verifications/+380673066669/actions/complete","type":"object","request_id":"9a0cee5e-a6d1-4cab-a976-5b7b8e07c7a2#30828","code":200},"data":{"status":"verified","id":"c40e916a-85f5-4e4f-9558-92bcdb6dbe26","code_expired_at":"2018-04-17T11:34:13.659117Z","active":false}}}
`

3. ApproveDeclaration?ehealthId=b062dfa7-f016-4c3f-a85b-ace8f8aa57ee&sms=XXXX

Ответ:
`
{"message":"success","responce":{"meta":{"url":"http://api-svc.il/api/declaration_requests/b062dfa7-f016-4c3f-a85b-ace8f8aa57ee/actions/approve","type":"object","request_id":"9a0cee5e-a6d1-4cab-a976-5b7b8e07c7a2#30830","code":403},"error":{"type":"forbidden","message":"Maximum attempts exceed"}}}
`

**Comment by cshevchukod** [comment]
UPD По нашей логике с вашей стороны неверен текст "Maximum attempts exceed". Мы со своей стороны разобрались, но потратили на это кучу времени. Если нужны запросы скажите. Но по сути должен быть текст: "Invalid validation code" или аналогичный, потому что ошибка происходит при попытке апрува валидного номера с неверным кодом СМС.

**Comment by lymychp** [comment]
@cshevchukod 403 повертається якщо користувач ввів некоректний смс-код більше ніж дозволено разів. Тобто текст помилки `Maximum attempts exceed` якраз коректний. До того як ліміт спроб буде досягнуто повертається інша помилка
