### ISSUE TITLE
Ошибка при загрузке документа [PROD]

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#344]
Ошибка при загрузке документа. На предпроде не воспроизводится.

## Steps to Reproduce (Repro steps)
Загружаем:

## Actual result
- [ ] response
`
`
## Expected result
- [ ] Успех.

**Comment by lymychp** [comment]
@cshevchukod 
1) не варто на публічних ресурсах публікувати фото документів пацієнтів
2) знову ж таки, Ви на публічному ресурсі опублікували signed url для завантаження документу по декларації. Використовуючи даний url хто завгодно може що завгодно завантажити в центальний компонент по даній декларації.
3) прошу надати лог загрузки документу з текстом відповіді від серверу. Те, що Ви вказали - це респонс, а не реквест. Нагадую, що signed urls дійсні тільки протягом декількох годин.

**Comment by cshevchukod** [comment]
UPD: Выяснили, что https://storage.ehealth-ukraine.org/ с IP 185.41.249.132 не пингуется с 185.9.40.149. Из-за этого все проблемы. Можно это как-то исправить?

**Comment by cshevchukod** [comment]
Any updates?

**Comment by gmile** [comment]
@vsirius please add 185.9.40.149 to the whitelist on edge router

**Comment by vsirius** [comment]
@gmile done

**Comment by gmile** [comment]
@cshevchukod пожалуйста, попробуйте еще раз

**Comment by cshevchukod** [comment]
Спасибо. Сделано. + аналогичная проблема с 185.9.40.197.

**Comment by cshevchukod** [comment]
Спасибо. Сделано. + аналогичная проблема с 185.9.40.197. @gmile  @vsirius

**Comment by lymychp** [comment]
З яких ще IP будуть приходити запити на завантаження документів?

**Comment by cshevchukod** [comment]
185.9.40.165, 185.9.40.197, 185.9.41.58, 185.9.41.104, 185.9.40.149, 185.9.41.42, 185.9.40.196, 185.9.41.113

**Comment by gmile** [comment]
@cshevchukod проверьте, пожалуйста, несколько айпи из списка – работает ли пинг с них сейчас

**Comment by cshevchukod** [comment]
@gmile  185.9.40.197 и 185.9.40.165 всё ещё не пингует.

**Comment by cshevchukod** [comment]
@gmile @lymychp @vsirius 185.9.40.197 и 185.9.40.165 всё ещё не пингует.

**Comment by cshevchukod** [comment]
И заодно так же требуется открыть ПРЕДПРОД для 52.178.33.223. Так же столкнулись сегодня с аналогичной проблемой.

**Comment by gmile** [comment]
@cshevchukod добавали адреса из подсетей `185.9.40.х` и `185.9.41.х`. Проверьте, пожалуйста с вашей стороны.

**Comment by gmile** [comment]
@cshevchukod касательно 52.178.33.223, вы не могли бы показать детальный вывод команды `curl`. Пример того что требуется – вот тут: https://github.com/ehealth-ua/api-spec/issues/310#issuecomment-379281452

**Comment by gmile** [comment]
@cshevchukod касательно 52.178.33.223, вы могли бы предоставить больше информации? Меня интересует вывод `curl`, как в примере https://github.com/ehealth-ua/api-spec/issues/310#issuecomment-379281452
