### ISSUE TITLE
Declaration sign(Prod, token.consumer_id)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#345]
===Доброго дня перевірте будь-ласка підписання декларації, зновштаки лікар без ІПН====  
  
## Patch request 

- [ ] https://api.ehealth-ukraine.org/api/declaration_requests/{id_here}/actions/sign

## Actual result
- [ ] {"meta":{"url":"http://api-svc.il/api/declaration_requests/{id_here}/actions/sign","type":"object","request_id":"51795241-ed15-480e-94ce-f86020a8a73c#51928","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"invalid","params":[],"description":"Does not match the signer drfo"}],"entry_type":"json_data_property","entry":"$.token.consumer_id"}]}}>

## Expected result
- [ ] signed declaration.

**Comment by superjonh** [comment]
@svetavedmed деталі запиту надіслав в приват!

**Comment by svetavedmed** [comment]
в подписи указано неверное дрфо, с использованием латинский букв = KS639891
