### ISSUE TITLE
Declaration_request create (Question)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#346]
*Доброго дня, наступне питання, що зазначити у адресі декларації, коли у пацієнта в паспорті не вказано вулиці і відповідно будинку, тільки населений пункт (село наприклад)*

## Declaration request create

- [ ] part with addresses

## Actual result
- [ ] building is required

## Expected result
- [ ] solution

**Comment by svetavedmed** [comment]
без номера дома зарегистрироваться нельзя. В таком случае следует спросить, где живет человек
