### ISSUE TITLE
UADresses mismstach for Васильків - missing district

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#35]
- [*] endpoint address
api.ehealth.world

- [*] preconditions if any
No preconditions

- [*] sequence of actions that should be taken to reproduce the behavior.

- [*] test data, requests examples, json files, curl requests etc

```
GET /api/uaddresses/search/settlements?settlement_name=ВАСИЛЬКІВ&amp;region=КИЇВСЬКА HTTP/1.1
Host: api.ehealth.world

```
## Actual result
```
  "data": [
    {
      "type": "CITY",
      "settlement_name": "ВАСИЛЬКІВ",
      "region": "КИЇВСЬКА",
      "parent_settlement": null,
      "mountain_group": "false",
      "koatuu": "3210700000",
      "id": "2564ff1f-6659-4af3-98bc-e74d6e49660d",
      **"district": null**
    }
```

## Expected result

District should not be null, according to KOATUU

**Comment by lymychp** [comment]
згідно КОАТУУ, Васильків - місто обласного підпорядкування - нема в нього району
<img width="601" alt="screen shot 2017-06-19 at 11 22 48 am" src="https://user-images.githubusercontent.com/5257001/27275787-ac81dc30-54e1-11e7-9929-d8dc3d090635.png">

So actual result = expected result. No issues)
