### ISSUE TITLE
Помилка авторизації лікаря

### ISSUE THREAD

**Issue by ytrrty** [ehealth-ua/api-spec#350]
## Steps to Reproduce (Repro steps)
Лікаря було зареєстровано в базі, він успішно авторизувався і стоврив близько 40-ка декларацій. Коли закінчився термін дії токену, лікар пробує авторизуватись і отримує помилку
```
invalid_user (type)
User not found. (message)
```
Перед цим цього лікаря було деактивовано і перереєстровано знову (тобто в базі по цій людині є 2 employee - зі статусами `APPROVED` та `DISMISSED`). 
Також така проблема зустрічалась з іншими лікарями, які раніше були деактивовані та створені заново з різних причин.

## Actual result
```
{  
  "meta":{  
    "url":"http://api-svc.mithril/oauth/apps/authorize",
    "type":"object",
    "request_id":"01ea7bff-1ca5-4c5b-88fe-a93e14b79a67#281341",
    "code":401
  },
  "error":{  
    "type":"invalid_user",
    "message":"User not found."
  }
}
```

## Expected result
Успішна авторизація

**Comment by strohush** [comment]
Та ж помилка.
http://prntscr.com/jw8smv
вже два тижні лікар не може працювати в системі через неї.

**Comment by strohush** [comment]
Що необхідно для вирішення цього, двомісячного токена?
Можливо ми якось можемо допомогти щоб його закрити нарешті?

**Comment by ioleksiy** [comment]
@warehousman це схоже на кейс, що ми сьогодні розбирали

**Comment by svetavedmed** [comment]
Виправили дану помилку
