### ISSUE TITLE
Помилки в печатній формі

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#353]
Це пре-прод, на проді ситуація аналогічна
1. Для Києва і Севастополя не має печататись область
![default](https://user-images.githubusercontent.com/29060924/39060191-62f6d0e2-44c9-11e8-8248-95f243f384d4.png)
2. Не заповнюється район 
![default](https://user-images.githubusercontent.com/29060924/39060231-799a904a-44c9-11e8-8b64-868da89f991c.png)
3. Не печатається 2-ий представник / опікун
![2-](https://user-images.githubusercontent.com/29060924/39060292-a102a6fe-44c9-11e8-9ba8-987c4bf82e5e.png)

Для кейсів 2 і 3 ось заявка на декларацію 

declaration_request_id c8f4c76a-8b1b-4400-9da9-0abcbe0cdca4
declaration_id = 0f6a7db5-93cb-4ac8-aedc-231578a34d39

**Comment by lymychp** [comment]
1) Такі дані в КОАТУУ
2) поправили довідник
3) в формі декларації нема блоіку для другого представника(

**Comment by sreva** [comment]
1. Тоді напевно потрібно якось поправити текст в печатній формі, так як там сказано (не запонюється для міст Києва і Севастополя)
2. Дякую
3. Немає на даний момент, чи взагалі він там не планується?

**Comment by lymychp** [comment]
1. Мабуть, потрібно
3. Не планувався

**Comment by cshevchukod** [comment]
По пункту 2. Есть аналогичная проблема. Район КОЗЕЛЕЦЬКИЙ.

_Тип та назва населеного пункту: місто ОСТЕР
Район: (не заповнюється для міст обласного значення) ––
Область: ЧЕРНІГІВСЬКА_

**Comment by Evgeniy0119** [comment]
Тоже есть декларации в которых не тянется район

**Comment by svetavedmed** [comment]
@Evgeniy0119 данная ошибка уже должна быть исправлена. Можно подробности, пожалуйста?

**Comment by Evgeniy0119** [comment]
да, получу requst отпишусь

**Comment by lymychp** [comment]
інформацію не надано
