### ISSUE TITLE
У випадку звільнення лікаря і повторного прийняття на роботу з різними email в декларацію печатається email першого співробітника

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#354]
## Steps to Reproduce (Repro steps)
1. Створюємо 1-го співробітника employee_id = 4a59d9b7-e306-4daa-9295-47848b848021
2. Звільняємо його 
3. Створюємо 2-го співробітника employee_id = 19fef5a4-8c5e-43f1-af30-a5e6439c45ac
4. Створюємо декларацію для цього лікаря і печатній формі бачимо email звільненого користувача
declaration_id = d23f4b81-c162-498d-b683-f6debf9d585d
declaration_request_id = e3c1f129-fe58-4c14-9dac-3b6a794da71a

## Expected result
- [ ] в декларації немає email звільненого співробітника

**Comment by dmmat** [comment]
при зміні телефону, теж старий в друці декларації.

**Comment by cshevchukod** [comment]
Периодически сталкиваемся и на PREPROD, и на PROD.

**Comment by cshevchukod** [comment]
https://github.com/ehealth-ua/api-spec/issues/289

**Comment by lymychp** [comment]
email - атрибут користувача. У одного `party` може бути декілька користувачів.
У одного `party` може бути декілька employee.  Якщо одна і та ж особа була прийната-звільнена-повторно прийнята на роботу, і кожного разу з новим email, то в результаті отримаємо:
- один запис в party, з яким зв'язані три користувачі
- три записи в employee, один з яких активний

В системі немає обмежень на використання облікових записів користувачів тільки в прив'язці з конкретним employee. Така була бізнес-вимога.
Тому немає можливості в друкованій формі друкувати саме той email, який використовувався при реєстрації employee, з яким оформлюється декларація.

Як рішення, пропоную в друкованій формі друкувати email підрозділу, а не користувача.

@dmmat Щодо номерів телефонів - прошу зареєструвати окремий тікет з деталями

**Comment by lymychp** [comment]
delivered to preprod

**Comment by lymychp** [comment]
delivered to prod
