### ISSUE TITLE
Prod відсутність відповіді при підписанні декларації

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#356]
## Steps to Reproduce (Repro steps)

- [ ] https://api.ehealth-ukraine.org/api/declaration_requests/13f4c483-8425-4f1e-aa18-dc86bd32d6ae/actions/sign"

## Actual result
- [ ] ```{ 
            "status" : "error",
            "message" : "cURL error 28: Operation timed out after 10001 milliseconds with 0 out of -1 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",
            "statusCode" : 0
        }```

## Expected result
- [ ] відповідь отримали

**Comment by PavelVesnin** [comment]
tl;dr - increase timeout. Request successfully completed after 13 seconds

Full description of issue you can find [here](https://github.com/edenlabllc/ehealth.api/issues/2209)
