### ISSUE TITLE
[PREPROD] Не приходит СМС при подтверждении декларации

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#357]
https://denovo.ehealth.world/api/declaration_requests

## Steps to Reproduce (Repro steps)

- [ ] Request

[Request.txt](https://github.com/ehealth-ua/api-spec/files/1937827/Request.txt)

## Actual result

- [ ] Response

[Response.txt](https://github.com/ehealth-ua/api-spec/files/1937829/Response.txt)

## Expected result
- [ ] Успех.

**Comment by lymychp** [comment]
```

  "urgent": {
    "authentication_method_current": {
      "type": "NA"
```
означає, що в даному випадку смс не треба

**Comment by cshevchukod** [comment]
ОК, но тогда не меняется статус реквеста на Approve. Как подтверждать в этом случае?

**Comment by lymychp** [comment]
треба все рівно зробити approve, просто без OTP
