### ISSUE TITLE
Не приходять коди підтвердження на номери телефонів.

### ISSUE THREAD

**Issue by LevOshchypok** [ehealth-ua/api-spec#360]
Не приходять коди підтвердження у смс.

Request 
{           "phone_number": "+380638877917"         }

Response
{
  "meta": {
    "url": "http://api-svc.verification/verifications",
    "type": "object",
    "request_id": "86123452-0900-4e1a-b538-1d606748d40b#122822",
    "code": 201
  },
  "data": {
    "status": "new",
    "id": "913c7aa0-30f6-41a9-8b3d-3faf8c11a0f8",
    "code_expired_at": "2018-04-24T10:28:06.091114Z",
    "active": true
  }
}

**Comment by lymychp** [comment]
SMS було відправлено 2018-04-24T10:13:06.179059168
SMS було доставлено 2018-04-24 10:22:53.000000
