### ISSUE TITLE
Pre-prod http 500 на GET api/employees

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#362]
## Steps to Reproduce (Repro steps)

- [ ] https://denovo.ehealth.world/api/employees?employee_type=DOCTOR&status=APPROVED'

## Actual result
- [ ] ```{
    "meta": {
        "url": "http://api-svc.il/api/employees",
        "type": "object",
        "request_id": "09b15ef5-6771-4cba-bf13-1259cfc12cea#6432",
        "code": 500
    },
    "error": {
        "errors": {
            "detail": "Internal server error"
        }
    }
}```

## Expected result
- [ ] не http 500

**Comment by svetavedmed** [comment]
fixed
