### ISSUE TITLE
Невозможно обновить пользователя [PROD]

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#364]
Пользователь ранее был зарегистрирован в другой МИС. Клиника сменила МИС. Пользователя заводят повторно с таким же имейлом для заведение и обновления. Всё успешно и только на эапе подтверждения получаем скрин:

![image](https://user-images.githubusercontent.com/20535372/39305284-31982b72-4965-11e8-953a-0d0c5d1a12c8.png)

Подробности кину в личку.

## Steps to Reproduce (Repro steps)

- [ ] employee_request 
- [ ] врач получает на email письмо для подтверждения
- [ ] переходит по ссылке из письма, вводит пароль и соглашается с регламентом

## Actual result
- [ ] "Даний електрониий адрес уже використовується іншою особою"
BTW! Правильно: "електронна адреса"

## Expected result
- [ ] "Ви успішно зареєстровані"

**Comment by lymychp** [comment]
@cshevchukod ІПН + дата народження точно співпадають?

**Comment by lymychp** [comment]
головний лікар або HR може переглянути інформацію про усіх співробітників, в тому числі, зареєстрованих через попередній МІС

**Comment by lymychp** [comment]
дана помилка означає, що email вже використовуєтсья особою з ІПН+дата народження, що відрізняються від введених
