### ISSUE TITLE
Верификация декларации по номеру телефона [prod/bug]

### ISSUE THREAD

**Issue by Hamiltone** [ehealth-ua/api-spec#365]
## Steps to Reproduce (Repro steps)
- Иметь заключеную декларацию с пациентом, которая верифицировалась через смс.
- Создать новую декларацию на этого же пациента, но уже с другим номером телефона.
- Верифицировать 

## Actual result
- Получаем СМС на номер телефона, указанный в заключеной декларации.

## Expected result
- Получаем СМС на введеный при создании декларации номер.

*JSON`s
-- реквест первой декларации (что была заключена в итоге) 
"meta" : {
            "url" : "http://api-svc.il/api/declaration_requests",
            "type" : "object",
            "request_id" : "006cda12-7e0e-4b28-88e3-4cd2031b7aa3#118658",
            "code" : 200
        }
-- реквест второй  декларации (уже с другим номером телефона)
"meta" : {
            "url" : "http://api-svc.il/api/declaration_requests",
            "type" : "object",
            "request_id" : "9ef10c5f-4b1a-4e96-8db4-21c2e41aac87#17836",
            "code" : 200
        }

**Comment by lymychp** [comment]
actual result is the expected one
