### ISSUE TITLE
[PROD] Смена телефона для ОТP в ранее подписанной декларации

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#367]
При смене номера телефона для ОТP и попытке завести новую декларацию СМС  приходит на старый номер.

## Steps to Reproduce (Repro steps)

- [ ] Создаю и подписываю декларацию.
- [ ] Редактирую телефон для ОТP.
- [ ] Создаю новую декларацию с новыми данными по ОТP.

## Actual result
- [ ] SMS приходит на старый номер

## Expected result
- [ ] SMS приходит на новый номер

Подробности скину в личку.

**Comment by cshevchukod** [comment]
ОК. Но при последующем обновлении декларации на какой номер будет приходит СМС? Но то, что был в последней предыдущей декларации?

**Comment by cshevchukod** [comment]
СПС.

**Comment by lymychp** [comment]
після підписання нової декларації новий телефон буде прописаний як телефон авторизації. Відповідно при підписанні третьої декларації, смс буде приходити вже на другий телефон
