### ISSUE TITLE
Пре-прод Невірна кількість declaration_count в get /api/employees

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#368]
## Steps to Reproduce (Repro steps)

- [ ] GET https://denovo.ehealth.world/api/employees/78b2444e-66e9-4ed1-9309-310222a356f2

## Actual result
- [ ] Повертається declaration_limit - 80, declaration_count - 55. Відповідно лікар вкладається в ліміт. По запиту на активні декларації цього користувача - їх 83

## Expected result
- [ ] повертається правильна кількість декларацій

**Comment by lymychp** [comment]
@sreva fixed and delivered to prod
