### ISSUE TITLE
тест3 - Підкажіть будь ласка REST API пошуку вулиці в населеному пункті.

### ISSUE THREAD

**Issue by romanm** [ehealth-ua/api-spec#37]
Підкажіть будь ласка REST API пошуку вулиці в населеному пункті.

Список областей і пошук населеного пункту в області працюють добре.
/uaddresses/search/regions
/uaddresses/search/settlements?settlement_name=уши&region=хмельницька
demo
http://medic.algoritmed.com/v/testMvpAddress
дубляж
https://github.com/romanm/algoritmed-mvp1-ehealth/issues/5

**Comment by lymychp** [comment]
вулиці ще не релізнуті
