### ISSUE TITLE
Відправка смс при перезаключенні декларації

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#370]
Опис ситуації 
1) Заключено декларацію declaration_id - 43989c48-4c3e-49dc-b502-5623a75bcf5f
2) Лікар і пацієнт через пів години, після підписання, зрозуміли що вказали невірно По-батькові і вирішили перезаключити декларацію.
3) Спроб перезаключити було декілька у всіх спосіб аутентифікації - ОТР 
create_date - 2018-04-27 13:33:39.000Z - declaration_request_id - 13d24380-8642-4fd4-8fea-6f9d2eb197e4
create_date - 2018-04-27 13:46:04.000Z - declaration_request_id - 4a4c9154-7bf7-4ebb-96cc-b03f043df347
create_date -  2018-04-30 10:26:47.000Z - declaration_request_id - e1067c27-129c-4b71-802d-efb9c36c0722
create_date - 2018-04-30 10:32:02.000Z - declaration_request_id - fe4074ce-d7a0-460f-b803-306ac1bfa5d9

Прохання перевірити, чи відправлялись СМС і який статус їх доставки

**Comment by lymychp** [comment]
@sreva прошу надати request_id будь-якої зі спроб перезаключення декларації і текст респонсу

**Comment by sreva** [comment]
declaration_request_id - e1067c27-129c-4b71-802d-efb9c36c0722 
`{
                "urgent" : {
                    "authentication_method_current" : {
                        "type" : "OTP",
                        "number" : "+38068*****76"
                    }
                },
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests",
                    "type" : "object",
                    "request_id" : "5efcae6b-f644-4871-a42f-596a55324f0b#50766",
                    "code" : 200
                }`


declaration_request_id - fe4074ce-d7a0-460f-b803-306ac1bfa5d9

`{
                "urgent" : {
                    "authentication_method_current" : {
                        "type" : "OTP",
                        "number" : "+38068*****76"
                    }
                },
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests",
                    "type" : "object",
                    "request_id" : "40a2a3f2-6e6c-4102-be28-811077c7355d#64118",
                    "code" : 200
                }`

**Comment by sreva** [comment]
дякую
