### ISSUE TITLE
PROD 401 при /admin/roles

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#371]
## Steps to Reproduce (Repro steps)

- [ ]  GET  https://api.ehealth-ukraine.org/admin/roles

## Actual result
- [ ] ```{
    "meta": {
        "url": "http://api.ehealth-ukraine.org:8000/admin/roles",
        "code": 401,
        "request_id": "2233f015-d0d7-4307-89db-9e2fe829ddda#432535",
        "type": "object"
    },
    "error": {
        "message": "Invalid access token",
        "type": "access_denied"
    }
}```

## Expected result
- [ ] ролі повернулись

**Comment by gmile** [comment]
@sreva please, try again.

**Comment by sreva** [comment]
@gmile результат той же

**Comment by gmile** [comment]
@sreva проверьте пожалуйста еще раз

**Comment by sreva** [comment]
@gmile 
```
{
    "meta": {
        "url": "http://api.ehealth-ukraine.org:8000/admin/roles",
        "code": 401,
        "request_id": "5949a041-f169-4d14-8ff2-6b3e42ba436c#52518",
        "type": "object"
    },
    "error": {
        "message": "Invalid access token",
        "type": "access_denied"
    }
}
```

**Comment by gmile** [comment]
@sreva попробуйте еще раз

**Comment by sreva** [comment]
Завелось 
дуже дякую

**Comment by ytrrty** [comment]
@gmile в мене досі не працює
```
{
    "meta": {
        "url": "http://api.ehealth-ukraine.org:8000/admin/roles",
        "code": 401,
        "request_id": "824580ff-0d88-4766-b6d6-1908b20b8e09#28596",
        "type": "object"
    },
    "error": {
        "message": "Invalid access token",
        "type": "access_denied"
    }
}
```
