### ISSUE TITLE
prod http 500 при POST /api/declaration_requests

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#372]
## Steps to Reproduce (Repro steps)

- [ ] POST  https://api.ehealth-ukraine.org/api/declaration_requests

## Actual result
- [ ] `{
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests",
                    "type" : "object",
                    "request_id" : "27235fe4-471b-43c7-8ba0-86b35a1c9258#8142",
                    "code" : 500
                },
                "error" : {
                    "errors" : {
                        "detail" : "Internal server error"
                    }
                }`

## Expected result
- [ ] Не http 500

**Comment by ioleksiy** [comment]
Чи актуальне ще питання?

**Comment by sreva** [comment]
не актуальне
