### ISSUE TITLE
Prod http 500 при GET /api/persons

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#374]
## Steps to Reproduce (Repro steps)

- [ ] /https://api.ehealth-ukraine.org/api/persons  (при потребі повний урл можу скинути особистим повідомленням)

## Actual result
- [ ] ` {
                        "status" : "error",
                        "message" : "Internal Server Error",
                        "statusCode" : 500,
                        "headers" : {
                            "Server" : "nginx/1.13.12",
                            "Date" : "Wed, 02 May 2018 16:50:07 GMT",
                            "Content-Type" : "text/plain; charset=UTF-8",
                            "Content-Length" : "186",
                            "Connection" : "keep-alive",
                            "Set-Cookie" : "__cfduid=d14f9a50996bf5b764ff1f40e00cd34091525279806; expires=Thu, 02-May-19 16:50:06 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure",
                            "Cache-Control" : "max-age=0, private, must-revalidate",
                            "Vary" : "Accept-Encoding",
                            "Via" : "kong/0.12.1",
                            "X-Content-Type-Options" : "nosniff",
                            "X-Download-Options" : "noopen",
                            "X-Frame-Options" : "SAMEORIGIN",
                            "X-Kong-Proxy-Latency" : "11",
                            "X-Kong-Upstream-Latency" : "47",
                            "X-Permitted-Cross-Domain-Policies" : "none",
                            "X-Ratelimit-Limit-Minute" : "9000",
                            "X-Ratelimit-Remaining-Minute" : "8997",
                            "X-Request-Id" : "8c9127a1-7be2-47dd-89b9-b747ff175c47#2778",
                            "X-Xss-Protection" : "1; mode=block",
                            "Expect-CT" : "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
                            "CF-RAY" : "414bfc296d4a647b-FRA"
                        },
                        "body" : {
                            "meta" : {
                                "url" : "http://api-svc.il/api/persons",
                                "type" : "object",
                                "request_id" : "8c9127a1-7be2-47dd-89b9-b747ff175c47#2778",
                                "code" : 500
                            },
                            "error" : {
                                "errors" : {
                                    "detail" : "Internal server error"
                                }
                            }
                        }
                    }`

## Expected result
- [ ] не http 500

**Comment by ioleksiy** [comment]
Чи актуальне ще питання?
