### ISSUE TITLE
Pre-Prod проблеми при зміні пароля

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#375]
## Steps to Reproduce (Repro steps)

- [ ] https://auth-denovo.ehealth.world/sign-in

1) натиснути "Змінити пароль"
2) Ввести логін пароль для s.reva+d1@helsi.me 

## Actual result

![image](https://user-images.githubusercontent.com/29060924/39541421-5d77df60-4e4e-11e8-82dc-5541f569d769.png)
при тому що з цим паролем і логіном в систему логінюсь успішно
![image](https://user-images.githubusercontent.com/29060924/39541491-8fbe1ef8-4e4e-11e8-81d6-39ffeebfa36d.png)

## Expected result
- [ ] успішно змінив пароль

**Comment by lymychp** [comment]
@svetavedmed please try to reproduce on preprod

**Comment by svetavedmed** [comment]
can't reproduce it
