### ISSUE TITLE
PROD 401 при /admin/roles

### ISSUE THREAD

**Issue by ytrrty** [ehealth-ua/api-spec#376]
## Steps to Reproduce (Repro steps)

`GET` `https://api.ehealth-ukraine.org/admin/roles`

## Actual result
```
{
    "meta": {
        "url": "http://api.ehealth-ukraine.org:8000/admin/roles",
        "code": 401,
        "request_id": "c5eb5703-0cc7-46ae-9161-8cc795da34c0#16312",
        "type": "object"
    },
    "error": {
        "message": "Invalid access token",
        "type": "access_denied"
    }
}
```
## Expected result
Працюючий МІС-токен, який повертає список ролей

**Comment by lymychp** [comment]
Reason: token has been expired. 
Solution: we have extended it. Now it should work. But for future you should reissue MIS token at least once per month using standard oauth2.0 flow
