### ISSUE TITLE
Заклад відносить до Криму

### ISSUE THREAD

**Issue by strohush** [ehealth-ua/api-spec#378]
Заклад
https://portal.ehealth-ukraine.org/divisions.html#/?page=1&legal_entity_edrpou=39153910
Знаходиться в Мукачено (закарпатська обл)
З сторони eHealth йде запит що бачуть заклад зареєстрованим в Криму.

1) Чому так?
2) Як репродюснути щоб ми теж могли бачити з сторони ехелсу де зареєстрований сам заклад а не лише відділення?

П.С. повторну вигрузку самого закладу робили - всерівно ситуація не змінилась.
http://prntscr.com/jd4t6b

**Comment by lymychp** [comment]
```
curl -X GET \
  https://api.ehealth-ukraine.org/api/legal_entities \
```

**Comment by strohush** [comment]
{"status":"success","statusCode":200,"message":"","message_type":"success","data":{"website":null,"updated_by":"c23f67b0-c555-4785-9a68-39926ea4f418","updated_at":"2018-05-03T12:29:04.560340","type":"MSP","status":"ACTIVE","short_name":"\u041c\u0415\u0414\u0418\u0427\u041d\u0418\u0419 \u0426\u0415\u041d\u0422\u0420 \"\u0412\u0406\u0422\u0410\u041b\u0406\u041d\u0415","receiver_funds_code":null,"public_name":"\u041f\u0420\u0418\u0412\u0410\u0422\u041d\u0415 \u041f\u0406\u0414\u041f\u0420\u0418\u0404\u041c\u0421\u0422\u0412\u041e \"\u041c\u0415\u0414\u0418\u0427\u041d\u0418\u0419 \u0426\u0415\u041d\u0422\u0420 \"\u0412\u0406\u0422\u0410\u041b\u0406\u041d\u0415\"","phones":[{"type":"MOBILE","number":"+380505437125"}],"owner_property_type":"PRIVATE","nhs_verified":false,"name":"\u041f\u0420\u0418\u0412\u0410\u0422\u041d\u0415 \u041f\u0406\u0414\u041f\u0420\u0418\u0404\u041c\u0421\u0422\u0412\u041e \"\u041c\u0415\u0414\u0418\u0427\u041d\u0418\u0419 \u0426\u0415\u041d\u0422\u0420 \"\u0412\u0406\u0422\u0410\u041b\u0406\u041d\u0415\"","mis_verified":"NOT_VERIFIED","medical_service_provider":{"licenses":[{"what_licensed":"\u041f\u0420\u0418\u0412\u0410\u0422\u041d\u0415 \u041f\u0406\u0414\u041f\u0420\u0418\u0404\u041c\u0421\u0422\u0412\u041e \"\u041c\u0415\u0414\u0418\u0427\u041d\u0418\u0419  \u0426\u0415\u041d\u0422\u0420 \"\u0412\u0406\u0422\u0410\u041b\u0406\u041d\u0415\"","order_no":"342","license_number":"459778","issued_date":"2014-06-11","issued_by":"\u041c\u0406\u041d\u0406\u0421\u0422\u0415\u0420\u0421\u0422\u0412\u041e \u041e\u0425\u041e\u0420\u041e\u041d\u0418 \u0417\u0414\u041e\u0420\u041e\u0412\u042f","active_from_date":"2014-05-21"}],"accreditation":null},"legal_form":"120","kveds":["86.10"],"is_active":true,"inserted_by":"c23f67b0-c555-4785-9a68-39926ea4f418","inserted_at":"2018-04-16T09:22:57.306331","id":"4f3d0924-4db9-4b8b-b7dc-7369e12f70e5","email":"vitaline.mukachevo@gmail.com","edrpou":"39153910","beneficiary":null,"archive":null,"addresses":[{"zip":"89600","type":"REGISTRATION","street_type":"STREET","street":"\u041d\u0435\u0434\u0435\u0446\u0435\u0457","settlement_type":"CITY","settlement_id":"6db1fb99-6234-4e1e-be22-79a87a2298fb","settlement":"\u041c\u0423\u041a\u0410\u0427\u0415\u0412\u0415","country":"UA","building":"10","area":"\u0417\u0410\u041a\u0410\u0420\u041f\u0410\u0422\u0421\u042c\u041a\u0410","apartment":""}]},"redirectTo":false,"errors":[]}

**Comment by strohush** [comment]
http://prntscr.com/jdnkxq

**Comment by lymychp** [comment]
2018-05-03 12:29:04.565649 - дата оновлення адреси по даному МЗ. 
А до цього часу був Крим
@strohush наступного разу прохання уважно перевіряти інформацію перед тим як реєструвати тікет

**Comment by strohush** [comment]
Декілька раз перезаливали - виявилось головний лікар по лінку в мейлі "не клікнув". 
Хоч казав що клікав.
Тому оновлення і не відбулось.
Вже проконтролювали весь процес і тепер ОК.

**Comment by kostikehealth** [comment]
На мапі все ще поінт в Криму

**Comment by MarkInvince** [comment]
Можете скинути посилання, де видно, що заклад в Криму?

**Comment by kostikehealth** [comment]
https://portal.ehealth-ukraine.org на мапі

пт, 4 мая 2018 г., 16:50 MarkInvince <notifications@github.com>:

**Comment by lymychp** [comment]
![image](https://user-images.githubusercontent.com/5257001/39631769-ca83b5ca-4fbb-11e8-9c8d-b218a1c79556.png)
0 медзакладів

**Comment by MarkInvince** [comment]
В мене там пише Мукачево
Ось відповідь з eHealth - http://prntscr.com/jdosh0
І тут Мукачево - https://portal.ehealth-ukraine.org/divisions.html#/?legal_entity_edrpou=39153910&page=1

Перевірте ще раз

**Comment by kostikehealth** [comment]
Як лікаря видалити/перенести?

пт, 4 мая 2018 г., 16:54 lymychp <notifications@github.com>:

**Comment by lymychp** [comment]
лікар не з цього закладу
