### ISSUE TITLE
Доопрацювання методу Show Login UI 

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#38]
Прохання додати параметр email в метод Show Login UI.
Очікуваний результат: в даному параметрі ми передаємо email користувача і він автоматично підставляється на формі логіна в поле логін.

**Comment by pzhuk** [comment]
@warehousman can we put this unti development? Looks like relatively small change which is not affecting any backend processes

**Comment by warehousman** [comment]
As CR this should be moved to health.api repo
