### ISSUE TITLE
Як скинути метод верифікації?

### ISSUE THREAD

**Issue by zackkozac** [ehealth-ua/api-spec#380]
Як скинути метод верифікації (людина втратила телефон)?

## Steps to Reproduce (Repro steps)

При перереєстрації декларації, СМС приходить на номер вказаний у попередній.

## Expected result
Мати можливість змінити номер телефон у верифікації при відсутності старого номеру.

**Comment by lymychp** [comment]
через АПІ - ніяк. Тільки через звернення в НСЗУ чи ДП. Процедуру краще уточнити в МОЗ
