### ISSUE TITLE
Завершення реєстрації МІС Helsi

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#381]
Не отримали: 
1) логін/пароль
2) mis_client_id

Також прохання надати аналогічний набір для пре-прод для тестування.

**Comment by lymychp** [comment]
передано в ПП,
набір для препрод по [лінку](https://docs.google.com/document/d/1pi40OZQ3ajKHmXHFHApoJiVRLLgx4iJVl8bNi93qzW8/edit)
