### ISSUE TITLE
Зміна тексту помилки 

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#382]
при запиті /api/declaration_requests/.../actions/sign
У випадку спроби підписати коли декларація в статусі відмінному від APPROVED і у впадку коли у лікаря перевищено ліміт деклараці, а відповідної мітки в декларації немає

Ми отримуємо один і тойже текст помилки 
`{
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests/dc0ae110-7366-45bb-b000-15405c513ccc/actions/sign",
                    "type" : "object",
                    "request_id" : "09b15ef5-6771-4cba-bf13-1259cfc12cea#22007",
                    "code" : 422
                },
                "error" : {
                    "type" : "validation_failed",
                    "message" : "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
                    "invalid" : [ 
                        {
                            "rules" : [ 
                                {
                                    "rule" : "invalid",
                                    "params" : [],
                                    "description" : "incorrect status"
                                }
                            ],
                            "entry_type" : "json_data_property",
                            "entry" : "$.status"
                        }
                    ]
                }
            }
        }`

Прохання в одному з випадків надсилати інший текст помилки

**Comment by svetavedmed** [comment]
Сейчас в случае, если доктор достиг лимита, возвращается следующая ошибка " "message": "This doctor reaches his limit and could not sign more declarations","
