### ISSUE TITLE
Завершення реєстрації МІС Medics

### ISSUE THREAD

**Issue by ytrrty** [ehealth-ua/api-spec#383]
Просимо надати логін/пароль до продуктиву та аналогічний набір всіх даних для препроду.

**Comment by lymychp** [comment]
прошу написати запит на ДП на заміну mis_user `email` та `redirect_uri` . Так як при реєстроації ці дані не були вказані

**Comment by ioleksiy** [comment]
Для отримання повного набору даних для проду та препроду просимо надати заяву на ДП з полями (форму можно отримати у @kostikehealth):

name: `MIS ПП Тех-Нет Сервіс Медкард Плюс`
user_email: `test_user@mail.com`
redirect_uri: `https://mis_name/auth/redirect`

Прошу звернути увагу, що `redirect_uri` повинен бути з https та доменом.

Дякую.

**Comment by lymychp** [comment]
credentials відправлено на вказану Вами пошту, прошу підтвердити отримання

**Comment by ytrrty** [comment]
@lymychp отримали, дякую
