### ISSUE TITLE
DEMO http 500 при реєстрації МСП 

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#384]
## Steps to Reproduce (Repro steps)

- [ ] PUT http://demo.ehealth.world/api/legal_entities
`"signed_legal_entity_request" : "MIIWXAYJKoZIhvcNAQcCoIIWTTCCFkkCAQExDjAMBgoqhiQCAQEBAQIBMIII4gYJKoZIhvcNAQcBoIII0wSCCM97Im5hbWUiOiLQotCe0JIg0KLQtdGB0YLQvtCy0LjQuSDQutC70Y7RhyIsInR5cGUiOiJQSEFSTUFDWSIsIm93bmVyX3Byb3BlcnR5X3R5cGUiOiJQUklWQVRFIiwibGVnYWxfZm9ybSI6IjI0MCIsImt2ZWRzIjpbIjQ3LjczIl0sImVkcnBvdSI6Ijc3NjU0MzIxIiwiYWRkcmVzc2VzIjpbeyJ0eXBlIjoiUkVTSURFTkNFIiwiY291bnRyeSI6IlVBIiwiYXJlYSI6ItCi0JXQoNCd0J7Qn9CG0JvQrNCh0KzQmtCQIiwic2V0dGxlbWVudCI6ItCi0JXQoNCd0J7Qn9CG0JvQrCIsInNldHRsZW1lbnRfdHlwZSI6IkNJVFkiLCJzZXR0bGVtZW50X2lkIjoiZmU5ZjYyZWUtNzk5Ni00ZTAzLWI3ZDQtMTMyYjRjYzRlZDdkIiwiYnVpbGRpbmciOiI0IiwiYXBhcnRtZW50IjoiMiIsInppcCI6IjAxMDI1Iiwic3RyZWV0X3R5cGUiOiJTVFJFRVQiLCJzdHJlZXQiOiLQotC10YDQvdC+0L/RltC70YzRgdGM0LrQsCJ9LHsidHlwZSI6IlJFR0lTVFJBVElPTiIsImNvdW50cnkiOiJVQSIsImFyZWEiOiLQotCV0KDQndCe0J/QhtCb0KzQodCs0JrQkCIsInNldHRsZW1lbnQiOiLQotCV0KDQndCe0J/QhtCb0KwiLCJzZXR0bGVtZW50X3R5cGUiOiJDSVRZIiwic2V0dGxlbWVudF9pZCI6ImZlOWY2MmVlLTc5OTYtNGUwMy1iN2Q0LTEzMmI0Y2M0ZWQ3ZCIsImJ1aWxkaW5nIjoiNCIsImFwYXJ0bWVudCI6IjIiLCJ6aXAiOiIwMTAyNSIsInN0cmVldF90eXBlIjoiU1RSRUVUIiwic3RyZWV0Ijoi0KLQtdGA0L3QvtC/0ZbQu9GM0YHRjNC60LAifV0sInBob25lcyI6W3sidHlwZSI6IkxBTkRfTElORSIsIm51bWJlciI6IiszODA1MDM0MTA4NzAifV0sImVtYWlsIjoidm92Y2hpa3N0YSsxMUBnbWFpbC5jb20iLCJvd25lciI6eyJmaXJzdF9uYW1lIjoi0KLQtdGB0YIiLCJsYXN0X25hbWUiOiLQotC10YHRgtC+0LIiLCJzZWNvbmRfbmFtZSI6ItCi0LXRgdGC0L7QstC40YciLCJ0YXhfaWQiOiIzMDg0NTIyOTIyIiwiYmlydGhfZGF0ZSI6IjE5ODQtMDYtMTMiLCJiaXJ0aF9wbGFjZSI6IiIsImdlbmRlciI6IkZFTUFMRSIsImVtYWlsIjoidm92Y2hpa3N0YSsxMUBnbWFpbC5jb20iLCJkb2N1bWVudHMiOlt7InR5cGUiOiJQQVNTUE9SVCIsIm51bWJlciI6ItCQ0JExMjM0NTYifV0sInBob25lcyI6W3sidHlwZSI6Ik1PQklMRSIsIm51bWJlciI6IiszODA2NzY4MjQzNjQifV0sInBvc2l0aW9uIjoiUDIifSwibWVkaWNhbF9zZXJ2aWNlX3Byb3ZpZGVyIjp7ImxpY2Vuc2VzIjpbeyJsaWNlbnNlX251bWJlciI6IjQzNDUiLCJpc3N1ZWRfYnkiOiLQmtCy0LDQu9GW0YTRltC60LDRhtC50L3QsCDQutC+0LzRltGB0ZbRjyIsImlzc3VlZF9kYXRlIjoiMjAxNy0wMi0yOCIsImV4cGlyeV9kYXRlIjoiMjAxOS0wMi0yOCIsImFjdGl2ZV9mcm9tX2RhdGUiOiIyMDE3LTAyLTI4Iiwid2hhdF9saWNlbnNlZCI6ItGA0LXQsNC70ZbQt9Cw0YbRltGPINC90LDRgNC60L7RgtC40YfQvdC40YUg0LfQsNGB0L7QsdGW0LIiLCJvcmRlcl9ubyI6IjM0NSJ9XX0sInNob3J0X25hbWUiOiLQotCe0JIg0KLQmiIsInB1YmxpY19uYW1lIjoi0KLQntCSINCi0LXRgdGC0L7QstC40Lkg0LrQu9GO0YciLCJ3ZWJzaXRlIjoiaHR0cDpcL1wvZGhnLmNvbSIsInJlY2VpdmVyX2Z1bmRzX2NvZGUiOiIyMzQ1IiwiYmVuZWZpY2lhcnkiOiLRltCy0YTQsNGE0ZYg0YTQstGWINCw0YTQstGW0LDRhCIsInB1YmxpY19vZmZlciI6eyJjb25zZW50Ijp0cnVlLCJjb25zZW50X3RleHQiOiLQl9C+0LHQvtCyJ9GP0LfRg9GO0YHRjCDQtNC+0YLRgNC40LzRg9Cy0LDRgtC40YHRjCDQoNC10LPQu9Cw0LzQtdC90YLRgyDRhNGD0L3QutGG0ZbQvtC90YPQstCw0L3QvdGPINGB0LjRgdGC0LXQvNC4IGVIZWFsdGguINCf0ZbQtNGC0LLQtdGA0LTQttGD0Y4g0LTQvtGB0YLQvtCy0ZbRgNC90ZbRgdGC0Ywg0LLQutCw0LfQsNC90LjRhSDQvNC90L7RjiDQtNCw0L3QuNGFINGC0LAg0LTQvtCx0YDQvtCy0ZbQu9GM0L3RltGB0YLRjCDQvdCw0LTQsNC90L3RjyDRhtC40YUg0LTQsNC90LjRhS4g0KPRgdCy0ZbQtNC+0LzQu9GO0Y4sINGJ0L4g0YMg0LLQuNC/0LDQtNC60YMg0L3QsNC00LDQvdC90Y8g0LzQvdC+0Y4g0L3QtdCy0ZbRgNC90L7RlyDRltC90YTQvtGA0LzQsNGG0ZbRlywg0LzQtdC90ZYg0LzQvtC20LUg0LHRg9GC0Lgg0LLRltC00LzQvtCy0LvQtdC90L4g0YMg0YDQtdGU0YHRgtGA0LDRhtGW0Zcg0LIg0YHQuNGB0YLQtdC80ZYgZUhlYWx0aC4ifSwic2VjdXJpdHkiOnsicmVkaXJlY3RfdXJpIjoiaHR0cDpcL1wvZGlzLmhlbHNpLnBybyJ9faCCBgMwggX/MIIFp6ADAgECAhQaFaZ7yOgvTAQAAADcoAQAVD8KADANBgsqhiQCAQEBAQMBATCB6zEYMBYGA1UECgwP0JTQnyAi0J3QkNCG0KEiMVQwUgYDVQQLDEvQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIxPjA8BgNVBAMMNdCQ0KbQodCaINC+0YDQs9Cw0L3RltCyINGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MRkwFwYDVQQFDBBVQS0zOTc4NzAwOC0yMDE1MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIwHhcNMTcxMTI0MTAzNDEyWhcNMTkxMTI0MTAzNDEyWjCB4zEpMCcGA1UECgwg0KLQntCSINCi0LXRgdGC0L7QstC40Lkg0LrQu9GO0YcxGTAXBgNVBAwMENCU0LjRgNC10LrRgtC+0YAxLzAtBgNVBAMMJtCi0LXRgdGC0L7QsiDQotC10YHRgiDQotC10YHRgtC+0LLQuNGHMRUwEwYDVQQEDAzQotC10YHRgtC+0LIxIjAgBgNVBCoMGdCi0LXRgdGCINCi0LXRgdGC0L7QstC40YcxDzANBgNVBAUMBjMwMzMyNDELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyMIHyMIHJBgsqhiQCAQEBAQMBATCBuTB1MAcCAgEBAgEMAgEABCEQvuPbauqeH4ZXjEXBJZT/lCOUp9c4+Rh+ZRUBcpT0zgECIQCAAAAAAAAAAAAAAAAAAAAAZ1khOvGC6YfT4XcUkH1HDQQhtg/S2NzoqTQjxhAbypHEegB+bDALJs1VbJsOfSDvKSoABECp1utF8TxwgoDElnsjH16t9ljrpMA3KR042WvwJcpOF/jpcg3GFbQ6KJdfC8Heo2Q4tWTqLBef0BI+bbj6xXkEAyQABCF3HJPBLmhpJDxWTKYqfjnf46N3GRVyYROwEFlAtfrITAGjggKQMIICjDApBgNVHQ4EIgQgLRF1ynMDNR28bVdlSl+Upf87DdvkHWWQaU00QuWadDowKwYDVR0jBCQwIoAgmhWme8joL0xVuQdk+S3S1sVKseLc/uJTv1jVWhVRe1EwLwYDVR0QBCgwJqARGA8yMDE3MTEyNDEwMzQxMlqhERgPMjAxOTExMjQxMDM0MTJaMA4GA1UdDwEB/wQEAwIGwDAZBgNVHSABAf8EDzANMAsGCSqGJAIBAQECAjAMBgNVHRMBAf8EAjAAMB4GCCsGAQUFBwEDAQH/BA8wDTALBgkqhiQCAQEBAgEwSwYDVR0fBEQwQjBAoD6gPIY6aHR0cDovL2NhLmluZm9ybWp1c3QudWEvZG93bmxvYWQvY3Jscy9DQS05QTE1QTY3Qi1GdWxsLmNybDBMBgNVHS4ERTBDMEGgP6A9hjtodHRwOi8vY2EuaW5mb3JtanVzdC51YS9kb3dubG9hZC9jcmxzL0NBLTlBMTVBNjdCLURlbHRhLmNybDCBhAYIKwYBBQUHAQEEeDB2MDIGCCsGAQUFBzABhiZodHRwOi8vY2EuaW5mb3JtanVzdC51YS9zZXJ2aWNlcy9vY3NwLzBABggrBgEFBQcwAoY0aHR0cDovL2NhLmluZm9ybWp1c3QudWEvY2EtY2VydGlmaWNhdGVzL2Fjc2tuYWlzLnA3YjBBBggrBgEFBQcBCwQ1MDMwMQYIKwYBBQUHMAOGJWh0dHA6Ly9jYS5pbmZvcm1qdXN0LnVhL3NlcnZpY2VzL3RzcC8wQwYDVR0JBDwwOjAaBgwqhiQCAQEBCwEEAgExChMINzc2NTQzMjEwHAYMKoYkAgEBAQsBBAEBMQwTCjMwODQ1MjI5MjIwDQYLKoYkAgEBAQEDAQEDQwAEQFPEEJN83mbg0q0MipOi7u/DI2/u0HqyMCedhMHd+ppTwqh/ggNmeZzxBw13+JPbViJpwDC4rQnRokSkcbhrmiUxggdFMIIHQQIBATCCAQQwgesxGDAWBgNVBAoMD9CU0J8gItCd0JDQhtChIjFUMFIGA1UECwxL0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyMT4wPAYDVQQDDDXQkNCm0KHQmiDQvtGA0LPQsNC90ZbQsiDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDEZMBcGA1UEBQwQVUEtMzk3ODcwMDgtMjAxNTELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQaFaZ7yOgvTAQAAADcoAQAVD8KADAMBgoqhiQCAQEBAQIBoIIF0zAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xODA1MDIyMDAyNTdaMC8GCSqGSIb3DQEJBDEiBCAwtn68zDAC69Z/Cy47SPgEWiSGN6hb2wthp/zEpx7BhzCCAVsGCyqGSIb3DQEJEAIvMYIBSjCCAUYwggFCMIIBPjAMBgoqhiQCAQEBAQIBBCDu1coGDf4E5JcnAMeldzfsRR3afAjZcgu9NI324klsYDCCAQowgfGkge4wgesxGDAWBgNVBAoMD9CU0J8gItCd0JDQhtChIjFUMFIGA1UECwxL0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyMT4wPAYDVQQDDDXQkNCm0KHQmiDQvtGA0LPQsNC90ZbQsiDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDEZMBcGA1UEBQwQVUEtMzk3ODcwMDgtMjAxNTELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQaFaZ7yOgvTAQAAADcoAQAVD8KADCCBAcGCyqGSIb3DQEJEAIUMYID9jCCA/IGCSqGSIb3DQEHAqCCA+MwggPfAgEDMQ4wDAYKKoYkAgEBAQECATBrBgsqhkiG9w0BCRABBKBcBFowWAIBAQYKKoYkAgEBAQIDATAwMAwGCiqGJAIBAQEBAgEEIDC2frzMMALr1n8LLjtI+ARaJIY3qFvbC2Gn/MSnHsGHAgQPCVIHGA8yMDE4MDUwMjIwMDM0NFoxggNbMIIDVwIBATCCARMwgfoxPzA9BgNVBAoMNtCc0ZbQvdGW0YHRgtC10YDRgdGC0LLQviDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotChINCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQstGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEtMDAwMTU2MjItMjAxMjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQwBHUd7yx4rgIAAAABAAAASgAAADAMBgoqhiQCAQEBAQIBoIIB2jAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwHAYJKoZIhvcNAQkFMQ8XDTE4MDUwMjIwMDM0NFowLwYJKoZIhvcNAQkEMSIEIKLCzOJHbOkfDhiNeDEGSOPmSL3A2ZJ+RzVwQ0yzXRn6MIIBawYLKoZIhvcNAQkQAi8xggFaMIIBVjCCAVIwggFOMAwGCiqGJAIBAQEBAgEEINkNprZIU8Mtv5e49uVczWrFeVID4phEuuPJ1lYbZ7zqMIIBGjCCAQCkgf0wgfoxPzA9BgNVBAoMNtCc0ZbQvdGW0YHRgtC10YDRgdGC0LLQviDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotChINCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQstGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEtMDAwMTU2MjItMjAxMjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQwBHUd7yx4rgIAAAABAAAASgAAADANBgsqhiQCAQEBAQMBAQRAChArwpJDDvo5J6J5JhyEWEdH+qEVQIUXEu+I6ioBXXeUKPGrH2/mpWRWqTeF+71ty0V3IYhVBXxQQGC+cHBnPzANBgsqhiQCAQEBAQMBAQRAp/uYmqYBoZWIKjPxrKUzEtPBj8CCSE29T9BNssoBUXT5I8ULBDEbqTCNpYvVjfmL35JP9Gkv6mWHss6qKS2iPQ==",
            "signed_content_encoding" : "base64"`

## Actual result
- [ ] `{
        "status" : "error",
        "message" : "Internal Server Error",
        "statusCode" : 500,
        "headers" : {
            "Date" : [ 
                "Wed, 02 May 2018 20:03:04 GMT"
            ],
            "Content-Type" : [ 
                "text/plain; charset=UTF-8"
            ],
            "Content-Length" : [ 
                "194"
            ],
            "Connection" : [ 
                "keep-alive"
            ],
            "Set-Cookie" : [ 
                "__cfduid=d1212f11f49b88ed61e3fed128b4f4c981525291383; expires=Thu, 02-May-19 20:03:03 GMT; path=/; domain=.ehealth.world; HttpOnly"
            ],
            "Cache-Control" : [ 
                "max-age=0, private, must-revalidate"
            ],
            "Vary" : [ 
                "Accept-Encoding"
            ],
            "Via" : [ 
                "kong/0.12.1"
            ],
            "X-Content-Type-Options" : [ 
                "nosniff"
            ],
            "X-Download-Options" : [ 
                "noopen"
            ],
            "X-Frame-Options" : [ 
                "SAMEORIGIN"
            ],
            "X-Kong-Proxy-Latency" : [ 
                "122"
            ],
            "X-Kong-Upstream-Latency" : [ 
                "773"
            ],
            "X-Permitted-Cross-Domain-Policies" : [ 
                "none"
            ],
            "X-Ratelimit-Limit-Minute" : [ 
                "9000"
            ],
            "X-Ratelimit-Remaining-Minute" : [ 
                "8999"
            ],
            "X-Request-Id" : [ 
                "3543601b-ad6b-4893-bade-dfbceb3b42eb#11858"
            ],
            "X-Xss-Protection" : [ 
                "1; mode=block"
            ],
            "Server" : [ 
                "cloudflare"
            ],
            "CF-RAY" : [ 
                "414d16cd403b8b64-KBP"
            ]
        },
        "body" : {
            "meta" : {
                "url" : "http://api-svc.il/api/legal_entities",
                "type" : "object",
                "request_id" : "3543601b-ad6b-4893-bade-dfbceb3b42eb#11858",
                "code" : 500
            },
            "error" : {
                "errors" : {
                    "detail" : "Internal server error"
                }
            }`

## Expected result
- [ ] не http 500

**Comment by danakonovalenko** [comment]
@sreva перевірте, будь ласка, чи працює зараз

**Comment by sreva** [comment]
Дякую, зареєструвати вдалосятепер правда інша проблема(
