### ISSUE TITLE
Завершення реєстрації МІС МедЕйр

### ISSUE THREAD

**Issue by Evgeniy0119** [ehealth-ua/api-spec#385]
Прошу предоставить логин пароль на Prod и PreProd

**Comment by ioleksiy** [comment]
Для отримання повного набору даних для проду та препроду просимо надати заяву на ДП з полями (форму можно отримати у @kostikehealth):

name: `MIS ПП Тех-Нет Сервіс Медкард Плюс`
user_email: `test_user@mail.com`
redirect_uri: `https://mis_name/auth/redirect`

Прошу звернути увагу, що `redirect_uri` повинен бути з https та доменом.

Дякую.

**Comment by lymychp** [comment]
credentials відправлено на вказану Вами пошту, прошу підтвердити отримання

**Comment by Evgeniy0119** [comment]
Добрый день, подтверждаю получения письма с данными для МИС МедЭйр

ср, 18 июл. 2018 г. в 10:19, lymychp <notifications@github.com>:
