### ISSUE TITLE
Документы на портале

### ISSUE THREAD

**Issue by goutsalova** [ehealth-ua/api-spec#386]
1. Убрать в разделе Документы 

НА ЗАТВЕРДЖЕННІ
Постанова КМУ
Про затвердження порядку функціонування електронної системи охорони здоров’я

2. Заменить вложение

Закон про державні фінансові гарантії надання медичних послуг та лікарських засобів
[ЗУ.pdf](https://github.com/ehealth-ua/api-spec/files/1973380/default.pdf)

**Comment by lymychp** [comment]
2) додати новий документ чи замінити якийсь існуючий?

**Comment by goutsalova** [comment]
замінити існуючий Закон про державні фінансові гарантії надання медичних послуг та лікарських засобів

**Comment by lymychp** [comment]
deployed to preprod-prod
