### ISSUE TITLE
Завершення реєстрації МІС Doctor Eleks

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#388]
Прошу надати :

логін/пароль
mis_client_id

**Comment by superjonh** [comment]
@lymychp @ioleksiy Доброго дня, коли очікувати отримання нового доступу ? і це я так розумію буде лист на пошту, яка зазначалась при підключенні до ЦК

**Comment by ioleksiy** [comment]
Для отримання повного набору даних для проду та препроду просимо надати заяву на ДП з полями (форму можно отримати у @kostikehealth):

name: `MIS ПП Тех-Нет Сервіс Медкард Плюс`
user_email: `test_user@mail.com`
redirect_uri: `https://mis_name/auth/redirect`

Прошу звернути увагу, що `redirect_uri` повинен бути з https та доменом.

Дякую.

**Comment by lymychp** [comment]
credentials відправлено на вказану Вами пошту, прошу підтвердити отримання
