### ISSUE TITLE
Завершення реєстрації МІС Поліклініка без черг

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#389]
Не отримали:
- логін/пароль

**Comment by cshevchukod** [comment]
Коллеги, ответа всё ещё нет. Сориентируйте по времени.

**Comment by cshevchukod** [comment]
Any updates?

**Comment by ioleksiy** [comment]
@kostikehealth просьба дать апрув если у текущего МИС всё хорошо, и мы выдадим логин/пароль.

**Comment by kostikehealth** [comment]
@cshevchukod будь ласка, для завершення реєстрації, надайте поштою коректний redirect_url. Його вже було запрошено раніше Русланом Прилипко, але замість redirect_url надали адресу МІСу.

**Comment by ioleksiy** [comment]
Для отримання повного набору даних для проду та препроду просимо надати заяву на ДП з полями (форму можно отримати у @kostikehealth):

name: `MIS ПП Тех-Нет Сервіс Медкард Плюс`
user_email: `test_user@mail.com`
redirect_uri: `https://mis_name/auth/redirect`

Прошу звернути увагу, що `redirect_uri` повинен бути з https та доменом.

Дякую.
