### ISSUE TITLE
Валидация электронной почты

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#39]
При регистрации юр. лица возвращается ошибка:
Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.
     $.email: expected "роliklinika3@i.ua" to be an email address     $.owner.email: expected "роliklinika3d@i.ua" to be an email address

Возможно это связанно с доменным именем.

**Comment by pzhuk** [comment]
$ echo "роliklinika3@i.ua" | iconv -t "UTF-16"
��@>liklinika3@i.ua

**Comment by pzhuk** [comment]
первые два символа из какой-то левой кодировки
