### ISSUE TITLE
DEMO проблема з підтвердженням співробітника

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#390]
## Steps to Reproduce (Repro steps)

1) Пройшов флоу створення аптеки
2) Отримав на почту лінк `http://auth.demo.ehealth.world/invite?invite=MUFBS2pCcE41a3doSHpzWmhTN1dtUk9uUUlsZWhTMkZpJTJGd2NrVmx4ZTZmRm5MTTZBWkdpTzdjSlp4UXBDelBp`
3) Створив пароль
4) відмітив чекбокс "Погоджуюсь з Регламентом функціонування системи eНealth"  і натиснув  "Прийняти запрошення". Ніяких змін не відбувається в консолі на запит `http://demo.ehealth.world/api/employee_requests/021d7af4-bcbd-4d45-927e-533081440320/approve`
приходить 403 Forbidden

**Comment by lymychp** [comment]
@svetavedmed please check whether it is reproducible on demo.

**Comment by svetavedmed** [comment]
fixed on demo
