### ISSUE TITLE
Prod http 500 /actions/sign 

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#392]
## Steps to Reproduce (Repro steps)

- [ ] "https://api.ehealth-ukraine.org/api/declaration_requests/14066518-e2e5-471c-af56-d4b193572845/actions/sign"

Деталі можу скинути через ПП

## Actual result
- [ ]  `{
            "status" : "error",
            "message" : "Internal Server Error",
            "statusCode" : 500,
            "headers" : {
                "Server" : "nginx/1.13.12",
                "Date" : "Mon, 07 May 2018 05:28:11 GMT",
                "Content-Type" : "text/plain; charset=UTF-8",
                "Content-Length" : "251",
                "Connection" : "keep-alive",
                "Set-Cookie" : "__cfduid=db9b6d76a4b5545474b6d25f2adce07d91525670891; expires=Tue, 07-May-19 05:28:11 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure",
                "Cache-Control" : "max-age=0, private, must-revalidate",
                "Vary" : "Accept-Encoding",
                "Via" : "kong/0.12.1",
                "X-Content-Type-Options" : "nosniff",
                "X-Download-Options" : "noopen",
                "X-Frame-Options" : "SAMEORIGIN",
                "X-Kong-Proxy-Latency" : "8",
                "X-Kong-Upstream-Latency" : "13",
                "X-Permitted-Cross-Domain-Policies" : "none",
                "X-Ratelimit-Limit-Minute" : "9000",
                "X-Ratelimit-Remaining-Minute" : "8983",
                "X-Request-Id" : "941b6127-caaf-4a78-9c89-875806c6631d#150742",
                "X-Xss-Protection" : "1; mode=block",
                "Expect-CT" : "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
                "CF-RAY" : "4171481e0a1d7cea-MUC"
            },
            "body" : {
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests/14066518-e2e5-471c-af56-d4b193572845/actions/sign",
                    "type" : "object",
                    "request_id" : "941b6127-caaf-4a78-9c89-875806c6631d#150742",
                    "code" : 500
                },
                "error" : {
                    "errors" : {
                        "detail" : "Internal server error"
                    }
                }
            }
        }`

## Expected result
- [ ]  не http 500

**Comment by sreva** [comment]
так

**Comment by lymychp** [comment]
залили фікс на прод. Більше не повинна повторюватись.
