### ISSUE TITLE
PROD http 500 /actions/approve

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#393]
## Steps to Reproduce (Repro steps)

- [ ] https://api.ehealth-ukraine.org/api/declaration_requests/70dc29e4-dc0b-4fd7-ae5e-b12bf343ee91/actions/approve

## Actual result
- [ ] `{
            "status" : "error",
            "message" : "Internal Server Error",
            "statusCode" : 500,
            "headers" : {
                "Server" : "nginx/1.13.12",
                "Date" : "Mon, 07 May 2018 05:00:00 GMT",
                "Content-Type" : "text/plain; charset=UTF-8",
                "Content-Length" : "253",
                "Connection" : "keep-alive",
                "Set-Cookie" : "__cfduid=dff987c8593fff1c1379e254b480289901525669198; expires=Tue, 07-May-19 04:59:58 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure",
                "Cache-Control" : "max-age=0, private, must-revalidate",
                "Vary" : "Accept-Encoding",
                "Via" : "kong/0.12.1",
                "X-Kong-Proxy-Latency" : "12",
                "X-Kong-Upstream-Latency" : "1879",
                "X-Ratelimit-Limit-Minute" : "9000",
                "X-Ratelimit-Remaining-Minute" : "8986",
                "X-Request-Id" : "2e499417-3fc9-4995-ab31-afb9553bcbbe#39753",
                "Expect-CT" : "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
                "CF-RAY" : "41711ecc1be27d0e-MUC"
            },
            "body" : {
                "meta" : {
                    "url" : "http://api-svc.il/api/declaration_requests/70dc29e4-dc0b-4fd7-ae5e-b12bf343ee91/actions/approve",
                    "type" : "object",
                    "request_id" : "2e499417-3fc9-4995-ab31-afb9553bcbbe#39753",
                    "code" : 500
                },
                "error" : {
                    "errors" : {
                        "detail" : "Internal server error"
                    }
                }
            }`

## Expected result
- [ ] не http 500

**Comment by ioleksiy** [comment]
Чи актуальне ще питання?

**Comment by sreva** [comment]
так

**Comment by lymychp** [comment]
fixed on prod
