### ISSUE TITLE
PROD http 500 на  POST /api/verifications/

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#394]
## Steps to Reproduce (Repro steps)

- [ ] POST https://api.ehealth-ukraine.org/api/verifications/

Номер телефона на який відпрвляли можу скинути в ПП

## Actual result
- [ ] ` {
            "status" : "error",
            "message" : "Internal Server Error",
            "statusCode" : 500,
            "headers" : {
                "Server" : "nginx/1.13.12",
                "Date" : "Mon, 07 May 2018 06:04:44 GMT",
                "Content-Type" : "text/plain; charset=UTF-8",
                "Content-Length" : "200",
                "Connection" : "keep-alive",
                "Set-Cookie" : "__cfduid=d30eebb2d1d5d2527114ea17c0ca69ebd1525673079; expires=Tue, 07-May-19 06:04:39 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure",
                "Cache-Control" : "max-age=0, private, must-revalidate",
                "Vary" : "Accept-Encoding",
                "Via" : "kong/0.12.1",
                "X-Kong-Proxy-Latency" : "15",
                "X-Kong-Upstream-Latency" : "5034",
                "X-Ratelimit-Limit-Minute" : "9000",
                "X-Ratelimit-Remaining-Minute" : "8960",
                "X-Request-Id" : "5195c30f-45b5-4451-ae80-f99ae4472298#34870",
                "Expect-CT" : "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
                "CF-RAY" : "41717d8aafe37cf0-MUC"
            },
            "body" : {
                "meta" : {
                    "url" : "http://api-svc.verification/verifications/",
                    "type" : "object",
                    "request_id" : "5195c30f-45b5-4451-ae80-f99ae4472298#34870",
                    "code" : 500
                },
                "error" : {
                    "errors" : {
                        "detail" : "Internal server error"
                    }
                }
            }
        }`

## Expected result
- [ ] не http 500

**Comment by gmile** [comment]
@sreva вы систематично на все запросы verification получаете 500?

**Comment by sreva** [comment]
@gmile  ні, лише на деякі.

**Comment by sreva** [comment]
@gmile станом на зараз, за сьогодні:
GET verification  - 670 рази
PATCH verification  - 422 рази
POST verification  - 124 рази

**Comment by ioleksiy** [comment]
@sreva Чи повторюється помилка?

**Comment by sreva** [comment]
на цьому ендпоінту ні.
Дякую
