### ISSUE TITLE
Employee_request create (mail)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#395]
* Подивіться будь-ласка чому можуть не приходити листи на пошту, ось мейли 
chuchukp@ukr.net
apolyanka.fp@i.ua
ala.korol@ukr.net

А також:
halyna.paradivska@gmail.com 
prociv.gal@gmail.com
lazvoda@ukr.net

## Actual result
- [ ] {
  "meta": {
    "url": "http://api-svc.il/api/employee_requests",
    "type": "object",
    "request_id": "2233f015-d0d7-4307-89db-9e2fe829ddda#369526",
    "code": 200
  }

- [ ]   {
  "meta": {
    "url": "http://api-svc.il/api/employee_requests",
    "type": "object",
    "request_id": "8d421db1-aaac-4d4c-a933-1f14099c2240#41415",
    "code": 200
  }

- [ ]   "meta": {
    "url": "http://api-svc.il/api/employee_requests",
    "type": "object",
    "request_id": "35196e98-9656-4311-840c-4069a9fd78e8#163931",
    "code": 200
  }

## Expected result
- [ ] delivered mail

**Comment by svetavedmed** [comment]
Деактивированы: chuchukp@ukr.net
apolyanka.fp@i.ua
ala.korol@ukr.net

письма доставлены: halyna.paradivska@gmail.com
prociv.gal@gmail.com
lazvoda@ukr.net
