### ISSUE TITLE
[PROD] Поле "person" в зависимости от способа получения информации о декларации отличается

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#396]
## Steps to Reproduce (Repro steps)

- [ ] Делаем Get Declarations List.
- [ ] Делаем Get Declaration by ID.

## Actual result
- [ ] Местами в списке после Get Declarations List поле "person" имеет значение Null
- [ ] При этом, если попробовать получить Get Declaration by ID, в тех декларациях, где "person" был Null, теперь видим нужные данные.

## Expected result
- [ ] Поле "person" имеет корректную информацию при Get Declarations List.

Подробности скину в личку.

**Comment by cshevchukod** [comment]
![image](https://user-images.githubusercontent.com/20535372/39695619-e925919e-51f3-11e8-828e-6625f63ed8c4.png)
host = https://api.ehealth-ukraine.org

**Comment by cshevchukod** [comment]
UPD При запросах в 50 деклараций на странице - всё ОК, и проблема не воспроизводится.

**Comment by lymychp** [comment]
fixed on prod
