### ISSUE TITLE
Legal Entity API validation error (ACSK Ukraine)

### ISSUE THREAD

**Issue by warehousman** [ehealth-ua/api-spec#4]
Костя, нужна помощь (не срочно, но надо) в тестировании с одним из МИСов.
Есть кто-нибудь, кто сможет уделить хотя бы минут 30 по проверке?

Тут 2 вопроса

1) Есть ли проблема с упомянутой подписью АЦСК "Украина" - почему-то приходит ошибка 500
1а) Есть ли проблема с подписями ФОП -  там не ЕДРПОУ а ИНН из подписи должен браться 

2) Уточнить что за проблема с HTTP/422 - validation failed. Это ошибка по несовпадению ЕДРПОУ в подписи и в докумете?

BR, Pavel V. Zhuk

---------- Переслане повідомлення ----------
Від: Песков Дмитрий Александрович <dmitriy.peskov@alt.ua>
Дата: 25 травня 2017 р. о 14:23
Тема: Підписи АЦСК "Україна"
Кому: "k.makarenko.ehealth@gmail.com" <k.makarenko.ehealth@gmail.com>
Копія: "Pavel V. Zhuk" <pavel.zhuk@gmail.com>

Добрий день.

Створюю юр. особу Org.json
Підписав файл Org.json ключами АЦСК "Україна" на сайті http://czo.gov.ua/sign. (ключ реальної юр. особи)
Перетворив у base64.

OrgTest.p7s - Org.json підписаний тестовими ключами 

OrgTest_base64.p7s - Org.json підписаний тестовими ключами у base64

рекв. ключа.txt - інформація по ключу.

Приходить у відповідь
{
  "meta": {
    "url": "http://api-svc.il/api/legal_entities",
    "type": "object",
    "request_id": "t656oacqfl42tm8ljap182gbs32e8vtc",
    "code": 500
  },
  "error": {
    "type": "internal_error"
  }
}

Все це роблю тестовими ключами, відповідь
{
  "meta": {
    "url": "http://api-svc.il/api/legal_entities",
    "type": "object",
    "request_id": "at041o8dasis5lriqnd1kogb3jp8um4q",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": "inclusion",
            "params": [
              "38469862"
            ],
            "description": "is invalid"
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.edrpou"
      }
    ]
  }
}

Може я щось роблю не так, виправте будь ласка.

Дякую.

**Comment by AlekzandrV** [comment]
@pzhuk , мы исправили валидацию подписей. Теперь возникает резонная ошибка на несоответсвие справочников. Проверялось как на тестовом сертификате, так и на реальном.

Можете подправить контент согласно значениям справочников и повторно подписать?

**Comment by warehousman** [comment]
fixed
