### ISSUE TITLE
Помилкове введення П.І.Б. у деклараціях

### ISSUE THREAD

**Issue by zackkozac** [ehealth-ua/api-spec#401]
Укладаємо декларацію з помилкою у прізвищі, імені або по-батькові, після завершення процесу знаходимо помилку і укладаємо нову декларацію із коректними даними.
В результаті отримуємо дві різні декларації, одна з них із невірними даними.
Допоможіть, будь ласка, розібратись що потрібно робити в цій ситуації.

**Comment by lymychp** [comment]
якщо це просто опечатка, то в майбутньому такі пацієнти будуть автоматично об'єднані, а одна з декларацій буде розірвана
