### ISSUE TITLE
[PROD] Некоторые declaration_requests удаляются, хотя не должны

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#402]
## Steps to Reproduce (Repro steps)

- [ ] Создаём и подписываем декларацию
- [ ] Декларация имеет статус "Active", declaration_request имеет статус "Signed"

## Actual result
- [ ] Через какое-то время при попытке получить declaration_request с помощью Get Declaration Request by ID получаем 404.

## Expected result
- [ ] Всегда при Get Declaration Request by ID получаем информацию о любом declaration_request

При необходимости могу скинуть более подробную информацию.
На вскидку, получили список деклараций и список declaration_request - количество отличается.

**Comment by cshevchukod** [comment]
Например, по одной из наших клиник сегодня почитали:
3024 - declarations, status = 'active'
1517 - declaration requests, status = 'signed'

**Comment by cshevchukod** [comment]
Коллеги, ответа всё ещё нет. Сориентируйте по времени.

**Comment by svetavedmed** [comment]
declaration requests не удаляются, а удаляются только данные из них, и статус изменяется на expired

**Comment by cshevchukod** [comment]
Тогда почему мы не можем получить declaration request по ID и получаем 404?

**Comment by svetavedmed** [comment]
А зачем вам старый declaration request без данных?

**Comment by cshevchukod** [comment]
Сам по себе он нам не нужен, но нам требуется его ID и статус. В нашей МИС по логике весь процесс заведения декларации основывается на статусах declaration request, по которым мы процесс разделяем на части. Из-за того, что мы получаем 404 при попытке посмотреть статус declaration request и по нему в том числе не можем найти декларацию, складывается впечатление, что декларация удалилась, хотя удалился только declaration request.
Если бы разу было сказано, что по declaration request удаляются (т.е. удаляются совсем, без какого-либо статуса), то мы бы логику внутри МИС продумали по-другому.
