### ISSUE TITLE
Зміна email лікаря без розривання декларацій

### ISSUE THREAD

**Issue by zackkozac** [ehealth-ua/api-spec#404]
Потрібна можливість змінити електронну пошту лікаря без втрати декларацій. Частина лікарів втратила доступ до своєї електронну пошти. Зміна можлива лише шляхом заведення нового профілю.

P.S. МІС Helsi

**Comment by svetavedmed** [comment]
done on dev

**Comment by svetavedmed** [comment]
deployed on prod
