### ISSUE TITLE
Employee password reset (not found user)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#409]
Доброго дня, подивіться будь-ласка до юзера (luba-Leluk@ukr.net), проблема з відновленням паролю;
employee_id: 0f13e966-e320-4c8a-a4bc-1991c1a24736
status: APPROVED

![image](https://user-images.githubusercontent.com/24266717/39761913-013e0876-52e2-11e8-8114-a072d1108fad.png)

employee_id: 507b82ae-89ce-4bc5-b3df-03812b8df8c9
email: kachmar.s.84@gmail.com
status: APPROVED

![image](https://user-images.githubusercontent.com/24266717/40309219-684ec5ee-5d11-11e8-9f46-f79fc4c8a4f9.png)

MIS: Doctor Eleks

**Comment by svetavedmed** [comment]
данный email существует и ошибка не воспроизводится

**Comment by superjonh** [comment]
@svetavedmed повторюється з користувачем kachmar.s.84@gmail.com - ононвив логи

**Comment by svetavedmed** [comment]
а можете ли вы воспроизвести это ошибку? Т.к. снова email существует

**Comment by superjonh** [comment]
@svetavedmed користувач вже відновив доступ, дякую.
