### ISSUE TITLE
am-test4 Успішна реєстрація на demo.ehealth.world не працює на api.ehealth.world . Причина?

### ISSUE THREAD

**Issue by romanm** [ehealth-ua/api-spec#41]
Дубль https://github.com/romanm/algoritmed-mvp1-ehealth/issues/6

Успішна реєстрація на demo.ehealth.world не працює на api.ehealth.world
Я підозрюю що невистачає https, чи може бути інша причина?

**Comment by pzhuk** [comment]
api.ehealth.world обов"язково вимагає https, це видно з відповіді http/302
