### ISSUE TITLE
Employee password reset (mail)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#411]
Доброго дня, подивіться будь-ласка до юзерів 
(
mykhalchukvm@ukr.net, employee_id: b4fc041c-6729-4b02-b6c8-9972f3e471c3
valentina.tyrsa1@gmail.com, employee_id: 4faeeeeb-f6a8-4802-919f-d123b0b5dd78
), 
проблема з відновленням паролю;

status: APPROVED
 
## Actual result
- [ ] not received mail

## Expected result
- [ ] mail to create new pass

MIS: Doctor Eleks

**Comment by svetavedmed** [comment]
mykhalchukvm@ukr.net - просьба повторить.
valentina.tyrsa1@gmail.com - доставлено May 11, 12:19:46 PM
