### ISSUE TITLE
[Prod] Identification bug

### ISSUE THREAD

**Issue by Hamiltone** [ehealth-ua/api-spec#412]
## Steps to Reproduce (Repro steps)

- [ ] Создаем декларацию на пациента без ИНН
- [ ] Фамилия, имя и дата рождения совпадают с пользователем, который уже есть в системе.
- [ ] Выбираем верификацию по номеру телефона и указываем номер.
- [ ] Отправляем СМС 

## Actual result
- [ ] Получаем СМС на номер пользователя, с которым ключевые поля совпали

## Expected result
- [ ] Получаем СМС на номер, который указали

реквест на создание декларации -
"meta" : {
            "url" : "http://api-svc.il/api/declaration_requests",
            "type" : "object",
            "request_id" : "b35f29a1-24b1-4d82-9904-0fac9e372b7e#110509",
            "code" : 200
        },
персона, с которой было найдено совпадение - 
"person_id" : "bd8cdcc1-da46-40d1-ba6d-9d68429cdc8d"

MIS - Helsi

**Comment by svetavedmed** [comment]
Actual result = Expected result.
Если ключевые поля совпали, значит, введенный Вами человек, уже есть в системе и он должен подтвердить изменения над собой назвав смс, отправленную на номер сохраненный в системе.

**Comment by Hamiltone** [comment]
Но по факту ведь, это разные люди. Совпадает лишь фамилия, имя и дата рождения. Что делать пациенту в таком случае? (в паспорте у него есть отметка о том, что ИНН у него нет) @svetavedmed

**Comment by svetavedmed** [comment]
Если у человека нет ИНН, поиск происходит именно но фимилия+имя+дата рождения.

**Comment by Hamiltone** [comment]
Я это понимаю. Вопрос в другом - как этому человеку заключить декларацию ?

**Comment by svetavedmed** [comment]
А точно ли это разные люди? можете прислать ее номер паспорта, например?
