### ISSUE TITLE
Особа із невірною контрольною сумою в ІПН

### ISSUE THREAD

**Issue by zackkozac** [ehealth-ua/api-spec#413]
Частина пацієнтів мають діючі ІПН із невірною контрольною сумою. Під час укладання декларацій валідація такі ІПН не пропускає.
Як укласти декларації із такими пацієнтами?

**Comment by svetavedmed** [comment]
Посьба предоставить скан такого инн. Спасибо

**Comment by lymychp** [comment]
інформацію не надано
