### ISSUE TITLE
Декларації із сімейним лікарем діють до 18 років

### ISSUE THREAD

**Issue by zackkozac** [ehealth-ua/api-spec#414]
Декларації із **сімейним лікарем** припиняють дію по досягненню пацієнтом 18 років.  За 503 наказом МОЗ мають продовжувати дію. З чим пов'язана така робота системи?

**Comment by kostikehealth** [comment]
@zackkozac буде виправлено

**Comment by AlekzandrV** [comment]
Виправлено на ДЕВ та ДЕМО
