### ISSUE TITLE
[PROD] Нельзя зарегистрировать клинику

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#417]
```
{"meta":{"url":"http://api.ehealth-ukraine.org:8000/api/legal_entities","code":401,"request_id":"27c7cb47-eff6-4f9e-b358-99909a34cb55#8318","type":"object"},"error":{"message":"Invalid access token","type":"access_denied"}}
```

Ранее работал и проблем не было. Подозреваю, что требуется обновить токен. Не нашёл никакой документации по поводу обновления токенов МИС или работы с ними. Подскажите где взять?

МИС: "Поліклініка без черг"

**Comment by svetavedmed** [comment]
Поправили.

**Comment by cshevchukod** [comment]
Так а работает сейчас "use-refresh-token-for-access-token-extension"? Судя из документации:

> Currently access_token and refresh_token are configured to have same lifetime, so we don't expect you to refresh it.In future, you will be able to refresh access tokens to extend access_token lifetime.
