### ISSUE TITLE
Завершення реєстрації МІС [MedCard Plus]

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#418]
После регистрации у нас нет данных.

логін/пароль, mis_client_id

**Comment by ioleksiy** [comment]
Для отримання повного набору даних для проду та препроду просимо надати заяву на ДП з полями (форму можно отримати у @kostikehealth):

name: `MIS ПП Тех-Нет Сервіс Медкард Плюс`
user_email: `test_user@mail.com`
redirect_uri: `https://mis_name/auth/redirect`

Прошу звернути увагу, що `redirect_uri` повинен бути з https та доменом.

Дякую.

**Comment by Charly3X** [comment]
а где найти @kostikehealth? в слаке нету.

**Comment by ehealthua** [comment]
@Charly3X а Ви надали запитану вище інформацію? Коли і кому?

**Comment by lymychp** [comment]
credentials відправлені на вказаний email. Прошу підтвердити отримання
