### ISSUE TITLE
На друкованій формі декларації вибиває контактні дані(емейл) не того лікаря (MIS Doctor Eleks)

### ISSUE THREAD

**Issue by LevOshchypok** [ehealth-ua/api-spec#419]
При друці декларацій у поле емейлу  підтягується емейл не того лікаря

![image](https://user-images.githubusercontent.com/25754494/40051975-47391cf4-5845-11e8-98df-1e3a854bd9a9.png)
![image](https://user-images.githubusercontent.com/25754494/40051982-4b99fdae-5845-11e8-9d52-a4ec22eb4025.png)

Частина відповіді
![image](https://user-images.githubusercontent.com/25754494/40052035-737b8662-5845-11e8-8e54-72a61421a3ba.png)

**Comment by lymychp** [comment]
відповідно до #354 друкується email підрозділу в якості контактного email лікаря
