### ISSUE TITLE
Неизвестная ошибка при регистрации клиники (ЕЦП от ПРИВАТБАНКА)

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#42]
При регистрации клиники выдаёт такую ошибку:

> {"meta":{"url":"http://api.ehealth-ukraine.org/api/legal_entities","type":"object","request_id":"rmpvb4gsv4meki2no95p3s26e6l3cset","code":400},"error":{"type":"request_malformed","message":"Signed request data is invalid","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}

Данный клиники, которую мы регистрируем:

> {"owner":{"gender":"MALE","phones":[{"type":"MOBILE","number":"+380509874741"},{"type":"LAND_LINE","number":"+380567495160"},{"type":"LAND_LINE","number":"+380567934460"}],"documents":[{"type":"PASSPORT","number":"АЕ 816138"}],"position":"P3","first_name":"Кондратенко","last_name":"Іван","second_name":"Миколайович","birth_date":"1978-01-31","tax_id":"2852004472","email":"blackbear11978@gmail.com","birth_place":"м. Житомир, Україна"},"medical_service_provider":{"accreditation":{"category":"FIRST","order_date":"2017-04-28","expiry_date":"2020-04-27","order_no":"466/0/197-17","issued_date":"2017-04-28"},"licenses":[{"license_number":"АД №063046","what_licensed":"Медична практика","issued_by":"Міністерство охорони здоров'я України","issued_date":"2012-07-12","active_from_date":"2012-07-12"}]},"addresses":[{"settlement":"ДНІПРО","settlement_type":"CITY","settlement_id":"ee73597c-273d-457c-a01a-5c86f2904db4","zip":"49020","street_type":"STREET","street":"Футбольна","building":"12","apartment":"-","type":"REGISTRATION","country":"UA","area":"ДНІПРОПЕТРОВСЬКА"}],"phones":[{"type":"LAND_LINE","number":"+380567495160"},{"type":"LAND_LINE","number":"+380567934460"}],"kveds":["86.21"],"owner_property_type":"STATE","name":"Комунальний заклад \"Дніпровський центр первинної медико-санітарної допомоги №12\"","short_name":"КЗ \"ДЦПМСД №12\"","legal_form":"430","edrpou":"37899720","public_name":"Комунальний заклад \"Дніпровський центр первинної медико-санітарної допомоги №12\"","email":"kzcentr12@ukr.net","type":"MSP","security":{"redirect_uri":"https://newmedicine.com.ua"},"public_offer":{"consent":true,"consent_text":"Зобов'язуюсь дотримуватись Регламенту функціонування системи eHealth. Підтверджую достовірність вказаних мною даних та добровільність надання цих даних. Усвідомлюю, що у випадку надання мною невірної інформації, мені може бути відмовлено у реєстрації в системі eHealth."}}

Используется ЕЦП от ПРИВАТБАНКА

**Comment by DPashchenko** [comment]
@cshevchukod Доброго времени суток! Будьте добры предоставить пример запроса (строку b64).

**Comment by lymychp** [comment]
Попробував відформатувати ваш json через pretty json pkg. Отримав помилку:
```
JSON Pretty: SyntaxError: Expected ',' instead of 'Д' at character 1251 near "{"owner":{"gender":"MALE","phones":[{"type":"MOBILE","number":"+380509874741"},{"type":"LAND_LINE","number":"+380567495160"},{"type":"LAND_LINE","number":"+380567934460"}],"documents":[{"type":"PASSPORT","number":"АЕ 816138"}],"position":"P3","first_name":"Кондратенко","last_name":"Іван","second_name":"Миколайович","birth_date":"1978-01-31","tax_id":"2852004472","email":"blackbear11978@gmail.com","birth_place":"м. Житомир, Україна"},"medical_service_provider":{"accreditation":{"category":"FIRST","order_date":"2017-04-28","expiry_date":"2020-04-27","order_no":"466/0/197-17","issued_date":"2017-04-28"},"licenses":[{"license_number":"АД №063046","what_licensed":"Медична практика","issued_by":"Міністерство охорони здоров'я України","issued_date":"2012-07-12","active_from_date":"2012-07-12"}]},"addresses":[{"settlement":"ДНІПРО","settlement_type":"CITY","settlement_id":"ee73597c-273d-457c-a01a-5c86f2904db4","zip":"49020","street_type":"STREET","street":"Футбольна","building":"12","apartment":"-","type":"REGISTRATION","country":"UA","area":"ДНІПРОПЕТРОВСЬКА"}],"phones":[{"type":"LAND_LINE","number":"+380567495160"},{"type":"LAND_LINE","number":"+380567934460"}],"kveds":["86.21"],"owner_property_type":"STATE","name":"Комунальний заклад "Дніпровський центр первинної медико-санітарної допомоги №12"","short_name":"КЗ "ДЦПМСД №12"","legal_form":"430","edrpou":"37899720","public_name":"Комунальний заклад "Дніпровський центр первинної медико-санітарної допомоги №12"","email":"kzcentr12@ukr.net","type":"MSP","security":{"redirect_uri":"https://newmedicine.com.ua"},"public_offer":{"consent":true,"consent_text":"Зобов'язуюсь дотримуватись Регламенту функціонування системи eHealth. Підтверджую достовірність вказаних мною даних та добровільність надання цих даних. Усвідомлюю, що у випадку надання мною невірної інформації, мені може бути відмовлено у реєстрації в системі eHealth."}}"
```
Можливо, є проблеми з кодуванням

**Comment by AlekzandrV** [comment]
Проблемы с экранированием кавычек
Нужно экранировать кавычки внутри `\"`

**Comment by cshevchukod** [comment]
@DPashchenko есои я всё верно понял, то вот:

> data:application/pkcs7-signature;base64,MIIN5wYJKoZIhvcNAQcCoIIN2DCCDdQCAQE…atpPuCNNh71qb4k1kme8KhDeSyilcNXc24wMDiFOGU29dy0crvg8g6uhLl3xHUxk1Hb/vx3GQ=

**Comment by DPashchenko** [comment]
@cshevchukod b64 не полная, проверьте еще раз, пожалуйста. Вместо ```...``` должен быть существенный кусок строки)

**Comment by cshevchukod** [comment]
@DPashchenko 

> data:application/pkcs7-signature;base64,MIIN5wYJKoZIhvcNAQcCoIIN2DCCDdQCAQExDjAMBgoqhiQCAQEBAQIBMAsGCSqGSIb3DQEHAaCCBbUwggWxMIIFWaADAgECAhQNhO2hu5OB6AQAAAAizxQAj2ZZADANBgsqhiQCAQEBAQMBATCCAUIxfDB6BgNVBAoMc9Cf0KPQkdCb0IbQp9Cd0JUg0JDQmtCm0IbQntCd0JXQoNCd0JUg0KLQntCS0JDQoNCY0KHQotCS0J4g0JrQntCc0JXQoNCm0IbQmdCd0JjQmSDQkdCQ0J3QmiDCq9Cf0KDQmNCS0JDQotCR0JDQndCawrsxETAPBgNVBAsMCNCQ0KbQodCaMTYwNAYDVQQDDC3QkNCm0KHQmiDQn9CQ0KIg0JrQkSDCq9Cf0KDQmNCS0JDQotCR0JDQndCawrsxFjAUBgNVBAUMDVVBLTE0MzYwNTcwLTExCzAJBgNVBAYTAlVBMScwJQYDVQQHDB7QlNC90ZbQv9GA0L7Qv9C10YLRgNC+0LLRgdGM0LoxKTAnBgNVBAgMINCU0L3RltC/0YDQvtC/0LXRgtGA0L7QstGB0YzQutCwMB4XDTE3MDYyOTA3MzQ1OFoXDTE4MDYyOTIwNTk1OVowggEVMSIwIAYDVQQKDBnQpNCG0JfQmNCn0J3QkCDQntCh0J7QkdCQMT8wPQYDVQQDDDbQmtCe0J3QlNCg0JDQotCV0J3QmtCeINCG0JLQkNCdINCc0JjQmtCe0JvQkNCZ0J7QktCY0KcxHzAdBgNVBAQMFtCa0J7QndCU0KDQkNCi0JXQndCa0J4xKDAmBgNVBCoMH9CG0JLQkNCdINCc0JjQmtCe0JvQkNCZ0J7QktCY0KcxEDAOBgNVBAUMBzEzNjM3NDYxCzAJBgNVBAYTAlVBMRkwFwYDVQQHDBDQnC4g0JTQndCG0J/QoNCeMSkwJwYDVQQIDCDQlNCd0IbQn9Cg0J7Qn9CV0KLQoNCe0JLQodCs0JrQkDBGMB4GCyqGJAIBAQEBAwEBMA8GDSqGJAIBAQEBAwEBAgYDJAAEISqO69ft4HDZ2YqSEb+XCz7z5OAALlmrKdEY6jM+bKvYAKOCAmQwggJgMCkGA1UdDgQiBCBiBI5jE5ZGXIzPs9TSfImlQY9o6zQALc0uYPgvw7BXGDArBgNVHSMEJDAigCCNhO2hu5OB6MMRkKiskoU/xNjHhMZKAbg3EVfYXRhVVzAvBgNVHRAEKDAmoBEYDzIwMTcwNjI5MDczNDU4WqERGA8yMDE4MDYyOTIwNTk1OVowDgYDVR0PAQH/BAQDAgbAMBkGA1UdIAEB/wQPMA0wCwYJKoYkAgEBAQICMAwGA1UdEwEB/wQCMAAwHgYIKwYBBQUHAQMBAf8EDzANMAsGCSqGJAIBAQECATA1BgNVHR8ELjAsMCqgKKAmhiRodHRwOi8vYWNzay5wcml2YXRiYW5rLnVhL2NybC9QQi5jcmwwQAYDVR0uBDkwNzA1oDOgMYYvaHR0cDovL2Fjc2sucHJpdmF0YmFuay51YS9jcmxkZWx0YS9QQi1EZWx0YS5jcmwwgZQGCCsGAQUFBwEBBIGHMIGEMDQGCCsGAQUFBzABhihodHRwOi8vYWNzay5wcml2YXRiYW5rLnVhL3NlcnZpY2VzL29jc3AvMEwGCCsGAQUFBzAChkBodHRwOi8vYWNzay5wcml2YXRiYW5rLnVhL2Rvd25sb2FkL2NlcnRpZmljYXRlcy9jZXJ0aWZpY2F0ZXMucDdiMEMGCCsGAQUFBwELBDcwNTAzBggrBgEFBQcwA4YnaHR0cDovL2Fjc2sucHJpdmF0YmFuay51YS9zZXJ2aWNlcy90c3AvMCcGA1UdCQQgMB4wHAYMKoYkAgEBAQsBBAEBMQwTCjI4NTIwMDQ0NzIwDQYLKoYkAgEBAQEDAQEDQwAEQJR1jA8/XyaW82vvJ+I+zEwYpVKQVZ0l54eb/hT2Nal1PySOvmx53WBZmPpVl/QTYXetVdcnfV56/cVSkSiRWk8xggf3MIIH8wIBATCCAVwwggFCMXwwegYDVQQKDHPQn9Cj0JHQm9CG0KfQndCVINCQ0JrQptCG0J7QndCV0KDQndCVINCi0J7QktCQ0KDQmNCh0KLQktCeINCa0J7QnNCV0KDQptCG0JnQndCY0Jkg0JHQkNCd0JogwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MREwDwYDVQQLDAjQkNCm0KHQmjE2MDQGA1UEAwwt0JDQptCh0Jog0J/QkNCiINCa0JEgwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MRYwFAYDVQQFDA1VQS0xNDM2MDU3MC0xMQswCQYDVQQGEwJVQTEnMCUGA1UEBwwe0JTQvdGW0L/RgNC+0L/QtdGC0YDQvtCy0YHRjNC6MSkwJwYDVQQIDCDQlNC90ZbQv9GA0L7Qv9C10YLRgNC+0LLRgdGM0LrQsAIUDYTtobuTgegEAAAAIs8UAI9mWQAwDAYKKoYkAgEBAQECAaCCBi0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTcwNjMwMTEyMTE2WjAvBgkqhkiG9w0BCQQxIgQgfg1z+MgjU41ZjHwrU6e1bjsXR36iO0UpC89xxj3VUPEwggG1BgsqhkiG9w0BCRACLzGCAaQwggGgMIIBnDCCAZgwDAYKKoYkAgEBAQECAQQg2M5nAYDOtgRft5UhEnOZmdNxyXSpgOKlorOHV+1UNZcwggFkMIIBSqSCAUYwggFCMXwwegYDVQQKDHPQn9Cj0JHQm9CG0KfQndCVINCQ0JrQptCG0J7QndCV0KDQndCVINCi0J7QktCQ0KDQmNCh0KLQktCeINCa0J7QnNCV0KDQptCG0JnQndCY0Jkg0JHQkNCd0JogwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MREwDwYDVQQLDAjQkNCm0KHQmjE2MDQGA1UEAwwt0JDQptCh0Jog0J/QkNCiINCa0JEgwqvQn9Cg0JjQktCQ0KLQkdCQ0J3QmsK7MRYwFAYDVQQFDA1VQS0xNDM2MDU3MC0xMQswCQYDVQQGEwJVQTEnMCUGA1UEBwwe0JTQvdGW0L/RgNC+0L/QtdGC0YDQvtCy0YHRjNC6MSkwJwYDVQQIDCDQlNC90ZbQv9GA0L7Qv9C10YLRgNC+0LLRgdGM0LrQsAIUDYTtobuTgegEAAAAIs8UAI9mWQAwggQHBgsqhkiG9w0BCRACFDGCA/YwggPyBgkqhkiG9w0BBwKgggPjMIID3wIBAzEOMAwGCiqGJAIBAQEBAgEwawYLKoZIhvcNAQkQAQSgXARaMFgCAQEGCiqGJAIBAQECAwEwMDAMBgoqhiQCAQEBAQIBBCB+DXP4yCNTjVmMfCtTp7VuOxdHfqI7RSkLz3HGPdVQ8QIEBofiExgPMjAxNzA2MzAxMTIxNDdaMYIDWzCCA1cCAQEwggETMIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTIxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUMAR1He8seK4CAAAAAQAAAEoAAAAwDAYKKoYkAgEBAQECAaCCAdowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJBTEPFw0xNzA2MzAxMTIxNDdaMC8GCSqGSIb3DQEJBDEiBCB+HWHUkp5xXB7OYw0SnnvV/VWMcn+MIkNnXBm7adJIZTCCAWsGCyqGSIb3DQEJEAIvMYIBWjCCAVYwggFSMIIBTjAMBgoqhiQCAQEBAQIBBCDZDaa2SFPDLb+XuPblXM1qxXlSA+KYRLrjydZWG2e86jCCARowggEApIH9MIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTIxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUMAR1He8seK4CAAAAAQAAAEoAAAAwDQYLKoYkAgEBAQEDAQEEQJjMlukXiXa3BxNvwV9XC8a422G92fLZwagOsLyXfrk3+NuYxD3i4EwujonEE+KzgHNCkG8iqDh0FkUj2S7Izl4wDQYLKoYkAgEBAQEDAQEEQNSXHDRLXRk/RiatpPuCNNh71qb4k1kme8KhDeSyilcNXc24wMDiFOGU29dy0crvg8g6uhLl3xHUxk1Hb/vx3GQ=

**Comment by AlekzandrV** [comment]
@DPashchenko @cshevchukod 

> Проблемы с экранированием кавычек
Нужно экранировать кавычки внутри \"

**Comment by DPashchenko** [comment]
@cshevchukod как вы подписываете данные?

**Comment by cshevchukod** [comment]
@DPashchenko Через ЦЗО используя АЦСК "ПРИВАТБАНКА".
@AlekzandrV Возможно проблема действительно с экранированием кавычек. Пока нет возможности проверить, но чуть позже попробуем.

**Comment by DPashchenko** [comment]
@cshevchukod http://czo.gov.ua/sign тут?
Какой вариант подписания данных выбираете?

**Comment by cshevchukod** [comment]
@DPashchenko АЦСК ПАТ КБ "ПРИВАТБАНК"

**Comment by DPashchenko** [comment]
Попробуйте подписать через сервис http://czo.gov.ua/sign

**Comment by DPashchenko** [comment]
@cshevchukod Вы когда подписываете данные выбираете метод подписания "данные и подпись раздельно". В нашем случае, согласно спецификации, требуется формат pkcs7 в котором и данные и подпись вместе.

**Comment by DPashchenko** [comment]
@cshevchukod Доброго времени суток! Удалось ли получить успешный ответ от сервиса?

**Comment by DPashchenko** [comment]
@cshevchukod День добрый! Ожидаем от Вас обратную связь по инциденту.
Спасибо

**Comment by cshevchukod** [comment]
Добрый день.
Так сложилось, то клинику удалось зарегистрировать в день подачи бага, но без нашего участия. письмо для подтверждения регистрации пришло на email ответственного сотрудника ещё 30.06.17. При этом мы так и не получили msp_key. Ответственный сотрудник сообщил, что письмо пришло без его участия самостоятельно через 3 часа, после сообщения нам о существовании такой ошибки.
В чём причина этого сложно сказать. Возможно человеческий фактор. Однако всё ещё остаётся проблема с msp_key.

**Comment by pzhuk** [comment]
@cshevchukod  я клинику с edrpou 37899720 не вижу вообще в системе.
Пожалуйста, уточните четко с каким именно запросом была проблема.

**Comment by cshevchukod** [comment]
При регистрации клиники выдаёт такую ошибку:

`{"meta":{"url":"http://api.ehealth-ukraine.org/api/legal_entities","type":"object","request_id":"rmpvb4gsv4meki2no95p3s26e6l3cset","code":400},"error":{"type":"request_malformed","message":"Signed request data is invalid","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}`

Очень странно, завтра сутра ещё раз всё проверим. Теперь совершенно непонятно по какой причине ответственному сотруднику клиники пришло письмо с просьбой подтвердить регистрацию.

**Comment by cshevchukod** [comment]
Сделали нужную подпись. Проверили.  Зарегистрировать невозможно. В Этот раз не проходит валидацию по ЕДРПОУ.

`{"meta":{"url":"http://api.ehealth-ukraine.org/api/legal_entities","type":"object","request_id":"27voetcmoicjol79krvh07rjlsbqdj0k","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"required","params":[],"description":"can't be blank"}],"entry_type":"json_data_property","entry":"$.edrpou"}]}}`

Похоже клиника всё же существует. И странно, что вы этого не видите.

**Comment by cshevchukod** [comment]
Коллеги, так и не получил ответа от вас. Есть ли какие-либо новости по проблеме?

**Comment by pzhuk** [comment]
В прошлом запросе явно не проходит валидация ЕДРПОУ, что означает несоответствие введенного ЕДРПОУ тому, который представлен в ЕЦП. Никакого отношения к наличию, или отсутствию клиники в системе данная ошибка не имеет

**Comment by cshevchukod** [comment]
1. Может ли проблема быть связана с ЕЦП от ПРИВАТБАНКА?
2. Если это так, то каким-то образом клиника получила письмо с подтверждением регистрации.
В остальном буду обращаться к клинике.

**Comment by pzhuk** [comment]
Укажите email, на который клиника получила письмо

**Comment by cshevchukod** [comment]
blackbear11978@gmail.com

**Comment by pzhuk** [comment]
На цей email надсилались листи тільки він ehealth.world, яка не є продакшн, і це не співпадає з даними, які ви наводите в запитах, які ви надсилали (ehealth-ukaine.org)

**Comment by cshevchukod** [comment]
Принял. Хотя вопросов возникает ещё больше, т.к.:
- мы не заводили эту клинику на тест
- на тесте не возникло проблем с валидацией
В остальном, обратимся в клинику. Спасибо. Это всё.

**Comment by pzhuk** [comment]
На всякий случай проверьте, что у вас в системе нигде хардкодом не прописан сайт демо.

На всякий случай напоминаю

* http://demo.ehealth.world -  dev env
* https://api.ehealth.world - pre-prod env (полностью аналогичная prod по версиям и конфигурации)
* htts://api.ehealth-ukraine.org - prod env (честный продакшн, полиси, регламент, все дела...)
