### ISSUE TITLE
Новые документы на Портал в раздел Документы

### ISSUE THREAD

**Issue by goutsalova** [ehealth-ua/api-spec#420]
Завесить ASAP 2 новых документа:

Наказ ДП "Електронне здоров'я" від 14.05.18р. №11-ГД "Про внесення змін до Наказу №3-ГД від 21.03.2018р."

Наказ ДП "Електронне здоров'я" від 14.05.18р. №10-ГД "Про внесення змін до Регламенту функціонування компонентів електронної системи обміну медичною інформацією, що необхідні для запуску нової моделі фінансування на первинному рівні надання медичної допомоги"

[Zminy_do_Reglamentu_Nakaz_10gd.pdf](https://github.com/ehealth-ua/api-spec/files/2005031/Zminy_do_Reglamentu_Nakaz_10gd.pdf)
[Zminy_do_Tymchasovogo_poraydku_testuvannya_Nakaz11gd.pdf](https://github.com/ehealth-ua/api-spec/files/2005032/Zminy_do_Tymchasovogo_poraydku_testuvannya_Nakaz11gd.pdf)

**Comment by lymychp** [comment]
delivered to prod
