### ISSUE TITLE
pre-prod http 500 на GET /api/declarations

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#423]
## Steps to Reproduce (Repro steps)

- [ ] https://api-preprod.ehealth-ukraine.org/api/declarations?status=active

## Actual result
- [ ] `{
        "meta" : {
            "url" : "http://api-svc.il/api/declarations",
            "type" : "object",
            "request_id" : "084f2c3a-f753-4474-857a-c0dd62a9b5bb#17701",
            "code" : 500
        },
        "error" : {
            "errors" : {
                "detail" : "Internal server error"
            }
        }
    }`

## Expected result
- [ ] не http 500

**Comment by svetavedmed** [comment]
fixed
