### ISSUE TITLE
Не изменили сервер в письме с приглашением на препроде

### ISSUE THREAD

**Issue by mishenya** [ehealth-ua/api-spec#424]
В письме с приглашением присоединиться в системе Ехелс остался старый сервер - 
https://auth-denovo.ehealth.world/invite?invite=SXJUTjB2cmo4Nm1DdmE0OFRTMjc1YVlJT2FNRSUyRmhGbGhHS3F2MzVNYiUyRnZDbTZMWFhQUGp2TVF4c0wlMkZJY2VHcw==
Как итог при переходе по ссылке не получается  зарегистрироваться в системе Ехелс. Вручную приходится менять на https://auth-preprod.ehealth-ukraine.org, тогда все работает. Просьба исправить

**Comment by svetavedmed** [comment]
fixed
