### ISSUE TITLE
Declaration_request create (authentication)

### ISSUE THREAD

**Issue by Evgeniy0119** [ehealth-ua/api-spec#425]
Пациент подписал декларацию с врачом (метод  authentication OTP),
потом пришёл к другому врачу, номер его уже не действителен, изменил на новый  в итоге смс идут на старый тел., врач меняет тип authentication на Ofline, но метод возвращается OTP.

Сделайте механизм Reset authentication.

У врачей нет возможности подписать декларации с такими пациентами, их становится всё больше и больше. Проблему нужно решать.

**Comment by lymychp** [comment]
Метод авторизації визначається автоматично системою на основі того, що приходить в payload та на основі даних в ЦБД. Якщо в пацієнта вже була декларація з методом авторизації отп, то незалежно від пейлоад в новому запиті на декларацію, метод буде визначено як отп.

Скидання телефону авторизації здійснюється тільки через ДП/НСЗУ. Відповідний функціонал вже реалізовано.

**Comment by Evgeniy0119** [comment]
КАК ЗАКЛЮЧАТЬ НА ДАННЫЙ МОМЕНТ ДЕКЛАРАЦИИ?

**Comment by lymychp** [comment]
Як варіант, пацієнт відновлює свій старий телефон. 
це не баг і не технічне запитання, а організаційне.

**Comment by zackkozac** [comment]
@lymychp Надходять звернення, коли пацієнт взагалі заперечує факт укладення декларації та стверджує, що такого номеру не знає. Як перевірити, що він не говорить правду. Чи відомо вже порядок звернення до НСЗУ?

**Comment by Evgeniy0119** [comment]
Нет, можете почитать переписку в слаке за 17.05,  ответа нет...
