### ISSUE TITLE
Неверное значение поля declaration_count

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#426]
При запросе http://ehealth.edenlabllc.com/api/employees/<employee_id> на проде поле declaration_count отображет общее кол-во деклараций по юр. лицу, а не по сотруднику.

**Comment by lymychp** [comment]
@pieskov прошу надати приклад запиту/відповіді

**Comment by pieskov** [comment]
Если доктор привязан к дивижину, то считает нормально. А если к юр. лицу то неправильно.

**Comment by lymychp** [comment]
@pieskov ждем приклад.
дякую

**Comment by lymychp** [comment]
employee `706c2b98-f22a-4b18-aca9-3f8de3950f29`, `19b544b9-8fc3-44eb-8e0e-27027793c854` це одна і та ж особа - party `5e813668-4f3b-4e7d-aed1-a32a126f29e3`
ЛІміт рахуєтсья на особу. Тому цифри співпадають.
Все ок
