### ISSUE TITLE
Декларации на проверке более месяца. Прод

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#427]
Есть несколько деклараций которые уже более месяца на проверке...

Номера некоторых из них.

0000-3EH7-P89E
0000-PHEA-H46E
0000-2ATE-3PP2
0000-01TM-6XHT

**Comment by svetavedmed** [comment]
0000-3EH7-P89E и 0000-01TM-6XHT - от 15-05 - поэтому не активны еще
0000-PHEA-H46E, 0000-2ATE-3PP2 - уже активны
