### ISSUE TITLE
Не работает offline подтверждение декларации на PREDPROD

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#428]
curl 198.54.117.200:443
c 52.178.33.223

Ответ:
curl: (7) Failed to connect to 198.54.117.200 port 443: Connection refused

**Comment by lymychp** [comment]
а по доменному імені?

**Comment by INFOPAUL** [comment]
Тоже самое

**Comment by lymychp** [comment]
1) дайте, будь ласка, лог спроби завантаження документу
2) з якого ІР завантажуєте?

**Comment by lymychp** [comment]
no feedback provided
