### ISSUE TITLE
bug in /api/declarations with person field

### ISSUE THREAD

**Issue by dmmat** [ehealth-ua/api-spec#429]
## Steps to Reproduce 
- [ ] /api/declarations [PROD]
- [ ] ```"request_id": "17cc0503-94c4-4a13-bfc5-5923942b1d2d#6575"```
- [ ] ``` "paging": {
"total_pages": 10,
"total_entries": 903,
"page_size": 100,
"page_number": 1
} ``` 
- [ ] if page_size ~ 100

## Actual result
- [ ] some items in data array without person (```"person": null,```) 

## Expected result
- [ ] items with persons field

**Comment by lymychp** [comment]
fixed on prod
