### ISSUE TITLE
Ошибка проверки поля employee_request.doctor.qualifications.[0].certificate_number

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#43]
При регистрации employee:
`{"employee_request":{"end_date": "1899-12-30", "legal_entity_id": "5933602e-c3bc-4a3a-a961-6ec3569052e5", "position": "P1", "start_date": "2017-07-03", "status": "NEW", "employee_type": "DOCTOR", "party": {"first_name": "Иван", "second_name": "Иванович", "birth_date": "1958-04-04", "gender": "MALE", "tax_id": "2222222222", "email": "email@example.com", "documents": [{"type": "PASSPORT", "number": "НС336478 "}], "phones": [{"type": "LAND_LINE", "number": "+380372373350"}]}, "doctor": {"educations": [{"country": "UA", "city": "Київ", "institution_name": "Академія Богомольця", "issued_date": "1977-04-04", "diploma_number": "DD123543", "degree": "MASTER", "speciality": "Педіатр"}], "qualifications": [{"type": "AWARDING", "institution_name": "Академія Богомольця", "speciality": "Педіатр", "issued_date": "2017-08-05", "certificate_number": "СТ123456"}], "specialities": [{"speciality": "PEDIATRICIAN", "speciality_officio": true, "level": "FIRST", "qualification_type": "AWARDING", "attestation_name": "Академія Богомольця", "attestation_date": "2017-08-05", "valid_to_date": "2017-08-05", "certificate_number": "AB\/21331"}], "science_degree": {"country": "UA", "city": "Київ", "institution_name": "Академія Богомольця", "issued_date": "2017-08-05", "diploma_number": "DD123543", "degree": "Доктор філософії", "speciality": "THERAPIST"}}}}`

`
"rules": [
                   {
                       "rule": "format",
                       "params": [
                           "^(\\d{4}(?!\\d{2}\\b))((-)((0[1-9]|1[0-2])(\\3([12]\\d|0[1-9]|3[01]))|(00[1-9]|0[1-9]\\d|[12]\\d{2}|3([0-5]\\d|6[1-6]))))$"
                       ],
                       "description": "string does not match pattern \"^(\\\\d{4}(?!\\\\d{2}\\\\b))((-)((0[1-9]|1[0-2])(\\\\3([12]\\\\d|0[1-9]|3[01]))|(00[1-9]|0[1-9]\\\\d|[12]\\\\d{2}|3([0-5]\\\\d|6[1-6]))))$\""
                   }
               ],
               "entry_type": "json_data_property",
               "entry": "$.employee_request.doctor.qualifications.[0].certificate_number
`

**Comment by DPashchenko** [comment]
@pieskov Доброго времени суток! Выставлен Pull Request на исправление данного инцидента.
Спасибо.

**Comment by lymychp** [comment]
deployed to demo
