### ISSUE TITLE
Пользователь не может подписывать декларации, срабатывает проверка "captcha"

### ISSUE THREAD

**Issue by Evgeniy0119** [ehealth-ua/api-spec#431]
Помогите разобраться как решить данную проблему:

При подписании декларации срабатывает проверка "captcha" врач не может подписывать декларации

текст ошибки:

HTTP/1.1 403 Forbidden
Date: Fri, 18 May 2018 10:21:58 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Set-Cookie: __cfduid=db4f1018ca0d9feae1953e44efc35e26d1526638918; expires=Sat, 18-May-19 10:21:58 GMT; path=/; domain=.ehealth-ukraine.org; HttpOnly; Secure
CF-Chl-Bypass: 1
Cache-Control: max-age=2
Expires: Fri, 18 May 2018 10:22:00 GMT
X-Frame-Options: SAMEORIGIN
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 41cd999acc6d2684-FRA

15be

**Comment by lymychp** [comment]
це відповідь не нашого api в додатку

**Comment by Evgeniy0119** [comment]
Мы делаем запрос на Ваш API и получаем такой ответ, Вы можете посмотреть в чём проблема?

**Comment by lymychp** [comment]
до нас ваш запит не приходив. І це видно з того, що відповідь не від нашого АПІ. Рекомендую звернутись до Ваших адміністраторів мережі і дослідити проблему спочатку в себе.

**Comment by Evgeniy0119** [comment]
А у Вас случайно хостинг не этот: Cloudflare? Который собственно и лочит запрос

**Comment by Evgeniy0119** [comment]
![img_21052018_163446_0](https://user-images.githubusercontent.com/37930918/40310285-f506eb58-5d14-11e8-95ce-3a80cc8b4a01.png)

**Comment by lymychp** [comment]
Дайте повний лог запиту

**Comment by lymychp** [comment]
https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor-
