### ISSUE TITLE
Перебиваются сотрудники с одним инн

### ISSUE THREAD

**Issue by mishenya** [ehealth-ua/api-spec#436]
Добрый день. На препроде:
1. регистрируем сотрудника с инн.
2. регистрируем другого сотрудника с таким же инн
Результат: у первого сотрудника изменяется ФИО на ФИО второго.
Вопрос: если кто то регистрирует сотрудника и ошибочно (или злонамеренно) указывает инн уже зарегистрированного сотрудника, первый вдруг увидит что его данные изменились. 
Это правильно? Или что-то тут не так?

**Comment by lymychp** [comment]
Прошу надати повний лог з послідовністю викликів апі

**Comment by lymychp** [comment]
inactive
