### ISSUE TITLE
PROD не авторизуется користувач

### ISSUE THREAD

**Issue by xSoulRootx** [ehealth-ua/api-spec#438]
Після вводу email'у та паролю на сторінці:
https://auth.ehealth-ukraine.org/accept?client_id=[CLIENT_ID]&email=[EMAIL]&redirect_uri=[URI]
Потрапляю на сторінку з всіма дозволами користувача:
`
• Отримання інформації про заклад
• Оновлення інформації про заклад
• Верифікація закладу через МІС
• Отримання переліку ролей системи
• user:request_factor
• user:approve_factor
• event:read
`

Натискую кнопку "прийняти та продовжити", проте нічого не відбуваєтся.
MIS: UASmart.

**Comment by svetavedmed** [comment]
а можно полный лог request и response?

**Comment by xSoulRootx** [comment]
Цей запит робився напряму в браузері.
Данні для доступу брались з листа, котрий видали при авторизації МІС.

**Comment by svetavedmed** [comment]
@xSoulRootx чтобы мы смогли вам помочь, нужны данные по ошибке. Ваш случай не носит массового характера и другие пользователи могут авторизоваться.

**Comment by xSoulRootx** [comment]
Так в тому то і річ. Нічого не з’являється. Клік на кнопку виходить наче в пустоту.

**Comment by xSoulRootx** [comment]
В консолі є помилка:
```
{
    "meta": {
        "url": "http://api-svc.mithril/oauth/apps/authorize",
        "type": "object",
        "request_id": "8f19db79-c296-4fb0-b3d4-df07d89de6e6#21545",
        "code": 422
    },
    "error": {
        "type": "request_malformed",
        "message": "Scope is not allowed by client type.",
        "invalid": [{
            "rules": [{
                "rule": "json"
            }],
            "entry_type": "request"
        }]
    }
}
```

**Comment by svetavedmed** [comment]
Судя по ответу у данного пользователя нет необходимых скоупов. А кто пытается залогинится? какая роль? email?
