### ISSUE TITLE
Ошибка при регистрации нового медзаклада. ДЕМО

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#439]
Регистрирую медзаклад. Получаю  письмо. Перехожу по ссылке. Задаю пароль. Ставлю галочку ПРИНЯТЬ РЕГЛАМЕНТ. Нажимаю кнопку. 
И ничего не происходит. В консоле ошибка

{"meta":{"url":"http://api.demo.asclepius.com.ua:8000/api/employee_requests/2599c159-ad26-4d06-8ad9-03cbb0419fec/approve","code":403,"request_id":"7683f5d3-d298-4ed4-9061-56718cee4ea0#9022","type":"object"},"error":{"message":"Your scope does not allow to access this resource. Missing allowances: employee_request:approve","type":"forbidden"}}

**Comment by svetavedmed** [comment]
fixed
