### ISSUE TITLE
Обновление short_name public_name в сущности LegalEntity

### ISSUE THREAD

**Issue by rshmorgun** [ehealth-ua/api-spec#444]
Добрый день!

При обновлении LegalEntity, допустим я удалил short_name или public_name, в подписанном json их нету, но в ответ они приходят не удаленными! Хотя если строки поменять, то все проходит отлично

**Comment by ioleksiy** [comment]
чи можете ви детальніше описати проблему? чи покроково з прикладом коду?

**Comment by rshmorgun** [comment]
Добрый день!

действия

1. я Создал в ehealth LegalEntity при этом заполнив все поля в том числе  short_name и public_name Сохранил! пришел валидный ответ!
2. я пытаюсь обновить LegalEntity удалив полностью значения полей short_name и public_name, но в ответ мне приходит ответ ОК, но поля short_name и public_name остаются не обновленными в ehealth
3. если надо то могу скинуть формат json-а

**Comment by rshmorgun** [comment]
Читает ли кто здесь сообщения?

**Comment by svetavedmed** [comment]
Добрый день. Вы можете только обнулить данные поля, только изменить.

**Comment by rshmorgun** [comment]
Добрый день! объясните как в конечном итоге, обнулить или изменить? изменить получилось, а обнулить нет

**Comment by svetavedmed** [comment]
Можно только изменить

**Comment by rshmorgun** [comment]
Спасибо!
