### ISSUE TITLE
Проблема з розсилкою смс-кодів

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#445]
*Доброго дня, перевірте будь-ласка чи немає збоїв по смс авторизації, користувачі скаржаться на розсилку, дякую!*

/*
Лікарям почали приходити масово смс з текстом "Код авторизації дій в системі eHealth: ****" іноді до 14 повторних смс. при цьому вони неіяких запитів в систему не робили. 
(https://ua-ehealth.slack.com/archives/C9P8Y4PK6/p1527598747000531)
*/

MIS: Doctor Eleks

**Comment by innashymkiv** [comment]
063 259 74 79

**Comment by lymychp** [comment]
по цьому телефону було ініційовано відправку смс через апі в `2018-05-29 07:56:00.952163`.
Відповідно було відправлено одну смс.

**Comment by innashymkiv** [comment]
це лікар, який давно реєструє пацієнтів. він каже, що нічого не ініціював.

**Comment by innashymkiv** [comment]
Доктор Елекс, попрошу) дякую, розібралися. питання можна закривати
