### ISSUE TITLE
PREPROD Не могу зарегистрировать новый НМП

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#446]
PUT /api/legal_entities HTTP/1.1
Host: api-preprod.ehealth-ukraine.org
Content-Type: application/json
Authorization: Bearer 41e1d188453e26846c469f0388322613
api-key: 7a07feaf4c37ef135f85
Cache-Control: no-cache
Postman-Token: 9e3ec771-698d-4fa9-8e03-2ec2513eb75e

{"signed_legal_entity_request":"MIIadwYJKoZIhvcNAQcCoIIaaDCCGmQCAQExDjAMBgoqhiQCAQEBAQIBMIIN8gYJKoZIhvcNAQcBoIIN4wSCDd97Im5hbWUiOiLQstC70YPRiCIsInNob3J0X25hbWUiOiLRiNGD0YjRhtGI0L7RhtGDIiwicHVibGljX25hbWUiOiLQvtGD0YjRiNGG0YMiLCJ0eXBlIjoiTUlTIiwib3duZXJfcHJvcGVydHlfdHlwZSI6IlNUQVRFIiwibGVnYWxfZm9ybSI6IjI0MCIsImVtYWlsIjoia29uc3RhbnRpbjk0QHVrci5uZXQiLCJlZHJwb3UiOiIzNjI1NzY0NyIsImt2ZWRzIjpbIjg2LjEwIl0sImFkZHJlc3NlcyI6W3sidHlwZSI6IlJFR0lTVFJBVElPTiIsImNvdW50cnkiOiJVQSIsImFyZWEiOiLQl9CQ0JrQkNCg0J/QkNCi0KHQrNCa0JAiLCJzZXR0bGVtZW50Ijoi0JTQndCG0J/QoNCeIiwic2V0dGxlbWVudF90eXBlIjoiQ0lUWSIsInNldHRsZW1lbnRfaWQiOiJlZTczNTk3Yy0yNzNkLTQ1N2MtYTAxYS01Yzg2ZjI5MDRkYjQiLCJzdHJlZXRfdHlwZSI6IlNUUkVFVCIsInN0cmVldCI6Ijgt0LPQviDQkdC10YDQtdC30L3RjyIsImJ1aWxkaW5nIjoiNTUiLCJhcGFydG1lbnQiOiI1IiwiemlwIjoiNTk5NTgifV0sInBob25lcyI6W3sidHlwZSI6Ik1PQklMRSIsIm51bWJlciI6IiszODAwMDk1OTU5NTUifV0sIm93bmVyIjp7ImZpcnN0X25hbWUiOiLQu9GD0L7Rg9GI0YgiLCJsYXN0X25hbWUiOiLQu9Cy0LvQu9CyIiwic2Vjb25kX25hbWUiOiLRgNGD0YjQs9C70L7RhtC0IiwidGF4X2lkIjoiMzAwMDAwNzU1NiIsImJpcnRoX2RhdGUiOiIxOTgyLTAyLTE5IiwiZ2VuZGVyIjoiTUFMRSIsImVtYWlsIjoia29uc3RhbnRpbjk0QHVrci5uZXQiLCJkb2N1bWVudHMiOlt7InR5cGUiOiJQQVNTUE9SVCIsIm51bWJlciI6IjU5NTU5NTk1In1dLCJwaG9uZXMiOlt7InR5cGUiOiJNT0JJTEUiLCJudW1iZXIiOiIrMzgwOTU5NTk1OTU1In1dLCJwb3NpdGlvbiI6IlAxMSJ9LCJtZWRpY2FsX3NlcnZpY2VfcHJvdmlkZXIiOnsiYWNjcmVkaXRhdGlvbiI6eyJjYXRlZ29yeSI6IkZJUlNUIiwiaXNzdWVkX2RhdGUiOiIyMDA1LTA1LTA1IiwiZXhwaXJ5X2RhdGUiOiIyMDE5LTEyLTI3Iiwib3JkZXJfbm8iOiI1NTU5NTk1Iiwib3JkZXJfZGF0ZSI6IjIwMTgtMTItMjkifSwibGljZW5zZXMiOlt7ImxpY2Vuc2VfbnVtYmVyIjoi0LI1OdGDIiwiaXNzdWVkX2J5Ijoi0LDRltCy0LDRltCy0LAiLCJpc3N1ZWRfZGF0ZSI6IjIwMTUtMTItMzEiLCJleHBpcnlfZGF0ZSI6IjIwMTgtMTItMzAiLCJhY3RpdmVfZnJvbV9kYXRlIjoiMjAxNi0xMS0zMCIsIndoYXRfbGljZW5zZWQiOiLQsNGW0LLQstGW0LDRltCyIiwib3JkZXJfbm8iOiI1OTU1OSJ9XX0sInNlY3VyaXR5Ijp7InJlZGlyZWN0X3VyaSI6Imh0dHBzOi8vOTMuMTgzLjIwNi44MyJ9LCJwdWJsaWNfb2ZmZXIiOnsiY29uc2VudCI6dHJ1ZSwiY29uc2VudF90ZXh0Ijoi0JLRltC00L/QvtCy0ZbQtNC90L4g0LTQviDQl9Cw0LrQvtC90YMg0KPQutGA0LDRl9C90LggXCLQn9GA0L4g0LfQsNGF0LjRgdGCINC/0LXRgNGB0L7QvdCw0LvRjNC90LjRhSDQtNCw0L3QuNGFXCIg0Lcg0LzQtdGC0L7RjiDQstC10LTQtdC90L3RjyDRgNC10ZTRgdGC0YDRltCyINC10LvQtdC60YLRgNC+0L3QvdC+0Zcg0YHQuNGB0YLQtdC80Lgg0L7RhdC+0YDQvtC90Lgg0LfQtNC+0YDQvtCyJ9GPINGC0LAg0LfQsNCx0LXQt9C/0LXRh9C10L3QvdGPINGX0Zcg0YTRg9C90LrRhtGW0L7QvdGD0LLQsNC90L3RjyDRgyDQtNC+0YHQu9GW0LTQvdGW0Lkg0LXQutGB0L/Qu9GD0LDRgtCw0YbRltGXINC90LDQtNCw0Y4g0LfQs9C+0LTRgyDQvtCx0YDQsNC90L7QvNGDINC+0L/QtdGA0LDRgtC+0YDRgyDRgtCwINCw0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGA0YMg0LXQu9C10LrRgtGA0L7QvdC90L7RlyDRgdC40YHRgtC10LzQuCDQvtGF0L7RgNC+0L3QuCDQt9C00L7RgNC+0LIn0Y8g0L3QsCDQvtCx0YDQvtCx0LrRgyDQvNC+0ZfRhSDQv9C10YDRgdC+0L3QsNC70YzQvdC40YUg0LTQsNC90LjRhSDQtyDQv9C10YDQstC40L3QvdC40YUg0LTQttC10YDQtdC7LCDQsCDRgtCw0LrQvtC2INC90LAg0LfQtNGW0LnRgdC90LXQvdC90Y8g0LTRltC5INC/0L7QsifRj9C30LDQvdC40YUg0LfRliDQt9Cx0LjRgNCw0L3QvdGP0LwsINGA0LXRlNGB0YLRgNCw0YbRltGU0Y4sINC90LDQutC+0L/QuNGH0LXQvdC90Y/QvCwg0LfQsdC10YDRltCz0LDQvdC90Y/QvCwg0LDQtNCw0L/RgtGD0LLQsNC90L3Rj9C8LCDQt9C80ZbQvdC+0Y4sINC/0L7QvdC+0LLQu9C10L3QvdGP0LwsINCy0LjQutC+0YDQuNGB0YLQsNC90L3Rj9C8LCDQv9C+0YjQuNGA0LXQvdC90Y/QvCwg0YDQvtC30L/QvtCy0YHRjtC00LbQtdC90L3Rj9C8LCDRgNC10LDQu9GW0LfQsNGG0ZbRlNGOLCDQv9C10YDQtdC00LDRh9C10Y4sINC30L3QtdC+0YHQvtCx0LvQtdC90L3Rj9C8LCDQt9C90LjRidC10L3QvdGP0Lwg0LHRg9C00YwtINGP0LrQuNGFINCy0ZbQtNC+0LzQvtGB0YLQtdC5LtCU0L7QtNCw0YLQutC+0LLQviDQvdCw0LTQsNGOINC30LPQvtC00YMg0L3QsCDQtNC+0YHRgtGD0L8g0LTQviDQvNC+0ZfRhSDQv9C10YDRgdC+0L3QsNC70YzQvdC40YUg0LTQsNC90LjRhSDRg9C/0L7QstC90L7QstCw0LbQtdC90LjRhSDRgtGA0LXRgtGW0YUg0L7RgdGW0LEsINGJ0L4g0LLQuNC30L3QsNGH0LDRlCDQtNGW0Zcg0L7Qv9C10YDQsNGC0L7RgNCwINCc0IbQoSDRgtCwINCw0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGA0LAg0YMg0YDQsNC30ZYg0L7RgtGA0LjQvNCw0L3QvdGPINC30LDQv9C40YLRgyDQstGW0LQg0YPQv9C+0LLQvdC+0LLQsNC20LXQvdC+0Zcg0YLRgNC10YLRjNC+0Zcg0L7RgdC+0LHQuCDRidC+0LTQviDQvdCw0LTQsNC90L3RjyDQtNC+0YHRgtGD0L/RgyDQtNC+INC/0LXRgNGB0L7QvdCw0LvRjNC90LjRhSDQtNCw0L3QuNGFLtCf0ZbQtNGC0LLQtdGA0LTQttGD0Y4g0LTQvtGB0YLQvtCy0ZbRgNC90ZbRgdGC0Ywg0LLQutCw0LfQsNC90LjRhSDQvNC90L7RjiDQtNCw0L3QuNGFINGC0LAg0LTQvtCx0YDQvtCy0ZbQu9GM0L3RltGB0YLRjCDQvdCw0LTQsNC90L3RjyDRhtC40YUg0LTQsNC90LjRhSDQtNC+INC10LvQtdC60YLRgNC+0L3QvdC+0Zcg0YHQuNGB0YLQtdC80Lgg0L7RhdC+0YDQvtC90Lgg0LfQtNC+0YDQvtCyJ9GPLCDRidC+INC/0YDQsNGG0Y7RlCDRgyDQtNC+0YHQu9GW0LTQvdGW0Lkg0LXQutGB0L/Qu9GD0LDRgtCw0YbRltGXLiDQo9GB0LLRltC00L7QvNC70Y7Rjiwg0YnQviDRgyDQstC40L/QsNC00LrRgyDQvdCw0LTQsNC90L3RjyDQvNC90L7RjiDQvdC10LLRltGA0L3QvtGXINGW0L3RhNC+0YDQvNCw0YbRltGXLCDQvNC10L3RliDQvNC+0LbQtSDQsdGD0YLQuCDQstGW0LTQvNC+0LLQu9C10L3QviDQsiDRgNC10ZTRgdGC0YDQsNGG0ZbRlyDQsiDQtdC70LXQutGC0YDQvtC90L3RltC5INGB0LjRgdGC0LXQvNGWINC+0YXQvtGA0L7QvdC4INC30LTQvtGA0L7QsifRjy7Ql9C+0LHQvtCyJ9GP0LfRg9GO0YHRjCDQtNC+0YLRgNC40LzRg9Cy0LDRgtC40YHRjCDQoNC10LPQu9Cw0LzQtdC90YLRgyDRhNGD0L3QutGG0ZbQvtC90YPQstCw0L3QvdGPINC10LvQtdC60YLRgNC+0L3QvdC+0Zcg0YHQuNGB0YLQtdC80Lgg0L7RhdC+0YDQvtC90Lgg0LfQtNC+0YDQvtCyJ9GPLiJ9faCCBbswggW3MIIFX6ADAgECAhRbr8kGAAAAAAAAAAAAAAAAAAAAATANBgsqhiQCAQEBAQMBATCCARwxWzBZBgNVBAMMUtCQ0KbQodCaINCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxETAPBgNVBAcMCNCa0LjRl9CyMRkwFwYDVQQFDBBVQS0zNjg2NTc1My0wMTE3MVIwUAYDVQQKDEnQotCe0JIgItCm0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C90LAiMS4wLAYDVQQLDCXQktGW0LTQtNGW0Lsg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXMQswCQYDVQQGDAJVQTAeFw0xNzEyMTUxMzM1MzRaFw0xODEyMTUyMTU5NTlaMIIBWTEkMCIGA1UEAwwb0KDQsNCx0YfQtdCy0YHRjNC60LAg0KEu0JIuMRwwGgYDVQQHDBPQvNGW0YHRgtC+INCa0LjRl9CyMQ4wDAYDVQQRDAUwMTEzMzE8MDoGA1UECQwz0LLRg9C7LiDQmtC+0LzQsNC90LTQsNGA0LzQsCDQmtCw0LzQtdC90ZTQstCwLCA0LdCQMRkwFwYDVQQMDBDRhNCw0YXRltCy0LXRhtGMMR0wGwYDVQQEDBTQoNCw0LHRh9C10LLRgdGM0LrQsDEuMCwGA1UEKgwl0KHQstGW0YLQu9Cw0L3QsCDQktCw0LvQtdGA0ZbRl9Cy0L3QsDEUMBIGA1UEBQwLMzA2NDQxODUyN1MxODA2BgNVBAoML9Ci0LXRgdGCINCi0J7QkiAi0JDQm9CiINCj0LrRgNCw0ZfQvdCwINCb0KLQlCIgMQswCQYDVQQGDAJVQTBGMB4GCyqGJAIBAQEBAwEBMA8GDSqGJAIBAQEBAwEBAgYDJAAEIcUWDIr8GtrTipNEh8KwFE4iSPW9/b+N0knFB6XjZorWAaOCAkwwggJIMEMGA1UdCQQ8MDowGgYMKoYkAgEBAQsBBAIBMQoTCDM2MjU3NjQ3MBwGDCqGJAIBAQELAQQBATEMEwozMDY0NDE4NTI3MB4GA1UdEQQXMBWBE3MucmFiY2hldnNrYUBhbHQudWEwKQYDVR0OBCIEINyIGQqIN63zSBwuh1eglm/gp80lgL5v5sEroBIfHpkfMCsGA1UdIwQkMCKAIJTGV3dyTasMIotrbbod3WJeB3bvWpFKyeW4w3SyexheMA4GA1UdDwEB/wQEAwIAwDAYBgNVHSUEETAPBg0qhiQCAQEBC5HKjVkDMBkGA1UdIAEB/wQPMA0wCwYJKoYkAgEBAQICMDIGCCsGAQUFBwEDAQH/BCMwITALBgkqhiQCAQEBAgEwEgYDBAACMAsTA1VBSAIBAQIBBjAzBgNVHS4ELDAqMCigJqAkhiJodHRwOi8vdWFrZXkuY29tLnVhL2xpc3QtZGVsdGEuY3JsMC0GA1UdHwQmMCQwIqAgoB6GHGh0dHA6Ly91YWtleS5jb20udWEvbGlzdC5jcmwwPQYIKwYBBQUHAQsEMTAvMC0GCCsGAQUFBzADhiFodHRwOi8vdWFrZXkuY29tLnVhL3NlcnZpY2VzL3RzcC8wbQYIKwYBBQUHAQEEYTBfMC0GCCsGAQUFBzAChiFodHRwOi8vdWFrZXkuY29tLnVhL3Vha2V5Y2VydC5wN2IwLgYIKwYBBQUHMAGGImh0dHA6Ly91YWtleS5jb20udWEvc2VydmljZXMvb2NzcC8wDQYLKoYkAgEBAQEDAQEDQwAEQMOcbgA5b/63sVirqG0w0BwykN8EY/C/Gi6LdtCtQngtpKCc4U/V7t8S84TxOsxdQcIl3rbgmc/LaXfuntL+oSIxggaYMIIGlAIBATCCATYwggEcMVswWQYDVQQDDFLQkNCm0KHQmiDQotCe0JIgItCm0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiAi0KPQutGA0LDRl9C90LAiMREwDwYDVQQHDAjQmtC40ZfQsjEZMBcGA1UEBQwQVUEtMzY4NjU3NTMtMDExNzFSMFAGA1UECgxJ0KLQntCSICLQptC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgItCj0LrRgNCw0ZfQvdCwIjEuMCwGA1UECwwl0JLRltC00LTRltC7INGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlzELMAkGA1UEBgwCVUECFFuvyQYAAAAAAAAAAAAAAAAAAAABMAwGCiqGJAIBAQEBAgGgggT0MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE4MDUyOTE0MTQ1MVowLwYJKoZIhvcNAQkEMSIEIH1lS84REY3+8aaBKuiWJlC0xa4wK1x2Zw2a6/Bfow1CMIIBjwYLKoZIhvcNAQkQAi8xggF+MIIBejCCAXYwggFyMAwGCiqGJAIBAQEBAgEEIEwdeazq67IDlZJX3uAP0/GYe8xKWdUafTTjL3X9coonMIIBPjCCASSkggEgMIIBHDFbMFkGA1UEAwxS0JDQptCh0Jog0KLQntCSICLQptC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIgItCj0LrRgNCw0ZfQvdCwIjERMA8GA1UEBwwI0JrQuNGX0LIxGTAXBgNVBAUMEFVBLTM2ODY1NzUzLTAxMTcxUjBQBgNVBAoMSdCi0J7QkiAi0KbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyICLQo9C60YDQsNGX0L3QsCIxLjAsBgNVBAsMJdCS0ZbQtNC00ZbQuyDRgdC10YDRgtC40YTRltC60LDRhtGW0ZcxCzAJBgNVBAYMAlVBAhRbr8kGAAAAAAAAAAAAAAAAAAAAATCCAvQGCyqGSIb3DQEJEAIUMYIC4zCCAt8GCSqGSIb3DQEHAqCCAtAwggLMAgEDMQ4wDAYKKoYkAgEBAQECATBpBgsqhkiG9w0BCRABBKBaBFgwVgIBAQYIKwYBBQUHAwgwMDAMBgoqhiQCAQEBAQIBBCB9ZUvOERGN/vGmgSroliZQtMWuMCtcdmcNmuvwX6MNQgIED0RGShgPMjAxODA1MjkxNDE0NTBaMYICSjCCAkYCAQGgIgQgZuzrjmRV2EI5y9+1euE4/pc33APvaufXCYEsCCF6Jc0wDAYKKoYkAgEBAQECAaCCAbwwLwYJKoZIhvcNAQkEMSIEIPo66E3SkjdSAESREYgtceYoGtMBflHDepThL7CblZJoMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDCCAWsGCyqGSIb3DQEJEAIvMYIBWjCCAVYwggFSMIIBTjAMBgoqhiQCAQEBAQIBBCDKkEMJu6YW24w28oLP5ROu/IIqn2iydCKgBqlBQpfyyjCCARowggEApIH9MIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTcxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUPbc+e/DVdbICAAAAAQAAAIQAAAAwDQYLKoYkAgEBAQEDAQEEQM7MIb6J0pNlCsxQavaoyxFRYbfkG9HJv9tAPu8FU58nKve7xygaJSoCbEgoW2A5cEku++MkU4o4fRI/+CaZKA8wDQYLKoYkAgEBAQEDAQEEQLfxhykSVzmhGUZEKXReqIs3QE25YjMUtRV3LNyJZbwFTozZRBqqbaNSn+Z56fZxE9oeK8iHiC2JJwWYJVQQIxs=","signed_content_encoding":"base64"}

ответ:
{"meta":{"url":"http://api-svc.il/api/legal_entities","type":"object","request_id":"c817aca1-2d6e-41bf-ad27-2d1b137abb60#51215","code":500},"error":{"errors":{"detail":"Internal server error"}}}

**Comment by svetavedmed** [comment]
You are creating legal_entity with "type": "MIS". Only MSP and Pharmacies could be created/ We will change response message
