### ISSUE TITLE
Затримки по розсилці смс-кодів

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#447]
*Доброго дня, подивіться  будь-ласка чому можуть бути затримки по розсилці смс-кодів! Для прикладу пару написав в приват у слаку*

MIS: Doctor Eleks

**Comment by lymychp** [comment]
затримка на стороні провайдера

**Comment by lymychp** [comment]
статистика за сьогодні```<2 mins, 27668
2-5 mins, 926
5-30 mins, 1224
>30 mins, 14
