### ISSUE TITLE
prod http 500 на post oauth/tokens 

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#448]
## Steps to Reproduce (Repro steps)

- [ ] post https://api.ehealth-ukraine.org/oauth/tokens

## Actual result
- [ ] `{
        "meta" : {
            "url" : "http://api-svc.mithril/oauth/tokens",
            "type" : "object",
            "request_id" : "497a4dff-5ce6-4d03-940e-2e576d2dcf25#174809",
            "code" : 500
        },
        "error" : {
            "errors" : {
                "detail" : "Internal server error"
            }
        }
    }`

## Expected result
- [ ] не http 500

**Comment by lymychp** [comment]
fixed with https://github.com/edenlabllc/ehealth.api/issues/2308
