### ISSUE TITLE
prod http 500 на  GET /api/employees

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#449]
## Steps to Reproduce (Repro steps)

- [ ] GET https://api.ehealth-ukraine.org/api/employees

## Actual result
- [ ] `{
        "meta" : {
            "url" : "http://api-svc.il/api/employees",
            "type" : "object",
            "request_id" : "497a4dff-5ce6-4d03-940e-2e576d2dcf25#175050",
            "code" : 500
        },
        "error" : {
            "errors" : {
                "detail" : "Internal server error"
            }
        }
    }`

## Expected result
- [ ] не http 500

**Comment by lymychp** [comment]
проблема вирішена
