### ISSUE TITLE
Зникла декларація

### ISSUE THREAD

**Issue by mark-lobanov** [ehealth-ua/api-spec#452]
По заявлению клиента "Зникла декларація. У програмі доктор її не бачить"
Речь идет об активной декларации 0000-2P53-7260. Что с ней не так?
Набираю со скана, не понятно буква "P" - латинская или кириллица

Upd: случай не единичный, со временем получим остальные номера

**Comment by lymychp** [comment]
це не декларація, а запит на декларацію, який не був підписаний, і він перейшов в статус `expired` `2018-05-18 00:09:36.575911`

**Comment by mark-lobanov** [comment]
термін життя заявки на декларацію - 7 діб ?
