### ISSUE TITLE
Права на чтение деклараций (препрод)

### ISSUE THREAD

**Issue by rshmorgun** [ehealth-ua/api-spec#455]
Возникла такая проблема, когда пользователь имеет несколько ролей (owner, doctor, HR) отдает ошибку что данный пользователь не имеет права на чтение деклараций, хотя судя по логике такого быть не должно, если все роли пользователя имеют права на чтение деклараций, то все проходит ок! в чем проблема!?

**Comment by lymychp** [comment]
в тікеті недостатньо інформації для аналізу. Прошу надати Логін/ІД користувача, лог послідовності кроків/викликів апі і відповідями. Тобто зареєструвати тікет по шаблону.

**Comment by rshmorgun** [comment]
Уточните пожалуйста запрос в работе? или опять не достаточно данных?

**Comment by lymychp** [comment]
`Qi9rR0NxR2l2c1EvNC9EbUJqMFZ6Zz08 ` - цей токен невалідний.
У інших токенах даного користувача не вказаний скоуп `declaration:read` Ви запитували цей скоуп в процесі проходження авторизації? Якщо так, то дайте лог.

**Comment by rshmorgun** [comment]
Валидный токен - Qi9rR0NxR2l2c1EvNC9EbUJqMFZ6Zz09

**Comment by rshmorgun** [comment]
Данный пользователь имеет роли: "employeeTypes":"відділ кадрів, реєстратор, лікар",

лікар - имеет права на чтение деклараций
відділ кадрів - не имеет прав чтения деклараций,
в итоге выдает ошибку что данный employee не имеет прав на чтение деклараций, хотя по логике такого не должно быть

**Comment by lymychp** [comment]
@rshmorgun прошу дати відповідь на запитання
>Що ви тут передавали для отримання access_token?
https://auth-preprod.ehealth-ukraine.org/sign-in?client_id=[redacted]&scope=legal_entity:read employee_request:read employee_request:write employee_request:approve employee_request:reject employee:read employee:write employee:details employee:deactivate division:write division:read division:details division:activate division:deactivate&redirect_uri=[redacted]
