### ISSUE TITLE
Додати дату народження пацієнта в Get Declarations List 

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#456]
Чи можливо додати дату народження пацієнта в блок "party" в ендпоінті Get Declarations List?
Потрібна для формування статистики по деклараціям за віком.

MIS: EMCiMED

**Comment by ioleksiy** [comment]
@lymychp чи є протиріччя по безпеці або продуктивності?

**Comment by lymychp** [comment]
Не бачу тут проблем

**Comment by pieskov** [comment]
Коли чекати на ПРЕПРОДІ та ПРОДІ?

**Comment by ehealthua** [comment]
@pieskov 
1. Повторно наголошу, будь ласка, вказуйте МІС, від якого звертаєтесь
2. Додано в беклог. Розробка чендж реквестів почнеться не раніше повного запуску функціоналу договорів.
