### ISSUE TITLE
Бердянск, переулок Нагорный

### ISSUE THREAD

**Issue by mark-lobanov** [ehealth-ua/api-spec#457]
Повідомлення від клієнта
**В списке улиц  Бердянска нет проулка Нагорний (паралельный проулку Вольному).
Есть только улица Нагорная, но на проулке Нагорный много домов и пациентов.**

**Comment by lymychp** [comment]
довідник вулиць ehealth не претендує на звання повного і абсолютно правильного. АПІ не забороняє передавати вулиці не з довідника. Можете використовувати свій.
