### ISSUE TITLE
Employee declaration limit (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#460]
*Доброго дня, перевірте будь ласка ліміти для лікаря, настільки я розумію для педіатра це число відповідно до закону має бути - 900*

## Steps to Reproduce
- [ ] employees "id": "a9740375-5726-4f28-b093-9723499d8105"
- [ ] "position": "P8"
- [ ] "speciality": "PEDIATRICIAN",
- [ ]  "declaration_count": 906

## Actual result
- [ ] declaration_limit": 2000

## Expected result
- [ ] declaration_limit": 900

MIS: Doctor Eleks

**Comment by ehealthua** [comment]
@superjonh я вже оголошував, але повторюсь. Індивідуальні ліміти, про які Ви питаєте, будуть реалізовані протягом кількох тижнів.
