### ISSUE TITLE
Employee info on declaration form

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#461]
*Доброго дня, прошу повернути дані лікаря (телефон, email) на друкованій формі декларації*

## Actual result
- [ ] division information

## Expected result
- [ ] employee contacts

MIS: Doctor Eleks

**Comment by ehealthua** [comment]
Колеги,

дане питання підіймалось багаторазово МІСами з проханням видалити особистий номер телефона лікаря з декларацій якнайшвидше, рішення було прийняте на зустрічі з МІС у МОЗ та імплементовано. Зараз друкується номер телефону division. Заплановано в розробку функціонал введення лікарем окремого контактного номеру в кабінеті, який буде друкуватись в декларації.
