### ISSUE TITLE
Authorization reset

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#462]
*Доброго дня, прошу реалізувати можливість відвязати моб.телефон від декларації, так як такі випадки вже є і в пацієнта немає можливості перепідписати нову декларацію!*

MIS: Doctor Eleks

**Comment by innashymkiv** [comment]
Юрків Євгенія Павлівна(пацієнтка) не може підписати декларацію з лікарем Шингерою Катериною, бо її зареєстрували під невідомим номером до іншого лікаря.

**Comment by ehealthua** [comment]
@superjonh даний функціонал передбачено на боці НСЗУ, оскільки за існуючою логікою ідентифікувати пацієнта та прийняти рішення про зміну номеру його телефону, або типу аутентифікації може лише НСЗУ. На жаль, протягом дослідної експлуатації компонентів існують подібні незручності, які згодом буде нівельовано.

**Comment by superjonh** [comment]
@ehealthua Дякую за відповідь.
