### ISSUE TITLE
Declaration request create (question)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#463]
*Доброго дня, перевірте будь ласка запит стосовно declaration_request create.*

## Steps to Reproduce (Repro steps)
- [ ] employee id: 3f3bde25-eb0b-4671-9e29-4d673acc809e
- [ ] "position": "P7" - (Лікар загальної практики - сімейний лікар)
- [ ] patient age is under 18 years

## Actual result when sending new request
- [ ] <error><code>422</code><description>UnprocessableEntity</description><body>{
  "meta": {
    "url": "http://api-svc.il/api/declaration_requests",
    "type": "object",
    "request_id": "c819a57a-a245-4559-a1c0-c9ed5ae07b89#193895",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": null,
            "params": [    ],
            "description": "Doctor speciality does not meet the patient's age requirement."
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.data"
      }
    ]
  }
}

## Expected result
- [ ] successful response

**Comment by svetavedmed** [comment]
Добрый день. "position": "P7" - это позиция врача в клинике. А при создании декларации проверяется специальность врача, и этот врач по специальности THERAPIST. Поэтому ошибка при создании.
