### ISSUE TITLE
Не работает Auth на PreProd

### ISSUE THREAD

**Issue by Evgeniy0119** [ehealth-ua/api-spec#464]
Не работает Auth на PreProd

## Steps to Reproduce (Repro steps)

1. https://auth-preprod.ehealth-ukraine.org/
2. https://auth.preprod.asclepius.com.ua/
## Actual result
1.Service Unavailable
2.Не удается получить доступ к сайту

## Expected result
Должен, работать.

Возможно снова переехали на новый домен. Сообщите корректный адрес

**Comment by lymychp** [comment]
була проблема з VM на препрод середовищі. 
Вже виправили
