### ISSUE TITLE
Event Manager (отсуствует евент) (PROD)

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#465]
Есть декларация - "341e8281-29bf-4920-9125-f7f364ed9398"
При ручной проверке eHealth возвращает статус terminated. Однако этой декларации нет в EventManage.

**Comment by AlekzandrV** [comment]
Записи в event_manager хранятся определенное время (и ограничены по кол-ву). Указанная декларация сменила статус 2018-06-04 08:43:58.123956. И эта запись уже была удалена из event_manager

**Comment by Charly3X** [comment]
Сколько по времени и сколько по количеству ограничения? И что делать в таких случаях когда уже было удалено?

**Comment by AlekzandrV** [comment]
Сейчас лимит на 50000 записей. 
Чтобы ответить на второй вопрос, мне нужно понимать контекст. Можете, пожалуйста, описать проблему?

**Comment by Charly3X** [comment]
у нас свалился бекграунд джоб который проверял статусы деклараций. пофиксили через пару дней... и теперь некоторые декларации выпали по статусам.

**Comment by ehealthua** [comment]
@AlekzandrV прокомментируй, пожалуйста

**Comment by AlekzandrV** [comment]
К сожалению, получить данные о статусе деклараций МИСом другим путем нельзя. Декларации может видеть только авторизованный пользователь и в контексте своей клиники
