### ISSUE TITLE
Лікар зареєстрований двічі в eHealth

### ISSUE THREAD

**Issue by RomanDelikatnyi** [ehealth-ua/api-spec#466]
Один лікар працює в 2х підрозділах, має 2 спеціалізації (педіатр, сімейний) і був успішно зареєстрований в eHealth на 2 різні пошти. При реєстрації лікаря були використані однаковий ІПН, серія і номер паспорту, дата народження лікаря. Наразі лікар підписує декларації як педіатр і як сімейний лікар.

  ID лікаря в eHealth як педіатра 88d94a70-aab1-466d-929f-379fd19b310a
  ID лікаря в eHealth як сімейного лікаря 3d7f819e-52f7-49c3-bf5c-82ac99bc259f

Чи може лікар бути зареєстрований в eHealth за двома спеціалізаціями і якщо так, то яким чином будуть обмежувати кількість підписаних ним декларацій? Якщо я правильно розумію, зараз він може підписати 2000 декларацій як сімейний лікар і 900 декларацій як педіатр.

**Comment by lymychp** [comment]
@RomanDelikatnyi Що це означає?
> Статус першого профілю: Так 88d94a70-aab1-466d-929f-379fd19b310a
Статус другого профілю: Так 3d7f819e-52f7-49c3-bf5c-82ac99bc259f

> Статус першого профілю: Так
Статус другого профілю: Ні

**Comment by RomanDelikatnyi** [comment]
@lymychp, відредагував питання)

**Comment by svetavedmed** [comment]
На данный момент лимит считается на человека, т.е. на party, а не на employee. Однако уже в скором времени лимиты докторов будут перенесены на контракты и уже контрактом будет контролироваться лимиты докторов.
