### ISSUE TITLE
Employee declaration_count (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#468]
*Доброго дня, перевірте будь ласка ліміт пацієнтів для цього лікаря, в нього перевищено к-сть декларацій, біт який позволяв це робити був = false*

## Steps to Reproduce (Repro steps)
- [ ] employee_id : 09275a45-9574-428a-800e-f1b5637eadf3
- [ ] url: https://api.ehealth-ukraine.org/api/employees/09275a45-9574-428a-800e-f1b5637eadf3

## Actual result
- [ ] "declaration_limit": 2000,
       "declaration_count": 2006,

## Expected result
- [ ] not overcome the limit

MIS: Doctor Eleks

**Comment by svetavedmed** [comment]
declaration_limit у данного врача действительно 2000

**Comment by svetavedmed** [comment]
После внедрения контрактов, лимит декларации переносится на уровень контракта и более не будет ограничен при аппруве декларации. 
Задачу закрываю, т.к изменение логики делает ее более не актуальной.
