### ISSUE TITLE
Пацієнт БЕЗ ІПН не може укласти декларацію

### ISSUE THREAD

**Issue by zackkozac** [ehealth-ua/api-spec#469]
Пацієнт без ІПН не може укласти декларацію. СМС приходить на номер іншого пацієнта З ІПН.
В пацієнтів співпадає Прізвище, Ім'я, дата народження. По батькові різне. Документи не співпадають.

JSON  укладеної декларації та запити можу надати в особистому чаті.

МІС: HELSI

**Comment by svetavedmed** [comment]
Добрый день. Если у пациента нет ИНН поиск осуществляется по Имя+Фамилия+Дата рождения. На данный момент зарегистрировать декларацию для этого человека можно только при использовании в поиске также и ИНН.

**Comment by zackkozac** [comment]
Зрозуміло дякую.
