### ISSUE TITLE
Вибір міста.

### ISSUE THREAD

**Issue by mblishch** [ehealth-ua/api-spec#47]
Мені необхідно вказати місто при виборі адреси.
Скажімо нехай це буде Вінниця.
Роблю запит на 
https://api.ehealth.world/api/uaddresses/details/region/C4C0F907-8B60-483E-BBF6-DFB34AB91574/districts?limit=100

Бачу всі райони включно з вінницьким.
Пробую отримати всі населені від цього району.
І міста Вінниця я там не бачу.

**Comment by pzhuk** [comment]
Вінницю можна знайти, наприклад, так

GET /api/uaddresses/search/settlements?settlement_name=ВІННИЦЯ&amp;region=ВІННИЦЬКА HTTP/1.1
Host: demo.ehealth.world

**Comment by mblishch** [comment]
працює, дякую
