### ISSUE TITLE
Статус pending_verification в декларации с методом авторизации offline

### ISSUE THREAD

**Issue by Evgeniy0119** [ehealth-ua/api-spec#470]
При регистрации декларации с методом авторизации offline, у декларации статус: pending_verification.

Уточните:
1. Сколько по времени декларация имеет статус  pending_verification?
2. Меняет ли она статус с  pending_verification на active, если да, то кто и когда выполняет данное действие?
3. Декларация со статусом  pending_verification считается действующей?

МИС: МедЭйр (Евгений)

**Comment by lymychp** [comment]
1. 30 днів
2. так, автоматично через 30 днів
3. якщо мається на увазі чи буде за цю декларацію оплата, то питання швидше до @ehealthua

**Comment by ehealthua** [comment]
@lymychp дякую за відповідь!

@Evgeniy0119 додали до пулу юридичних питань

**Comment by Evgeniy0119** [comment]
Относительно ответа №3
1. Вопрос будет ли считаться такая декларация, успешно зарегистрированной 
(со статусом )pending_verification? Или же она успешно зарегистрирована только через 30 дней?
2. Пациент и врач, подписавшие такую декларацию, должны исходить из того, что врач обязан бесплатно принимать этого пациента сразу или через 30 дней?

**Comment by lymychp** [comment]
related to https://github.com/edenlabllc/ehealth.api/issues/2542

**Comment by lymychp** [comment]
на продуктиві оптимізована процедура авто-апруву декларацій.
Сьогодні вночі усі декларації зі статусом `pending_verification` старше 30 днів перейдуть в статус `active`
