### ISSUE TITLE
Declaration, printed form (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#471]
*Доброго дня, перевірте будь ласка друковану форму декларації блоки 1.12.1. та 2.1. Прізвище, ім’я, по-батькові йде в неправильному порядку, тобто наразі там ім’я, по-батькові, прізвище*

## Steps to Reproduce (Repro steps)
- [ ] "declaration_id": "7f4b1138-cd82-401d-87cb-a67c04ffac8d"

## Actual result
- [ ] not right name order

## Expected result
- [ ] correct order

MIS: Doctor Eleks

**Comment by ehealthua** [comment]
Формат є припустимим, питання підіймалось раніше
