### ISSUE TITLE
Declaration request create (building field)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#473]
*Доброго дня, що робити у випадку коли немає номеру будинку у адресі (смт. Вишкого Закарпатська область вул Ракушська б-н), так як це поле по специфікації обовязкове, як зареєструвати декларацію таким пацієнтам?*

## Actual result
- [ ] not created declaration request.

## Expected result
- [ ] successful response.

MIS: Doctor Eleks

**Comment by dmmat** [comment]
https://github.com/ehealth-ua/api-spec/issues/406

**Comment by ehealthua** [comment]
@superjonh в листі про валідацію даних є відповідь на Ваше питання. Поле буде зроблено необов'язковим.
