### ISSUE TITLE
Declaration confidant_person (tax_id)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#475]
*Доброго дня, можете дати пояснення по друкованій формі декларації, а саме пункті 4.3. Унікальний номер запису в Єдиному державному демографічному реєстрі (у разі наявності) , який відповідає специфікації  declaration_request -> person -> confidant_person -> tax_id (https://ehealthmisapi1.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/declaration-requests/create-declaration-request)

При за посиланням зазначено, що для законного представника потрібно вказати ІПН (https://portal.ehealth.gov.ua/clarifications/2018-03-29-shcho-potribno-maty-patsiientu/)
*

MIS: Doctor Eleks

**Comment by svetavedmed** [comment]
@superjonh не совсем понятен ваш вопрос, вы указываете tax_id для confidant_person и тогда он будет напечатан в печатной форме декларации.
