### ISSUE TITLE
User authorize

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#476]
*Доброго дня, користувач не може авторизуватись, при переході далі нічого не відбувається!*

![image](https://user-images.githubusercontent.com/24266717/41418244-0120cdd2-6ff8-11e8-8d1e-f38ae3e84bfe.png)

MIS: Doctor Eleks

**Comment by lymychp** [comment]
https://support.cloudflare.com/hc/en-us/articles/203366080-Why-do-I-see-a-captcha-or-challenge-page-Attention-Required-trying-to-visit-a-site-protected-by-Cloudflare-as-a-site-visitor-
related to #431
