### ISSUE TITLE
Declaration tax_id (question)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#477]
Доброго дня, дайте розяснення з приводу зазначення ІПН-а, так як по специфікації це поле не є обовязковим, а в наказі 503 (http://moz.gov.ua/uploads/0/4204-dn_20180319_503_dod_1.pdf), а саме розділ 3, пункт 2 ІПН є обовязковим.

MIS: Doctor Eleks

**Comment by ehealthua** [comment]
Дане поле є не обов'язковим ЛИШЕ у випадку, коли у пацієнта в паспорті є офіційне підтвердження про відмову отримання ІПН. Питання багаторазово підіймалося. Будь ласка, подивіться лист про валідацію даних.

**Comment by superjonh** [comment]
@ehealthua  Гаразд, а у випадку коли це дитина, тоді чий ІПН вказувати?

**Comment by lymychp** [comment]
Якщо у дитини є ІПН - вказувати, якщо нема - не вказувати. Ні в якому разі не вказувати ІПН батьків/родичів/сусідів і т.д.
