### ISSUE TITLE
Declaration (pending_verification)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#479]
*Доброго дня, цікавить декілька питань по деклараціях авторизованих через документи:
      1) хто займається верифікацією цих документів
      2) які терміни їх розглядання (вже є декларації створені більше місяця тому - для прикладу 2018-05-11)
      3) яка причина відхилення декларації*

MIS: Doctor Eleks

**Comment by lymychp** [comment]
на продуктиві оптимізована процедура авто-апруву декларацій.
Сьогодні вночі усі декларації зі статусом `pending_verification` старше 30 днів перейдуть в статус `active`
