### ISSUE TITLE
am-test5: Неможливо знайти повний перелік типів адресів.

### ISSUE THREAD

**Issue by romanm** [ehealth-ua/api-spec#48]
Підскажіть будьласка де міститься повна інформація про типи адресів
addresses.type:[]
В документації http://docs.ehealthapi1.apiary.io її неможливо знайти.

**Comment by lymychp** [comment]
Значення усіх довідників можна отримати через dictionaries endpoint:
```
curl -X GET \
  'http://dev.ehealth.world/api/dictionaries?name=ADDRESS_TYPE' \
  -H 'authorization: Bearer scope_legal_entity' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 1ad6c127-b820-cdde-fa0d-f7e1ea28a996'
```
