### ISSUE TITLE
Declaration approve (OTP)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#480]
Доброго дня,  поясніть чому для деяких номерів не потрібно вводити смс-код підтвердження ?(https://ua-ehealth.slack.com/archives/C9P8Y4PK6/p1526630903000221)

MIS: Doctor Eleks

**Comment by ehealthua** [comment]
Деталізуйте, будь ласка, питання

**Comment by superjonh** [comment]
@ehealthua тобто для деяких пацієнтів не потрібно вводити смс-код, так як при створенні declaration_request повертається такий блок
--------------------------------------------------
"urgent": {
    "authentication_method_current": {
      "type": "NA"
    }
  }
--------------------------------------------------
хоча авторизація OTP, відповідно в запиті на declaration approve body ми передаємо null

**Comment by ehealthua** [comment]
@ioleksiy посмотри, пожалуйста

**Comment by ioleksiy** [comment]
если вы буквально пару минут назад уже верифицировали нового человека через ОТР, и это его первая декларация, то система считает, что повторно не нужно верифицировать человека, поэтому возвращает NA - что одначает ничего не нужно делать.

**Comment by superjonh** [comment]
дякую, зрозуміло)
