### ISSUE TITLE
Новий документ в розділ ДОКУМЕНТИ на порталі

### ISSUE THREAD

**Issue by ehealthua** [ehealth-ua/api-spec#481]
Прохання опублікувати ASAP на порталі в розділі документи 

Наказ ДП "Електронне здоров'я" від 15.06.18р. №20-ГД "Про внесення змін до Регламенту функціонування компонентів електронної системи обміну медичною інформацією, що необхідні для запуску нової моделі фінансування на первинному рівні надання медичної допомоги"

[Zminy_do_Reglamentu_Nakaz_20GD.pdf](https://github.com/ehealth-ua/api-spec/files/2106436/Zminy_do_Reglamentu_Nakaz_20GD.pdf)

**Comment by ioleksiy** [comment]
https://github.com/edenlabllc/nhs.portal.web/pull/65
