### ISSUE TITLE
Типи вулиць

### ISSUE THREAD

**Issue by mark-lobanov** [ehealth-ua/api-spec#484]
Просимо додати до довідника STREET_TYPE такі значення:
- завулок (Чернівці, м.Біла Церква, Тростянець...)
- містечко (Кривий Ріг, Васильків)
- острів (Миколаїв, Дніпр)
- спуск (Дніпро,Нікополь,Маріуполь...)
- хутір (Вінницька, Волинська, Донецька обл...)
- шлях (Житомир, Новоград-Волинський, Ромни...)

**Comment by ehealthua** [comment]
Вже стоїть в беклозі, чекає на імплементацію
