### ISSUE TITLE
Не подписывается декларация без ИНН персоны и опекуна

### ISSUE THREAD

**Issue by stager94** [ehealth-ua/api-spec#485]
Появились проблемы с подписанием декларации. Все этапы проходит нормально, но когда подгружаем файл - пишет, что проблема в $.content

Дополнения к проблеме: делаем совершенно одинаковые 2 декларации (все поля 1-к-1), НО не указываем ИНН ни персоны, ни опекуна.
Результат: когда есть ИНН - подписание проходит успешно, когда нет ИНН - ошибка

ID declaration request BAD: ee15d8c5-d868-4b87-8790-d2865f4d00d7
ID declaration request GOOD: e57e3d8c-df16-46c2-b32f-a29c0fe6010e

Ошибка, которую получаем от eHealth:
`{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"invalid","params":"[]","description":"Signed content does not match the previously created content"}],"entry_type":"json_data_property","entry":"$.content"}]}`

**Comment by lymychp** [comment]
demo/preprod/prod?

**Comment by H24Kirka** [comment]
preprod Denovo

**Comment by lymychp** [comment]
тоді вишліть плз
1) `request_id` відповіді з помилкою
2) curl вашого request або хоча б підписаний контент

**Comment by rshmorgun** [comment]
Добрый день!  подписанный контент

[sign_content.zip](https://github.com/ehealth-ua/api-spec/files/2118267/sign_content.zip)

**Comment by rshmorgun** [comment]
Подскажите в каком случает бывают такие ошибки "description":"Signed content does not match the previously created content" ?

**Comment by rshmorgun** [comment]
Подписанный и не подписанный контент
[new_sign_data.zip](https://github.com/ehealth-ua/api-spec/files/2120271/new_sign_data.zip)

**Comment by stager94** [comment]
Все - разобрались сами - если нет ИНН, то не нужно отправлять ключ tax_id: null
