### ISSUE TITLE
НСЗУ не видит зарегистрированных врачей

### ISSUE THREAD

**Issue by Evgeniy0119** [ehealth-ua/api-spec#489]
"Барский "ЦПМСД", Винницкой области ("legal_entity": "id": "8cb4cd14-569d-43b3-a424-49763b74c45f").
Зарегистрировано в eHealth 32 врача.
При заключении договора  с НСЗУ закачику сообщили о том что есть информация только по 8.
Мы перепроверили данные 24 остальных врачей, все они подтвердили регистрацию и авторизирвоаны. Они вносят декларации(порядка 1000 деклараций у каждого).  У всех заполнен ИНН

Почему НСЗУ может их не видеть?

МедЭйр (Евгений)

**Comment by Evgeniy0119** [comment]
Добрый вечер, уточню и предоставлю

**Comment by Evgeniy0119** [comment]
Видны врачи: Лисак Т., Богданова Л, Черкас Т., Королишин М., Мельник Н, Цицюрська Л., Клімов Ф., Климчук Н.,

**Comment by Evgeniy0119** [comment]
не видны соотвественно: Шубіна Галина Василівна,  Вовк Валерій Леонідович, Коваль Наталія Федорівна, Крайчак Микола Миколайович,  Любінецька Жанна Леонідівна, Пустовіт Лариса Петрівна, Лиштва Тетяна Олегівна,  Попова Олена Миколаївна, Шубіна Любов Федорівна, Гутаревич Ярослав Михайлович, Черкас Олександр Петрович, Черкас Тамара Михайлівна,  Косяк Валентин Борисович, Сотнічук Антоніна Іванівна и др..

**Comment by ehealthua** [comment]
@Evgeniy0119 пожалуйста, удалите персональные данные с github, для рабочих вопросов у нас есть id врачей.

**Comment by Evgeniy0119** [comment]
Исправлено, указаны идентификаторы

**Comment by ehealthua** [comment]
@ioleksiy @lymychp необходимо проверить

**Comment by lymychp** [comment]
@Evgeniy0119  API повертає усіх 32 лікарів?

**Comment by Evgeniy0119** [comment]
Да, апи возвращает всех в состоянии "APPROVED"

**Comment by lymychp** [comment]
Ну значить все працює.

**Comment by Evgeniy0119** [comment]
Продолжения ответа не будет? 
Если все работает- почему НСУЗ не видит остальных врачей? 
Может некорректно работает функционал для НСЗУ? 
Или это делается специально чтобы скомроментировать МИС, который регистрировал? 
Что нам сообщить заказчику?

**Comment by ehealthua** [comment]
@Evgeniy0119 НСЗУ працює виключно з даними з ЦБД. Рекомендуємо закладу на своїй стороні перевірити, чи насправді має місце проблема, а саме звірити дані в системі і в новій редакції Додатку до Договору, яка набула чинності внаслідок підписання Додаткової угоди. Якщо є різниця, це означає, що після підписання Додаткової угоди в систему було внесено зміни.

Прошу утриматись від звинувачувальних формулювань щодо спроби скомпрометувати МІС, або інших подібних.
