### ISSUE TITLE
Internal error (501) для запроса /declaration_requests/<uuid>/actions/sign

### ISSUE THREAD

**Issue by pavel-yablonskiy** [ehealth-ua/api-spec#490]
При подписании декларации получаем 501 ошибку

Пример 1:
/declaration_requests/732589fb-440b-4556-8ffb-eaaffdac551f/actions/sign
request_id: d2abbccd-cd8a-47b7-9a27-88b041a11593#13111

Пример 2: 
/declaration_requests/6420f424-4704-426a-b770-4c643ce7fe1f/actions/sign
request_id: 20aee453-cec4-4175-ac95-c44c25ad262c#47218

**Comment by lymychp** [comment]
fixed on prod
