### ISSUE TITLE
500 по /oauth/tokens на demo

### ISSUE THREAD

**Issue by Lextor** [ehealth-ua/api-spec#492]
## Steps to Reproduce (Repro steps)
- [ ] 'API_URL': 'http://api.demo.asclepius.com.ua/api'
- [ ] 'AUTH': 'http://auth.demo.asclepius.com.ua'
- [ ] Endpoint: /oauth/tokens
- [ ] request params (//предоставлю по запросу)

## Actual result
- [ ] response "Internal Server Error"

## Expected result
- [ ] not 500

**Comment by Lextor** [comment]
{
    "token": {
        "code": "TG9BV1NaTkxuTnNRcCs2OXJaUlBydz09", 
        "redirect_uri": "http://org.mis.local:1246/e-health/oauth/redirect/d85cef70-33b3-4665-a727-eb0750a98bed/", 
        "client_id": "a858041c-e526-48cd-aadb-d7e0c03ac416", 
        "client_secret": "emlNQzNSNDdWK1lSRlVDZTRXM254dz09", 
        "scope": "division:read division:deactivate division:details legal_entity:read division:activate division:write", 
        "grant_type": "authorization_code"
    }
}

**Comment by lymychp** [comment]
it should be ok now
