### ISSUE TITLE
501 Declaration sign (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#493]
## Steps to Reproduce (Repro steps)
- [ ] "request_id": "676f9310-1b42-44c5-8602-34f5ca7106e8#24404"
- [ ] declaration_ref: 2f1ead8e-8906-4125-974d-85162198c593

## Actual result
- [ ] {
  "meta": {
    "url": "http://api-svc.il/api/declaration_requests/2f1ead8e-8906-4125-974d-85162198c593/actions/sign",
    "type": "object",
    "request_id": "676f9310-1b42-44c5-8602-34f5ca7106e8#24404",
    "code": 501
  },
  "error": {
    "type": "internal_error"
  }
}

## Expected result
- [ ] signed declaration

MIS: Doctor Eleks

**Comment by superjonh** [comment]
https://github.com/ehealth-ua/api-spec/issues/490

**Comment by lymychp** [comment]
фікс залили на прод. Має бути сильно краще, але ми вже бачимо, що не всі причини були усунені. Наступного тижня будем продовжувати над цим працювати.

**Comment by dmmat** [comment]
Щось сьогодні багато приходить помилок

**Comment by lymychp** [comment]
fixed on prod
