### ISSUE TITLE
Запрос подразделений юр. лица на ДЕМО

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#494]
Возникла проблемма с получением Дивижнов на ДЕМО.

По запросу https://api.demo.asclepius.com.ua/reports/stats/divisions?page=1&page_size=50&legal_entity_edrpou=21560045 возврящается 1-н дивижн, а на самом деле их 2-ва. Что не так с этим запросом?

**Comment by Charly3X** [comment]
Аналогичная ситуация. Скорей всего там не актуализированы данные.

**Comment by lymychp** [comment]
так, дані були не актуальні. Відновили репліку
