### ISSUE TITLE
Ошибка при подписании договора со стороны NHS

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#496]
Попробовали токены для реализации ответа со стороны NHS. Что это за ошибка?

{"meta":{"url":"http://api-svc.il/api/contract_requests/8691f14b-8cd9-4ce2-bb3f-825bce00051e/actions/approve","type":"object","request_id":"8471b154-0146-4922-ac11-c3f850623a7a#4784","code":422},"error":{"type":"request_malformed","message":"Does not match the signer drfo","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}
D, [2018-06-21T20:36:29.347513 #122440] DEBUG -- : [httplog] Connecting: api.demo.asclepius.com.ua:443
D, [2018-06-21T20:36:29.508616 #122440] DEBUG -- : [httplog] Sending: PATCH http://api.demo.asclepius.com.ua:443/api/contract_requests/8691f14b-8cd9-4ce2-bb3f-825bce00051e/actions/approve
D, [2018-06-21T20:36:29.509036 #122440] DEBUG -- : [httplog] Header: content-type: application/json
D, [2018-06-21T20:36:29.509096 #122440] DEBUG -- : [httplog] Header: authorization: Bearer QUsyV3ZJNXpDMDVZSWM1N2JHYVpZZz09
D, [2018-06-21T20:36:29.509171 #122440] DEBUG -- : [httplog] Header: api-key: 7a07feaf4c37ef135f85
D, [2018-06-21T20:36:29.509197 #122440] DEBUG -- : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2018-06-21T20:36:29.509861 #122440] DEBUG -- : [httplog] Header: accept: */*
D, [2018-06-21T20:36:29.509929 #122440] DEBUG -- : [httplog] Header: user-agent: Ruby
D, [2018-06-21T20:36:29.509955 #122440] DEBUG -- : [httplog] Header: x-newrelic-id: VQ8CVVdVABAFVVFbBAIOXw==
D, [2018-06-21T20:36:29.509977 #122440] DEBUG -- : [httplog] Header: x-newrelic-transaction: PxQDWQVRWQIEAVZWUVRTUVMAFB8EBw8RVU4aVgBbBlMCUVxWBQdWBlMBBkNKQQoFAVQFBwJSFTs=
D, [2018-06-21T20:36:29.509999 #122440] DEBUG -- : [httplog] Header: connection: close
D, [2018-06-21T20:36:29.510074 #122440] DEBUG -- : [httplog] Data: {"signed_content":"MIIPngYJKoZIhvcNAQcCoIIPjzCCD4sCAQExDjAMBgoqhiQCAQEBAQIBMIHDBgkqhkiG9w0BBwGggbUEgbJ7ImlkIjoiODY5MWYxNGItOGNkOS00Y2UyLWJiM2YtODI1YmNlMDAwNTFlIiwiY29udHJhY3Rvcl9sZWdhbF9lbnRpdHkiOnsiaWQiOiIzMTBmNWJhMy0wNWM5LTQ5MjctOWY0Mi1lOTBmNzMxMzQ1YmQiLCJuYW1lIjoi0J/QtdC10YAiLCJlZHJwb3UiOiIyODgwNjE0MzEwIn0sInRleHQiOiJzdGF0aWNfdGV4dCJ9oIIGlzCCBpMwggY7oAMCAQICFDO2y3v3IbnOBAAAAN1qGwCtUVgAMA0GCyqGJAIBAQEBAwEBMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjAeFw0xNzA2MTIyMTAwMDBaFw0xOTA2MTIyMTAwMDBaMIHzMRwwGgYDVQQKDBPQp9Cw0YDQvtGP0L0g0J4u0JIuMTkwNwYDVQQDDDDQp9Cw0YDQvtGP0L0g0J7Qu9C10LrRgdGW0Lkg0JLQsNGA0YLQsNC90L7QstC40YcxFTATBgNVBAQMDNCn0LDRgNC+0Y/QvTEsMCoGA1UEKgwj0J7Qu9C10LrRgdGW0Lkg0JLQsNGA0YLQsNC90L7QstC40YcxEDAOBgNVBAUMBzE3OTY4MjkxCzAJBgNVBAYTAlVBMRUwEwYDVQQHDAzQpdCw0YDQutGW0LIxHTAbBgNVBAgMFNCl0LDRgNC60ZbQstGB0YzQutCwMIHyMIHJBgsqhiQCAQEBAQMBATCBuTB1MAcCAgEBAgEMAgEABCEQvuPbauqeH4ZXjEXBJZT/lCOUp9c4+Rh+ZRUBcpT0zgECIQCAAAAAAAAAAAAAAAAAAAAAZ1khOvGC6YfT4XcUkH1HDQQhtg/S2NzoqTQjxhAbypHEegB+bDALJs1VbJsOfSDvKSoABECp1utF8TxwgoDElnsjH16t9ljrpMA3KR042WvwJcpOF/jpcg3GFbQ6KJdfC8Heo2Q4tWTqLBef0BI+bbj6xXkEAyQABCFxgNs8P6EmHKD4+hDcg1fyhPY5U284oOvhuHkhBJOG7AGjggKuMIICqjApBgNVHQ4EIgQgPYpQd1CFaIMIOlt9HJBFd3R8uAF53D2nAI9HPL5fuCwwKwYDVR0jBCQwIoAgM7bLe/chuc7u494uYv7qO3AaS2dgvBwvzzVlFrUOvKowLwYDVR0QBCgwJqARGA8yMDE3MDYxMjIxMDAwMFqhERgPMjAxOTA2MTIyMTAwMDBaMA4GA1UdDwEB/wQEAwIGwDAZBgNVHSABAf8EDzANMAsGCSqGJAIBAQECAjAMBgNVHRMBAf8EAjAAMB4GCCsGAQUFBwEDAQH/BA8wDTALBgkqhiQCAQEBAgEwHgYDVR0RBBcwFaATBgorBgEEAYI3FAIDoAUMAzE0NDBIBgNVHR8EQTA/MD2gO6A5hjdodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxvYWQvY3Jscy9BQ1NLSUREREZTLUZ1bGwuY3JsMEkGA1UdLgRCMEAwPqA8oDqGOGh0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jcmxzL0FDU0tJRERERlMtRGVsdGEuY3JsMIGIBggrBgEFBQcBAQR8MHowMAYIKwYBBQUHMAGGJGh0dHA6Ly9hY3NraWRkLmdvdi51YS9zZXJ2aWNlcy9vY3NwLzBGBggrBgEFBQcwAoY6aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NlcnRpZmljYXRlcy9hbGxhY3NraWRkLnA3YjA/BggrBgEFBQcBCwQzMDEwLwYIKwYBBQUHMAOGI2h0dHA6Ly9hY3NraWRkLmdvdi51YS9zZXJ2aWNlcy90c3AvMEUGA1UdCQQ+MDwwHAYMKoYkAgEBAQsBBAIBMQwTCjI4ODA2MTQzMTAwHAYMKoYkAgEBAQsBBAEBMQwTCjI4ODA2MTQzMTAwDQYLKoYkAgEBAQEDAQEDQwAEQMWg1OLNQqYuTQTaOYeEfyGPvYtLnFizmVLBdWtq9qNcepAjc9nHi7AYAUb4aCwuqpP+CwMBhrWcf8qUYccPhEcxgggTMIIIDwIBATCCAWowggFQMVQwUgYDVQQKDEvQhtC90YTQvtGA0LzQsNGG0ZbQudC90L4t0LTQvtCy0ZbQtNC60L7QstC40Lkg0LTQtdC/0LDRgNGC0LDQvNC10L3RgiDQlNCk0KExXjBcBgNVBAsMVdCj0L/RgNCw0LLQu9GW0L3QvdGPICjRhtC10L3RgtGAKSDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExYjBgBgNVBAMMWdCQ0LrRgNC10LTQuNGC0L7QstCw0L3QuNC5INGG0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMRQwEgYDVQQFDAtVQS0zOTM4NDQ3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQztst79yG5zgQAAADdahsArVFYADAMBgoqhiQCAQEBAQIBoIIGOzAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xODA2MjExNzM2MjBaMC8GCSqGSIb3DQEJBDEiBCD6D34j/gXkZocMlWD2XiioBS2pZHxMDX9v7dPmKYhGozCCAcMGCyqGSIb3DQEJEAIvMYIBsjCCAa4wggGqMIIBpjAMBgoqhiQCAQEBAQIBBCBCirj6uuFHEmw+oePXcyHide+F9T4EW+dFBAQyxeeTJjCCAXIwggFYpIIBVDCCAVAxVDBSBgNVBAoMS9CG0L3RhNC+0YDQvNCw0YbRltC50L3Qvi3QtNC+0LLRltC00LrQvtCy0LjQuSDQtNC10L/QsNGA0YLQsNC80LXQvdGCINCU0KTQoTFeMFwGA1UECwxV0KPQv9GA0LDQstC70ZbQvdC90Y8gKNGG0LXQvdGC0YApINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTFiMGAGA1UEAwxZ0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExFDASBgNVBAUMC1VBLTM5Mzg0NDc2MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFDO2y3v3IbnOBAAAAN1qGwCtUVgAMIIEBwYLKoZIhvcNAQkQAhQxggP2MIID8gYJKoZIhvcNAQcCoIID4zCCA98CAQMxDjAMBgoqhiQCAQEBAQIBMGsGCyqGSIb3DQEJEAEEoFwEWjBYAgEBBgoqhiQCAQEBAgMBMDAwDAYKKoYkAgEBAQECAQQg+g9+I/4F5GaHDJVg9l4oqAUtqWR8TA1/b+3T5imIRqMCBAMwznUYDzIwMTgwNjIxMTczNjE5WjGCA1swggNXAgEBMIIBEzCB+jE/MD0GA1UECgw20JzRltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDE3MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFD23Pnvw1XWyAgAAAAEAAACXAAAAMAwGCiqGJAIBAQEBAgGgggHaMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAcBgkqhkiG9w0BCQUxDxcNMTgwNjIxMTczNjE5WjAvBgkqhkiG9w0BCQQxIgQgGgiDi31kXuTQcLMSU6b9zctDNzyGTBbk6FRdCMhuy5gwggFrBgsqhkiG9w0BCRACLzGCAVowggFWMIIBUjCCAU4wDAYKKoYkAgEBAQECAQQgi2ySeKAQiXg26YI5oxioiCPdvzI81eStsSHuoGRA6DcwggEaMIIBAKSB/TCB+jE/MD0GA1UECgw20JzRltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDE3MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFD23Pnvw1XWyAgAAAAEAAACXAAAAMA0GCyqGJAIBAQEBAwEBBED5tM9dvLqX2gWLZPQm9FNRCOoY8iEETv70GyNbflY3WwocVyIFUoPCh4fwIsRJn20QJgGmkxdbBntVF/X07R5gMA0GCyqGJAIBAQEBAwEBBEBXc3mRS9xgkR4m4MUrpruLiWTkDQHgIqxq3Lwn8ZFCClGWN9YnKHv3OSrgKqYDYg0yibJLVwsjCFunXRzEMdQY","signed_content_encoding":"base64"}
D, [2018-06-21T20:36:29.887313 #122440] DEBUG -- : [httplog] Status: 422
D, [2018-06-21T20:36:29.887528 #122440] DEBUG -- : [httplog] Header: cache-control: max-age=0, private, must-revalidate
D, [2018-06-21T20:36:29.887574 #122440] DEBUG -- : [httplog] Header: content-length: 338
D, [2018-06-21T20:36:29.887597 #122440] DEBUG -- : [httplog] Header: content-type: application/json; charset=utf-8
D, [2018-06-21T20:36:29.887617 #122440] DEBUG -- : [httplog] Header: date: Thu, 21 Jun 2018 17:36:29 GMT
D, [2018-06-21T20:36:29.887635 #122440] DEBUG -- : [httplog] Header: server: Cowboy
D, [2018-06-21T20:36:29.887652 #122440] DEBUG -- : [httplog] Header: vary: Accept-Encoding
D, [2018-06-21T20:36:29.887669 #122440] DEBUG -- : [httplog] Header: via: kong/0.12.1
D, [2018-06-21T20:36:29.887686 #122440] DEBUG -- : [httplog] Header: x-content-type-options: nosniff
D, [2018-06-21T20:36:29.887703 #122440] DEBUG -- : [httplog] Header: x-download-options: noopen
D, [2018-06-21T20:36:29.887836 #122440] DEBUG -- : [httplog] Header: x-frame-options: SAMEORIGIN
D, [2018-06-21T20:36:29.887871 #122440] DEBUG -- : [httplog] Header: x-kong-proxy-latency: 10
D, [2018-06-21T20:36:29.887890 #122440] DEBUG -- : [httplog] Header: x-kong-upstream-latency: 260
D, [2018-06-21T20:36:29.887908 #122440] DEBUG -- : [httplog] Header: x-permitted-cross-domain-policies: none
D, [2018-06-21T20:36:29.887925 #122440] DEBUG -- : [httplog] Header: x-request-id: 85e033e8-2b38-4640-ab01-ff05acf505e0#4834
D, [2018-06-21T20:36:29.887944 #122440] DEBUG -- : [httplog] Header: x-xss-protection: 1; mode=block
D, [2018-06-21T20:36:29.887961 #122440] DEBUG -- : [httplog] Header: connection: close
D, [2018-06-21T20:36:29.888019 #122440] DEBUG -- : [httplog] Response:
{"meta":{"url":"http://api-svc.il/api/contract_requests/8691f14b-8cd9-4ce2-bb3f-825bce00051e/actions/approve","type":"object","request_id":"85e033e8-2b38-4640-ab01-ff05acf505e0#4834","code":422},"error":{"type":"request_malformed","message":"Does not match the signer drfo","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}

**Comment by svetavedmed** [comment]
вы подписали approve подписью с инн = 2880614310, а тестовый сотрудник NHS сделан под тестовую подпись с инн=1111111111. Вот потому и ошибка, что не совпадают ИНН. Вам нужно подписать approve тестовой подписью и тогда все будет работать верно.
