### ISSUE TITLE
Подписание договора со стороны NHS

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#498]
Ругается на Base64

D, [2018-06-24T09:28:41.998435 #18262] DEBUG -- : [httplog] Connecting: api.demo.asclepius.com.ua:443
D, [2018-06-24T09:28:42.134347 #18262] DEBUG -- : [httplog] Sending: PATCH http://api.demo.asclepius.com.ua:443/api/contract_requests/8691f14b-8cd9-4ce2-bb3f-825bce00051e/actions/approve
D, [2018-06-24T09:28:42.134485 #18262] DEBUG -- : [httplog] Header: content-type: application/json
D, [2018-06-24T09:28:42.134519 #18262] DEBUG -- : [httplog] Header: authorization: Bearer QUsyV3ZJNXpDMDVZSWM1N2JHYVpZZz09
D, [2018-06-24T09:28:42.134540 #18262] DEBUG -- : [httplog] Header: api-key: 7a07feaf4c37ef135f85
D, [2018-06-24T09:28:42.134558 #18262] DEBUG -- : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2018-06-24T09:28:42.134575 #18262] DEBUG -- : [httplog] Header: accept: */*
D, [2018-06-24T09:28:42.134590 #18262] DEBUG -- : [httplog] Header: user-agent: Ruby
D, [2018-06-24T09:28:42.134631 #18262] DEBUG -- : [httplog] Header: x-newrelic-id: VQ8CVVdVABAFVVFbBAIOXw==
D, [2018-06-24T09:28:42.134708 #18262] DEBUG -- : [httplog] Header: x-newrelic-transaction: PxRWWFZVW1EDXFdRDwlTVlIGFB8EBw8RVU4aAwEIAlFRVgFXAlkLBlQAAENKQQoFAVQFBwJSFTs=
D, [2018-06-24T09:28:42.134778 #18262] DEBUG -- : [httplog] Header: connection: close
D, [2018-06-24T09:28:42.134829 #18262] DEBUG -- : [httplog] Data: {"signed_content":"MIIR1wYJKoZIhvcNAQcCoIIRyDCCEcQCAQExDjAMBgoqhiQCAQEBAQIBMIIC+wYJKoZIhvcNAQcBoIIC7ASCAuh7ImNvbnRyYWN0b3Jfb3duZXJfaWQiOiIzOWM4NDQzMC05YTUxLTQ4MGYtYTkxOS0xMzUxMjliYzU5NDEiLCJjb250cmFjdG9yX2Jhc2UiOiLQvdCwINC/0ZbQtNGB0YLQsNCy0ZYg0LfQsNC60L7QvdGDINC/0YDQviDQnNC10LTQuNGH0L3QtSDQvtCx0YHQu9GD0LPQvtCy0YPQstCw0L3QvdGPINC90LDRgdC10LvQtdC90L3RjyIsImNvbnRyYWN0b3JfcGF5bWVudF9kZXRhaWxzIjp7ImJhbmtfbmFtZSI6InR0eWh0cmh0cmgiLCJNRk8iOiI2NTY3ODgiLCJwYXllcl9hY2NvdW50IjoiMzQ1MzQ1MjM0NTIzNSJ9LCJjb250cmFjdG9yX3Jtc3BfYW1vdW50IjowLCJjb250cmFjdG9yX2RpdmlzaW9ucyI6WyJhZWNlODc0My00ODdmLTRmOTMtYTgzYS0yMjc4NWJiMTNkZDUiXSwiY29udHJhY3Rvcl9lbXBsb3llZV9kaXZpc2lvbnMiOlt7ImVtcGxveWVlX2lkIjoiZTk5ZjVhOTItMjBhOC00NDEzLThjZjQtMDY4ZTUzZTdhNmUzIiwic3RhZmZfdW5pdHMiOjEuMCwiZGVjbGFyYXRpb25fbGltaXQiOjIwMDAsImRpdmlzaW9uX2lkIjoiYWVjZTg3NDMtNDg3Zi00ZjkzLWE4M2EtMjI3ODViYjEzZGQ1In1dLCJzdGFydF9kYXRlIjoiMjAxOC0wNy0wMSIsImVuZF9kYXRlIjoiMjAxOC0wNy0zMSIsImlkX2Zvcm0iOiJQTURfMSIsInN0YXR1dGVfbWQ1IjoiZGRkNGNkMjI2NjliOGM2MmQ2ZTcxNWE2NDQzOTIzMWEiLCJlcXVpcG1lbnRfYWdyZWVtZW50X21kNSI6IjQ2NjY0NmJjOTE0MTFjNThkYTk0ZTgxYWM4NDNjODJkIn2gggaXMIIGkzCCBjugAwIBAgIUM7bLe/chuc4EAAAA3WobAK1RWAAwDQYLKoYkAgEBAQEDAQEwggFQMVQwUgYDVQQKDEvQhtC90YTQvtGA0LzQsNGG0ZbQudC90L4t0LTQvtCy0ZbQtNC60L7QstC40Lkg0LTQtdC/0LDRgNGC0LDQvNC10L3RgiDQlNCk0KExXjBcBgNVBAsMVdCj0L/RgNCw0LLQu9GW0L3QvdGPICjRhtC10L3RgtGAKSDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExYjBgBgNVBAMMWdCQ0LrRgNC10LTQuNGC0L7QstCw0L3QuNC5INGG0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMRQwEgYDVQQFDAtVQS0zOTM4NDQ3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyMB4XDTE3MDYxMjIxMDAwMFoXDTE5MDYxMjIxMDAwMFowgfMxHDAaBgNVBAoME9Cn0LDRgNC+0Y/QvSDQni7Qki4xOTA3BgNVBAMMMNCn0LDRgNC+0Y/QvSDQntC70LXQutGB0ZbQuSDQktCw0YDRgtCw0L3QvtCy0LjRhzEVMBMGA1UEBAwM0KfQsNGA0L7Rj9C9MSwwKgYDVQQqDCPQntC70LXQutGB0ZbQuSDQktCw0YDRgtCw0L3QvtCy0LjRhzEQMA4GA1UEBQwHMTc5NjgyOTELMAkGA1UEBhMCVUExFTATBgNVBAcMDNCl0LDRgNC60ZbQsjEdMBsGA1UECAwU0KXQsNGA0LrRltCy0YHRjNC60LAwgfIwgckGCyqGJAIBAQEBAwEBMIG5MHUwBwICAQECAQwCAQAEIRC+49tq6p4fhleMRcEllP+UI5Sn1zj5GH5lFQFylPTOAQIhAIAAAAAAAAAAAAAAAAAAAABnWSE68YLph9PhdxSQfUcNBCG2D9LY3OipNCPGEBvKkcR6AH5sMAsmzVVsmw59IO8pKgAEQKnW60XxPHCCgMSWeyMfXq32WOukwDcpHTjZa/Alyk4X+OlyDcYVtDool18Lwd6jZDi1ZOosF5/QEj5tuPrFeQQDJAAEIXGA2zw/oSYcoPj6ENyDV/KE9jlTbzig6+G4eSEEk4bsAaOCAq4wggKqMCkGA1UdDgQiBCA9ilB3UIVogwg6W30ckEV3dHy4AXncPacAj0c8vl+4LDArBgNVHSMEJDAigCAztst79yG5zu7j3i5i/uo7cBpLZ2C8HC/PNWUWtQ68qjAvBgNVHRAEKDAmoBEYDzIwMTcwNjEyMjEwMDAwWqERGA8yMDE5MDYxMjIxMDAwMFowDgYDVR0PAQH/BAQDAgbAMBkGA1UdIAEB/wQPMA0wCwYJKoYkAgEBAQICMAwGA1UdEwEB/wQCMAAwHgYIKwYBBQUHAQMBAf8EDzANMAsGCSqGJAIBAQECATAeBgNVHREEFzAVoBMGCisGAQQBgjcUAgOgBQwDMTQ0MEgGA1UdHwRBMD8wPaA7oDmGN2h0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jcmxzL0FDU0tJRERERlMtRnVsbC5jcmwwSQYDVR0uBEIwQDA+oDygOoY4aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NybHMvQUNTS0lERERGUy1EZWx0YS5jcmwwgYgGCCsGAQUFBwEBBHwwejAwBggrBgEFBQcwAYYkaHR0cDovL2Fjc2tpZGQuZ292LnVhL3NlcnZpY2VzL29jc3AvMEYGCCsGAQUFBzAChjpodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxvYWQvY2VydGlmaWNhdGVzL2FsbGFjc2tpZGQucDdiMD8GCCsGAQUFBwELBDMwMTAvBggrBgEFBQcwA4YjaHR0cDovL2Fjc2tpZGQuZ292LnVhL3NlcnZpY2VzL3RzcC8wRQYDVR0JBD4wPDAcBgwqhiQCAQEBCwEEAgExDBMKMjg4MDYxNDMxMDAcBgwqhiQCAQEBCwEEAQExDBMKMjg4MDYxNDMxMDANBgsqhiQCAQEBAQMBAQNDAARAxaDU4s1Cpi5NBNo5h4R/IY+9i0ucWLOZUsF1a2r2o1x6kCNz2ceLsBgBRvhoLC6qk/4LAwGGtZx/ypRhxw+ERzGCCBMwgggPAgEBMIIBajCCAVAxVDBSBgNVBAoMS9CG0L3RhNC+0YDQvNCw0YbRltC50L3Qvi3QtNC+0LLRltC00LrQvtCy0LjQuSDQtNC10L/QsNGA0YLQsNC80LXQvdGCINCU0KTQoTFeMFwGA1UECwxV0KPQv9GA0LDQstC70ZbQvdC90Y8gKNGG0LXQvdGC0YApINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTFiMGAGA1UEAwxZ0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExFDASBgNVBAUMC1VBLTM5Mzg0NDc2MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFDO2y3v3IbnOBAAAAN1qGwCtUVgAMAwGCiqGJAIBAQEBAgGgggY7MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE4MDYxOTEyMDMxN1owLwYJKoZIhvcNAQkEMSIEICbJsFkxmvFiKPg0yPZiBwBNT+f84RgBKSC60NxAySQUMIIBwwYLKoZIhvcNAQkQAi8xggGyMIIBrjCCAaowggGmMAwGCiqGJAIBAQEBAgEEIEKKuPq64UcSbD6h49dzIeJ174X1PgRb50UEBDLF55MmMIIBcjCCAVikggFUMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUM7bLe/chuc4EAAAA3WobAK1RWAAwggQHBgsqhkiG9w0BCRACFDGCA/YwggPyBgkqhkiG9w0BBwKgggPjMIID3wIBAzEOMAwGCiqGJAIBAQEBAgEwawYLKoZIhvcNAQkQAQSgXARaMFgCAQEGCiqGJAIBAQECAwEwMDAMBgoqhiQCAQEBAQIBBCAmybBZMZrxYij4NMj2YgcATU/n/OEYASkgutDcQMkkFAIEAx6TJhgPMjAxODA2MTkxMjAzMThaMYIDWzCCA1cCAQEwggETMIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTcxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUPbc+e/DVdbICAAAAAQAAAJcAAAAwDAYKKoYkAgEBAQECAaCCAdowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJBTEPFw0xODA2MTkxMjAzMThaMC8GCSqGSIb3DQEJBDEiBCDu8s2vSsbJRpFx46d0m+pK9wbsSZRcUJmy3dJ4uw1wXzCCAWsGCyqGSIb3DQEJEAIvMYIBWjCCAVYwggFSMIIBTjAMBgoqhiQCAQEBAQIBBCCLbJJ4oBCJeDbpgjmjGKiII92/MjzV5K2xIe6gZEDoNzCCARowggEApIH9MIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTcxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUPbc+e/DVdbICAAAAAQAAAJcAAAAwDQYLKoYkAgEBAQEDAQEEQNlIM4Yquz2euqJ+Ef8Di6C1buuPn7GB5YYn2WmiyPgIucBFlHTQ10tYvd7iqkWGD1WYbUfLq94X6TZAJ/dFcX0wDQYLKoYkAgEBAQEDAQEEQDTxi+m9tL44CRmqgcemb6lGhcWnhRFrRdP28rVZ0hUShk4d6EIdVtPHsmDA2bdHrCirOOhMcMFuoDAp1X4p+Tc=","signed_content_encoding":"base64"}
D, [2018-06-24T09:28:42.387546 #18262] DEBUG -- : [httplog] Status: 422
D, [2018-06-24T09:28:42.387701 #18262] DEBUG -- : [httplog] Header: cache-control: max-age=0, private, must-revalidate
D, [2018-06-24T09:28:42.387733 #18262] DEBUG -- : [httplog] Header: content-type: application/json; charset=utf-8
D, [2018-06-24T09:28:42.387752 #18262] DEBUG -- : [httplog] Header: date: Sun, 24 Jun 2018 06:28:41 GMT
D, [2018-06-24T09:28:42.387767 #18262] DEBUG -- : [httplog] Header: server: Cowboy
D, [2018-06-24T09:28:42.387784 #18262] DEBUG -- : [httplog] Header: vary: Accept-Encoding
D, [2018-06-24T09:28:42.387798 #18262] DEBUG -- : [httplog] Header: via: kong/0.12.1
D, [2018-06-24T09:28:42.387822 #18262] DEBUG -- : [httplog] Header: x-content-type-options: nosniff
D, [2018-06-24T09:28:42.387836 #18262] DEBUG -- : [httplog] Header: x-download-options: noopen
D, [2018-06-24T09:28:42.387849 #18262] DEBUG -- : [httplog] Header: x-frame-options: SAMEORIGIN
D, [2018-06-24T09:28:42.387863 #18262] DEBUG -- : [httplog] Header: x-kong-proxy-latency: 58
D, [2018-06-24T09:28:42.387876 #18262] DEBUG -- : [httplog] Header: x-kong-upstream-latency: 108
D, [2018-06-24T09:28:42.387890 #18262] DEBUG -- : [httplog] Header: x-permitted-cross-domain-policies: none
D, [2018-06-24T09:28:42.387903 #18262] DEBUG -- : [httplog] Header: x-request-id: 85e033e8-2b38-4640-ab01-ff05acf505e0#6573
D, [2018-06-24T09:28:42.387918 #18262] DEBUG -- : [httplog] Header: x-xss-protection: 1; mode=block
D, [2018-06-24T09:28:42.387932 #18262] DEBUG -- : [httplog] Header: content-length: 384
D, [2018-06-24T09:28:42.387945 #18262] DEBUG -- : [httplog] Header: connection: close
D, [2018-06-24T09:28:42.388000 #18262] DEBUG -- : [httplog] Response:
{"meta":{"url":"http://api-svc.il/api/contract_requests/8691f14b-8cd9-4ce2-bb3f-825bce00051e/actions/approve","type":"object","request_id":"85e033e8-2b38-4640-ab01-ff05acf505e0#6573","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"invalid","params":[],"description":"Not a base64 string"}],"entry_type":"json_data_property","entry":"$.signed_content"}]}}

**Comment by AlekzandrV** [comment]
Fixed on DEMO
