### ISSUE TITLE
Переоформлення ОТР декларації при втраті номеру телефону ПРОД

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#499]
Як переоформити активну декларацію, якщо номер телефону втрачено/відключено або т.п.?
СМС буде відправлятись на старий номер.
Деякі наші лікарі вже зіткнулись з такою проблемою.

**Comment by ehealthua** [comment]
@pieskov  это можно отнести ко всем кейсам со сбросом типа авторизации. Поскольку это сможет делать только НСЗУ, ожидаем включения саппорта НСЗУ.
