### ISSUE TITLE
DigSign verification fails even though it's a proper test Signature

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#5]
Mutiple bugs on this requests

First of all - wrong response code is returned
Second - DigSign verification fails even though it's a proper test Signature

`{ "_id" : ObjectId("592b019d8fe080d4186fabd2"), "request_id" : "9034ee3c-d391-4274-919f-19ecf3400c38", "request_data" : { "edrpou" : "38782323", "legal_form" : "540", "name" : "Helsi DIS", "short_name" : "Helsi", "public_name" : "Helsi eHealth DIS", "owner_property_type" : "STATE", "kveds" : [ "33.12", "87.12" ], "addresses" : [ { "type" : "REGISTRATION", "area" : "Вінницька область", "settlement" : "Киев", "street_type" : "STREET", "street" : "Прохора", "building" : "12", "apartment" : "111", "zip" : "23433", "country" : "UA", "settlement_id" : "43432432", "settlement_type" : "CITY", "region" : "Вінницька область" }, { "area" : "Вінницька область", "settlement" : "Лунь", "street_type" : "STREET", "street" : "Мишина", "building" : "12", "apartment" : "", "zip" : "34534", "country" : "UA", "settlement_id" : "43432432", "settlement_type" : "CITY", "region" : "Вінницька область" } ], "owner" : { "last_name" : "Лапуга", "first_name" : "Борис", "second_name" : "Казановиич", "birth_date" : "19.11.1986", "birth_place" : "Россия, Украина", "gender" : "MALE", "documents" : [ { "type" : "TEMPORARY_CERTIFICATE", "number" : "34534544" } ], "tax_id" : "3453453454", "position" : "P9", "phones" : [ { "number" : "+380734439137", "type" : "MOBILE" } ], "email" : "boris@helsi.me" }, "medical_service_provider" : { "accreditation" : { "category" : "SECOND", "issued_date" : "1999-11-11", "expiry_date" : "1999-11-11", "order_no" : "12312312", "order_date" : "2231-12-12" }, "licenses" : [ { "license_number" : "23423423", "issued_by" : "", "issued_date" : "", "expiry_date" : "", "kved" : "", "what_licensed" : "" } ] }, "phones" : [ { "number" : "+380449134324", "type" : "LAND_LINE" } ], "email" : "health@helsi.me", "type" : "MSP", "security" : { "redirect_uri" : "http://dis.helsi.dev/legal_entity/msp_ready" }, "public_offer" : { "consent" : true, "consent_text" : "Test" } }, "create_date" : ISODate("2017-05-28T16:58:05Z"), "signedRequestData" : "MIIV8wYJKoZIhvcNAQcCoIIV5DCCFeACAQExDjAMBgoqhiQCAQEBAQIBMIIGgQYJKoZIhvcNAQcBoIIGcgSCBm57ImVkcnBvdSI6IjM4NzgyMzIzIiwibGVnYWxfZm9ybSI6IjU0MCIsIm5hbWUiOiJIZWxzaSBESVMiLCJzaG9ydF9uYW1lIjoiSGVsc2kiLCJwdWJsaWNfbmFtZSI6IkhlbHNpIGVIZWFsdGggRElTIiwib3duZXJfcHJvcGVydHlfdHlwZSI6IlNUQVRFIiwia3ZlZHMiOlsiMzMuMTIiLCI4Ny4xMiJdLCJhZGRyZXNzZXMiOlt7InR5cGUiOiJSRUdJU1RSQVRJT04iLCJhcmVhIjoi0JLRltC90L3QuNGG0YzQutCwINC+0LHQu9Cw0YHRgtGMIiwic2V0dGxlbWVudCI6ItCa0LjQtdCyIiwic3RyZWV0X3R5cGUiOiJTVFJFRVQiLCJzdHJlZXQiOiLQn9GA0L7RhdC+0YDQsCIsImJ1aWxkaW5nIjoiMTIiLCJhcGFydG1lbnQiOiIxMTEiLCJ6aXAiOiIyMzQzMyIsImNvdW50cnkiOiJVQSIsInNldHRsZW1lbnRfaWQiOiI0MzQzMjQzMiIsInNldHRsZW1lbnRfdHlwZSI6IkNJVFkiLCJyZWdpb24iOiLQktGW0L3QvdC40YbRjNC60LAg0L7QsdC70LDRgdGC0YwifSx7ImFyZWEiOiLQktGW0L3QvdC40YbRjNC60LAg0L7QsdC70LDRgdGC0YwiLCJzZXR0bGVtZW50Ijoi0JvRg9C90YwiLCJzdHJlZXRfdHlwZSI6IlNUUkVFVCIsInN0cmVldCI6ItCc0LjRiNC40L3QsCIsImJ1aWxkaW5nIjoiMTIiLCJhcGFydG1lbnQiOiIiLCJ6aXAiOiIzNDUzNCIsImNvdW50cnkiOiJVQSIsInNldHRsZW1lbnRfaWQiOiI0MzQzMjQzMiIsInNldHRsZW1lbnRfdHlwZSI6IkNJVFkiLCJyZWdpb24iOiLQktGW0L3QvdC40YbRjNC60LAg0L7QsdC70LDRgdGC0YwifV0sIm93bmVyIjp7Imxhc3RfbmFtZSI6ItCb0LDQv9GD0LPQsCIsImZpcnN0X25hbWUiOiLQkdC+0YDQuNGBIiwic2Vjb25kX25hbWUiOiLQmtCw0LfQsNC90L7QstC40LjRhyIsImJpcnRoX2RhdGUiOiIxOS4xMS4xOTg2IiwiYmlydGhfcGxhY2UiOiLQoNC+0YHRgdC40Y8sINCj0LrRgNCw0LjQvdCwIiwiZ2VuZGVyIjoiTUFMRSIsImRvY3VtZW50cyI6W3sidHlwZSI6IlRFTVBPUkFSWV9DRVJUSUZJQ0FURSIsIm51bWJlciI6IjM0NTM0NTQ0In1dLCJ0YXhfaWQiOiIzNDUzNDUzNDU0IiwicG9zaXRpb24iOiJQOSIsInBob25lcyI6W3sibnVtYmVyIjoiKzM4MDczNDQzOTEzNyIsInR5cGUiOiJNT0JJTEUifV0sImVtYWlsIjoiYm9yaXNAaGVsc2kubWUifSwibWVkaWNhbF9zZXJ2aWNlX3Byb3ZpZGVyIjp7ImFjY3JlZGl0YXRpb24iOnsiY2F0ZWdvcnkiOiJTRUNPTkQiLCJpc3N1ZWRfZGF0ZSI6IjE5OTktMTEtMTEiLCJleHBpcnlfZGF0ZSI6IjE5OTktMTEtMTEiLCJvcmRlcl9ubyI6IjEyMzEyMzEyIiwib3JkZXJfZGF0ZSI6IjIyMzEtMTItMTIifSwibGljZW5zZXMiOlt7ImxpY2Vuc2VfbnVtYmVyIjoiMjM0MjM0MjMiLCJpc3N1ZWRfYnkiOiIiLCJpc3N1ZWRfZGF0ZSI6IiIsImV4cGlyeV9kYXRlIjoiIiwia3ZlZCI6IiIsIndoYXRfbGljZW5zZWQiOiIifV19LCJwaG9uZXMiOlt7Im51bWJlciI6IiszODA0NDkxMzQzMjQiLCJ0eXBlIjoiTEFORF9MSU5FIn1dLCJlbWFpbCI6ImhlYWx0aEBoZWxzaS5tZSIsInR5cGUiOiJNU1AiLCJzZWN1cml0eSI6eyJyZWRpcmVjdF91cmkiOiJodHRwOlwvXC9kaXMuaGVsc2kuZGV2XC9sZWdhbF9lbnRpdHlcL21zcF9yZWFkeSJ9LCJwdWJsaWNfb2ZmZXIiOnsiY29uc2VudCI6dHJ1ZSwiY29uc2VudF90ZXh0IjoiVGVzdCJ9faCCBy0wggcpMIIG0aADAgECAhQztst79yG5zgQAAAB9wyEASWFPADANBgsqhiQCAQEBAQMBATCCAVAxVDBSBgNVBAoMS9CG0L3RhNC+0YDQvNCw0YbRltC50L3Qvi3QtNC+0LLRltC00LrQvtCy0LjQuSDQtNC10L/QsNGA0YLQsNC80LXQvdGCINCU0KTQoTFeMFwGA1UECwxV0KPQv9GA0LDQstC70ZbQvdC90Y8gKNGG0LXQvdGC0YApINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTFiMGAGA1UEAwxZ0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExFDASBgNVBAUMC1VBLTM5Mzg0NDc2MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIwHhcNMTcwMTE3MjIwMDAwWhcNMTkwMTE3MjIwMDAwWjCB3zE8MDoGA1UECgwz0KLQntCSICLQldCk0IbQoiDQotCV0JrQndCe0JvQntCU0JbQhtChIiAo0KLQldCh0KIpMREwDwYDVQQLDAjQotC10YHRgjERMA8GA1UEDAwI0YLQtdGB0YIxGDAWBgNVBAMMD9Ci0LXRgdGCINCiLtCiLjERMA8GA1UEBAwI0KLQtdGB0YIxGjAYBgNVBCoMEdCi0LXRgdGCINCi0LXRgdGCMRAwDgYDVQQFDAcyMjEyNzMzMQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LIwgfIwgckGCyqGJAIBAQEBAwEBMIG5MHUwBwICAQECAQwCAQAEIRC+49tq6p4fhleMRcEllP+UI5Sn1zj5GH5lFQFylPTOAQIhAIAAAAAAAAAAAAAAAAAAAABnWSE68YLph9PhdxSQfUcNBCG2D9LY3OipNCPGEBvKkcR6AH5sMAsmzVVsmw59IO8pKgAEQKnW60XxPHCCgMSWeyMfXq32WOukwDcpHTjZa/Alyk4X+OlyDcYVtDool18Lwd6jZDi1ZOosF5/QEj5tuPrFeQQDJAAEIZGDb2seIO/u4I3wv8PAqSNdIuAwtuyMrKWnc0qZAw0iAKOCA1gwggNUMCkGA1UdDgQiBCBUL7RNpgF5Cez6tDtwY/HhONbweSp8VvKrBW2wtIECwjArBgNVHSMEJDAigCAztst79yG5zu7j3i5i/uo7cBpLZ2C8HC/PNWUWtQ68qjAvBgNVHRAEKDAmoBEYDzIwMTcwMTE3MjIwMDAwWqERGA8yMDE5MDExNzIyMDAwMFowDgYDVR0PAQH/BAQDAgbAMBkGA1UdIAEB/wQPMA0wCwYJKoYkAgEBAQICMAwGA1UdEwEB/wQCMAAwHgYIKwYBBQUHAQMBAf8EDzANMAsGCSqGJAIBAQECATCBpwYDVR0RBIGfMIGcoE0GDCsGAQQBgZdGAQEEAqA9DDswNDA4Niwg0LwuINCa0LjRl9CyLCDQstGD0LsuINCe0LvQtdC90Lgg0KLQtdC70ZbQs9C4LCAzOS3QkKAmBgwrBgEEAYGXRgEBBAGgFgwUKzM4ICgwIDQ0KSAzODMtMzItMzeBEGluZm9AZWZpdC5jb20udWGgEQYKKwYBBAGCNxQCA6ADDAE2MEgGA1UdHwRBMD8wPaA7oDmGN2h0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jcmxzL0FDU0tJRERERlMtRnVsbC5jcmwwSQYDVR0uBEIwQDA+oDygOoY4aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NybHMvQUNTS0lERERGUy1EZWx0YS5jcmwwgYgGCCsGAQUFBwEBBHwwejAwBggrBgEFBQcwAYYkaHR0cDovL2Fjc2tpZGQuZ292LnVhL3NlcnZpY2VzL29jc3AvMEYGCCsGAQUFBzAChjpodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxvYWQvY2VydGlmaWNhdGVzL2FsbGFjc2tpZGQucDdiMD8GCCsGAQUFBwELBDMwMTAvBggrBgEFBQcwA4YjaHR0cDovL2Fjc2tpZGQuZ292LnVhL3NlcnZpY2VzL3RzcC8wZQYDVR0JBF4wXDAaBgwqhiQCAQEBCwEEAgExChMIMzg3ODIzMjMwHAYMKoYkAgEBAQsBBAEBMQwTCjExMTExMTExMTEwIAYMKoYkAgEBAQsBBAsBMRATDjE5OTEwODI0LTAwMDI2MA0GCyqGJAIBAQEBAwEBA0MABEANDSYnZP3K3h4btUkLXDQ1UhVjcCI1XowtD0+hX343N9xfwWOq34G+hYlPAogkNSrjj8erdoGh+xptn9qtUi8aMYIIEzCCCA8CAQEwggFqMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUM7bLe/chuc4EAAAAfcMhAElhTwAwDAYKKoYkAgEBAQECAaCCBjswGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTcwNTI4MTY1ODIxWjAvBgkqhkiG9w0BCQQxIgQgGgEkWMxZ4suBLN0f8krTqSGUGHUTeF4FzjHcQ9+7VGYwggHDBgsqhkiG9w0BCRACLzGCAbIwggGuMIIBqjCCAaYwDAYKKoYkAgEBAQECAQQgu3HKZnnH4cO5cwoRg4uYEfQRNFf4iiIdOVHDcyfybdAwggFyMIIBWKSCAVQwggFQMVQwUgYDVQQKDEvQhtC90YTQvtGA0LzQsNGG0ZbQudC90L4t0LTQvtCy0ZbQtNC60L7QstC40Lkg0LTQtdC/0LDRgNGC0LDQvNC10L3RgiDQlNCk0KExXjBcBgNVBAsMVdCj0L/RgNCw0LLQu9GW0L3QvdGPICjRhtC10L3RgtGAKSDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExYjBgBgNVBAMMWdCQ0LrRgNC10LTQuNGC0L7QstCw0L3QuNC5INGG0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMRQwEgYDVQQFDAtVQS0zOTM4NDQ3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQztst79yG5zgQAAAB9wyEASWFPADCCBAcGCyqGSIb3DQEJEAIUMYID9jCCA/IGCSqGSIb3DQEHAqCCA+MwggPfAgEDMQ4wDAYKKoYkAgEBAQECATBrBgsqhkiG9w0BCRABBKBcBFowWAIBAQYKKoYkAgEBAQIDATAwMAwGCiqGJAIBAQEBAgEEIBoBJFjMWeLLgSzdH/JK06khlBh1E3heBc4x3EPfu1RmAgQDyMDgGA8yMDE3MDUyODE2NTgyMVoxggNbMIIDVwIBATCCARMwgfoxPzA9BgNVBAoMNtCc0ZbQvdGW0YHRgtC10YDRgdGC0LLQviDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotChINCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQstGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEtMDAwMTU2MjItMjAxMjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQwBHUd7yx4rgIAAAABAAAAYgAAADAMBgoqhiQCAQEBAQIBoIIB2jAaBgkqhkiG9w0BCQMxDQYLKoZIhvcNAQkQAQQwHAYJKoZIhvcNAQkFMQ8XDTE3MDUyODE2NTgyMVowLwYJKoZIhvcNAQkEMSIEIPwXPtoPE9qFC11c9tkRz9iC819Lr84B1M32rrPWFXlXMIIBawYLKoZIhvcNAQkQAi8xggFaMIIBVjCCAVIwggFOMAwGCiqGJAIBAQEBAgEEICP1iscom/9Bg+TJ66TODB47R571v/bVbqjoOh4Vxny7MIIBGjCCAQCkgf0wgfoxPzA9BgNVBAoMNtCc0ZbQvdGW0YHRgtC10YDRgdGC0LLQviDRjtGB0YLQuNGG0ZbRlyDQo9C60YDQsNGX0L3QuDExMC8GA1UECwwo0JDQtNC80ZbQvdGW0YHRgtGA0LDRgtC+0YAg0IbQotChINCm0JfQnjFJMEcGA1UEAwxA0KbQtdC90YLRgNCw0LvRjNC90LjQuSDQt9Cw0YHQstGW0LTRh9GD0LLQsNC70YzQvdC40Lkg0L7RgNCz0LDQvTEZMBcGA1UEBQwQVUEtMDAwMTU2MjItMjAxMjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQwBHUd7yx4rgIAAAABAAAAYgAAADANBgsqhiQCAQEBAQMBAQRAu0a91ib/bT5sBv5TDYnZ5bb2N5VfHDC5kHvOJJ7cpC26jb+itPwPSSimF8vCtvOXa/2EPBKsRlkwlpvw1X8CJTANBgsqhiQCAQEBAQMBAQRA46bTUbfCq9rc9/qTKO6p6ZXmR1qN/tsUdiSVu35BjBzZZ/9RJb+tSQeZABhr5d7NF3Xq3Or5OT4tPa8jyz4CSw==", "signedRequestDate" : ISODate("2017-05-28T16:58:22Z"), "ehealthRequests" : [ { "meta" : { "url" : "http://api-svc.il/api/legal_entities", "type" : "object", "request_id" : "b6v23dq1c04p0t0r5ig2lj2963qmbhru", "code" : 400 }, "error" : { "type" : "request_malformed", "message" : "Signed request data is invalid", "invalid" : [ { "rules" : [ { "rule" : "json" } ], "entry_type" : "request" } ] } } ] }`

**Comment by AlekzandrV** [comment]
We've fixed DigSign but now validation error occurs

```
{
  "meta": {
    "url": "http://api-svc.il/api/legal_entities",
    "type": "object",
    "request_id": "pok8jnsf3kom6idk0077e9buv0k7clks",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": "format",
            "params": [
              "^[0-9]{2}\\.[0-9]{2}$"
            ],
            "description": "string does not match pattern \"^[0-9]{2}\\\\.[0-9]{2}$\""
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.medical_service_provider.licenses.[0].kved"
      }
    ]
  }
}
```

**Comment by pzhuk** [comment]
@AlekzandrV is this fix already available on demo env?

**Comment by lymychp** [comment]
@pzhuk yes

**Comment by warehousman** [comment]
fixed
