### ISSUE TITLE
SPECIALITY_LEVEL - missing "no speciality" or "doctor-specialist"

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#50]
Структура словника SPECIALITY_LEVEL(кваліфікаційний рівень лікаря) не передбачає нульового рівня, тобто лікаря-спеціаліста. Причому, сам квадіфікаційний рівень є обов"язковим для create employee request.

Пропоную додати категорію "Лікар-спеціаліст"

```
    {
      "values": {
        "SECOND": "Друга категорія",
        "HIGHEST": "Вища категорія",
        "FIRST": "Перша категорія"
      },
      "name": "SPECIALITY_LEVEL",
      "labels": [
        "SYSTEM",
        "EXTERNAL"
      ],
      "is_active": true
    },

```

**Comment by pzhuk** [comment]
Або інше рішення - зробити поле level в структурі specialities опціональним

**Comment by lymychp** [comment]
можемо додати значенняч в довідник. Як назвати?

**Comment by pzhuk** [comment]
Правильна назва "лікар-спеціаліст"

**Comment by pzhuk** [comment]
В общем, мы посидели-подумали, и кажется тут сразу несколько проблем

1) "лікар-спеціаліст" добавлять не надо
2) qualitifications в Employee Request должен быть обязательным, 
3) speciality в Employee Request НЕ должен быть обязательным

По сути, наличие одного любого действующего qualifications - это и есть "лікар-спеціаліст"

**Comment by sreva** [comment]
2. "qualitifications в Employee Request должен быть обязательным" - якщо судити з коментів в апіарі то це інфа про курси Підвищення кваліфікації і не факт що це є у всіх.
3. "speciality в Employee Request НЕ должен быть обязательным" - спеціальність лікар отримує на інтернатурі і вона в нього є, але ось якраз категорії може і не бути (без категорії = лікар-спеціаліст)

**Comment by lymychp** [comment]
Гляньте плз всю структуру employee_request, може ще щось треба поміняти з required/optional?

**Comment by sreva** [comment]
По решті наче на даний момент питань немає. 
Єдине те що я писав вище.

**Comment by lymychp** [comment]
@sreva діло каже
@pzhuk що скажеш?

**Comment by lymychp** [comment]
- [ ] add new value to the dic "SPECIALITY_LEVEL" - лікар-спеціаліст
- [ ] `attestation_date` should be required

**Comment by lymychp** [comment]
done on dev

**Comment by lymychp** [comment]
deployed to demo
