### ISSUE TITLE
Помилка ствопення заявки на договір ДЕМО

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#500]
На ДЕМО неможливо створити заявку на договір: $.signed_content: Not a base64 string.

**Comment by pieskov** [comment]
POST /api/contract_requests/0dc8cb1c-0743-4388-b054-63a722278a1c HTTP/1.1
Host: api.demo.asclepius.com.ua
Authorization: Bearer WmxBS1RrTXQ5RmlJSzhDYzYzZ2dSdz09
api-key: 200515ff0fe141f1b2f4
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 183b3318-2e9a-4871-8518-867180728986

{"signed_content":"MIITwwYJKoZIhvcNAQcCoIITtDCCE7ACAQExDjAMBgoqhiQCAQEBAQIBMIIDiQYJKoZIhvcNAQcBoIIDegSCA3Z7ImlkX2Zvcm0iOiJQTURfMSIsInN0YXJ0X2RhdGUiOiIyMDE4LTA2LTI2IiwiZW5kX2RhdGUiOiIyMDE4LTEyLTMxIiwic3RhdHV0ZV9tZDUiOiJhOGQ1ZDA4NDE3ZjQ3OTUwNThkMTU4OWNhODJiYjg2ZSIsImFkZGl0aW9uYWxfZG9jdW1lbnRfbWQ1IjoiYThkNWQwODQxN2Y0Nzk1MDU4ZDE1ODljYTgyYmI4NmUiLCJjb250cmFjdG9yX293bmVyX2lkIjoiNjA0OGI4OGQtZmQwYy00OTgwLTg1ZDktY2NmNmY4ODJmMzU2IiwiY29udHJhY3Rvcl9iYXNlIjoi0ZbQstGW0L/RltGE0L8iLCJjb250cmFjdG9yX3Jtc3BfYW1vdW50IjoxMjAwMCwiZXh0ZXJuYWxfY29udHJhY3Rvcl9mbGFnIjpmYWxzZSwiY29udHJhY3Rvcl9wYXltZW50X2RldGFpbHMiOnsiYmFua19uYW1lIjoi0LLQsNGE0ZbQstC/IiwiTUZPIjoiMTIzMTIzIiwicGF5ZXJfYWNjb3VudCI6IjEyMzUzMTI2MTIzNTEyMzUxMjM1In0sImNvbnRyYWN0b3JfZGl2aXNpb25zIjpbImIzMDJhOTVjLTZjM2ItNDNkMS1hMTA2LWM4ZGU0YjE5ZjQ0MyIsImU0MGJlYTQxLTMxY2EtNDEwZS04MzE5LTgzODc4N2Y1NWQxMiJdLCJjb250cmFjdG9yX2VtcGxveWVlX2RpdmlzaW9ucyI6W3siZW1wbG95ZWVfaWQiOiJiMzc5MmUxNy00OTZhLTQ0Y2EtYjRiNi00NmIxNTA1YWY3YzciLCJzdGFmZl91bml0cyI6MSwiZGVjbGFyYXRpb25fbGltaXQiOjIwMDAsImRpdmlzaW9uX2lkIjoiYjMwMmE5NWMtNmMzYi00M2QxLWExMDYtYzhkZTRiMTlmNDQzIn0seyJlbXBsb3llZV9pZCI6ImViODQxZTI4LTQxZmYtNGI0OS05NGQ4LThhN2Q0ZDM2YTAwYyIsInN0YWZmX3VuaXRzIjoxLCJkZWNsYXJhdGlvbl9saW1pdCI6MjAwMCwiZGl2aXNpb25faWQiOiJlNDBiZWE0MS0zMWNhLTQxMGUtODMxOS04Mzg3ODdmNTVkMTIifV19oIIH9TCCB/EwggeZoAMCAQICFDO2y3v3IbnOBAAAACgPJAD6NFUAMA0GCyqGJAIBAQEBAwEBMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjAeFw0xNzAzMTQyMjAwMDBaFw0xOTAzMTQyMjAwMDBaMIIBsjFWMFQGA1UECgxN0J/Rg9Cx0LvRltGH0L3QtSDQsNC60YbRltC+0L3QtdGA0L3QtSDRgtC+0LLQsNGA0LjRgdGC0LLQviAi0KPQutGA0L/QvtGI0YLQsCIxdjB0BgNVBAsMbdCj0L/RgNCw0LLQu9GW0L3QvdGPINGA0L7Qt9Cy0LjRgtC60YMg0LHQsNC3INC00LDQvdC40YUg0YLQsCDRltC90YLQtdCz0YDQsNGG0ZbRlyDQv9GA0L7Qs9GA0LDQvC4g0LfQsNCx0LXQty4xTTBLBgNVBAwMRNCd0LDRh9Cw0LvRjNC90LjQuiDQstGW0LTQtNGW0LvRgyDRgNC+0LfQstC40YLQutGDINCx0LDQtyDQtNCw0L3QuNGFMR4wHAYDVQQDDBXQm9C+0LHQsNC90L7QsiDQnC7Qki4xFzAVBgNVBAQMDtCb0L7QsdCw0L3QvtCyMSYwJAYDVQQqDB3QnNCw0YDQuiDQktGW0LrRgtC+0YDQvtCy0LjRhzEQMA4GA1UEBQwHMjM2MzE3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyMIHyMIHJBgsqhiQCAQEBAQMBATCBuTB1MAcCAgEBAgEMAgEABCEQvuPbauqeH4ZXjEXBJZT/lCOUp9c4+Rh+ZRUBcpT0zgECIQCAAAAAAAAAAAAAAAAAAAAAZ1khOvGC6YfT4XcUkH1HDQQhtg/S2NzoqTQjxhAbypHEegB+bDALJs1VbJsOfSDvKSoABECp1utF8TxwgoDElnsjH16t9ljrpMA3KR042WvwJcpOF/jpcg3GFbQ6KJdfC8Heo2Q4tWTqLBef0BI+bbj6xXkEAyQABCFOUxdNwfKXyamGh300HPm4VjbsFllnp69ZUEPNQQesHQGjggNMMIIDSDApBgNVHQ4EIgQg/VYUrHouw1USeQ9hkxzFSz2KZ6iXODjkmkoD6n9xMK0wKwYDVR0jBCQwIoAgM7bLe/chuc7u494uYv7qO3AaS2dgvBwvzzVlFrUOvKowLwYDVR0QBCgwJqARGA8yMDE3MDMxNDIyMDAwMFqhERgPMjAxOTAzMTQyMjAwMDBaMA4GA1UdDwEB/wQEAwIGwDAZBgNVHSABAf8EDzANMAsGCSqGJAIBAQECAjAMBgNVHRMBAf8EAjAAMDcGCCsGAQUFBwEDAQH/BCgwJjALBgkqhiQCAQEBAgEwFwYGBACORgECMA0TA1VBSAIDD0JAAgEAMIGkBgNVHREEgZwwgZmgQwYMKwYBBAGBl0YBAQQCoDMMMTAxMDAxLCDQvC4g0JrQuNGX0LIsINCy0YPQuy4g0KXRgNC10YnQsNGC0LjQuiwgMjKgJgYMKwYBBAGBl0YBAQQBoBYMFCszOCAoMCA0NCkgMjc4LTc5LTY5gRVvZmZpY2VsQHVrcnBvc2h0YS5jb22gEwYKKwYBBAGCNxQCA6AFDAMzNjEwSAYDVR0fBEEwPzA9oDugOYY3aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NybHMvQUNTS0lERERGUy1GdWxsLmNybDBJBgNVHS4EQjBAMD6gPKA6hjhodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxvYWQvY3Jscy9BQ1NLSUREREZTLURlbHRhLmNybDCBiAYIKwYBBQUHAQEEfDB6MDAGCCsGAQUFBzABhiRodHRwOi8vYWNza2lkZC5nb3YudWEvc2VydmljZXMvb2NzcC8wRgYIKwYBBQUHMAKGOmh0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jZXJ0aWZpY2F0ZXMvYWxsYWNza2lkZC5wN2IwPwYIKwYBBQUHAQsEMzAxMC8GCCsGAQUFBzADhiNodHRwOi8vYWNza2lkZC5nb3YudWEvc2VydmljZXMvdHNwLzBDBgNVHQkEPDA6MBoGDCqGJAIBAQELAQQCATEKEwgyMTU2MDA0NTAcBgwqhiQCAQEBCwEEAQExDBMKMjU3MDYxNzE5OTANBgsqhiQCAQEBAQMBAQNDAARAW2MlhIwwvUeArukBr4aluBmN5ctujOzyWHqrN5hJJXleDtWM/6tALgnLy2fDabZn2Ckg0HuJBY5QfRiVBe2PBjGCCBMwgggPAgEBMIIBajCCAVAxVDBSBgNVBAoMS9CG0L3RhNC+0YDQvNCw0YbRltC50L3Qvi3QtNC+0LLRltC00LrQvtCy0LjQuSDQtNC10L/QsNGA0YLQsNC80LXQvdGCINCU0KTQoTFeMFwGA1UECwxV0KPQv9GA0LDQstC70ZbQvdC90Y8gKNGG0LXQvdGC0YApINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTFiMGAGA1UEAwxZ0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExFDASBgNVBAUMC1VBLTM5Mzg0NDc2MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFDO2y3v3IbnOBAAAACgPJAD6NFUAMAwGCiqGJAIBAQEBAgGgggY7MBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE4MDYyNTA5MzcyM1owLwYJKoZIhvcNAQkEMSIEILxx0eVuDwxbkwIBmCivsb3Si7zth1Xuc5FoIBlHME4eMIIBwwYLKoZIhvcNAQkQAi8xggGyMIIBrjCCAaowggGmMAwGCiqGJAIBAQEBAgEEIMKYojg5e6xOx6fM9alzEbMn7MB0fa3SrAztzcGajm4JMIIBcjCCAVikggFUMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUM7bLe/chuc4EAAAAKA8kAPo0VQAwggQHBgsqhkiG9w0BCRACFDGCA/YwggPyBgkqhkiG9w0BBwKgggPjMIID3wIBAzEOMAwGCiqGJAIBAQEBAgEwawYLKoZIhvcNAQkQAQSgXARaMFgCAQEGCiqGJAIBAQECAwEwMDAMBgoqhiQCAQEBAQIBBCC8cdHlbg8MW5MCAZgor7G90ou87YdV7nORaCAZRzBOHgIEAz8VDBgPMjAxODA2MjUwOTM3MjNaMYIDWzCCA1cCAQEwggETMIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTcxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUPbc+e/DVdbICAAAAAQAAAJcAAAAwDAYKKoYkAgEBAQECAaCCAdowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJEAEEMBwGCSqGSIb3DQEJBTEPFw0xODA2MjUwOTM3MjNaMC8GCSqGSIb3DQEJBDEiBCAOYpBLNmLQeG+ZoSym8BsJMmxxr202rZTYPKhaXbGESzCCAWsGCyqGSIb3DQEJEAIvMYIBWjCCAVYwggFSMIIBTjAMBgoqhiQCAQEBAQIBBCCLbJJ4oBCJeDbpgjmjGKiII92/MjzV5K2xIe6gZEDoNzCCARowggEApIH9MIH6MT8wPQYDVQQKDDbQnNGW0L3RltGB0YLQtdGA0YHRgtCy0L4g0Y7RgdGC0LjRhtGW0Zcg0KPQutGA0LDRl9C90LgxMTAvBgNVBAsMKNCQ0LTQvNGW0L3RltGB0YLRgNCw0YLQvtGAINCG0KLQoSDQptCX0J4xSTBHBgNVBAMMQNCm0LXQvdGC0YDQsNC70YzQvdC40Lkg0LfQsNGB0LLRltC00YfRg9Cy0LDQu9GM0L3QuNC5INC+0YDQs9Cw0L0xGTAXBgNVBAUMEFVBLTAwMDE1NjIyLTIwMTcxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsgIUPbc+e/DVdbICAAAAAQAAAJcAAAAwDQYLKoYkAgEBAQEDAQEEQGOb4ec8GlAd7tWjL5TmiHlR8palWTOIS5jlOIZsvh9vsQYYhqv53KVWzcs0oRCCsvodVc+cSLpbeLqqGd5fIFcwDQYLKoYkAgEBAQEDAQEEQOFb9HGT8tJ7E8qbIk5Dgh9Zuq3V9gZ40X825Q3MUJB1lyDaB0vGtHUs4CKP8e0RnsiZgL/CnfxMU3hx//RBQTg=","signed_content_encoding":"base64"}

Помилка:
{
    "meta": {
        "url": "http://api-svc.il/api/contract_requests/0dc8cb1c-0743-4388-b054-63a722278a1c",
        "type": "object",
        "request_id": "b2cf0ad1-9b47-4d60-9603-577d4167130e#7239",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "invalid",
                        "params": [],
                        "description": "Not a base64 string"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.signed_content"
            }
        ]
    }
}

**Comment by AlekzandrV** [comment]
Fixed on DEMO
