### ISSUE TITLE
Не обновляется сотрудник на препроде

### ISSUE THREAD

**Issue by evgenkai** [ehealth-ua/api-spec#501]
Просматриваю сотрудников предприятия запросом.
https://api-preprod.ehealth-ukraine.org/api/employees?edrpou=40869188

В респонс получаю 
{"paging":{"total_pages":1,"total_entries":6,"page_size":50,"page_number":1},"meta":{"url":"http://api-svc.il/api/employees","type":"list","request_id":"334f4b03-4c5a-473a-8192-4d213351b307#32772","code":200},"data":[{"status":"APPROVED","start_date":"2018-01-01","position":"P7","party":{"second_name":"Миколаївна","no_tax_id":false,"last_name":"Зіма","id":"e745c244-fc95-49e0-a3dc-9002280ea50e","first_name":"Світлана","declaration_limit":200000000,"declaration_count":null},"legal_entity":{"type":"MSP","status":"ACTIVE","short_name":"ГЛ №8","public_name":"Головна лікарня № 8","owner_property_type":"PRIVATE","name":"Головна лікарня № 8","mis_verified":"NOT_VERIFIED","legal_form":"150","id":"25fa4917-d84a-47bd-b28d-fe816e23473b","edrpou":"40869188"},"id":"2b429385-fefa-4141-ba6e-efbb5aad72cf","end_date":null,"employee_type":"DOCTOR","doctor":{"specialities":[{"valid_to_date":"2020-01-03","speciality_officio":true,"speciality":"FAMILY_DOCTOR","qualification_type":"DEFENSE","level":"FIRST","certificate_number":"1234ASD","attestation_name":"Фізіотерапевтичне відділення КЗ \"Криворізька міська лікарня №11\" ДОР/КЗ \"Криворізька міська лікарня №11\" ДОР","attestation_date":"2015-09-01"}]},"division":{"type":"CLINIC","status":"ACTIVE","name":"Філіал Великої лікарні КАІ","mountain_group":false,"legal_entity_id":"25fa4917-d84a-47bd-b28d-fe816e23473b","id":"4184149a-38e5-45f8-8f63-d8d0deb84b90"}},{"status":"DISMISSED","start_date":"2018-01-01","position":"P7","party":{"second_name":"Миколаївна","no_tax_id":false,"last_name":"Зіма","id":"e745c244-fc95-49e0-a3dc-9002280ea50e","first_name":"Світлана","declaration_limit":200000000,"declaration_count":null},"legal_entity":{"type":"MSP","status":"ACTIVE","short_name":"ГЛ №8","public_name":"Головна лікарня № 8","owner_property_type":"PRIVATE","name":"Головна лікарня № 8","mis_verified":"NOT_VERIFIED","legal_form":"150","id":"25fa4917-d84a-47bd-b28d-fe816e23473b","edrpou":"40869188"},"id":"3a234a17-1654-477e-b800-a2ae72b3d963","end_date":"2018-06-25","employee_type":"DOCTOR","doctor":{"specialities":[{"valid_to_date":"2020-01-03","speciality_officio":true,"speciality":"FAMILY_DOCTOR","qualification_type":"DEFENSE","level":"FIRST","certificate_number":"1234ASD","attestation_name":"Фізіотерапевтичне відділення КЗ \"Криворізька міська лікарня №11\" ДОР/КЗ \"Криворізька міська лікарня №11\" ДОР","attestation_date":"2015-09-01"}]},"division":{"type":"CLINIC","status":"ACTIVE","name":"Філіал Великої лікарні КАІ","mountain_group":false,"legal_entity_id":"25fa4917-d84a-47bd-b28d-fe816e23473b","id":"4184149a-38e5-45f8-8f63-d8d0deb84b90"}},{"status":"DISMISSED","start_date":"2018-01-01","position":"P7","party":{"second_name":"Миколаївна","no_tax_id":false,"last_name":"Зіма","id":"e745c244-fc95-49e0-a3dc-9002280ea50e","first_name":"Світлана","declaration_limit":200000000,"declaration_count":null},"legal_entity":{"type":"MSP","status":"ACTIVE","short_name":"ГЛ №8","public_name":"Головна лікарня № 8","owner_property_type":"PRIVATE","name":"Головна лікарня № 8","mis_verified":"NOT_VERIFIED","legal_form":"150","id":"25fa4917-d84a-47bd-b28d-fe816e23473b","edrpou":"40869188"},"id":"ec64a6f6-52b8-4cde-9965-6b4d7736606a","end_date":"2018-06-25","employee_type":"DOCTOR","doctor":{"specialities":[{"valid_to_date":"2020-01-03","speciality_officio":true,"speciality":"FAMILY_DOCTOR","qualification_type":"DEFENSE","level":"FIRST","certificate_number":"1234ASD","attestation_name":"Фізіотерапевтичне відділення КЗ \"Криворізька міська лікарня №11\" ДОР/КЗ \"Криворізька міська лікарня №11\" ДОР","attestation_date":"2015-09-01"}]},"division":{"type":"CLINIC","status":"ACTIVE","name":"Філіал Великої лікарні КАІ","mountain_group":false,"legal_entity_id":"25fa4917-d84a-47bd-b28d-fe816e23473b","id":"fbf35637-8e1f-4b51-b287-5fa683f5ef54"}},{"status":"APPROVED","start_date":"2018-06-25","position":"P3","party":{"second_name":"Миколаївна","no_tax_id":false,"last_name":"Зіма","id":"e745c244-fc95-49e0-a3dc-9002280ea50e","first_name":"Світлана","declaration_limit":200000000,"declaration_count":null},"legal_entity":{"type":"MSP","status":"ACTIVE","short_name":"ГЛ №8","public_name":"Головна лікарня № 8","owner_property_type":"PRIVATE","name":"Головна лікарня № 8","mis_verified":"NOT_VERIFIED","legal_form":"150","id":"25fa4917-d84a-47bd-b28d-fe816e23473b","edrpou":"40869188"},"id":"85b09247-a403-4fb9-8eed-2b657de033bc","end_date":null,"employee_type":"OWNER"},{"status":"DISMISSED","start_date":"2018-01-01","position":"P7","party":{"second_name":"Миколаївна","no_tax_id":false,"last_name":"Зіма","id":"e745c244-fc95-49e0-a3dc-9002280ea50e","first_name":"Світлана","declaration_limit":200000000,"declaration_count":null},"legal_entity":{"type":"MSP","status":"ACTIVE","short_name":"ГЛ №8","public_name":"Головна лікарня № 8","owner_property_type":"PRIVATE","name":"Головна лікарня № 8","mis_verified":"NOT_VERIFIED","legal_form":"150","id":"25fa4917-d84a-47bd-b28d-fe816e23473b","edrpou":"40869188"},"id":"0a17ed04-044d-48be-ac8d-2f037e2bb785","end_date":"2018-06-25","employee_type":"DOCTOR","doctor":{"specialities":[{"valid_to_date":"2020-01-03","speciality_officio":true,"speciality":"FAMILY_DOCTOR","qualification_type":"DEFENSE","level":"FIRST","certificate_number":"1234ASD","attestation_name":"Фізіотерапевтичне відділення КЗ \"Криворізька міська лікарня №11\" ДОР/КЗ \"Криворізька міська лікарня №11\" ДОР","attestation_date":"2015-09-01"}]},"division":{"type":"CLINIC","status":"ACTIVE","name":"Філіал Великої лікарні КАІ","mountain_group":false,"legal_entity_id":"25fa4917-d84a-47bd-b28d-fe816e23473b","id":"4184149a-38e5-45f8-8f63-d8d0deb84b90"}},{"status":"DISMISSED","start_date":"2018-01-01","position":"P11","party":{"second_name":"Миколаївна","no_tax_id":false,"last_name":"Зіма","id":"e745c244-fc95-49e0-a3dc-9002280ea50e","first_name":"Світлана","declaration_limit":200000000,"declaration_count":null},"legal_entity":{"type":"MSP","status":"ACTIVE","short_name":"ГЛ №8","public_name":"Головна лікарня № 8","owner_property_type":"PRIVATE","name":"Головна лікарня № 8","mis_verified":"NOT_VERIFIED","legal_form":"150","id":"25fa4917-d84a-47bd-b28d-fe816e23473b","edrpou":"40869188"},"id":"1ca75fd5-7f0a-4802-a645-0d5d8e281140","end_date":"2018-06-25","employee_type":"DOCTOR","doctor":{"specialities":[{"valid_to_date":"2020-01-03","speciality_officio":true,"speciality":"THERAPIST","qualification_type":"DEFENSE","level":"FIRST","certificate_number":"1234ASD","attestation_name":"Фізіотерапевтичне відділення КЗ \"Криворізька міська лікарня №11\" ДОР/КЗ \"Криворізька міська лікарня №11\" ДОР","attestation_date":"2015-09-01"}]},"division":{"type":"CLINIC","status":"ACTIVE","name":"Філія \"Головної лікарні № 8\"","mountain_group":false,"legal_entity_id":"25fa4917-d84a-47bd-b28d-fe816e23473b","id":"a4563e0e-fad8-435f-8f04-87905aac15e6"}}]}

сотрудник с  ID 2b429385-fefa-4141-ba6e-efbb5aad72cf есть

Обновляю сотрудника https://api-preprod.ehealth-ukraine.org/api/employees/2b429385-fefa-4141-ba6e-efbb5aad72cf  ( Put )

В ответ приходит 
{"message":"no API found with those values"}

Подскажите как корректно обновить employee

**Comment by lymychp** [comment]
тільки через створення нового employee_request
Такого ендпойнту в специфікації немає
` https://api-preprod.ehealth-ukraine.org/api/employees/2b429385-fefa-4141-ba6e-efbb5aad72cf ( Put )`

**Comment by evgenkai** [comment]
Тогда получается, что у нас может быть несколько абсолютно одинаковых Employee с разными Guid? С которым из них тогда подписывать декларации? В плане тестирования есть пункт - обновление Employee. Если у Empployee, будет новый Guid - это будет обновление Employee? И если у сотрудника поменяются персональные данные (напр. образование), и на момент изменения персональных данных будут подписаны декларации, конфликта не будет?
