### ISSUE TITLE
Прод. Не правильный номер телефона в ОТП при создании декларации.

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#502]
Человек первый раз создает декларацию. Передает один номер телефона. В ответе от ехелса приходит другой. Как понять кто когда и как завел этот номер.

request_id - 05620891-9a11-4568-8105-c3c9818feeac

ответ ехелса

{"urgent"=>{"authentication_method_current"=>{"type"=>"OTP", "number"=>"+38067*****55"}}, "meta"=>{"url"=>"http://api-svc.il/api/declaration_requests", "type"=>"object", "request_id"=>"c6715ea9-fce4-4691-9072-e78d7d614ada#44134", "code"=>200}, "data"=>{"status"=>"NEW", "start_date"=>"2018-06-19", "seed"=>"\\x9970c86762212151cb0c609e9f96004ca2365d21cd602ec5cf0c421360868293c54d452b48f8793d0c428704b4b1bd9314cd3b7f822ddeac1a883b81df3c18cb", "scope"=>"family_doctor", "person"=>{"tax_id"=>"2903407188", "secret"=>"290679", "second_name"=>"Олексіївна", "process_disclosure_data_consent"=>true, "phones"=>[{"type"=>"MOBILE", "number"=>"+380503004887"}], "patient_signed"=>false, "last_name"=>"Соколова", "gender"=>"FEMALE", "first_name"=>"Анастасія", "emergency_contact"=>{"second_name"=>"Володимирович", "phones"=>[{"type"=>"MOBILE", "number"=>"+380505177089"}], "last_name"=>"Криволапов", "first_name"=>"Олександр"}, "email"=>nil, "documents"=>[{"type"=>"PASSPORT", "number"=>"МН021184"}], "birth_settlement"=>"ХАРКІВ",

**Comment by lymychp** [comment]
Декларація з таким же ІПН та датою народження була створена раніше. Якщо Ваш клієнт не помилився з даними в цих полях, то помилка або свідомий фрод було введено раніше

**Comment by Charly3X** [comment]
Какой выход из ситуации?

**Comment by ehealthua** [comment]
@Charly3X это можно отнести ко всем кейсам со сбросом типа авторизации. Поскольку это сможет делать только НСЗУ, ожидаем включения саппорта НСЗУ.
