### ISSUE TITLE
Присылать информацию об owner'e в ответе PUT https://api-preprod.ehealth-ukraine.org/api/legal_entities

### ISSUE THREAD

**Issue by oshklyarova** [ehealth-ua/api-spec#503]
При создании организации в api https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity прописано, что будет приходить информация об owner. На самом деле не приходит. Это важно для нас, т.к. мы хотим сохранять эту информацию у себя в базе, в случае успешного создания организации.

## Steps to Reproduce (Repro steps)

- https://api-preprod.ehealth-ukraine.org/api/legal_entities

[3441_Full.txt](https://github.com/ehealth-ua/api-spec/files/2137741/3441_Full.txt)

## Actual result
- (см. прикрепленный файл)

## Expected result
- есть инф-я об owner, как прописано в https://uaehealthapi.docs.apiary.io/#reference/public.-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity-medical-service-provider-integration-layer/legal-entities/create/update-legal-entity

**Comment by lymychp** [comment]
це помилка в специфікації,  блок owner ніколи не був присутній в респонсі на create legal_entity. Буде виправлено.
