### ISSUE TITLE
Offline-декларації залишилися без верифікації (EMCiMED)

### ISSUE THREAD

**Issue by mark-lobanov** [ehealth-ua/api-spec#504]
Доброго дня!
Клієнт стверджує, що нижчеперелічені Offline-декларації залишилися без верифікації:
- 000-M8E9TA-H9, Григор'ев Сергій Леонідович (створена 03.05.2018)
- 0000-58E1-1К20, Данченко Світлана Григорівна (створена 08.05.2018)

просимо перевірити та надати рекомендації, щодо подальших дій

**Comment by lymychp** [comment]
related to https://github.com/edenlabllc/ehealth.api/issues/2542

**Comment by lymychp** [comment]
на продуктиві оптимізована процедура авто-апруву декларацій.
Сьогодні вночі усі декларації зі статусом `pending_verification` старше 30 днів перейдуть в статус `active`
