### ISSUE TITLE
Підпис ЕЦП договору с НСЗУ. ДЕМО

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#505]
При підписанні договору керівником ключем ЕЦП від юр. особи видає помилку:
{
    "meta": {
        "url": "http://api-svc.il/api/contract_requests/0dc8cb1c-0743-4388-b054-63a722278a1c",
        "type": "object",
        "request_id": "85e033e8-2b38-4640-ab01-ff05acf505e0#8689",
        "code": 422
    },
    "error": {
        "type": "request_malformed",
        "message": "Does not match the signer drfo",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "json"
                    }
                ],
                "entry_type": "request"
            }
        ]
    }
}
**Але якщо підписати особистим ключем ЕЦП (фіз. особи) то все ОК.**

Але ж це неправильно. Як керівник може підписати договір особистим ключем. Він же в такому випадку діє від імені юр. особи, а отже і підпис повинен бути "керівника".

**Comment by AlekzandrV** [comment]
Проверка выполняется по drfo, а не по edrpou - контракт надо подписывать именно сотрудником  (физ. лицом)
