### ISSUE TITLE
Помилка при створенні заявки на договір с НСЗУ. ДЕМО

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#506]
При створенні заявки на договір с НСЗУ помилка:
{
    "meta": {
        "url": "http://api-svc.il/api/contract_requests/0dc8cb1c-0743-4388-b054-63a722278a1c",
        "type": "object",
        "request_id": "00ea7ef4-7ef1-4f7a-9ddb-e909b7867a8d#8993",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "schema",
                        "params": {
                            "consent_text": "Погоджуюсь з публічними правилами"
                        },
                        "description": "schema does not allow additional properties"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.consent_text"
            }
        ]
    }
}
В прикладі тут https://uaehealthapi.docs.apiary.io/#reference/public.-contracts/contract-request/pubic.-create-contract-request поле consent_text є в JSON. Якщо відправляти без consent_text то все ОК.

**Comment by AlekzandrV** [comment]
Fixed. Consent text added to schema
