### ISSUE TITLE
Не повертається тип договору при  Get Contract Requests list. ДЕМО

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#507]
Не повертається тип договору при  Get Contract Requests list.

**Comment by pieskov** [comment]
А як нам зрозуміти якого типу заявка на договір?Добре що зараз тільки 1-н тип, а як їх буде більше 2-х?

**Comment by lymychp** [comment]
так Ви пропонуєте enhancement поточної реалізації? просто описаий зареєстровано в форматі bug. 
@AlekzandrV @warehousman @ehealthua що скажете?
