### ISSUE TITLE
Не має довідника статусів по договорах та заявкам по договорах. ДЕМО.

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#508]
Не має довідника статусів по договорах та заявкам по договорах.

**Comment by AlekzandrV** [comment]
Статусы в справочник не вынесены
Статусная модель [тут](https://edenlab.atlassian.net/wiki/spaces/EH/pages/583827480/Status+Chart)

**Comment by AlekzandrV** [comment]
Договора в двух статусах
* VERIFIED
* TERMINATED
