### ISSUE TITLE
Договор get printout_content ошибка

### ISSUE THREAD

**Issue by Charly3X** [ehealth-ua/api-spec#509]
при получении printout context ошибка

{"meta":{"url":"http://api-svc.il/api/contract_requests/8272e19f-79cc-4f8d-947a-13020e0f0e6d/actions/approve_msp","type":"object","request_id":"b2cf0ad1-9b47-4d60-9603-577d4167130e#8750","code":200},"data":{"status":"PENDING_NHS_SIGN","start_date":"2018-06-30","printout_coЬКА"}]}],"contractor_base":"на підставі закону про Медичне обслуговування населення","contract_number":"0000-7K4M-M000"}}
D, [2018-06-26T13:34:55.258326 #71571] DEBUG -- : [httplog] Connecting: api.demo.asclepius.com.ua:443
D, [2018-06-26T13:34:55.417897 #71571] DEBUG -- : [httplog] Sending: GET http://api.demo.asclepius.com.ua:443/api/contract_requests/8272e19f-79cc-4f8d-947a-13020e0f0e6d/printout_content
D, [2018-06-26T13:34:55.418060 #71571] DEBUG -- : [httplog] Header: content-type: application/json
D, [2018-06-26T13:34:55.418107 #71571] DEBUG -- : [httplog] Header: authorization: Bearer dVVCdjlERmZKQWJKNVJwc0Y4L0VoQT09
D, [2018-06-26T13:34:55.418128 #71571] DEBUG -- : [httplog] Header: api-key: 7a07feaf4c37ef135f85
D, [2018-06-26T13:34:55.418147 #71571] DEBUG -- : [httplog] Header: accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
D, [2018-06-26T13:34:55.418163 #71571] DEBUG -- : [httplog] Header: accept: */*
D, [2018-06-26T13:34:55.418179 #71571] DEBUG -- : [httplog] Header: user-agent: Ruby
D, [2018-06-26T13:34:55.418194 #71571] DEBUG -- : [httplog] Header: x-newrelic-id: VQ8CVVdVABAFVVFbBAIOXw==
D, [2018-06-26T13:34:55.418210 #71571] DEBUG -- : [httplog] Header: x-newrelic-transaction: PxQGUgcFC1VVUldbB1AEXwAFFB8EBw8RVU4aUwtZUgFVAA9XCFFSUV1SA0NKQQxSUlZQVw9VFTs=
D, [2018-06-26T13:34:55.418225 #71571] DEBUG -- : [httplog] Header: connection: close
D, [2018-06-26T13:34:55.418277 #71571] DEBUG -- : [httplog] Data: 
D, [2018-06-26T13:34:55.684822 #71571] DEBUG -- : [httplog] Status: 501

D, [2018-06-26T13:34:55.685374 #71571] DEBUG -- : [httplog] Response:
{"meta":{"url":"http://api-svc.il/api/contract_requests/8272e19f-79cc-4f8d-947a-13020e0f0e6d/printout_content","type":"object","request_id":"b2327e67-7496-4ae6-a751-5273596fa732#7570","code":501},"error":{"type":"internal_error"}}

**Comment by AlekzandrV** [comment]
Fixed on DEMO
