### ISSUE TITLE
missing dictionary SCIENCE_DEGREE

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#51]
As per specification, science degree is managed by a enum dictionary SCIENCE_DEGREE which is currently absent in /api/dictionaries response

https://github.com/ehealth-ua/api-spec/blob/master/apiary.apib#L2125

**Comment by lymychp** [comment]
@AlekzandrV please add new dictionary [SCIENCE_DEGREE](https://docs.google.com/spreadsheets/d/1Cu7YFECaTjKkrcvorusVHIyM8MpB2WsXGO4nHlKuGBw/edit#gid=0)

**Comment by pzhuk** [comment]
status?

**Comment by lymychp** [comment]
added on dev

**Comment by lymychp** [comment]
deployed to demo
