### ISSUE TITLE
Get declaration_request by id (Prod)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#510]
*Доброго дня, перевірте будь ласка видалення з declaration_requests, настільки я розумію заявки декларацій живуть 7 днів, якщо вона не підписана, проте є підписана декларація (думаю це не одиничний випадок), яка ссилається на declaration_request, якого немає*

## Steps to Reproduce (Repro steps)
- [ ]  declaration "status": "active"
- [ ]  declaration "id": "ed61a3cf-27bb-46de-83fa-bc7811923317" 
- [ ]  "declaration_request_id": "0a9734af-b5ff-454f-b425-536394c95791"
- [ ]  https://api.ehealth-ukraine.org/api/declaration_requests/0a9734af-b5ff-454f-b425-536394c95791

## Actual result
- [ ]  not_found

## Expected result
- [ ] get declaration_request by id

MIS: DoctorEleks

**Comment by lymychp** [comment]
related to https://github.com/edenlabllc/ehealth.api/issues/2561

**Comment by lymychp** [comment]
declaration_request - тимчасовий об'єкт, який видаляється після 7ми днів.
Технічно він не видаляється, але апі більше його не повертає
