### ISSUE TITLE
501 при підписі декларації на продуктиві

### ISSUE THREAD

**Issue by ytrrty** [ehealth-ua/api-spec#515]
## Steps to Reproduce (Repro steps)

- [ ] `/api/declaration_requests/81912758-43e2-4928-a038-8681c7070d60/actions/sign`
- [ ] method `PATCH`

## Actual result
- [ ] response example (*.json file)
```
{  
  "error":{  
    "type":"internal_error"
  },
  "meta":{  
    "code":501,
    "request_id":"50e3a843-6c0a-426d-9172-19f2166060fa#138037",
    "type":"object",
    "url":"http://api-svc.il/api/declaration_requests/81912758-43e2-4928-a038-8681c7070d60/actions/sign"
  }
}
```

## Expected result
- [ ] code 200

**Comment by lymychp** [comment]
related to https://github.com/edenlabllc/ehealth.api/issues/2517

**Comment by lymychp** [comment]
fixed on prod
