### ISSUE TITLE
Declaration sign Error code 400 (OCSP certificate)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#516]
*Доброго дня, отримуємо наступну помилку при підписанні декларації, получається підписати через декілька спроб*

## Steps to Reproduce (Repro steps)
- [ ] request to sign declaration with body, header etc. (also could provide body, generally signed data looks ok)

## Actual result
- [ ] {"meta":{"url":"http://api-svc.il/api/declaration_requests/f430369d-1cca-46a4-95ba-e6a79c3b5528/actions/sign","type":"object","request_id":"5b4b7bc2-bf1b-45f0-9633-fb50d8290811#214432","code":400},"error":{"type":"request_malformed","message":"OCSP certificate verificaton failed","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}

## Expected result
- [ ] signed declaration

MIS: DoctorEleks

**Comment by lymychp** [comment]
даена помилка пов'язана з доступністю АЦСК.
З точки зору ЦК - це нормальна поведінка
