### ISSUE TITLE
Ошибка с сертификатом ключа

### ISSUE THREAD

**Issue by mishenya** [ehealth-ua/api-spec#518]
Уже 2ю неделю продолжается проблема с подписью деклараций при наложении ЕЦП врача. Приходит ответ:
'{"meta":{"url":"http://api-svc.il/api/declaration_requests/d3b6554e-79e9-4ee8-a02e-e3861553d51c/actions/sign","type":"object","request_id":"cb029101-2996-4078-a8c7-07559199a9ec#35949","code":400},"error":{"type":"request_malformed","message":"OCSP certificate verificaton failed","invalid":[{"rules":[{"rule":"json"}],"entry_type":"request"}]}}',\
Понимаю, что проблема на стороне центра сертификации ключей, но возможно вы в курсе того, решается эта проблема или нет. 
Спасибо.

**Comment by lymychp** [comment]
1. проблема тільки з певними ЕЦП чи з усіма?
2. Проблема стабільно відтворюється чи проявляється епізодично?

**Comment by mishenya** [comment]
1. У деяких лікарів є, у деяких - нема. Поголовна більшість працюють з ключами ПриватБанку. І якщо зараз не підписав, то це не значить, що через годину чи дві не підпише. Хоча є лікар, у якого вже 2й день не підпусуються декларації.
2. Проблема то є, то зникає. Хоча головний лікар ЦПМСД Львівської області вже тиждень не може змінити дані про заклад, оскільки ЕЦП система не приймає, видає, що не знайдено сертифікат.

**Comment by lymychp** [comment]
`OCSP certificate verificaton failed` дана помилка означає, що не вдалось перевірити підпис в АЦСК або що верифікація була негативна
Якщо проблема для певного ЕЦП постійно повторюється, то варто перевірит, що ЕЦП не прострочений, не відізваний і т.д.

Якщо проблема проявляєтсья епізодично, то можу тільки порадити продовжувати спроби. Ми не можемо впливати на доступність сервісів усіх АЦСК.

@ehealthua для системного вирішення проблеми можна реалізувати оффлайн синхронізацію списків відкликаних сертифікатів.
