### ISSUE TITLE
Не удается залогинится

### ISSUE THREAD

**Issue by DmitriyGladkiy** [ehealth-ua/api-spec#519]
Пользователь-главврач: it4medconsole@hotmail.com
------------------------------------------------------------

Среда: https://auth-demo.ehealth-ukraine.org (указано в доках к API)
Ответ: {"message":"no API found with those values"}

Эту среду закрыли полностью?
Данные не куда не переносили?

Среда: https://auth.demo.asclepius.com.ua (передали нам в Slack)
Ответ: {
error:{
type: "access_denied",
message: "Identity, password combination is wrong."},
meta:{
code:401,
request_id:"340ab2fe-8917-4ea5-ab17-34039710fe39#36272",
type:"object",
url:"http://api-svc.mithril/oauth/tokens"}
}

Среда: https://auth-preprod.ehealth-ukraine.org/ (указано в доках к API)
Ответ:{
error: {type: "not_found"}
meta:{
code:404,
request_id:"0d6f349a-02ed-42ef-9d4e-201cdfd8501b#40667",
type:"object",
url:"http://api-svc.mithril/admin/clients/4b634921-552a-40eb-b664-cd5400d8f526/details"}
}

**Comment by lymychp** [comment]
1. даний урл вже не актуальний
2. message: "Identity, password combination is wrong."}, що саме не зрозуміло з повідомлення?
3. endpoint `/admin/clients/4b634921-552a-40eb-b664-cd5400d8f526/details` і не повинен бути доступний. Ви можете користуватись тільки ендпойнтами з префіксом `public`

**Comment by DmitriyGladkiy** [comment]
1. Спасибо.
2. Не понятно почему неверная комбинация паролей при "логине" а не регистрации.("Не удается залогинится #519"), а регистрация прошла успешно без каких либо ошибок и проблем.
3. "Не удается залогинится #519"- по сылке https://auth-preprod.ehealth-ukraine.org/ есть фронт (не наш) с помощью которого мы очень хотим залогинится, но у нас не получается, а консоль хрома говорит нам error: {type: "not_found"} при вызове метода /admin/clients/4b634921-552a-40eb-b664-cd5400d8f526/details

**Comment by lymychp** [comment]
2. при чому тут реєстрація. Введіть правильні логін/пароль на логіні і все буде ок
3. треба більше інформації з детальним описом кожного кроку. Який урл відкриваєте? які параметри передаєте? Які методи викликаєте

**Comment by DmitriyGladkiy** [comment]
2. когда вводишь логин пароль вызывается метод "http://api-svc.mithril/oauth/tokens" и если логин пароль не правильный то он говорит "Identity, password combination is wrong."
когда вводишь правильно то ответ приходит 
expires_at:1533128747
id:"9ea638ae-c3dd-48b4-95af-10257a4f4b79"
name:"access_token"
user_id:"61c278d8-b009-4152-92b8-641db8e9b0a6"
value:"KzdLZXM2WDUxS3RUMXJDK3g2U293dz09"

но после этого сразу вызывается метод admin/clients/4b634921-552a-40eb-b664-cd5400d8f526/details который и не работал и на который мы со своей стороны повлиять никак не можем и дело здесь не в правильности введения логина пароля.

на данный момент пункт 2 работает.
пункт 3 снимаем вопрос, так как там еще нет контрактов, а там где есть пока мы можем залогинится
