### ISSUE TITLE
get Employees does not return contact points any more

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#52]
Call for all employees returns neither phone nor emails of employees. This was different before - contact points should be returned ? Or is it a kind of privacy feature?

```

GET /api/employees HTTP/1.1
Host: demo.ehealth.world
```

**Comment by lymychp** [comment]
it works according to the [spec](http://docs.ehealthapi1.apiary.io/#reference/public.-medical-service-provider-integration-layer/employees/get-employees-list)

**Comment by lymychp** [comment]
the idea was to limit response of the search endpoint to avoid personal data disclosure.

**Comment by sreva** [comment]
Я вірно розумію, певертати дані атрибути в цьому запиті ви не будете? Запитую щоб розуміти які атрибути виводити.

**Comment by lymychp** [comment]
вірно, не будемо.
всі ці атрибути будуть повертатись тільки ендпойнтом /employees/:id

**Comment by sreva** [comment]
Дякую
