### ISSUE TITLE
Не надійшло СМС (EMCiMED)

### ISSUE THREAD

**Issue by mark-lobanov** [ehealth-ua/api-spec#520]
Доброго дня, колеги!
Під час укладання декларації пацієнту Крупська Оксана Миколаївна, РНОКПП: 2650111440, Тел.: +380959196075 не надійшло СМС.
Припускаємо, що з цим пацієнтом раніше було укладено декларацію "без її відома" на інший номер телефону.
Просимо прояснити ситуацію.

**Comment by lymychp** [comment]
прошу надати лог requests/response
що прийшло у відповідь на створення declaration_request від ehealth?

**Comment by mark-lobanov** [comment]
розібралися самі, припущення виявилось вірним
з цим пацієнтом раніше було укладено декларацію "без її відома" на інший номер телефону
