### ISSUE TITLE
Линки для загрузки документов при создании запроса на контракт (demo)

### ISSUE THREAD

**Issue by rshmorgun** [ehealth-ua/api-spec#521]
Ошибка при загрузке документов при инициализации контракта!
последовательность действий:
1. Инициализация запроса на контракт в ответ приходят ссылки для загрузки документов
2. пытаюсь сделать upload документа на полученный линк:
PUT:
url: https://storage.googleapis.com/contract-requests-dev/a50abbd5-32ae-454e-b202-cb1b93693703/contract_request_statute.jpeg?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1530623163&Signature=ZucNez6mR7XecWWmiKJcIKEuGXnwWcHwz2WVhrwCDIk4O89GK1LcI12eRBCBnGQN57zIKdjJ9%2FLBBPsD9V5iOfkEP%2FpBt7na36YEe1c5qazBn2Ni5%2BY2DD7CRZVVi4dMdHjsTl8BmDtJMcVdpROUBCA4QdFDFi%2FYhtS5Eg2k6kT6vPfaxbESezUKrkmkhro2RPLY5wP9cntW%2BBVTpMMVU34uYZDXASaX8eQh%2FxDTHJMZn6Acyjvr%2Bh2JV5MY7s%2BRmiYfmvQDrm7i707ZbA21gS0VL9LOv2yrsVoNbxMLxVmSTrOPVwIp5EXfI5COLIkxPUqbEbs7W0EAtp3DkcRq6Q%3D%3D

Headers:
Content-Type:application/pdf

![image](https://user-images.githubusercontent.com/39626095/42220496-ca0302a4-7ed7-11e8-84dd-7548e8d661e8.png)

**Comment by AlekzandrV** [comment]
На демо загрузка документов с типом pdf работает

**Comment by AlekzandrV** [comment]
Если проблемы повторяются, переоткройте тикет и добавьте CURL по загрузке файла

**Comment by rshmorgun** [comment]
Решено! все работает!
