### ISSUE TITLE
Contractor_divisions demo(question)

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#522]
Доброго дня, як правильно має виглядати масив contractor_divisions при запиті Create Contract Request? так як повертає, що проблема з валідацією"

## Steps to Reproduce (Repro steps)
- [ ] divisions json part:  
...
"contractor_divisions": ["id: 32ddb8ff-279a-40b-9d6-b35bc5ec1228"],
...

## Actual result
- [ ] {
  "meta": {
    "url": "http://api-svc.il/api/contract_requests/aeb74614-96be-48e6-a6ec-f412ea6e56b2",
    "type": "object",
    "request_id": "b2327e67-7496-4ae6-a751-5273596fa732#15699",
    "code": 422
  },
  "error": {
    "type": "validation_failed",
    "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
    "invalid": [
      {
        "rules": [
          {
            "rule": "format",
            "params": [
              "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
            ],
            "description": "string does not match pattern \"^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$\""
          }
        ],
        "entry_type": "json_data_property",
        "entry": "$.contractor_divisions.[0]"
      }
    ]
  }
}

## Expected result
- [ ] created contract

**Comment by vsmihaylovsky** [comment]
может как то так?
"contractor_divisions": ["id": "32ddb8ff-279a-40b-9d6-b35bc5ec1228"]

**Comment by Lextor** [comment]
https://docs.google.com/spreadsheets/d/1maFuJMY2ucu4gZlvKE5MYZYA2mEAPrvmKWqWTGuKt4w/edit#gid=0
ответ в 16 вопросе
