### ISSUE TITLE
Невідповідність структури JSON заявки на конртакт ДЕМО

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#524]
При запиті деталей по контракту api/contract_requests/<ContractRequestID> повертається блок:

"external_contractors":[
    {
        "legal_entity_id":"942db94b-32e3-496e-9610-1e3b106a74f4",
        "divisions":[
            {
                "medical_service":"Послуга ПМД",
                "id":"b302a95c-6c3b-43d1-a106-c8de4b19f443"
            },
            {
                "medical_service":"Послуга ПМД",
                "id":"e40bea41-31ca-410e-8319-838787f55d12"
            }
        ],
        "contract":{
            "number":"1512351235",
            "issued_at":"2017-01-01",
            "expires_at":"2020-01-01"
        }
    }
]

В документації цей блок описаний так:
    "external_contractors": [
      {
        "legal_entity": {
          "id": "b075f148-7f93-4fc2-b2ec-2d81b19a9b7b",
          "name": "Клініка Ноунейм"
        },
        "contract": {
          "number": "1234567",
          "issued_at": "2018-01-01",
          "expires_at": "2019-01-01"
        },
        "divisions": [
          {
            "id": "2922a240-63db-404e-b730-09222bfeb2dd",
            "name": "Бориспільське відділення Клініки Ноунейм",
            "medical_service": "Послуга ПМД"
          }
        ]
      }
    ],

Приведіть у відповідність АПІ та документацію. І де правильно?

**Comment by pieskov** [comment]
І з блоком.
Приходить: 
"urgent":[
    {
        "url":"https://storage.googleapis.com/contract-requests-dev/5c0c1945-cb41-49a4-a8ba-fbc56131204e/media/contract_request_additional_document.pdf?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1530712360&Signature=F1%2B9KGqgBdwBdCcw9Vo%2FW9tTOzpbOnbBYMhrVN6kvMQV2LIB%2F8QGaNqhW8HsPRvpqAGVfIIaFyz5c11Gv3bBxu2Agx9YR3aV%2B5ywJyvrvVRq%2FZZkFpFekgiwVhGNgyF84B5cYqMDvnwcu%2BBt5gr%2FmS4kr2wQJP4VBGdhC%2BvvJoF0Au%2BSi6t5XARxddoE4gh1BmXcPow77x4kKh9cGEadn%2FY0irm31lzhs1y0Hja72HR5UpcRA7fCDNjOTUXqSbNNAQV4m5P4FMilLQkHZfWesN5e1bD2Q8GCkr4KyPIUSfZrvNfk5xHYlyo5SQ93dAJq0sJjkEmxV5PycXA2gAV2yw%3D%3D",
        "type":"additional_document"
    },
    {
        "url":"https://storage.googleapis.com/contract-requests-dev/5c0c1945-cb41-49a4-a8ba-fbc56131204e/media/contract_request_statute.pdf?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1530712360&Signature=t2ODTX4E2RGNdYbzq7yfcyQJ0Figh9rj%2FqFr7lxo36k7VHkTE%2BdXNNwlIVxRxXimxztZHEVfDRHTlINZ%2BQj1Mr1y0k3EFlkMQ0cIKS8bBIOqCijZWnyHfIJ2gX6T%2BqK3wcVpvejHral7fw%2FgNMyQoPbCXsTAyJKpugL5yqjGdcT7kZK1ssisVknc%2FxEhvJIMpCnLJHJ5Euhc1EQbTofGKMwzN0zNZNNbrdgG2YggsoOLwL8uUkOLdZqMM09MwscJf45DLf%2F3E%2F3ue6MPUT7FK9m3fH%2BsuUgYPV3vJ%2BicrcoqZdEpiQg6O%2Fzt19t2%2FKCxLpcK1ja1AOLDvN6m3bRPTA%3D%3D",
        "type":"contract_request_statute"
    }
]

В документації цей блок описаний так:
"urgent": {
    "documents": [
      {
        "type": "signed_content",
        "url": "https://storage.ehealth.world"
      }
    ]
  }

**Comment by danakonovalenko** [comment]
related to edenlabllc/ehealth.api#2603
