### ISSUE TITLE
Scope translation (person:read)

### ISSUE THREAD

**Issue by Lextor** [ehealth-ua/api-spec#525]
![screenshot from 2018-07-04 15 42 24](https://user-images.githubusercontent.com/458180/42277696-eb97b5a8-7fa0-11e8-851b-79a4571831b0.png)
  
## Steps to Reproduce (Repro steps)

- [ ] при добавлении/обновлении скопов

## Actual result
- [ ] отсутствует перевод для scope - person:read

## Expected result
- [ ] перевод для scope - person:read

**Comment by danakonovalenko** [comment]
related to Translation for scopes #2768

**Comment by svetavedmed** [comment]
fixed on prod
