### ISSUE TITLE
Вопрос по Отделению амбулаторий

### ISSUE THREAD

**Issue by Evgeniy0119** [ehealth-ua/api-spec#527]
На данный момент, случаев когда амб. отделаются и создают ОТГ становится всё больше.
Дайте ответ, что делать ЗОЗам?

1. Что делать с divisions, подвязать под новый Legal_Entity, или же создавать новые divisions?
2. Что делать с employees, новые создавать, или есть механизм переноса с одного legal_Entity в другой?
3. Самый главный вопрос что будет с декларациями, если уволить сотрудника, они разрываются. Вопрос юридический, но решения до сих пор нет. Будет ли извещение пациентов о разрыве?

Евгений (МедЭйр)

**Comment by Evgeniy0119** [comment]
Добрый день! Да амб. отделяются и создают новое Юр. Лицо с новым ЕДРПОУ.

Я так, понимаю, Вы предоставляете ответ, как сейчас это делать?!

У меня есть комментарий немного другого ответа с helpdesk ehealth, и как я понимаю это ответ на будующее:

Evgeniy13/Jul/18 10:17 AM
3. У разі реорганізації юридичної особи - надавача ПМД Декларації, подані такому надавачу ПМД до реорганізації, не припиняються, а залишаються чинними і вважаються поданими юридичній особі - правонаступнику за умови збереження відповідних правовідносин з лікарем, який був обраний пацієнтом. "
народ интересуется, когда можно будет им воспользоваться?

Ruslan Prylypko13/Jul/18 2:33 PM
EvgeniyДякую за уточнення! Оскільки це питання юридичного характеру, то ми будем змушені його адресувати юридичним консультантам. Питання про дату прийняття рішення можливо матиме значення, оскільки ми вже мали преценденти, коли юридична позиція залежала від того, яка норма законодавства діяла на момент прийняття рішення.
Технічна реалізація положень наказу щодо збереження декларацій у випадку реорганізації ПМД в роботі, але час завершення залежить від багатьох чинників і ми не можемо спрогнозувати точну дату. 
Ми спрямуємо Ваше запитання до юридичних консультантів з метою отримання роз'яснення, як краще діяти конкретному ПМД в умовах перехідного періоду, враховуючи, що сам процес реорганізації також зазвичай є досить тривалим. 
Дякую за розуміння! 

https://e-health-ua.atlassian.net/servicedesk/customer/portal/3/SUPPORT-74

**Comment by AlekzandrV** [comment]
Да, я прокомментировал исходя из того как это есть сейчас. Пока планов по перезакреплению деклараций за правоприемником нет. Когда они появятся - думаю об этом отдельно будет проинформировано.
Пока же на моменте предлагаю тикет закрывать.

**Comment by Evgeniy0119** [comment]
Спасибо за ответ. Закрываю
