### ISSUE TITLE
Помилка авторизації під двома ролями одночасно (Prod)

### ISSUE THREAD

**Issue by ytrrty** [ehealth-ua/api-spec#529]
## Steps to Reproduce (Repro steps)

Працівник закладу мав роль лікаря, потім йому надали ще роль адміністратора на одну і ту ж електронну адресу. При авторизації отримуємо помилку `User requested scope that is not allowed by role based access policies.`
Два `employee` мають статус `APPROVED` і однаковий `party id`. Скоупи для авторизації беруться напряму з `https://api.ehealth-ukraine.org/admin/roles`

party_id: `a29cf6df-33dc-4df2-9866-10db3dc2ef08`
employee_id 1: `0d9a7a44-f496-4378-8b16-93e0922bde32`
employee_id 2: `e38a5940-07db-4c9e-a153-edbc3d5c27a7`

Скоупи, з якими виконується спроба авторизації
declaration:read
declaration_request:approve
declaration_request:read
declaration_request:reject
declaration_request:sign
declaration_request:write
division:details
division:read
employee:read
employee_request:approve
employee_request:read
employee_request:reject
legal_entity:read
otp:read
otp:write
person:read

## Actual result
```
{
  "meta": {
    "url": "http://api-svc.mithril/oauth/apps/authorize",
    "type": "object",
    "request_id": "46c801cc-1611-4e65-91cd-a5e4b1e2889c#50087",
    "code": 422
  },
  "error": {
    "type": "request_malformed",
    "message": "User requested scope that is not allowed by role based access policies.",
    "invalid": [
      {
        "rules": [
          {
            "rule": "json"
          }
        ],
        "entry_type": "request"
      }
    ]
  }
}
```

## Expected result
Успішна авторизація

**Comment by lymychp** [comment]
прошу надати логін користувача
