### ISSUE TITLE
CR: Licenses structure for LE

### ISSUE THREAD

**Issue by pzhuk** [ehealth-ua/api-spec#53]
As per recent changes in licensing of LE, there are no more such paper document as license
http://www.moz.gov.ua/ua/portal/pre_20170126_a.html

Basically Legal Entity could have only order number now, and no any license number exist

Could you please analyze and suggest a solution? 

Should we make licence_no optional?

**Comment by warehousman** [comment]
Should be registered as CR (health.api) and more info to be provided.
