### ISSUE TITLE
На ДЕМО не працює авторизація з допомогою ЕЦП

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#530]
{"meta":{"url":"http://api-svc.mithril/oauth/tokens","type":"object","request_id":"8471b154-0146-4922-ac11-c3f850623a7a#17195","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"invalid","params":[],"description":"Not a base64 string"}],"entry_type":"json_data_property","entry":"$.signed_content"}]}}

**Comment by AlekzandrV** [comment]
На демо еще не запущена авторизация через ЕЦП. Пока данную фичу не используйте
