### ISSUE TITLE
Email receiving (Prod) 

### ISSUE THREAD

**Issue by superjonh** [ehealth-ua/api-spec#534]
Доброго дня, перевірте будь ласка чи прийшов лист для реєстрації цього користувача (Єдакова Лариса Юріївна, email: edakovaly@ukr.net) і чи можна реалізувати ендпоінт для перевірки таких кейсів?

MIS: DoctorEleks

**Comment by ehealthua-tech** [comment]
Добрый день. 
Для решения вопросов вам следует обращаться на службу поддержки:

https://e-health-ua.atlassian.net/servicedesk/customer/portal/3

Также, большая просьба удалить личные данные пользователя  с сообщения выше. 

Спасибо за понимание.

С уважением, Служба поддержки eHealth

**Comment by superjonh** [comment]
Дякую, зрозуміло
