### ISSUE TITLE
Ошибка при попытке авторизации на демо 

### ISSUE THREAD

**Issue by aladog** [ehealth-ua/api-spec#535]
Коллеги, добрый день!

Со вчерашнего дня получаем следующую ошибку при попытке авторизации на ДЕМО.
![img_05072018_143417_0](https://user-images.githubusercontent.com/39902334/42371239-873ed73a-8117-11e8-98c2-dd73004a2c5c.png)

Вчера был получен ответ, что проблема известна и решается. 
Сегодня сталкиваемся с такой же ошибкой. 

Александр (МедЭйр)

**Comment by Evgeniy0119** [comment]
![image](https://user-images.githubusercontent.com/37930918/42375257-ae53dda0-8123-11e8-8b89-4af33a808e58.png)

**Comment by AlekzandrV** [comment]
Опишите, пожалуйста, последовательность шагов - каким образом вы получаете ошибку на втором скрине

**Comment by aladog** [comment]
Коллеги! 
Нам удалось обнаружить проблему с авторизацией на ДЕМО.

Получаем эту ошибку в форме авторизации, которая запускается из нашего приложения.

В Internet Explorer-і (навіть v.11) получаем аналогичную ошибку при вводе:

https://auth.demo.asclepius.com.ua/sign-in?client_id=ed46ea49-ff14-42e7-8b2f-c2019b4f60c5&redirect_uri=http:%2f%2fe-life.com.ua%2f&scope=client:read+legal_entity:read+employee_request:read+employee_request:write+employee_request:approve+employee_request:reject+employee:read+employee:write+employee:details+employee:deactivate+division:write+division:read+division:details+division:activate+division:deactivate+declaration_request:write+declaration_request:approve+declaration_request:reject+declaration_request:read+declaration:read+otp:read+otp:write+person:read+contract_request:create&email=syrogozy%2bdemoNemyr1%40gmail.com 

Для нашего приложения это критично.  На Prod и Preprod такой проблемы нету.

**Comment by lymychp** [comment]
IE support has been fixed on demo.
please check and reopen issue if still doesn't work.
