### ISSUE TITLE
Помилка при Sign Contract Request by NHS ДЕМО

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#536]
Намагаюсь підписати заявку на договір з боку НСЗУ. JSON для підпису взяв з Get Contract Request Details і тільки "data".

PATCH /api/contract_requests/cdf7d5f6-4c08-43fb-af0e-91296e6ee9af/actions/sign_nhs HTTP/1.1
Host: api.demo.asclepius.com.ua
Content-Type: application/json
Authorization: Bearer a2F0TFcwWUVuanRRdXB1OWtMaSt0UT09
Cache-Control: no-cache
Postman-Token: c60b3d64-9c05-46fb-b4a3-47fc788d04ff

{"signed_content": "MIIfBwYJKoZIhvcNAQcCoIIe+DCCHvQCAQExDjAMBgoqhiQCAQEBAQIBMIIPlQYJKoZIhvcNAQcBoIIPhgSCD4J7InN0YXR1cyI6IlBFTkRJTkdfTkhTX1NJR04iLCJzdGFydF9kYXRlIjoiMjAxOC0wNy0wOSIsInByaW50b3V0X2NvbnRlbnQiOm51bGwsInBhcmVudF9jb250cmFjdF9pZCI6bnVsbCwibmhzX3NpZ25lcl9iYXNlIjoi0L3QsCDQv9GW0LTRgdGC0LDQstGWINC90LDQutCw0LfRgyIsIm5oc19zaWduZXIiOnsicGFydHkiOnsic2Vjb25kX25hbWUiOiLQktC+0LvQvtC00LjQvNC40YDRltCy0L3QsCIsImxhc3RfbmFtZSI6ItCg0LXQstGD0YbRjNC60LAiLCJmaXJzdF9uYW1lIjoi0IbRgNC40L3QsCJ9LCJpZCI6IjM3ODk1YWY3LWY5ZGQtNGYwYS05ZThlLTAyMGM3MWY0YTc1MyJ9LCJuaHNfcGF5bWVudF9tZXRob2QiOiJGT1JXQVJEIiwibmhzX2xlZ2FsX2VudGl0eSI6eyJuYW1lIjoi0J3QsNGG0ZbQvtC90LDQu9GM0L3QsCDRgdC70YPQttCx0LAg0LfQtNC+0YDQvtCyJ9GPINCj0LrRgNCw0ZfQvdC4IiwiaWQiOiJlMzJlNTFhYy1mNzIwLTRlNDItYWRiMy02N2Q1MDRmM2FkMzAiLCJlZHJwb3UiOiIzMDg5Njc0MjUwIiwiYWRkcmVzc2VzIjpbeyJ6aXAiOiIwMjAwMCIsInR5cGUiOiJSRUdJU1RSQVRJT04iLCJzdHJlZXRfdHlwZSI6IlNUUkVFVCIsInN0cmVldCI6ItCy0YPQuy4g0JzQuNGF0LDQudC70LAg0JPRgNGD0YjQtdCy0YHRjNC60L7Qs9C+Iiwic2V0dGxlbWVudF90eXBlIjoiQ0lUWSIsInNldHRsZW1lbnRfaWQiOiJhZGFhNGFiZi1mNTMwLTQ2MWMtYmNiZi1hMGFjMjEwZDk1NWIiLCJzZXR0bGVtZW50Ijoi0JrQmNCH0JIiLCJjb3VudHJ5IjoiVUEiLCJidWlsZGluZyI6IjcifV19LCJuaHNfY29udHJhY3RfcHJpY2UiOjUuMGU0LCJpc3N1ZV9jaXR5Ijoi0JrQuNGX0LIiLCJpZF9mb3JtIjoiUE1EXzEiLCJpZCI6ImNkZjdkNWY2LTRjMDgtNDNmYi1hZjBlLTkxMjk2ZTZlZTlhZiIsImV4dGVybmFsX2NvbnRyYWN0b3JzIjpbeyJsZWdhbF9lbnRpdHlfaWQiOiI5NDJkYjk0Yi0zMmUzLTQ5NmUtOTYxMC0xZTNiMTA2YTc0ZjQiLCJkaXZpc2lvbnMiOlt7Im1lZGljYWxfc2VydmljZSI6IlBIQ19TRVJWSUNFUyIsImlkIjoiYjMwMmE5NWMtNmMzYi00M2QxLWExMDYtYzhkZTRiMTlmNDQzIn0seyJtZWRpY2FsX3NlcnZpY2UiOiJQSENfU0VSVklDRVMiLCJpZCI6ImU0MGJlYTQxLTMxY2EtNDEwZS04MzE5LTgzODc4N2Y1NWQxMiJ9XSwiY29udHJhY3QiOnsibnVtYmVyIjoi0YbQtdGG0LXQudGG0YPQtSIsImlzc3VlZF9hdCI6IjIwMTYtMTItMzAiLCJleHBpcmVzX2F0IjoiMjAyMC0xMi0zMCJ9fV0sImV4dGVybmFsX2NvbnRyYWN0b3JfZmxhZyI6dHJ1ZSwiZW5kX2RhdGUiOiIyMDE4LTEyLTMxIiwiY29udHJhY3Rvcl9ybXNwX2Ftb3VudCI6NDI1MjMwLCJjb250cmFjdG9yX3BheW1lbnRfZGV0YWlscyI6eyJwYXllcl9hY2NvdW50IjoiMzUxMjYxMzQ2MTIzNTM1IiwiYmFua19uYW1lIjoi0ZbQv9GE0ZbQv9C/0ZYiLCJNRk8iOiIxMjMxMjMifSwiY29udHJhY3Rvcl9vd25lciI6eyJwYXJ0eSI6eyJzZWNvbmRfbmFtZSI6ItCi0LXRgdGC0L7QstC40YciLCJsYXN0X25hbWUiOiLQotC10YHRgtC+0LIiLCJmaXJzdF9uYW1lIjoi0KLQtdGB0YIifSwiaWQiOiI2MDQ4Yjg4ZC1mZDBjLTQ5ODAtODVkOS1jY2Y2Zjg4MmYzNTYifSwiY29udHJhY3Rvcl9sZWdhbF9lbnRpdHkiOnsibmFtZSI6ItCi0LXRgdGCINCc0KHQnNCV0JQiLCJpZCI6ImE2ZmFkZmFiLWRlNjctNDBkNy1iOTRiLTkxZTEzZWZiYzk0MyIsImVkcnBvdSI6IjIxNTYwMDQ1IiwiYWRkcmVzc2VzIjpbeyJ6aXAiOiIwMTAwMSIsInR5cGUiOiJSRUdJU1RSQVRJT04iLCJzdHJlZXRfdHlwZSI6IlNUUkVFVCIsInN0cmVldCI6ItCc0LjRgNC+0L3RltCy0YHRjNC60LAiLCJzZXR0bGVtZW50X3R5cGUiOiJDSVRZIiwic2V0dGxlbWVudF9pZCI6ImFkYWE0YWJmLWY1MzAtNDYxYy1iY2JmLWEwYWMyMTBkOTU1YiIsInNldHRsZW1lbnQiOiLQmtCY0IfQkiIsImNvdW50cnkiOiJVQSIsImJ1aWxkaW5nIjoiMTMiLCJhcmVhIjoi0Jwu0JrQmNCH0JIifV19LCJjb250cmFjdG9yX2VtcGxveWVlX2RpdmlzaW9ucyI6W3sic3RhZmZfdW5pdHMiOjEsImVtcGxveWVlIjp7InNwZWNpYWxpdHkiOnsic3BlY2lhbGl0eV9vZmZpY2lvIjp0cnVlLCJzcGVjaWFsaXR5IjoiRkFNSUxZX0RPQ1RPUiIsInF1YWxpZmljYXRpb25fdHlwZSI6IkRFRkVOU0UiLCJsZXZlbCI6IkhJR0hFU1QiLCJjZXJ0aWZpY2F0ZV9udW1iZXIiOiLQudGG0YMiLCJhdHRlc3RhdGlvbl9uYW1lIjoi0LnRhtGDIiwiYXR0ZXN0YXRpb25fZGF0ZSI6IjIwMTgtMDUtMjkifSwicGFydHkiOnsic2Vjb25kX25hbWUiOiLQotC10YHRgtC+0LLQuNGHIiwibGFzdF9uYW1lIjoi0KLQtdGB0YLQvtCyIiwiZmlyc3RfbmFtZSI6ItCi0LXRgdGCIn0sImlkIjoiYjM3OTJlMTctNDk2YS00NGNhLWI0YjYtNDZiMTUwNWFmN2M3In0sImRpdmlzaW9uX2lkIjoiYjMwMmE5NWMtNmMzYi00M2QxLWExMDYtYzhkZTRiMTlmNDQzIiwiZGVjbGFyYXRpb25fbGltaXQiOjIwMDB9LHsic3RhZmZfdW5pdHMiOjEsImVtcGxveWVlIjp7InNwZWNpYWxpdHkiOnsic3BlY2lhbGl0eV9vZmZpY2lvIjp0cnVlLCJzcGVjaWFsaXR5IjoiRkFNSUxZX0RPQ1RPUiIsInF1YWxpZmljYXRpb25fdHlwZSI6IkRFRkVOU0UiLCJsZXZlbCI6IkhJR0hFU1QiLCJjZXJ0aWZpY2F0ZV9udW1iZXIiOiLQudGG0YPQudGG0YMiLCJhdHRlc3RhdGlvbl9uYW1lIjoi0LnRhtGDIiwiYXR0ZXN0YXRpb25fZGF0ZSI6IjIwMTgtMDUtMjgifSwicGFydHkiOnsic2Vjb25kX25hbWUiOiLQotC10YHRgtC+0LLQuNGHIiwibGFzdF9uYW1lIjoi0KLQtdGB0YLQvtCyIiwiZmlyc3RfbmFtZSI6ItCi0LXRgdGCIn0sImlkIjoiZWI4NDFlMjgtNDFmZi00YjQ5LTk0ZDgtOGE3ZDRkMzZhMDBjIn0sImRpdmlzaW9uX2lkIjoiZTQwYmVhNDEtMzFjYS00MTBlLTgzMTktODM4Nzg3ZjU1ZDEyIiwiZGVjbGFyYXRpb25fbGltaXQiOjIwMDB9XSwiY29udHJhY3Rvcl9kaXZpc2lvbnMiOlt7IndvcmtpbmdfaG91cnMiOm51bGwsInBob25lcyI6W3sidHlwZSI6Ik1PQklMRSIsIm51bWJlciI6IiszODAyMzQ2MjM0NjIifV0sIm5hbWUiOiLQkNC80LHRg9C70LDRgtC+0YDRltGPMSIsIm1vdW50YWluX2dyb3VwIjpmYWxzZSwiaWQiOiJiMzAyYTk1Yy02YzNiLTQzZDEtYTEwNi1jOGRlNGIxOWY0NDMiLCJlbWFpbCI6ImExQGdtYWlsLmNvbSIsImFkZHJlc3NlcyI6W3siemlwIjoiMDEwMDEiLCJ0eXBlIjoiUkVTSURFTkNFIiwic3RyZWV0X3R5cGUiOiJTVFJFRVQiLCJzdHJlZXQiOiLQktC40YjQvdGP0LrRltCy0YHRjNC60LAiLCJzZXR0bGVtZW50X3R5cGUiOiJDSVRZIiwic2V0dGxlbWVudF9pZCI6ImFkYWE0YWJmLWY1MzAtNDYxYy1iY2JmLWEwYWMyMTBkOTU1YiIsInNldHRsZW1lbnQiOiLQmtCY0IfQkiIsImNvdW50cnkiOiJVQSIsImJ1aWxkaW5nIjoiMTIiLCJhcmVhIjoi0Jwu0JrQmNCH0JIifV19LHsid29ya2luZ19ob3VycyI6bnVsbCwicGhvbmVzIjpbeyJ0eXBlIjoiTU9CSUxFIiwibnVtYmVyIjoiKzM4MDIzNTEyMzUxMiJ9XSwibmFtZSI6ItCQ0LzQsdGD0LvQsNGC0L7RgNGW0Y8yIiwibW91bnRhaW5fZ3JvdXAiOmZhbHNlLCJpZCI6ImU0MGJlYTQxLTMxY2EtNDEwZS04MzE5LTgzODc4N2Y1NWQxMiIsImVtYWlsIjoiYW0yQHVrci5uZXQiLCJhZGRyZXNzZXMiOlt7InppcCI6IjAxMDAxIiwidHlwZSI6IlJFU0lERU5DRSIsInN0cmVldF90eXBlIjoiU1RSRUVUIiwic3RyZWV0Ijoi0J/QsNCy0LvRltCy0YHRjNC60LAiLCJzZXR0bGVtZW50X3R5cGUiOiJDSVRZIiwic2V0dGxlbWVudF9pZCI6ImFkYWE0YWJmLWY1MzAtNDYxYy1iY2JmLWEwYWMyMTBkOTU1YiIsInNldHRsZW1lbnQiOiLQmtCY0IfQkiIsImNvdW50cnkiOiJVQSIsImJ1aWxkaW5nIjoiMTMiLCJhcmVhIjoi0Jwu0JrQmNCH0JIifV19XSwiY29udHJhY3Rvcl9iYXNlIjoi0ZbQstC/0YTRltC/0YTRltCy0L8iLCJjb250cmFjdF9udW1iZXIiOiIwMDAwLVg0NE0tTTAwMCJ9oIIHLTCCBykwggbRoAMCAQICFDO2y3v3IbnOBAAAAH3DIQBJYU8AMA0GCyqGJAIBAQEBAwEBMIIBUDFUMFIGA1UECgxL0IbQvdGE0L7RgNC80LDRhtGW0LnQvdC+LdC00L7QstGW0LTQutC+0LLQuNC5INC00LXQv9Cw0YDRgtCw0LzQtdC90YIg0JTQpNChMV4wXAYDVQQLDFXQo9C/0YDQsNCy0LvRltC90L3RjyAo0YbQtdC90YLRgCkg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMWIwYAYDVQQDDFnQkNC60YDQtdC00LjRgtC+0LLQsNC90LjQuSDRhtC10L3RgtGAINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTEUMBIGA1UEBQwLVUEtMzkzODQ0NzYxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjAeFw0xNzAxMTcyMjAwMDBaFw0xOTAxMTcyMjAwMDBaMIHfMTwwOgYDVQQKDDPQotCe0JIgItCV0KTQhtCiINCi0JXQmtCd0J7Qm9Ce0JTQltCG0KEiICjQotCV0KHQoikxETAPBgNVBAsMCNCi0LXRgdGCMREwDwYDVQQMDAjRgtC10YHRgjEYMBYGA1UEAwwP0KLQtdGB0YIg0KIu0KIuMREwDwYDVQQEDAjQotC10YHRgjEaMBgGA1UEKgwR0KLQtdGB0YIg0KLQtdGB0YIxEDAOBgNVBAUMBzIyMTI3MzMxCzAJBgNVBAYTAlVBMREwDwYDVQQHDAjQmtC40ZfQsjCB8jCByQYLKoYkAgEBAQEDAQEwgbkwdTAHAgIBAQIBDAIBAAQhEL7j22rqnh+GV4xFwSWU/5QjlKfXOPkYfmUVAXKU9M4BAiEAgAAAAAAAAAAAAAAAAAAAAGdZITrxgumH0+F3FJB9Rw0EIbYP0tjc6Kk0I8YQG8qRxHoAfmwwCybNVWybDn0g7ykqAARAqdbrRfE8cIKAxJZ7Ix9erfZY66TANykdONlr8CXKThf46XINxhW0OiiXXwvB3qNkOLVk6iwXn9ASPm24+sV5BAMkAAQhkYNvax4g7+7gjfC/w8CpI10i4DC27IyspadzSpkDDSIAo4IDWDCCA1QwKQYDVR0OBCIEIFQvtE2mAXkJ7Pq0O3Bj8eE41vB5KnxW8qsFbbC0gQLCMCsGA1UdIwQkMCKAIDO2y3v3IbnO7uPeLmL+6jtwGktnYLwcL881ZRa1DryqMC8GA1UdEAQoMCagERgPMjAxNzAxMTcyMjAwMDBaoREYDzIwMTkwMTE3MjIwMDAwWjAOBgNVHQ8BAf8EBAMCBsAwGQYDVR0gAQH/BA8wDTALBgkqhiQCAQEBAgIwDAYDVR0TAQH/BAIwADAeBggrBgEFBQcBAwEB/wQPMA0wCwYJKoYkAgEBAQIBMIGnBgNVHREEgZ8wgZygTQYMKwYBBAGBl0YBAQQCoD0MOzA0MDg2LCDQvC4g0JrQuNGX0LIsINCy0YPQuy4g0J7Qu9C10L3QuCDQotC10LvRltCz0LgsIDM5LdCQoCYGDCsGAQQBgZdGAQEEAaAWDBQrMzggKDAgNDQpIDM4My0zMi0zN4EQaW5mb0BlZml0LmNvbS51YaARBgorBgEEAYI3FAIDoAMMATYwSAYDVR0fBEEwPzA9oDugOYY3aHR0cDovL2Fjc2tpZGQuZ292LnVhL2Rvd25sb2FkL2NybHMvQUNTS0lERERGUy1GdWxsLmNybDBJBgNVHS4EQjBAMD6gPKA6hjhodHRwOi8vYWNza2lkZC5nb3YudWEvZG93bmxvYWQvY3Jscy9BQ1NLSUREREZTLURlbHRhLmNybDCBiAYIKwYBBQUHAQEEfDB6MDAGCCsGAQUFBzABhiRodHRwOi8vYWNza2lkZC5nb3YudWEvc2VydmljZXMvb2NzcC8wRgYIKwYBBQUHMAKGOmh0dHA6Ly9hY3NraWRkLmdvdi51YS9kb3dubG9hZC9jZXJ0aWZpY2F0ZXMvYWxsYWNza2lkZC5wN2IwPwYIKwYBBQUHAQsEMzAxMC8GCCsGAQUFBzADhiNodHRwOi8vYWNza2lkZC5nb3YudWEvc2VydmljZXMvdHNwLzBlBgNVHQkEXjBcMBoGDCqGJAIBAQELAQQCATEKEwgzODc4MjMyMzAcBgwqhiQCAQEBCwEEAQExDBMKMTExMTExMTExMTAgBgwqhiQCAQEBCwEECwExEBMOMTk5MTA4MjQtMDAwMjYwDQYLKoYkAgEBAQEDAQEDQwAEQA0NJidk/creHhu1SQtcNDVSFWNwIjVejC0PT6Fffjc33F/BY6rfgb6FiU8CiCQ1KuOPx6t2gaH7Gm2f2q1SLxoxgggTMIIIDwIBATCCAWowggFQMVQwUgYDVQQKDEvQhtC90YTQvtGA0LzQsNGG0ZbQudC90L4t0LTQvtCy0ZbQtNC60L7QstC40Lkg0LTQtdC/0LDRgNGC0LDQvNC10L3RgiDQlNCk0KExXjBcBgNVBAsMVdCj0L/RgNCw0LLQu9GW0L3QvdGPICjRhtC10L3RgtGAKSDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExYjBgBgNVBAMMWdCQ0LrRgNC10LTQuNGC0L7QstCw0L3QuNC5INGG0LXQvdGC0YAg0YHQtdGA0YLQuNGE0ZbQutCw0YbRltGXINC60LvRjtGH0ZbQsiDQhtCU0JQg0JTQpNChMRQwEgYDVQQFDAtVQS0zOTM4NDQ3NjELMAkGA1UEBhMCVUExETAPBgNVBAcMCNCa0LjRl9CyAhQztst79yG5zgQAAAB9wyEASWFPADAMBgoqhiQCAQEBAQIBoIIGOzAYBgkqhkiG9w0BCQMxCwYJKoZIhvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0xODA3MDgyMTAyNTRaMC8GCSqGSIb3DQEJBDEiBCBzm8BEIBwOGHt72HjK8PfcDAlTMfyTQVDlqBmC675+fTCCAcMGCyqGSIb3DQEJEAIvMYIBsjCCAa4wggGqMIIBpjAMBgoqhiQCAQEBAQIBBCC7ccpmecfhw7lzChGDi5gR9BE0V/iKIh05UcNzJ/Jt0DCCAXIwggFYpIIBVDCCAVAxVDBSBgNVBAoMS9CG0L3RhNC+0YDQvNCw0YbRltC50L3Qvi3QtNC+0LLRltC00LrQvtCy0LjQuSDQtNC10L/QsNGA0YLQsNC80LXQvdGCINCU0KTQoTFeMFwGA1UECwxV0KPQv9GA0LDQstC70ZbQvdC90Y8gKNGG0LXQvdGC0YApINGB0LXRgNGC0LjRhNGW0LrQsNGG0ZbRlyDQutC70Y7Rh9GW0LIg0IbQlNCUINCU0KTQoTFiMGAGA1UEAwxZ0JDQutGA0LXQtNC40YLQvtCy0LDQvdC40Lkg0YbQtdC90YLRgCDRgdC10YDRgtC40YTRltC60LDRhtGW0Zcg0LrQu9GO0YfRltCyINCG0JTQlCDQlNCk0KExFDASBgNVBAUMC1VBLTM5Mzg0NDc2MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFDO2y3v3IbnOBAAAAH3DIQBJYU8AMIIEBwYLKoZIhvcNAQkQAhQxggP2MIID8gYJKoZIhvcNAQcCoIID4zCCA98CAQMxDjAMBgoqhiQCAQEBAQIBMGsGCyqGSIb3DQEJEAEEoFwEWjBYAgEBBgoqhiQCAQEBAgMBMDAwDAYKKoYkAgEBAQECAQQgc5vARCAcDhh7e9h4yvD33AwJUzH8k0FQ5agZguu+fn0CBAN90kUYDzIwMTgwNzA4MjEwMjU0WjGCA1swggNXAgEBMIIBEzCB+jE/MD0GA1UECgw20JzRltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDE3MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFD23Pnvw1XWyAgAAAAEAAACXAAAAMAwGCiqGJAIBAQEBAgGgggHaMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAcBgkqhkiG9w0BCQUxDxcNMTgwNzA4MjEwMjU0WjAvBgkqhkiG9w0BCQQxIgQg0udLPWl9tNYZDP963u0JcEXjOXmlwKvVLivBv2FDQHEwggFrBgsqhkiG9w0BCRACLzGCAVowggFWMIIBUjCCAU4wDAYKKoYkAgEBAQECAQQgi2ySeKAQiXg26YI5oxioiCPdvzI81eStsSHuoGRA6DcwggEaMIIBAKSB/TCB+jE/MD0GA1UECgw20JzRltC90ZbRgdGC0LXRgNGB0YLQstC+INGO0YHRgtC40YbRltGXINCj0LrRgNCw0ZfQvdC4MTEwLwYDVQQLDCjQkNC00LzRltC90ZbRgdGC0YDQsNGC0L7RgCDQhtCi0KEg0KbQl9CeMUkwRwYDVQQDDEDQptC10L3RgtGA0LDQu9GM0L3QuNC5INC30LDRgdCy0ZbQtNGH0YPQstCw0LvRjNC90LjQuSDQvtGA0LPQsNC9MRkwFwYDVQQFDBBVQS0wMDAxNTYyMi0yMDE3MQswCQYDVQQGEwJVQTERMA8GA1UEBwwI0JrQuNGX0LICFD23Pnvw1XWyAgAAAAEAAACXAAAAMA0GCyqGJAIBAQEBAwEBBEDasHw9xYhirp9hpBSDT04F5ibLKsxobDr9DKp2Qe9CBVJYsiKCOlBiAeSmDSucl1zxZ2995WKomU4b/QEMuQF+MA0GCyqGJAIBAQEBAwEBBED3REpKCdUy2d2elUoaKc80FO7pHE+wzsc4sv6uLVbzVNqEGagBSbSDGNuMQ+222tLpmxf7WCxUdqcybZ8fOwQ5", "signed_content_encoding": "base64"}

отримую
{
    "meta": {
        "url": "http://api-svc.il/api/contract_requests/cdf7d5f6-4c08-43fb-af0e-91296e6ee9af/actions/sign_nhs",
        "type": "object",
        "request_id": "fc95e686-572c-4fb0-bba4-e70f79a0f681#22161",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "invalid",
                        "params": [],
                        "description": "Does not match the signer drfo"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.nhs_signer_id"
            }
        ]
    }
}

**Comment by AlekzandrV** [comment]
Вы выбрали подписанта, со стороны НСЗУ у которого в системе отличный ДРФО от вашего (который в подписи). Используйте сотрудника Підписант Підпис Підписувач для тестирования. У него ДРФО совпадающий с ДРФО в тестовой ЕЦП
