### ISSUE TITLE
У довідниках відсутні міста

### ISSUE THREAD

**Issue by mishenya** [ehealth-ua/api-spec#539]
Добрий день.

Лікарі зіштовхнулись з ситуацією, що не можуть заключити декларацію з пацієнтом, оскільки місто, в якому ті прописані відсутнє у довідниках адрес.

Проблема з м. Новоград-Волинський, Житомирська область та м. Чугуєв, Харківська область.

![default](https://user-images.githubusercontent.com/36700676/42577250-a9c5f086-852c-11e8-92aa-65d2075624ca.jpg)
![default](https://user-images.githubusercontent.com/36700676/42577400-eaf2be90-852c-11e8-9489-e12cf0e987cf.jpg)
Прохання допомогти. Дякую.

**Comment by vsmihaylovsky** [comment]
Это же текстовое поле. Туда что угодно можно внести.

**Comment by ehealthua-tech** [comment]
Вопрос был решен в службе поддержки

**Comment by mishenya** [comment]
AlekzandrV, на першому зі скрінів так і робили, шукали по Житомирській області з порожнім полем Район.

**Comment by lymychp** [comment]
![image](https://user-images.githubusercontent.com/5257001/43022501-2c8e73c2-8c70-11e8-8a46-1f0f8bfc412d.png)

2. правильна назва чугуїв
