### ISSUE TITLE
Добавить информацию о новом МИС "Каштан" в разделе providers | Портал

### ISSUE THREAD

**Issue by ViktoriiaApolonova** [ehealth-ua/api-spec#541]
Функції в системі eHealth 
Реєстрація закладів, лікарів, декларацій

Про МІС
МІС «Каштан» успішно працює та постійно розвивається з 2000 року у більш ніж п’ятиста ЗОЗ всіх рівнів надання медичної допомоги, органах управління охороною здоров’я від району до області та комплексно охоплює  всі медичні, економічні, аналітичні та управлінські процеси системи охорони здоров’я від АСМ до МОЗ.
Важливими на етапі переходу до нової моделі фінансування на основі результату є компоненти МІС щодо оцінки рівня складності, ефективності  та якості обслуговування пацієнтів, обліку витрат та розрахунку вартості медпослуг

Технічні вимоги
Браузери: Gogle Chrome,Mozilla Firefox, Internet Explorer, Opera, Safari 

ТОВ «СІЕТ Холдінг», м.Київ
097 121 03 03
066 121 03 03
093 121 03 03
info@ciet-holding.com

![ciet_logo_450x450](https://user-images.githubusercontent.com/41331685/42817071-9b809726-89d5-11e8-8641-1e8570f5e0e0.png)

**Comment by lymychp** [comment]
done
