### ISSUE TITLE
Питання по редагуванню контракту ДЕМО.

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#542]
Можно ли в одном запросе Public. Update Contract Employees добавить и удалить сотрудника?
Как в таком случае будет выглядеть структура JSON?

**Comment by danakonovalenko** [comment]
added additional description to [apiary](
https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contracts/public.-update-contract-employees)
