### ISSUE TITLE
ДЕМО Update Contract Employees.

### ISSUE THREAD

**Issue by mark-lobanov** [ehealth-ua/api-spec#544]
Как удалить сотрудника из контракта по эндпоинту Public. Update Contract Employees.
Отправляю подписанный JSON:
{
   "employee_id": "2ddc622d-1e42-4967-b654-4d889408fad5",
   "division_id": "e40bea41-31ca-410e-8319-838787f55d12",
   "is_active": false
}
Приходит 200. Но сотрудник из контракта не удаляется.

**Comment by danakonovalenko** [comment]
added additional description to [apiary](
https://uaehealthapi.docs.apiary.io/reference/public.-contracts/contracts/public.-update-contract-employees)
