### ISSUE TITLE
При обновлении контракта возникает ошибка 409 request_conflict

### ISSUE THREAD

**Issue by oshklyarova** [ehealth-ua/api-spec#545]
при обновлении существующего контракта через CreateContractRequest с указанием contract_number возникает ошибка

## Steps to Reproduce (Repro steps)

https://api-demo.ehealth-ukraine.org/api/contract_requests/1bccb5fa-7fb9-42f7-8c50-b5b67b4e34ce
(см. вложение)

## Actual result
"error":{"type":"request_conflict","message":"Invalid contract_request id"}

## Expected result
updated contract
[20730_Full.txt](https://github.com/ehealth-ua/api-spec/files/2206302/20730_Full.txt)

**Comment by lymychp** [comment]
@ehealthua FYI

**Comment by svetavedmed** [comment]
При обновлении контракта, вам нужно прохордить все те же шаги, что и при созддании. Т.е. вам нужно заново создать contract_request
1. initialize contract request
2. add documents
3. create contract_request
И вот при создании contract_request вам нужно в json написать старый номер контракта.
"contract_number": "0000-9P4M-M000"
И уже этот json с номером контракта подписать, а дальше также проходить все шаги поп одписанию contract request

**Comment by lymychp** [comment]
і в POST `/contract_requests/` треба передавати новий ID, згенерований на initialize contract request.
А Ви передаєте ID попереднього contract_request, який вже в статусі signed.
