### ISSUE TITLE
DEMO Не отправляется смс с кодом верификации

### ISSUE THREAD

**Issue by oceanvibes** [ehealth-ua/api-spec#551]
**Request Headers:**
POST /api/verifications HTTP/1.1
Host: api.demo.asclepius.com.ua

Authorization: Bearer cmhJaVhLTWZhNnJDUVZyUnpDeFJxUT09
Content-Type: application/json
api-key: 9cea483e5eb8af18a598

**Request Body:**
{
  "phone_number": "+38066XXXXXXX"
}

Телефон в запросе указываем конечно реальный

**Response:**
{
    "meta": {
        "url": "http://api-svc.verification/verifications",
        "type": "object",
        "request_id": "783dfcf0-c0a1-46f2-80c8-5b90efbb9b1e#85457",
        "code": 201
    },
    "data": {
        "status": "new",
        "id": "5f0ecf26-12f6-494e-8b06-d6eb12e1fb9a",
        "code_expired_at": "2018-08-08T07:46:00.941975Z",
        "active": true
    }
}

СМС на телефон при этом не приходит, ждали 10 часов.

**Comment by svetavedmed** [comment]
на демо отправка смс отключена. Отправка смс работает только на препроде

**Comment by oceanvibes** [comment]
Как тогда протестировать отправку декларации на демо?
При отправке Declaration Request с неверифицированным телефоном получаем ошибку:

```
"error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": null,
                        "params": [],
                        "description": "The phone number is not verified."
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.data"
            }
        ]
    }
```

**Comment by oceanvibes** [comment]
Судя по всему на DEMO только OFFLINE верификация работает, её и выбрали.

**Comment by svetavedmed** [comment]
если вы выбрали метод OFFLINE, то номер телефона не проверяется. Скорее всего вы указали метод OFFLINE, но персону ввели не новую. В таком случае проверяется ранее указаный метод у персоны.
