### ISSUE TITLE
Реєстрація MSP. зняти required з атрибутів адреси

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#6]
Колеги, як обговорювали на останній зустрічі в рамках реєстрації MSP ви знімете required з полів 
addresses.settlement_id і addresses.building, так як це адреси юредичні і особливої інфи для Вас не несуть. На даний момент вони ще required.

**Comment by lymychp** [comment]
@pzhuk треба уточнити чи варто реалізовувати

**Comment by lymychp** [comment]
@sreva 
how to get settlement_id examples:
`curl -X GET \
  http://demo.ehealth.world/api/uaddresses/details/district/f067ffa8-31ea-42fd-aec0-7655bb817eef/settlements \
  -H 'authorization: Bearer scope_address' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 629d381a-0b45-ec4c-8bff-784bfdf4dc5b'`

`curl -X GET \
  'http://demo.ehealth.world/api/uaddresses/search/settlements?settlement_name=%D0%9B%D1%83%D1%86%D1%8C%D0%BA&region=%D0%92%D0%BE%D0%BB%D0%B8%D0%BD%D1%81%D1%8C%D0%BA%D0%B0&district=%D0%92%D0%BE%D0%BB%D0%B8%D0%BD%D1%81%D1%8C%D0%BA%D0%B0' \
  -H 'authorization: Bearer UHdoeVoxOHl4enBsMVVsY1A3SXorQT09' \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 267ba277-9008-98f5-eb00-1a4399110999'`

**Comment by sreva** [comment]
@lymychp Дякую В цьому запиті

**Comment by lymychp** [comment]
@sreva 

> В цьому запиті
> region = Create/Update Legal Entity.addresses.area
> district = Create/Update Legal Entity.addresses.region
> Чи я щось не вірно розумію?
Правильно

@ytrrty 
не працює і на реліз 01.06 не планується. Буде вже в повноцінному проді

**Comment by sreva** [comment]
@lymychp  @ytrrty 
я запитував про мапінг атрибутів, так як вони називаються по різному, а суть, з першого погляду, одна і таж

**Comment by lymychp** [comment]
@sreva 
мапінг правильний

**Comment by lymychp** [comment]
@sreva @pzhuk пропоную закрити тікет
