### ISSUE TITLE
Помилка при створенні Legal Entity.

### ISSUE THREAD

**Issue by sashavalotovskiy** [ehealth-ua/api-spec#61]
Надсилаємо такі данні
[legal.txt](https://github.com/ehealth-ua/api-spec/files/1158587/legal.txt)

отримуємо таку помилку - {  
   "meta":{  
      "url":"http://demo.ehealth.world/api/legal_entities",
      "type":"object",
      "request_id":"aouv8653ho3km9i7ab85c0r35t4d291t",
      "code":422
   },
   "error":{  
      "type":"validation_failed",
      "message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
      "invalid":[  
         {  
            "rules":[  
               {  
                  "rule":"invalid",
                  "params":[  

                  ],
                  "description":"one and only one registration address is required"
               }
            ],
            "entry_type":"json_data_property",
            "entry":"$.addresses"
         }
      ]
   }
}

Підкажіть, будь ласка, в чому може бути проблема.

**Comment by pzhuk** [comment]
Ви додаєте адресу типу       "type": "RESIDENCE", але обов"язковим атрибутом при реєстрації є адреса типу       "type": "REGISTRATION"

**Comment by sashavalotovskiy** [comment]
Дякую.
