### ISSUE TITLE
Помилка створення підрозділу

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#62]
- [x]  POST http://demo.ehealth.world/api/divisions
- [x] `{
  "name": "Бориспільське відділення Клініки Борис 111",
  "addresses": [
    {
      "type": "REGISTRATION",
      "country": "UA",
      "area": "ЛЬВІВСЬКА",
      "region": "ПУСТОМИТІВСЬКИЙ",
      "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
      "settlement_type": "CITY",
      "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
      "street_type": "STREET",
      "street": "вул. Ніжинська",
      "building": "15",
      "apartment": "23",
      "zip": "02090"
    }
  ],
  "phones": [
    {
      "type": "MOBILE",
      "number": "+380503410870"
    }
  ],
  "email": "sp.virny+51@gmail.com",
  "type": "clinic",
  "external_id": "3213213",
  "active": true
}`

## Actual result
- [x] `{
    "meta": {
        "url": "http://demo.ehealth.world/api/divisions",
        "type": "object",
        "request_id": "kterogiukddgimtesit4rohvt1hck3up",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "schema",
                        "params": {
                            "active": true
                        },
                        "description": "schema does not allow additional properties"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.active"
            }
        ]
    }
}`

## Expected result
- [x] Підрозділ буде успішно зареєстровано і валідаційної помилки по атрибуту active не буде у відповідності до http://docs.ehealthmisapi.apiary.io/#reference/0/divisions/create-division

**Comment by pzhuk** [comment]
looks like a bug to me - either specification or implementation are wrong. Active flag is present in spec request

**Comment by AlekzandrV** [comment]
Атрибут active було вилучено з об'єкту division. По-замовчанню підрозділ створюється в статусі активний
Щоб уникнути помилки - не передавайте даний атрибут, так як схема не дозволяє додаткові атрибути.
У внутрішню специфікацію зміни внесено.
[Тут](http://docs.ehealthmisapi.apiary.io/#reference/0/divisions/create-division) буде відображено згодом

**Comment by lymychp** [comment]
deployed to demo
