### ISSUE TITLE
Заявка на створення співробітника не змінює статус

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#64]
- [x] http://demo.ehealth.world/api/employee_requests/c826a0a5-47b8-4b30-9feb-31bbab3243d7
- [x]  1. Створили заявку на співробітника ID c826a0a5-47b8-4b30-9feb-31bbab3243d7 ("request_id" : "jg2j8kiocl1mh57snnsko0cers2ve6c9")
        2. Перейшли по лінку в email і створили пароль.
        3. Перевірили статус заявки ("request_id" : "kfmq7g4m8554k2rncln5qd1at5sblsb6"). 

## Actual result
- [x] заявка статус не змінила "status" : "NEW"

## Expected result
- [x] заявка мала змінити статус на "APPROVED"

**Comment by pzhuk** [comment]
Статус заявки змінюється, не після прийняття запрошення лікарем, а після відповідного виклику API
напримклад POST /api/employee_requests/{{ employee_request_id_to_approve }}/approve

Будь-ласка перевірте бізнес процес, згідно документу спецификації параграф 5.5
https://docs.google.com/document/d/1CNQu6R05Piq6HWI4t0L3C_UJC0EVsxPaZ3D-F4b-hcc/edit#heading=h.5qhpzedo67l4

**Comment by sreva** [comment]
@pzhuk вірно, тільки судячи з процесу це на стороні eHealth http://prntscr.com/fxnd4r і  закрито для МІСа.

**Comment by lymychp** [comment]
@sreva  вис створювали багато заявок на один і той же email. І не всі заявки були підтверджені.
Судячи з даних postmark конкретно лінк `http://demo.ehealth.world/api/employee_requests/c826a0a5-47b8-4b30-9feb-31bbab3243d7`  не відкривали. Його ніхто не підтверджував, тому статус не змінився. 
Приблизно в той же час відкривали і підверджували лінк `http://auth.demo.ehealth.world/invite?invite=316a6428-3f36-4b8d-afe1-40768ff67aa7` на того ж самого користувача. Але request `c826a0a5-47b8-4b30-9feb-31bbab3243d7` ніхто не підтверджував. Можете спробувати зараз його підвтердити і статус зміниться.

**Comment by sreva** [comment]
@lymychp дякую. Все ок. Вибачаюсь за запит.
