### ISSUE TITLE
settlement_id при створенні legal_entity

### ISSUE THREAD

**Issue by vladshut** [ehealth-ua/api-spec#65]
Доброго дня! 

Підкажіть, будь ласка, навіщо в запиті на створення **legal entity** передавати не просто **settlement_id**, а й **settlement_type**, **settlement**, **area**, **country**? Чи не можна по **settlement_id** однозначно визначити всі інші параметри?  

Дякую.

**Comment by pzhuk** [comment]
Тому що ми хочемо бути впевненими, що користувач, який вибрав певний населений пункт і побачив назву і атрибути передав id саме цього населеного пункту.

**Comment by vladshut** [comment]
Добре, дякую за пояснення.
