### ISSUE TITLE
Активація і тестування АЦСК  Держінформ'юсту

### ISSUE THREAD

**Issue by vakafonic** [ehealth-ua/api-spec#66]
Последовательность формирования запроса

(string)Json (из примера) -> подпись с помощью библиотек ИИТ (ключ внутри данных) -> base64_encode -> отправка на ендпоинт http://demo.ehealth.world/api/legal_entities

## Данные запроса

- [ ] Тестовые данные для использования в примере  - [json_data.txt](https://github.com/ehealth-ua/api-spec/files/1159206/json_data.txt)
- [ ] Запрос после подписи и шифрования base64_encode [req_data.txt](https://github.com/ehealth-ua/api-spec/files/1159212/req_data.txt). Сами данные могу прочитать, если обратно расшифрую и воспользуюсь функциями библиотеки ИИТ.

## Полученный ответ
- [ ]  [response.txt](https://github.com/ehealth-ua/api-spec/files/1159217/response.txt)

**Comment by pzhuk** [comment]
ЕЦП от какого АЦСК использовался для подписи?

**Comment by vakafonic** [comment]
CN = АЦСК Держінформ'юсту
OU = Акредитований центр сертифікації ключів

**Comment by pzhuk** [comment]
@vakafonic , названий АЦСК поки що не активовано в нашій системі. Ми постараємося зробити все можливе для тестування і включення цього АЦСК.

**Comment by pzhuk** [comment]
status please?

**Comment by lymychp** [comment]
@pzhuk прошу підтвердити, що сертифікти брати тут - https://ca.informjust.ua/ca-certificates

**Comment by pzhuk** [comment]
@lymychp підтверджую!

**Comment by pzhuk** [comment]
@vakafonic Ви можете протстувати, будь-ласка? Названий АЦСК активовано - можете тестувати
