### ISSUE TITLE
Повернення списку підрозділів

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#69]
## Steps to Reproduce (Repro steps)

- [x] http://demo.ehealth.world/api/divisions
- [x]  виконуємо запит GET http://demo.ehealth.world/api/divisions?limit=100
- [x]  відповідь [Get divisions respons.txt](https://github.com/ehealth-ua/api-spec/files/1164561/Get.divisions.respons.txt)

## Actual result
- [x] у відповіді підрозділи як в статусі INACTIVE так ACTIVE

## Expected result
- [x] потрібна можливість фільтрувати по статусу.

**Comment by pzhuk** [comment]
sreva: наразі ми не вважаємо, що кількість підрозділів з якими доведеться працювати буде надто великою. Тому рекомендуємо робити фільтрацію на стороні клієнта

**Comment by sreva** [comment]
@pzhuk Дякую
