### ISSUE TITLE
Проблема создания Legal Entity через АЦСК "Приватбанк"

### ISSUE THREAD

**Issue by vakafonic** [ehealth-ua/api-spec#72]
Подписывал раньше через [ АЦСК Держінформ'юсту](https://github.com/ehealth-ua/api-spec/issues/66 ) получая ошибку request malformed.

Решили не останавливать разработку пока АЦСК Держінформ'юсту полностью введут на боевое состояние на демо, пробуем подписывать через приват.

Получили ключ в лк Приват 24, скачали корректные сертификаты. Но при подписе через другой сертификат и ключ та же ошибка request_malformed. 
У себя все хорошо протестил :
 - При инициализации библиотеки, считывании ключа, подписи, и дальнейшего теста  - раскодировании, получении данных о подписи и  получении самой даты - ошибок нет.
 - Посредством библиотеки удалось получить подписанные данные из signed_legal_entity_request
 - Запрос тестировался и через сервер и через postman

Все попытки провалились.

Прикрипляю файлы с информацией о данных, запросом и ответом

В чем может быть причина отказа сервера???

P.S. Заметил что при проверке и извлечении данных подписи через библиотеки IIT и переводе ее из json формата через функцию php json_decode() возвращается обьект, а не массив, как было на входе.

[json_data.txt](https://github.com/ehealth-ua/api-spec/files/1169191/json_data.txt)
[request_data.txt](https://github.com/ehealth-ua/api-spec/files/1169189/req_data.txt)
[response.txt](https://github.com/ehealth-ua/api-spec/files/1169190/response.txt)

**Comment by pzhuk** [comment]
@DPashchenko any update on it please?

**Comment by TarasenkoA** [comment]
Добрый день!
В данном примере в контейнере (pkcs7) содержится данные и подпись, при этом отсутствует сертификат. Прошу проверить методы подписания.
