### ISSUE TITLE
Помилка авторизації з повними скоупами для Owner

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#73]
## Steps to Reproduce (Repro steps)

-  endpoint address -  http://auth.demo.ehealth.world/
- preconditions if any - беремо повний набір скоупів для Owner з  https://edenlab.atlassian.net/wiki/display/EH/Scopes+model і пробуємо пройти авторизацію

1) _визиваємо_ `http://auth.demo.ehealth.world/accept?client_id=879d1c9a-1e59-46bf-8dad-75f625d32c5b&email=petrovich130%40ukr.net&redirect_uri=https%3A%2F%2Fstagingreform.helsi.me%2Fclinics%2Fmsp_ready&request_type=code&scope=division%3Aread+legal_entity%3Aread+employee%3Aread+employee%3Awrite+division%3Awrite+employee_request%3Aread+employee_request%3Awrite+employee_request%3Aapprove+employee_request%3Areject+declaration_request%3Awrite+declaration%3Aread+employee%3Adetails+division%3Adetails+division%3Aactivate+division%3Adeactivate+declaration_request%3Aapprove+`
_отримуємо помилку_ http://prntscr.com/g05mp4
2) _прибираємо скоупи  по одному і відправляємо запит_ `http://auth.demo.ehealth.world/accept?client_id=879d1c9a-1e59-46bf-8dad-75f625d32c5b&email=petrovich130%40ukr.net&redirect_uri=https%3A%2F%2Fstagingreform.helsi.me%2Fclinics%2Fmsp_ready&request_type=code&scope=division%3Aread+legal_entity%3Aread+employee%3Aread+employee%3Awrite+division%3Awrite+employee_request%3Aread+employee_request%3Awrite+employee_request%3Aapprove+employee_request%3Areject+declaration_request%3Awrite+declaration%3Aread+` 
_в результаті логінимся успішно_

**Набір скоупів з якими авторизація для Owner проходить:** `division:read legal_entity:read employee:read employee:write division:write employee_request:read employee_request:write employee_request:approve employee_request:reject declaration_request:write declaration:read`
**Набір скоупів з якими авторизація для Owner НЕ проходить:** `employee:details division:details division:activate division:deactivate  declaration_request:approve`

**Comment by TarasenkoA** [comment]
Колеги, добрий день!
Внесли зміни по скоупам. Прошу повторно перевірити.

**Comment by TarasenkoA** [comment]
Доброго дня!
Актуальний набір скоупів:
employee:read employee:write employee_request:approve employee_request:read employee_request:write employee_request:reject legal_entity:read declaration_request:read declaration_request:write otp:write otp:read division:read division:write employee:deactivate employee:write declaration:read declaration_request:reject employee:details division:details division:activate division:deactivate declaration_request:approve

**Comment by sreva** [comment]
Дякую
