### ISSUE TITLE
Дробні намера будинків не зберігає 

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#74]
## Steps to Reproduce (Repro steps)

- [x] POST /api/divisions
- [x] Створюємо підрозділ 
- [x] `{
  "name": "Бориспільське відділення Клініки Борис",
  "addresses": [
    {
      "type": "REGISTRATION",
      "country": "UA",
      "area": "КИЇВСЬКА",
      "settlement": "ОБУХІВ",
      "settlement_type": "CITY",
      "settlement_id": "c6fcb23c-f621-45c0-a62c-820494ac702c",
      "street_type": "STREET",
      "street": "КАШТАНОВА",
      "building": "1/5",
      "apartment": "23",
      "zip": "08700"
    }
  ],
  "phones": [
    {
      "type": "MOBILE",
      "number": "+380503410870"
    }
  ],
  "email": "sp.virny+51@gmail.com",
  "type": "clinic",
  "external_id": "3213213"
}`

## Actual result
- [x] `{
    "meta": {
        "url": "http://demo.ehealth.world/api/divisions",
        "type": "object",
        "request_id": "ur3g6u7aqmi8khmvksinuq21etcfq82q",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "format",
                        "params": [
                            "^[0-9]{1,3}(([ \\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?((\\s)?(\\|/)(\\s)?[0-9]{1,3}(([ \\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?)?$"
                        ],
                        "description": "string does not match pattern \"^[0-9]{1,3}(([ \\\\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?((\\\\s)?(\\\\|/)(\\\\s)?[0-9]{1,3}(([ \\\\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?)?$\""
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.addresses.[0].building"
            }
        ]
    }
}`
## Expected result
- [x] реєстрація має пройти успішно

**Comment by pzhuk** [comment]
regex has to be verified. Addresses with dash and slash should pass(like  1/2 and 1-6) succesfuly

**Comment by sreva** [comment]
@pzhuk так і отримуємо помилку 
request: `POST /api/divisions
{
  "name": "Бориспільське відділення Клініки Борис 111",
  "addresses": [
    {
      "type": "REGISTRATION",
      "country": "UA",
      "area": "ЛЬВІВСЬКА",
      "region": "ПУСТОМИТІВСЬКИЙ",
      "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
      "settlement_type": "CITY",
      "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
      "street_type": "STREET",
      "street": "вул. Ніжинська",
      "building": "1/5",
      "apartment": "23",
      "zip": "02090"
    }
  ],
  "phones": [
    {
      "type": "MOBILE",
      "number": "+380503410870"
    }
  ],
  "email": "sp.virny+51@gmail.com",
  "type": "clinic",
  "external_id": "3213213"
}`

respouns : `{
    "meta": {
        "url": "http://demo.ehealth.world/api/divisions",
        "type": "object",
        "request_id": "h4fh0486sa2iqti0rf5mr3fqtupma9fq",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "format",
                        "params": [
                            "^[0-9]{1,3}(([ \\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?((\\s)?(\\|/)(\\s)?[0-9]{1,3}(([ \\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?)?$"
                        ],
                        "description": "string does not match pattern \"^[0-9]{1,3}(([ \\\\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?((\\\\s)?(\\\\|/)(\\\\s)?[0-9]{1,3}(([ \\\\-]{1})?(?![ЫЪЭЁыъэё])[А-ЯҐЇЄа-яґїє]{1})?)?$\""
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.addresses.[0].building"
            }
        ]
    }
}`

**Comment by lymychp** [comment]
fixed on demo
