### ISSUE TITLE
повернення інфи по співробітнику

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#75]
## Steps to Reproduce (Repro steps)

- [x] get http://demo.ehealth.world/api/employee_requests/
- [x] зареєструвати МСП (id мсп на якому отримали помилку 14c5f300-16e9-4d19-9579-64d7e0a9068d)
- [ ]
 1) Зареєстрували мсп, підтвердили заявку на створення співробітника.
 2) зробили запит на статус заявки на створення співробітника `http://demo.ehealth.world/api/employee_requests/b02d7b4a-a86f-4acb-8c83-45546c04d0ad` отримуємо відповідь 200, статус - APPROVED  
 3) зробили запит  `http://demo.ehealth.world/api/employees/b02d7b4a-a86f-4acb-8c83-45546c04d0ad`

## Actual result
- [x] `{
    "meta": {
        "url": "http://demo.ehealth.world/api/employees/b02d7b4a-a86f-4acb-8c83-45546c04d0ad",
        "type": "object",
        "request_id": "6bophbrdtjk6pod82nb92pf00rts86n1",
        "code": 404
    },
    "error": {
        "meta": {
            "url": "http://demo.ehealth.world/api/employees/b02d7b4a-a86f-4acb-8c83-45546c04d0ad",
            "type": "object",
            "request_id": "6bophbrdtjk6pod82nb92pf00rts86n1",
            "code": 404
        },
        "error": {
            "type": "not_found"
        }
    }
}`

## Expected result
- [x] повернення інфи по даному співробітнику

**Comment by lymychp** [comment]
`employee_request_id` та `employee_id` - це різні ідентифікатори

**Comment by sreva** [comment]
@lymychp досить дивно, так як @pzhuk розповідав, що employee_request_id і employee_id - це один "сквозной" ідентифікатор.

**Comment by sreva** [comment]
@lymychp можеш, підказати будь ласка, який у цьому кейсі employee_id і як його отримати?

**Comment by lymychp** [comment]
`employee_id` = `8f0a8dd8-101c-4a82-aaa0-48568b6bead1`
отримати можна через /api/employees?tax_id=2590800739

**Comment by sreva** [comment]
Дякую
