### ISSUE TITLE
Помилка створення декларації. Телефон

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#77]
При створенні декларації, якщо вказати номер телфону відмінний від +380936235985 - отримуємо помилку.

## Steps to Reproduce (Repro steps)

- [ ] api/declaration_requests
- [ ] 1) успішний флоу 
[успішний флоу запит.txt](https://github.com/ehealth-ua/api-spec/files/1193890/default.txt)
Відповідь: 
[успішний флоу відповідь.txt](https://github.com/ehealth-ua/api-spec/files/1193891/default.txt)
 

2) не успішний флоу. Змінили номер телефону на +380932233506 ` "phones": [
        {
          "type": "MOBILE",
          "number": "++380932233506"
        }
      ],
      "authentication_methods": [
        {
          "type": "OTP",
          "phone_number": "+380932233506"
        }
      ],`
Запит:
[Не успішний флоу запит.txt](https://github.com/ehealth-ua/api-spec/files/1193892/default.txt)

## Actual result
- [ ] [Не успішний флоу відповідь.txt](https://github.com/ehealth-ua/api-spec/files/1193893/default.txt)

## Expected result
- [ ] можливість зареєструватись з номером телефону відмінним від +380936235985 (на демо лише з Life)

**Comment by lymychp** [comment]
у вас в неуспішному запиті два ++:
```json
"phones": [
        {
          "type": "MOBILE",
          "number": "++380932233506"
        }
```

**Comment by sreva** [comment]
@lymychp за той приклад вибачаюсь.
ось без ++ 
[Не успішний флоу запит_2.txt](https://github.com/ehealth-ua/api-spec/files/1193998/_2.txt)
[Не успішний флоу відповідь 2.txt](https://github.com/ehealth-ua/api-spec/files/1193999/2.txt)

**Comment by lymychp** [comment]
перед створенням декларації телефон повинен бути верифікований через методи
Initialize OTP
Complete OTP

**Comment by sreva** [comment]
@lymychp @pzhuk Як розповідалося на одному з колів, а ткож як описано https://docs.google.com/document/d/1CNQu6R05Piq6HWI4t0L3C_UJC0EVsxPaZ3D-F4b-hcc/edit# в сіквенс діаграмі по Create declaration request OTP ініціалізується (відправляється пацієнту СМС) в результаті виклику методу Create Declaration Request. 
Про методи Initialize OTP і Complete OTP взагалі ніде не сказано і при їх винекненні взагалі не зрозуміло скільки пацієнту буде напрвлено смс? одна через  Initialize OTP і друга в результаті Create Declaration Request?

**Comment by pzhuk** [comment]
@sreva по результатам create declaration request може відправлятись, або не відправлятись СМС -це наша опція авторизації. Незалежно від цього, кожен телефон має бути перевірений на правильність вводу, через методи OTP. Наразі MIS API документ не описує цього достатньо чітко - це ми будемо виправляти

**Comment by sreva** [comment]
@pzhuk дякую, чекаю оновленої документації.
