### ISSUE TITLE
Помилка верифікації телефону

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#78]
## Steps to Reproduce (Repro steps)

- [x] http://demo.ehealth.world/verifications/
- [x] Послідовність дій
1)  Запит GET /verifications/+380637675498 
    Відповідь   `{
    "meta": {
        "url": "http://demo.ehealth.world/verifications/+380637675498",
        "type": "object",
        "request_id": "glfv5h6nnblttpjj7h9kjmnpn2pobi4e",
        "code": 404
    },
    "error": {
        "type": "not_found"
    }
}`  
2) Запит POST /verifications
`{
  "phone_number": "+380637675498"
}`
 Відповідь `{
    "meta": {
        "url": "http://demo.ehealth.world/verifications",
        "type": "object",
        "request_id": "fhtuvbe8mek2bg065dv4v3cd47j8t295",
        "code": 201
    },
    "data": {
        "status": "new",
        "id": "0ef5aeab-f234-48bc-af10-f861f4fc5e16",
        "code_expired_at": "2017-08-03T06:02:23.264716Z",
        "active": true
    }
}`
3) Запит PATCH /verifications/+380637675498/actions/complete `{
  "code": 9779
}`
Відповідь `{
    "meta": {
        "url": "http://demo.ehealth.world/verifications/+380637675498/actions/complete",
        "type": "object",
        "request_id": "s3lp1f04k669o9nvf4e1kuc3fg8af83m",
        "code": 200
    },
    "data": {
        "status": "verified",
        "id": "0ef5aeab-f234-48bc-af10-f861f4fc5e16",
        "code_expired_at": "2017-08-03T06:02:23.264716Z",
        "active": false
    }
}`
4) запит GET /verifications/+380637675498

## Actual result
- [x] `{
    "meta": {
        "url": "http://demo.ehealth.world/verifications/+380637675498",
        "type": "object",
        "request_id": "bl2rqimkosbdjrms5kqsnn327vjtvm58",
        "code": 404
    },
    "error": {
        "type": "not_found"
    }
}`

## Expected result
-  [x] телефон верифіковано

**Comment by pzhuk** [comment]
@AlekzandrV any update on this one pls?

**Comment by lymychp** [comment]
deployed to demo
