### ISSUE TITLE
Словник адрес

### ISSUE THREAD

**Issue by ytrrty** [ehealth-ua/api-spec#8]
@lymychp
Чи працює зараз `GET`-запит на словник адрес?
`http://demo.ehealth.world/api/uaddresses/addresses`

При запиті отримую:
`{ "type": "not_found" }`

**Comment by lymychp** [comment]
@ytrrty
не працює і на реліз 01.06 не планується. Буде вже в повноцінному проді. Ну тобто сам ендпоінт є, але даних там ще нема
