### ISSUE TITLE
Помилка при створенні декларації з типом аутентифікації offline

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#81]
## Steps to Reproduce (Repro steps)

- [ ] http://demo.ehealth.world/api/declaration_requests
- [ ] робимо запит `{
  "declaration_request": {
    "person": {
      "first_name": "{{declaration_first_name}}",
      "last_name": "{{declaration_last_name}}",
      "second_name": "{{declaration_second_name}}",
      "birth_date": "2001-08-19",
      "birth_country": "Україна",
      "birth_settlement": "Вінниця",
      "gender": "MALE",
      "email": "email@example.com",
      "tax_id": "3378115538",
      "secret": "secret",
      "documents": [
        {
          "type": "PASSPORT",
          "number": "120518"
        }
      ],
      "addresses": [
      {
        "type": "REGISTRATION",
        "country": "UA",
        "area": "ЛЬВІВСЬКА",
        "region": "ПУСТОМИТІВСЬКИЙ",
        "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
        "settlement_type": "CITY",
        "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
        "street_type": "STREET",
        "street": "Ніжинська",
        "building": "15",
        "apartment": "23",
        "zip": "02090"
      },
      {
        "type": "RESIDENCE",
        "country": "UA",
        "area": "ЛЬВІВСЬКА",
        "region": "ПУСТОМИТІВСЬКИЙ",
        "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
        "settlement_type": "CITY",
        "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
        "street_type": "STREET",
        "street": "Ніжинська",
        "building": "15",
        "apartment": "23",
        "zip": "02090"
      }
    ],

      "authentication_methods": [
        {
          "type": "OFFLINE"
        }
      ],
      "emergency_contact": {
        "first_name": "Петро",
        "last_name": "Іванов",
        "second_name": "Миколайович",
        "phones": [
          {
            "type": "MOBILE",
            "number": "+380503410870"
          }
        ]
      },
      "confidant_person": [
        {
          "relation_type": "PRIMARY",
          "first_name": "Петро",
          "last_name": "Іванов",
          "second_name": "Миколайович",
          "birth_date": "1991-08-19",
          "birth_country": "Україна",
          "birth_settlement": "Вінниця",
          "gender": "MALE",
          "tax_id": "3378115538",
          "secret": "secret",
          "documents_person": [
            {
              "type": "PASSPORT",
              "number": "120518"
            }
          ],
          "documents_relationship": [
            {
              "type": "PASSPORT",
              "number": "120518"
            }
          ],
          "phones": [
            {
              "type": "MOBILE",
              "number": "+380503410870"
            }
          ]
        },
        {
          "relation_type": "SECONDARY",
          "first_name": "Петро",
          "last_name": "Іванов",
          "second_name": "Миколайович",
          "birth_date": "1991-08-19",
          "birth_country": "Україна",
          "birth_settlement": "Вінниця",
          "gender": "MALE",
          "tax_id": "3378115538",
          "secret": "secret",
          "documents_person": [
            {
              "type": "PASSPORT",
              "number": "120518"
            }
          ],
          "documents_relationship": [
            {
              "type": "PASSPORT",
              "number": "120518"
            }
          ],
          "phones": [
            {
              "type": "MOBILE",
              "number": "+380503410870"
            }
          ]
        }
      ],
      "patient_signed": false,
      "process_disclosure_data_consent": true
    },
    "scope": "family_doctor",
    "employee_id": "27b7672c-aa94-4bf8-9ea8-6b5540ea8a26",
    "division_id": "17e39df8-f6f4-4283-a6f8-32b75edac9d6"
  }
}`

## Actual result
- [ ] отримуємо відповідь `{
    "meta": {
        "url": "http://demo.ehealth.world/api/declaration_requests",
        "type": "object",
        "request_id": "kncnsemuuiqd64it3jjv0lm899hfukmh",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "required",
                        "params": [],
                        "description": "required property phone_number was not present"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.declaration_request.person.authentication_methods.[0]"
            }
        ]
    }
}`

## Expected result
- [ ] декларацію буде зареєстровано

**Comment by pzhuk** [comment]
Контактний телефон в будь-якому випадку є необхідним, навіть якщо авторизація оффлайн

**Comment by pzhuk** [comment]
Це може бути і не мобільний телефон в такому випадку

**Comment by lymychp** [comment]
`declaration_request.person.authentication_methods. phone_number` should be optional for the offline_method.
