### ISSUE TITLE
Помилка при загрузці документів

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#82]
## Steps to Reproduce (Repro steps)

- [ ] https://storage.googleapis.com/declaration-requests-dev/
- [ ] створюємо заявку на декларацію і отримуємо відповідь  "request_id": "mr2b4h0999vgf5l6mgrcduf1p8diqifp" , 
`{
    "urgent": {
        "documents": [
            {
                "url": "https://storage.googleapis.com/declaration-requests-dev/69906c89-8d37-40f4-9263-098d531d0db5/declaration_request_person.TEMPORARY_CERTIFICATE.jpeg?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1501769332&Signature=a76zHSO1E7FzrQA73c1laSiBwmCiAhs%2FTm2jz9N5x2Ed%2FyFgjlo3Oi2508iLzbVQSxrKo8AIW0oVysWFKfn5xNcN9mv%2FLIT26M%2BAWiQ1UaMGqAK6hEhyjaLz42Gc2B%2F0YvMJQzQXzkkvBVJMSdVGOr6vj6%2BKW9kkVEMDRgtzUxp6Ueiu0aalMNypDYvW3uxP1DepUh0XnLq4r8%2ByutfOrv%2FQS%2FLDpRVEmOdtbUwVxiRRr9NXimPj%2Bbn6Mz4ZH%2F%2BAajgSeEZ%2BJ6X%2BtLRTT8lRhsTagyA8Ymi4gk8orm7vg24n2wuUNzPv5ijdRNLHPcZYB0sQ3y3bHSgOJT9fC9wEhQ%3D%3D",
                "type": "person.TEMPORARY_CERTIFICATE"
            },
            {
                "url": "https://storage.googleapis.com/declaration-requests-dev/69906c89-8d37-40f4-9263-098d531d0db5/declaration_request_person.SSN.jpeg?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1501769332&Signature=Yzw2JgGSt56y%2B3O4Bq%2FrYdUZLD3fLpokmd%2BJBP%2Fb9Q8EswSgoTz1hNukwHytAV3QSjRX%2BSDa%2FOxB58%2BiozohvpMe9OIIx6JTcDfhQxVRR4nvKF8EAG7ZdWMH5%2BMcKV5T7cV0WJaXHrtDZD726E3nGhN%2FNgJ%2FCClgeqmaAcOwMU7uOZ4q3THHsWTkyfi3X0Sk2q6gn6dlFKww6xTBob818TDGxnoPhyMLPDb4UJUL2fjQGnCULpmE0uibAQ5JLD6WJMZxqILhD5mzRCcxIoF7xCAXyaYPffsyhoxOHnXnMtYA4H7DMmDyn%2FtA0N%2FlMSV%2FyBIVcKkDoGOhlOSkG1L8Wg%3D%3D",
                "type": "person.SSN"
            },
            {
                "url": "https://storage.googleapis.com/declaration-requests-dev/69906c89-8d37-40f4-9263-098d531d0db5/declaration_request_confidant_person.0.PRIMARY.COURT_DECISION.jpeg?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1501769332&Signature=KENGh7Os2qN9xR0IqLIdBIQuWgwPljnBUYvuBbdA6dIPD8Gg8zuVwUDaQNR7sLR8V9JLQXMCZHqD5gw6fp%2B%2FTLPwEA7thoswCoZAzicKbJJsRuIB5y5BQBJYAmGCVnA%2B8OZrJKjhatboMYY%2FE4KLwPmABnEGlM1%2B7d6c4IwfuQR3PjJAA3cCjIZ3hDx1mdIDMoyiW%2B7FLMfmLzSVi1I5IWNOlN5jkrGfnuHfTqphWXU6Ij%2FT2%2FaxVPQ9z312lru709E73L%2FuLFcCTbhgvwJ3YrZ1foc8Xq%2BCxNnrsnGoVxxuxP2JXANoi%2BjDbfbvN1uXSYt2gSiva7iliHCFEnWITw%3D%3D",
                "type": "confidant_person.0.PRIMARY.COURT_DECISION"
            },
            {
                "url": "https://storage.googleapis.com/declaration-requests-dev/69906c89-8d37-40f4-9263-098d531d0db5/declaration_request_confidant_person.0.PRIMARY.PASSPORT.jpeg?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1501769332&Signature=mW78P4qVsLv83w3Yg%2BXvKqzAuJ2ml9oxmQMbXgtU5H0ZWI1gZIgnbHyJn8i9jc%2BBzkwEfhTyAdCLA8sodCYbuIz7VtluLJdUzWnJMCnYJOQHcyISIqpI1NYEPBT5KxYiMZOd3c8wW2iBr6%2B%2FwJ%2FvCrl6cgdpa1Uqf8rekX0Rcoq%2BrNJwmjGt9QOtJh9hGqpbCLNlzIIJ3rURuAtpc2%2FVdS5oIfXd2fKuAxiadngSJXM3Z%2F3yOdi91dU643FKE0lbNB0sg84fZYo87KjZ6jjpPqPQDmCaQyQQZPTeJW1p6rsCeyvGSK6PShJNEhy0KQUtd%2FuSQ2F4nfRMMKAbfUsrig%3D%3D",
                "type": "confidant_person.0.PRIMARY.PASSPORT"
            },
            {
                "url": "https://storage.googleapis.com/declaration-requests-dev/69906c89-8d37-40f4-9263-098d531d0db5/declaration_request_confidant_person.0.PRIMARY.SSN.jpeg?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1501769332&Signature=AJ9m4Qch8knKXdIvFiVqspkLYhP7qgdk%2BzICbHCe8Ef2eXDNpv7GVa0z%2BDDk7l%2BY7CKrTfXaa7froVO%2FCRJRsDknDI4QaL9BKlsI1hJ2sBwwHway1%2FQ%2B6PcbhEemc%2Bl3xbH3kJFGo%2Fg%2BRixRx3YM44W74dQ5D1%2BP58Q7akphRi3scxCGiYM6ERpv8zR40JsIw4EmEBNYIUReu1pf36hfGCBwkKstP9GS9fenXbxfU6l4OWVb5BZMMvNh2u5YP2cwpfGgOm6KMByl9AYo%2F2tdfXKzhzhWd4URsDakWg%2FH8RBZG39vnerPDIGY%2BT%2FGErhHFHkyMY14aze%2FDC5ixhKlNA%3D%3D",
                "type": "confidant_person.0.PRIMARY.SSN"
            }
        ],
        "authentication_method_current": {
            "type": "OFFLINE",
            "number": "+38093*****85"
        }
    }`
- [ ] робимо запит `curl -X PUT \
  'https://storage.googleapis.com/declaration-requests-dev/69906c89-8d37-40f4-9263-098d531d0db5/declaration_request_person.SSN.jpeg?GoogleAccessId=ael-dev%40ehealth-162117.iam.gserviceaccount.com&Expires=1501769332&Signature=Yzw2JgGSt56y%2B3O4Bq%2FrYdUZLD3fLpokmd%2BJBP%2Fb9Q8EswSgoTz1hNukwHytAV3QSjRX%2BSDa%2FOxB58%2BiozohvpMe9OIIx6JTcDfhQxVRR4nvKF8EAG7ZdWMH5%2BMcKV5T7cV0WJaXHrtDZD726E3nGhN%2FNgJ%2FCClgeqmaAcOwMU7uOZ4q3THHsWTkyfi3X0Sk2q6gn6dlFKww6xTBob818TDGxnoPhyMLPDb4UJUL2fjQGnCULpmE0uibAQ5JLD6WJMZxqILhD5mzRCcxIoF7xCAXyaYPffsyhoxOHnXnMtYA4H7DMmDyn%2FtA0N%2FlMSV%2FyBIVcKkDoGOhlOSkG1L8Wg%3D%3D' \
  -H 'cache-control: no-cache' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW' \
  -F =@declaration_request_person.SSN.jpeg`

## Actual result
- [ ] `<?xml version='1.0' encoding='UTF-8'?>
<Error>
    <Code>SignatureDoesNotMatch</Code>
    <Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message>
    <StringToSign>PUT

multipart/form-data; boundary=----WebKitFormBoundaryMumm5E1jtdEaBXZJ
1501769332
/declaration-requests-dev/69906c89-8d37-40f4-9263-098d531d0db5/declaration_request_person.SSN.jpeg</StringToSign>
</Error>`

## Expected result
- [ ] Можливо загрузити документи

**Comment by sreva** [comment]
Поспілкувались з @DPashchenko 
@pzhuk можете, будь ласка, докинути корси, щоб ми могли загружати документи напряму з фронта.

**Comment by pzhuk** [comment]
@lymychp  it's about cors settings during signed URLs generation. We should probably pass the full whitelist of redirect URLs

**Comment by lymychp** [comment]
we have added MISes origins from @sreva to the buckets configuration. 
It should work now. Please check

**Comment by sreva** [comment]
@lymychp отримали відповідь `Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. Origin 'http://dis.helsi.dev' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute`

**Comment by sreva** [comment]
спробували сьогодні підгрузити документи.
отримали помилку 
`<?xml version='1.0' encoding='UTF-8'?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.</Message><StringToSign>PUT

image/jpeg
1503062245
/declaration-requests-dev/854d9daa-687b-4db5-aa60-b747f69387e5/declaration_request_person.TEMPORARY_CERTIFICATE.jpeg</StringToSign></Error>`


Зпит до google (заголовки)

`:authority:storage.googleapis.com
:method:PUT
:path:/declaration-requests-dev/854d9daa-687b-4db5-aa60-b747f69387e5/declaration_request_person.TEMPORARY_CERTIFICATE.jpeg?GoogleAccessId=ael-dev@ehealth-162117.iam.gserviceaccount.com&Expires=1503062245&Signature=ZOVVjhKr%2Bk9aKIS8zrlPOrlmQeqRNKbHuJBGg3F9ypWEujLGRBNBHBjEPQe8juJwEcvFr28SXu3xwlIt0MWI6ALEhjOOLYK11kwhUfg6Ihb7luDdw20aUlzK1WyXyKUOhLMyTgbpBSUjFUVCmKoDAsnKyuvpO7mICU0124LqYJSXeql8FOH6UcAtIMr1gCWGuwFpz7rKyMyuZVY%2FOx%2Bm5EsCkv%2Brgx6MOEpQVkQw%2Fk%2FrSEF84rhgLETVMH7peM84gCXLsmh4%2B%2BysiCC9zII%2FjRRCnkZzr9wWn3p5HiqrvamvPKtRlyw%2Fn%2BxfSIe4ThVk%2Fl3b8myYN5nCZlHq%2FXLzPA%3D%3D
:scheme:https
accept:*/*
accept-encoding:gzip, deflate, br
accept-language:ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4
cache-control:no-cache
content-length:787406
content-type:image/jpeg
origin:http://dis.helsi.dev
pragma:no-cache
referer:http://dis.helsi.dev/declarations/confirm/854d9daa-687b-4db5-aa60-b747f69387e5
user-agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
x-client-data:CIm2yQEIo7bJAQjBtskBCIuYygEI+pzKAQipncoB`

**Comment by lymychp** [comment]
fixed on demo
