### ISSUE TITLE
помилка реєстрації МСП

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#84]
Колеги, отримуємо наступну помилку при реєстрації МСП, допоможіть розібратися в чому причина:
```
		{
			"meta" : {
				"url" : "http://api.ehealth-ukraine.org/api/legal_entities",
				"type" : "object",
				"request_id" : "36n4ti6m8ccgfgdkg4f5phgpl97dv030",
				"code" : 400
			},
			"error" : {
				"type" : "request_malformed",
				"message" : "Signed request data is invalid",
				"invalid" : [
					{
						"rules" : [
							{
								"rule" : "json"
							}
						],
						"entry_type" : "request"
					}
				]
			}
		}
```

**Comment by pzhuk** [comment]
@lymychp unable to reproduce on demo - registration is succesful. Any chance this kind of error could be returned on digital signature verification failures, or is it pure gateway response?

**Comment by lymychp** [comment]
it looks like an error from the DS service

**Comment by pzhuk** [comment]
@sreva  ми підозрюємо, що АЦСК був недоступний в момент реєстрації. Наразі на демо все працює. Можете повторити спробу реєстрації?

**Comment by sreva** [comment]
дякую, спробуємо
