### ISSUE TITLE
Довіднік типів докіментів, що засвідчують предствництво

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#85]
При створенні декларації в блоці documents_relationship в apiary вказано посилання Dictionary DOCUMENT_TYPE http://prntscr.com/g49ab4 , але судячи запитів в postman і самої декларації, там має бути інший довідник (з атрибутами "Рцшення суду", "Посвідчення", "Свідотство про народження").

**Comment by lymychp** [comment]
we have added new dictionary - `DOCUMENT_RELATIONSHIP_TYPE`
