### ISSUE TITLE
Однаковий атрибут для підгрузки документів різного виду

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#86]
## Steps to Reproduce (Repro steps)

- [ ]  /api/declaration_requests
- [ ] Робимо запит на створення декларації з типом верифікації офлайн, тип документу опікуна - "посвідка", тип документу що засвідчує представництво - "посвідчення" 
`{
  "declaration_request": {
    "person": {
      "first_name": "{{declaration_first_name}}",
      "last_name": "{{declaration_last_name}}",
      "second_name": "{{declaration_second_name}}",
      "birth_date": "2001-08-19",
      "birth_country": "Україна",
      "birth_settlement": "Вінниця",
      "gender": "MALE",
      "email": "email@example.com",
      "tax_id": "3378115538",
      "secret": "secret",
      "documents": [
        {
          "type": "PASSPORT",
          "number": "120518"
        }
      ],
      "addresses": [
      {
        "type": "REGISTRATION",
        "country": "UA",
        "area": "ЛЬВІВСЬКА",
        "region": "ПУСТОМИТІВСЬКИЙ",
        "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
        "settlement_type": "CITY",
        "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
        "street_type": "STREET",
        "street": "Ніжинська",
        "building": "15",
        "apartment": "23",
        "zip": "02090"
      },
      {
        "type": "RESIDENCE",
        "country": "UA",
        "area": "ЛЬВІВСЬКА",
        "region": "ПУСТОМИТІВСЬКИЙ",
        "settlement": "СОРОКИ-ЛЬВІВСЬКІ",
        "settlement_type": "CITY",
        "settlement_id": "707dbc55-cb6b-4aaa-97c1-2a1e03476100",
        "street_type": "STREET",
        "street": "Ніжинська",
        "building": "15",
        "apartment": "23",
        "zip": "02090"
      }
    ],
      "phones": [
        {
          "type": "MOBILE",
          "number": "+380936235985"
        }
      ],
      "authentication_methods": [
        {
          "type": "OFFLINE",
          "phone_number": "+380936235985"
        }
      ],
      "emergency_contact": {
        "first_name": "Петро",
        "last_name": "Іванов",
        "second_name": "Миколайович",
        "phones": [
          {
            "type": "MOBILE",
            "number": "+380503410870"
          }
        ]
      },
      "confidant_person": [
        {
          "relation_type": "PRIMARY",
          "first_name": "Петро",
          "last_name": "Іванов",
          "second_name": "Миколайович",
          "birth_date": "1991-08-19",
          "birth_country": "Україна",
          "birth_settlement": "Вінниця",
          "gender": "MALE",
          "tax_id": "3378115538",
          "secret": "secret",
          "documents_person": [
            {
              "type": "PASSPORT",
              "number": "120518"
            }
          ],
          "documents_relationship": [
            {
              "type": "BIRTH_CERTIFICATE",
              "number": "120518"
            }
          ],
          "phones": [
            {
              "type": "MOBILE",
              "number": "+380503410870"
            }
          ]
        },
        {
          "relation_type": "SECONDARY",
          "first_name": "Петро",
          "last_name": "Іванов",
          "second_name": "Миколайович",
          "birth_date": "1991-08-19",
          "birth_country": "Україна",
          "birth_settlement": "Вінниця",
          "gender": "MALE",
          "tax_id": "3378115538",
          "secret": "secret",
          "documents_person": [
            {
              "type": "TEMPORARY_CERTIFICATE",
              "number": "120518"
            }
          ],
          "documents_relationship": [
            {
              "type": "TEMPORARY_CERTIFICATE",
              "number": "120518"
            }
          ],
          "phones": [
            {
              "type": "MOBILE",
              "number": "+380503410870"
            }
          ]
        }
      ],
      "patient_signed": false,
      "process_disclosure_data_consent": true
    },
    "scope": "family_doctor",
    "employee_id": "27b7672c-aa94-4bf8-9ea8-6b5540ea8a26",
    "division_id": "17e39df8-f6f4-4283-a6f8-32b75edac9d6"
  }
}` 

Тип документу що засвідчує представництво, за відсутності окремого довідника було підібрано з валідаційної схеми 

` "invalid": [
            {
                "rules": [
                    {
                        "rule": "inclusion",
                        "params": [
                            "PASSPORT",
                            "NATIONAL_ID",
                            "BIRTH_CERTIFICATE",
                            "TEMPORARY_CERTIFICATE",
                            "COURT_DECISION"
                        ],
                        "description": "value is not allowed in enum"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.declaration_request.person.confidant_person.[0].documents_relationship.[0].type"
            }
        ]`

## Actual result
- атрибут confidant_person.1.SECONDARY.TEMPORARY_CERTIFICATE  отримали як для  "Посвідки" 
іншого законного представника, опікуна чи піклувальника пацієнта так і на  "Посвідчення" (документу, що засвідчує факт представництва)

## Expected result
- [ ] Отримати різні назви атрибутів, для коректного відображення на фронті.

**Comment by pzhuk** [comment]
@lymychp пропоную створити словник, який визначає типи документів і їх назви

**Comment by lymychp** [comment]
fixed and new dictionary added
