### ISSUE TITLE
Неможливо відхилити заявку на створення співробітника

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#88]
## Steps to Reproduce (Repro steps)

- [x] http://auth.demo.ehealth.world/invite/accept?invite=1381f4f2-a23c-4004-97ef-0b1b4be010c3
- [x] подати заявку на створення співробітника
- [ ] 
1) перейти по лінку підтвердження в почті
2) спробуваати відхилити запрошення http://prntscr.com/g69a3s

## Actual result
- [x] Failed to load resource: the server responded with a status of 403 (Forbidden)

## Expected result
- [x] Можна відхилити запрошення

**Comment by lymychp** [comment]
The problem was with the demo configuration after deployment.
now fixed, please try again.
