### ISSUE TITLE
Addresses not found

### ISSUE THREAD

**Issue by kmakarenko** [ehealth-ua/api-spec#9]
не вдається отримати список адрес:

Request:
http://demo.ehealth.world/api/uaddresses/addresses?settlement_name=Адамівка&settlement_id=857c7f5b-db60-4e59-9383-555accf573a9
{"Authorization":"Bearer c490c936651a0f6badeb426721076437»}

Response:
{
  "type": "not_found"
}

**Comment by lymychp** [comment]
endpoint http://demo.ehealth.world/api/uaddresses/addresses створений для отримання списку вулиць. В даний момент у нас немає даних по вулицях, будуть тільки після 15.07

how to get settlement_id examples:
`curl -X GET \ http://demo.ehealth.world/api/uaddresses/details/district/f067ffa8-31ea-42fd-aec0-7655bb817eef/settlements \ -H 'authorization: Bearer scope_address' \ -H 'cache-control: no-cache' \ -H 'postman-token: 629d381a-0b45-ec4c-8bff-784bfdf4dc5b'`

`curl -X GET \ 'http://demo.ehealth.world/api/uaddresses/search/settlements?settlement_name=%D0%9B%D1%83%D1%86%D1%8C%D0%BA&region=%D0%92%D0%BE%D0%BB%D0%B8%D0%BD%D1%81%D1%8C%D0%BA%D0%B0&district=%D0%92%D0%BE%D0%BB%D0%B8%D0%BD%D1%81%D1%8C%D0%BA%D0%B0' \ -H 'authorization: Bearer UHdoeVoxOHl4enBsMVVsY1A3SXorQT09' \ -H 'cache-control: no-cache' \ -H 'postman-token: 267ba277-9008-98f5-eb00-1a4399110999'`

**Comment by lymychp** [comment]
duplicates #8
