### ISSUE TITLE
Помилка при вході в систему

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#90]
Не можемо ввійти в систему ні одним з попередньо зареєстрованих користувачів.
Нижче приклад на одному з них.

## Steps to Reproduce (Repro steps)
- [ ] `http://auth.demo.ehealth.world/sign-in?request_type=code&email=thesakharov@gmail.com&redirect_uri=https%3A%2F%2Fstagingreform.helsi.me%2Fuser%2Fauth&client_id=0651e111-82fd-4f52-a921-a5835eef266e&scope=employee%3Aread+employee%3Awrite+employee_request%3Aapprove+employee_request%3Aread+employee_request%3Awrite+employee_request%3Areject+legal_entity%3Aread+declaration_request%3Aread+declaration_request%3Awrite+otp%3Awrite+otp%3Aread+division%3Aread+division%3Awrite+employee%3Adeactivate+employee%3Awrite+declaration%3Aread+declaration_request%3Areject+employee%3Adetails+division%3Adetails+division%3Aactivate+division%3Adeactivate+declaration_request%3Aapprove`
- [ ] вводимо пароль. 

## Actual result
- [ ] `{"meta":{"url":"http://dev.ehealth.world/oauth/tokens","type":"object","request_id":"go8icsspvi1701kaium8osu3suvlee7h","code":401},"error":{"invalid_grant":"Identity not found."}}`

## Expected result
- [ ] ми входимо в систему

**Comment by lymychp** [comment]
The problem was with the demo configuration after deployment.
now fixed, please try again.
