### ISSUE TITLE
Не працює відновлення паролю

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#91]
## Steps to Reproduce (Repro steps)

- [ ] http://auth.demo.ehealth.world/reset
- [ ] вводимо почту thesakharov@gmail.com. такий користувач точно є, 

## Actual result
- [ ] `{"meta":{"url":"http://dev.ehealth.world/api/credentials_recovery_requests","type":"object","request_id":"f71gi470ol9q2lv2posr55m7rhdhlcir","code":422},"error":{"type":"validation_failed","message":"Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.","invalid":[{"rules":[{"rule":"existence","params":[],"description":"does not exist"}],"entry_type":"json_data_property","entry":"$.email"}]}}`

## Expected result
- [ ] ми можемо відновити пароль

**Comment by lymychp** [comment]
The problem was with the demo configuration after deployment.
now fixed, please try again.
