### ISSUE TITLE
Помилка при підтвердженні запрошення для Owner

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#92]
## Steps to Reproduce (Repro steps)

- [ ] http://auth.demo.ehealth.world
- [ ] зареєстрували новий МСП. На вказану для керівника почту отримали лист і перейшли по посиланню http://auth.demo.ehealth.world/invite?invite=70df0a6f-43af-40b7-9ce7-2fac0e6b7af9

## Actual result
- [ ] http://prntscr.com/g6q5ic 
`{"meta":{"url":"http://dev.ehealth.world/api/employee_requests/70df0a6f-43af-40b7-9ce7-2fac0e6b7af9","type":"object","request_id":"20nmcfek2inq74j40mkg7e6d317c3lt2","code":404},"error":{"type":"not_found"}}`

## Expected result
- [ ] ми можемо прийняти запрошення

**Comment by lymychp** [comment]
The problem was with the demo configuration after deployment.
now fixed, please try again.

**Comment by sreva** [comment]
Пробували 5 хв тому, нічого не змінилося

**Comment by sreva** [comment]
Деталі в @pzhuk в слаці
