### ISSUE TITLE
Не відправляються СМС

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#94]
## Steps to Reproduce (Repro steps)

- [ ]  http://demo.ehealth.world/verifications
- [ ] Робимо запит:

```
`POST /verifications HTTP/1.1
Host: demo.ehealth.world
Content-Type: application/json
Cache-Control: no-cache

{
  "phone_number": "+380637675498"
}`
```

Отримуємо відповідь:

`{
    "meta": {
        "url": "http://demo.ehealth.world/verifications",
        "type": "object",
        "request_id": "gdsp5tccltl5injcq01alnrlgsfl9c8d",
        "code": 201
    },
    "data": {
        "status": "new",
        "id": "a6a3d4cb-7966-46f1-a4df-9770bb22bd34",
        "code_expired_at": "2017-08-14T05:51:20.207126Z",
        "active": true
    }
}`

## Actual result
- [ ] СМС на даний номер не отримано.

## Expected result
- [ ] отримати смс на даний номер.

**Comment by pzhuk** [comment]
@lymychp потрібно оновити дані авторизації на мобільного оператора - змінилися минулої п"ятниці.  Катя надсилала деталі поштою - прошу змінити якомога швидше

**Comment by lymychp** [comment]
тут питання не до нас, доставка смс - це lifecell. Ми credentials підключення до lifecell поміняли в п'ятницю.
