### ISSUE TITLE
HTML декларації для печаті

### ISSUE THREAD

**Issue by sreva** [ehealth-ua/api-spec#96]
## Steps to Reproduce (Repro steps)

- [ ]   http://demo.ehealth.world/api/declaration_requests
- [ ] Робимо запит 
[запит.txt](https://github.com/ehealth-ua/api-spec/files/1225491/default.txt)
Отримуємо відповідь:[Відповідь.txt](https://github.com/ehealth-ua/api-spec/files/1225493/default.txt)

## Actual result
- [ ] отримуємо ось такий HTML для печаті 
[HTML у відповіді.txt](https://github.com/ehealth-ua/api-spec/files/1225499/HTML.txt)

## Expected result
- [ ] отримати коректний HTML для печаті

**Comment by lymychp** [comment]
в роботі

**Comment by AlekzandrV** [comment]
Виправлено та задеплоєно на демо

**Comment by sreva** [comment]
дякую
