### ISSUE TITLE
Помилка реєстрації лікаря(на демо)

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#97]
POST /api/employee_requests HTTP/1.1
Host: demo.ehealth.world
Authorization: Bearer c490c936651a0f6badeb426721076437
Content-Type: application/json
Cache-Control: no-cache
Postman-Token: 234fd13d-3ce1-3c52-a9cd-ab403eb6b16c

{"employee_request":{"position":"P8","start_date":"2017-08-16","end_date":"2018-08-16","status":"NEW","employee_type":"DOCTOR","legal_entity_id":"51d1b966-2bab-4b02-8e72-f4157e46c461","party":{"first_name":"Песков","last_name":"Дмитрий","second_name":"Александрович","birth_date":"1991-08-19","gender":"MALE","tax_id":"3126509816","email":"dmytropieskov@gmail.com","documents":[{"type":"PASSPORT","number":"120518"}],"phones":[{"type":"MOBILE","number":"+380503410870"}]},"doctor":{"educations":[{"country":"UA","city":"Київ","institution_name":"Академія Богомольця","issued_date":"2017-01-01","diploma_number":"DD123543","degree":"MASTER","speciality":"Педіатр"}],"qualifications":[{"type":"SPECIALIZATION","institution_name":"Академія Богомольця","speciality":"Педіатр","issued_date":"2017-01-01","certificate_number":"2017-01-01"}],"specialities":[{"speciality":"THERAPIST","speciality_officio":true,"level":"FIRST","qualification_type":"AWARDING","attestation_name":"Академія Богомольця","attestation_date":"2017-01-01","valid_to_date":"2020-01-01","certificate_number":"AB/21331"}],"science_degree":{"country":"UA","city":"Київ","degree":"Candidate_of_Science","institution_name":"Академія Богомольця","diploma_number":"DD123543","speciality":"PEDIATRICIAN","issued_date":"2017-01-01"}}}}

`{
    "meta": {
        "url": "http://demo.ehealth.world/api/employee_requests",
        "type": "object",
        "request_id": "2ne7qbid8k79l4c4plebgbljsjs85m6t",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "format",
                        "params": [
                            "^[0-9a-f]{8}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{12}$"
                        ],
                        "description": "string does not match pattern \"^[0-9a-f]{8}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{12}$\""
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.employee_request.legal_entity_id"
            }
        ]
    }
}`

**Comment by lymychp** [comment]
@pieskov дуже рекомендую читати тест помилок у респонсі - некоректний `legal_entity_id`:
```json
"legal_entity_id": "51d1b966-2bab-4b02-8e72-f4157e46c461"
```
тут явно guid кривий

**Comment by pieskov** [comment]
А ще там написано "string does not match pattern \"^[0-9a-f]{8}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{4}(-?)[0-9a-f]{12}$\"" } ], що в точності спивпадає з 51d1b966-2bab-4b02-8e72-f4157e46c461

**Comment by lymychp** [comment]
Ви створюєте `employee_request` з некоректним токеном. Співробітників може створювати тільки owner або HR з токеном в контексті MSP. Такий токен можна отримати тільки по oauth flow. Ви використовуєте токен MIS, а він може створювати тільки legal_entity.

**Comment by pieskov** [comment]
Так токен тестовий. але ругається не на токен. а на ніби-то"неправильний" legal_entity_id. То проблема не в токені, токен перевірений і йде перевірка json співробітника. а при перевірці на валідність данних співробітника видає помилку.
Я вважаю що задача не закрита.

**Comment by lymychp** [comment]
@pieskov текст помилки не зовсім очевидно вказує на проблему, але проблема саме в токені.
Створювати співробітників може тільки користувач  MSP з використанням персонального токену  в контексті MSP. З токеном MIS, який Вам видали для тестування, можна тільки працювати з об'єктом legal_entity. Далі новостворений owner повинен пройти по oauth flow, отримати нові токени з новими скоупами і тільки після цього можна створювати employees.

**Comment by pieskov** [comment]
Не очевидна помилка. Дякую.
