### ISSUE TITLE
Помилка реєстрації юр. особи(на демо)

### ISSUE THREAD

**Issue by pieskov** [ehealth-ua/api-spec#98]
{
    "meta": {
        "url": "http://demo.ehealth.world/api/legal_entities",
        "type": "object",
        "request_id": "9t0jsj378iqlda2b4pdt98k13hf89548",
        "code": 422
    },
    "error": {
        "type": "validation_failed",
        "message": "Validation failed. You can find validators description at our API Manifest: http://docs.apimanifest.apiary.io/#introduction/interacting-with-api/errors.",
        "invalid": [
            {
                "rules": [
                    {
                        "rule": "required",
                        "params": [],
                        "description": "required property documents was not present"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.employee_request.party.documents"
            },
            {
                "rules": [
                    {
                        "rule": "required",
                        "params": [],
                        "description": "required property phones was not present"
                    }
                ],
                "entry_type": "json_data_property",
                "entry": "$.employee_request.party.phones"
            }
        ]
    }
}

**Comment by lymychp** [comment]
@pieskov судячи з тексту помилки ви не передали обов'язкові поля ownera у реквесті, а конкретно - телефон.

**Comment by pieskov** [comment]
З чого це видно? З цього $.employee_request.party.phones видно, що не заповнені телефони блоку "party". а не "owner". Тому і був створений "issue".
