### ISSUE TITLE
Owner authorize token

### ISSUE THREAD

**Issue by cshevchukod** [ehealth-ua/api-spec#99]
Коллеги, подскажите:

{{host}}/oauth/tokens
`{
   "token":{
      "grant_type":"password",
      "email":"{{owner_email}}",
      "password":"12345678",
      "client_id":"{{fe_client_id}}",
      "scope":"app:authorize"
   }
}`

Этот токен даётся один на всё регистрируемые клиники? Кто должен вводить её?
Не понятно где взять информацию для данного токена.

**Comment by lymychp** [comment]
а що Ви намагаєтесь зробити?

**Comment by cshevchukod** [comment]
Авторизоваться. Это первый токен из трёх.

**Comment by cshevchukod** [comment]
По сути, непонятно что такое owner_email, password, client_id, и где это взять.

**Comment by pzhuk** [comment]
owner_email - передается при регистрации MSP
client_id - возвращается в ответе от eHealth после регистрации MSP
password - задается пользователем, после получения и принятия приглашения
через email

Документ для ознакомления с процессами
https://docs.google.com/document/d/1CNQu6R05Piq6HWI4t0L3C_UJC0EVsxPaZ3D-F4b-hcc/edit?usp=sharing


BR, Pavel V. Zhuk


2017-08-18 10:55 GMT+03:00 cshevchukod <notifications@github.com>:

**Comment by cshevchukod** [comment]
Понял, спасибо.
